### ISSUE TITLE
c4db_createIndex asserts 

### ISSUE THREAD

**Issue by KraemerDEM** [couchbase/couchbase-lite-core#1000]
A call to c4db_createIndex sometimes asserts in beginTransactionScope as it already seems to be inside a transaction.
Unfortunately this behaviour cannot be consistently reproduced, but it sometimes also happens directly after opening the database with c4db_open, so no synchronization or other database statement should be running.
I don't think it is neccessary on sqlite to put a "create index" statement into a transaction.

**Comment by snej** [comment]
> A call to c4db_createIndex sometimes asserts in beginTransactionScope as it already seems to be inside a transaction.

Let's see ... it looks as though `c4db_createIndxex` must not be called when already in a transaction. There ought to be a check for that, but there isn't.

> Unfortunately this behaviour cannot be consistently reproduced

That seems weird; it should be easy to reproduce by calling `c4db_beginTransaction` and then `c4db_createIndex`. If it's not consistent, is that because you're using the C4Database on multiple threads? (It sounds like you're calling LiteCore yourself rather than using CBL; is that correct?)

> I don't think it is neccessary on sqlite to put a "create index" statement into a transaction.

A single `CREATE INDEX...` statement does not require a transaction. But creating a CBL index does more than that, depending on the type of index, and the multiple things it does need to have ACID semantics. For example, creating a FTS index involves looking for an existing table (and returning if it exists), creating an FTS table, running an INSERT statement to populate the table, and creating three or four triggers to keep it up to date.

**Comment by KraemerDEM** [comment]
I could reproduce this with putting c4db_beginTransaction ahead of c4db_createIndex:
`
Assertion failed: !_inTransaction (../../../../qt/basis/DSQtDatabase/couchbaselite/LiteCore/Storage/DataFile.cc:326, in beginTransactionScope)
1   litecore::DataFile::beginTransactionScope                                                                                                                         DataFile.cc               326  0x555555ecdf01 
2   litecore::Transaction::Transaction                                                                                                                                DataFile.cc               382  0x555555ece218 
3   litecore::Transaction::Transaction                                                                                                                                DataFile.cc               375  0x555555ece1d6 
4   litecore::Transaction::Transaction                                                                                                                                DataFile.hh               274  0x555555e86505 
5   litecore::SQLiteKeyStore::createIndex                                                                                                                             SQLiteKeyStore+Indexes.cc 60   0x555555f3b391 
6   litecore::KeyStore::createIndex                                                                                                                                   KeyStore.cc               77   0x555555ed78d1 
7   <lambda()>::operator()(void) const                                                                                                                                c4Query.cc                219  0x555555e7777e 
8   fleece::function_ref<void()>::callback_fn<c4db_createIndex(C4Database *, C4Slice, C4Slice, C4IndexType, const C4IndexOptions *, C4Error *)::<lambda()>>(intptr_t) function_ref.hh           59   0x555555e78235 
9   fleece::function_ref<void ()>::operator()() const                                                                                                                 function_ref.hh           72   0x555555ed14e2 
10  c4Internal::tryCatch(C4Error *, fleece::function_ref<void ()>)                                                                                                    c4ExceptionUtils.cc       35   0x555555f31402 
11  c4db_createIndex                                                                                                                                                  c4Query.cc                223  0x555555e7784a 
1
`
However this doesn't help much, as removing the c4db_beginTransaction of course "fixes" it.

At that point there is no multithreaded access to the opened database (it has just been opened) and the replicator has not yet been started.
Or does opening a database trigger some multithreaded actions?
Then maybe making _inTransaction an atomic_bool (in DataFile.hh, line 263) would help. 

The only other thing worth mentioning is that another unrelated database (different database file) is already open at that time (and may be replicating), but I don't know how that could affect the just opened one.

**Comment by borrrden** [comment]
Sometimes when using complicated frameworks like Qt you think you are doing things one way but it's actually happening another so perhaps try putting a breakpoint in `beginTransactionScope` to see where else it might be getting called from.

**Comment by snej** [comment]
> Or does opening a database trigger some multithreaded actions?

Not in the sense of the same C4Database being used on multiple threads — that doesn't happen, since C4Database is not thread-safe.

**Comment by KraemerDEM** [comment]
It was an error in my code, the database was opened twice under some circumstances...
