### ISSUE TITLE
crash if websocket is closed before connection

### ISSUE THREAD

**Issue by KraemerDEM** [couchbase/couchbase-lite-core#1009]
since commit https://github.com/couchbase/couchbase-lite-core/commit/2ea5fdec4a001ccc894c75c2c0f2b8f2744f2cf3 our programm crashes if the websocket is closed before it is connected.
This is because we use a c4WebSocketFactory with flag kC4NoFraming, which is not properly handled in WebSocketImpl::close().
I think it should call requestClose() instead of closeSocket() if _framing is false.

**Comment by borrrden** [comment]
Sounds like a reasonable theory.  I'll try to modify the test I added to make sure that both of these cases are handled.
