### ISSUE TITLE
JSON parsing error in sync_gateway log

### ISSUE THREAD

**Issue by KraemerDEM** [couchbase/couchbase-lite-core#1012]
I sometimes get errors like the following in sync_gateway:
`
Invalid response to 'changes' message: RPY#1~ -- invalid character '0' after array element.  Body: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[
],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],["1-7781dc933d6d6223e1db93375bb023ac706a0e0e"],["1-fb22426686a2f6b0680f25b825dfd07068411cee"],["3-3c24d95faf0255887
a9bc38970fcb7689d47b4b7"],["1-1677661c9366e6f1d5bcbfd091f6248abeb498d5"],["1-13906a63322676b549966dc317f986c5b440b5ed"],["1-9dc04f3c139184c5daaf8058fbfba9a4f5e272e2"],["3-9faa2d8ef200fefc3caf76e82bcfc0821ab6e51
2"],["1-e6286797c7b475f402631bf3f2daba8dd42c17c6"],["1-622a18e96c89bbc4620c618e2e1f597eef6a58af"],["1-aeb1ff1198b67d40293640e215b3a5662db54a21"]0,0,["1-49be82d1c040edd88c308ab856f15af2b94c0283"],0,0,0,0,["1-cf2
0c2e8bb3551dd5e21d908cd8781564c95eca1"]] -- rest.(*blipSyncContext).handleChangesResponse() at blip_sync.go:556`
As you can see, the JSON is really invalid at 
`....["1-aeb1ff1198b67d40293640e215b3a5662db54a21"]0,0,...`
IMHO this is due to writing raw commas in RevFinder::_findOrRequestRevs, RevFinder.cc line 174.
I think this leads to not properly handling the _first flag in the JSONEncoder class.

**Comment by KraemerDEM** [comment]
As a quick workaround I've made the JSONEncoder::comma() method public and used that in RevFinder.cc. 
That seems to work...

**Comment by borrrden** [comment]
@snej Do you know what is going on here?

**Comment by borrrden** [comment]
Migrated to [CBL-1208](https://issues.couchbase.com/browse/CBL-1208)

**Comment by borrrden** [comment]
By the way what version of what library are you using?

**Comment by borrrden** [comment]
2.8.0 has been released with a fix for this.  Will close in a week unless there is further correspondence.

**Comment by KraemerDEM** [comment]
Sorry, I forgot to reply.
The problem is solved with the latest version, so I close this.
