### ISSUE TITLE
Compilation failure with MSVC2019

### ISSUE THREAD

**Issue by KraemerDEM** [couchbase/couchbase-lite-core#1016]
While trying to compile with msvc2019 in Windows, we got the errormessage
```
couchbaselite\LiteCore\Storage\DataFile.cc(105): fatal error C1001: An internal error has occurred in the compiler
```
This seems to be an error in msvc, as it compiles correctly with msvc2017,
so we have to wait for a fix by Microsoft...
However, as a workaround, replacing
```
 const DataFile::Options DataFile::Options::defaults = DataFile::Options {
 {true}, // sequences
 true, true, true, true // create, writeable, useDocumentKeys, upgradeable
 };
```
with
```
 const DataFile::Options DataFile::Options::defaults = {
 {true}, // sequences
 true, true, true, true // create, writeable, useDocumentKeys, upgradeable
 };
```
compiles correctly.

Is there anything to be said against this approach?

**Comment by Dushistov** [comment]
By the way I filled complain about this 
https://developercommunity.visualstudio.com/content/problem/1047005/bit-field-not-trivial-class-intialization-internal.html 
month ago. 
But the bug is still under investigation.

**Comment by borrrden** [comment]
I see no problem with doing that.
