### ISSUE TITLE
Android Compilation Error

### ISSUE THREAD

**Issue by fijemax** [couchbase/couchbase-lite-core#107]
Hi,

I tried to compile couchbase-lite-core for android platform but the compilation fail.

Here my command line compilation : 
> ANDROID_NDK=~/android-ndk-r10/ ANDROID_STL=none ANDROID_STL_FORCE_FEATURES=ON ANDROID_GOLD_LINKER=OFF CMAKE_BUILD_TYPE=Release ANDROID_NATIVE_API_LEVEL=android-9 ./scripts/build_android.sh 

And here the error code : 
> ~/DEV/cpp/couchbase-lite-core/build_cmake ~/DEV/cpp/couchbase-lite-core/build_cmake
~/DEV/cpp/couchbase-lite-core/build_cmake/android/lib/x86 ~/DEV/cpp/couchbase-lite-core/build_cmake ~/DEV/cpp/couchbase-lite-core/build_cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maxime/DEV/cpp/couchbase-lite-core/build_cmake/android/lib/x86
Scanning dependencies of target CivetWeb
[  1%] Built target sqlite3
Scanning dependencies of target BLIPStatic
[  1%] Building CXX object vendor/fleece/CMakeFiles/FleeceStatic.dir/Fleece/Path.cc.o
[ 20%] Built target SQLite3_UnicodeSN
Scanning dependencies of target LiteCoreStatic
[ 21%] Building CXX object vendor/fleece/CMakeFiles/FleeceStatic.dir/Fleece/Value.cc.o
[ 21%] Building CXX object vendor/BLIP-Cpp/CMakeFiles/BLIPStatic.dir/src/blip/BLIPConnection.cc.o
[ 23%] Building C object REST/CMakeFiles/CivetWeb.dir/__/vendor/civetweb/src/civetweb.c.o
/home/maxime/DEV/cpp/couchbase-lite-core/vendor/civetweb/src/civetweb.c:6296:13: warning: implicit declaration of function 'timegm' is
      invalid in C99 [-Wimplicit-function-declaration]
                        result = timegm(&tm);
                                 ^
[ 24%] Building CXX object CMakeFiles/LiteCoreStatic.dir/LiteCore/BlobStore/BlobStore.cc.o
/home/maxime/DEV/cpp/couchbase-lite-core/vendor/fleece/Fleece/Path.cc:57:53: error: use of undeclared identifier 'INT32_MAX'
                if (_usuallyFalse(n.size > 0 || i > INT32_MAX || i < INT32_MIN))
                                                    ^
/home/maxime/DEV/cpp/couchbase-lite-core/vendor/fleece/Fleece/PlatformCompat.hh:59:62: note: expanded from macro '_usuallyFalse'
    #define _usuallyFalse(VAL)              __builtin_expect(VAL, false)
                                                             ^
/home/maxime/DEV/cpp/couchbase-lite-core/vendor/fleece/Fleece/Path.cc:57:70: error: use of undeclared identifier 'INT32_MIN'
                if (_usuallyFalse(n.size > 0 || i > INT32_MAX || i < INT32_MIN))
                                                                     ^
/home/maxime/DEV/cpp/couchbase-lite-core/vendor/fleece/Fleece/PlatformCompat.hh:59:62: note: expanded from macro '_usuallyFalse'
    #define _usuallyFalse(VAL)              __builtin_expect(VAL, false)
                                                             ^
2 errors generated.

**Comment by hideki** [comment]
Hi @fijemax,

Thank you for trying to use lite-core with Android.

Followings are the differences between our build configuration and yours:
- We are using latest NDK (ndk-r14b)
- `CMAKE_ANDROID_STL_TYPE=c++_static`
- Minimum API version that Couchbase Lite supports is `16`.

Thanks,

**Comment by fijemax** [comment]
Hi @hideki 

Thank you for the feedback.

I have update my ndk to r14b release.

I try with using only : 
> ANDROID_NDK_ROOT=~/android-ndk-r14b/ ./scripts/build_android.sh

But I have the same compilation error : 
> In file included from /home/maxime/DEV/cpp/couchbase-lite-core/LiteCore/BlobStore/BlobStore.cc:19:
/home/maxime/DEV/cpp/couchbase-lite-core/LiteCore/Support/EncryptedStream.hh:74:36: error: use of undeclared identifier 'UINT64_MAX'
        uint64_t _cleartextLength {UINT64_MAX};
                                   ^
/home/maxime/DEV/cpp/couchbase-lite-core/LiteCore/Support/EncryptedStream.hh:75:34: error: use of undeclared identifier 'UINT64_MAX'
        uint64_t _bufferBlockID {UINT64_MAX};

**Comment by fijemax** [comment]
Hi,

Compilation is successfull only for arm64-v8a architecture.
And fail for both x86 and armeabi-v7a architecture.

**Comment by snej** [comment]
@borrrden: which Android architectures does UberJenkins currently build?

**Comment by borrrden** [comment]
The same three as this person is doing. They are using the script I wrote which almost exactly imitates what Jenkins does.

**Comment by borrrden** [comment]
That being said the defines they are using are not the defines that vanilla CMake uses. They are using the Android variants which will have no effect. The cmake ones are listed on the cmake cross compilation docs page.

**Comment by snej** [comment]
@fijemax Could you retry with the supported defines and see if it works?

**Comment by fijemax** [comment]
Hi @snej 
I try with `ANDROID_NDK=~/android-ndk-r10/ ./scripts/build_android.s`
that I found at : https://developer.android.com/ndk/guides/cmake.html

But the result is the same.

**Comment by borrrden** [comment]
We use r13b on the build server.  Is the result still the same when you use that one with the relevant defines?

**Comment by borrrden** [comment]
@fijemax One thing that occurred to me now is that you need to be using CMake 3.7 or higher to compile for Android (that's when Android support was added)

**Comment by borrrden** [comment]
I was able to work around this so it should compile alright now with 3.7 or 3.8.
