### ISSUE TITLE
N1QL lower(), upper() doesn't work on Android.

### ISSUE THREAD

**Issue by stephlang** [couchbase/couchbase-lite-core#1077]
I'm using couchbase and Qt to build an application for Android OS. I saw the `lower()` and `upper()` functions doesn't work.
There are my unit test.
```
    //Data
    QJsonObject dataInput1{{"recordId", "r_1234"},
                           {"name", "testing"}};
    QJsonObject dataInput2{{"recordId", "r_5678"},
                           {"name", "TESTING"}};
    QJsonObject dataInput3{{"recordId", "r_6789"},
                           {"name", "tesTing"}};
    QJsonObject dataInput4{{"recordId", "r_678910"},
                           {"name", "test"}};

    //Statement
    QString statement = "[\"SELECT\",{\"WHAT\":[[\".\",\"recordId\"]],\"WHERE\":[\"=\",[\"lower()"
                        "\",[\".\",\"name\"]],\"testing\"]}]";
```
It doesn't work on Android.

Android NDK: 21.2.6472646
Android abi: "armeabi-v7a"
jdk1.8.0_251
couchbase: commit 775893eddbfaff3569f1d351e12d1b27eb19fd40

**Comment by borrrden** [comment]
What are you getting instead?  The same value as in the data?

**Comment by stephlang** [comment]
> What are you getting instead? Only the first record emitted?

@borrrden Yes. I only get the first

**Comment by borrrden** [comment]
Well I won't be able to set up Android to test this easily, so do you know if this is the case on other platforms or is it only Android?  I'll write a test to see what happens, but if it doesn't fail on other platforms then I will have to resort to hacks to test it out.

**Comment by borrrden** [comment]
I ran a quick test on Linux desktop, which will use the same logic as Android, and the results are fine.  Barring an ICU bug I don't see what could cause this in LiteCore.

**Comment by stephlang** [comment]
Yes. It works on other platforms too (checked Windows, MacOS, iOS)

**Comment by borrrden** [comment]
Those platforms all have different engines in that area.  Have you tried Linux desktop?

**Comment by stephlang** [comment]
> Those platforms all have different engines in that area. Have you tried Linux desktop?

@borrrden  Yes. I have tried on the Ubuntu desktop and it works. All my unit tests works on other platforms except Android.

**Comment by borrrden** [comment]
Any odd locale settings that might be in play?  The code in play here is shared with Linux so it is very odd that Linux desktop would work while Android fails.

**Comment by nguoithichkhampha** [comment]
@borrrden , we just tested again. the issue does not happen on real android device. it happens on our Unit test system when run with Android emulator. something related to icu library
`2020-11-30 13:42:23.113 5478-5502/org.qtproject.example.CortexUnitTest E/NDKICU: Cannot open ICU libraries.
2020-11-30 13:42:23.119 5478-5502/org.qtproject.example.CortexUnitTest I/QTestLib: QINFO  : Test::CouchBaseNative::CouchBaseNativeTest::test_lower() [CBL] "{QueryEnum#67} Created on {Query#66} with 0 rows (2 bytes) in 6.137ms"
2020-11-30 13:42:23.122 5478-5502/org.qtproject.example.CortexUnitTest I/QTestLib: QDEBUG : Test::CouchBaseNative::CouchBaseNativeTest::test_lower() QJsonArray()
2020-11-30 13:42:23.124 5478-5502/org.qtproject.example.CortexUnitTest I/QTestLib: FAIL!  : Test::CouchBaseNative::CouchBaseNativeTest::test_lower() Compared values are not the same
`
it's not issue in couchbase library. So, I think you should close ticket. Thanks for your support.

**Comment by borrrden** [comment]
Thanks for the update.   Now that you point that out I've actually seen this before.  See here -> https://github.com/couchbase/couchbase-lite-core/issues/983

The consensus was this method should continue working for now but eventually when our min version is 29 (probably) some changes will need to be made.  I hope you find the other ticket informative!
