### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by cedseat** [couchbase/couchbase-lite-core#1080]
Hi,

In our app (in rust using couchbase-lite-rust) with continuous replication which do some save of the same doc with sometimes doc size > 10Ko we have regularly message like "database is locked". Also sometimes since a revision of one doc the next revisions of this doc are not replicated without logs, even if we modified this doc after, but the other docs are still replicated :-/. 

My first question is : when the database is really locked (transaction?, replication?) ? 

Second : How can a revision of a document can be frozen and not replicated after that ?

Thanks

**Comment by borrrden** [comment]
Please direct questions to the [forums](https://forums.couchbase.com/c/mobile/) and reserve the issue tracker for bug reports.  Thanks!
