### ISSUE TITLE
EWOULDBLOCK returned by socket on Windows instead of WSAEWOULDBLOCK

### ISSUE THREAD

**Issue by ionutcosminmihaipfa** [couchbase/couchbase-lite-core#1082]
OS: Windows 10, UWP app

Hi, I'm encountering the following issue originated in the `poll()` method from` TCPSocket.cc`.
When calling [removeListeners](https://github.com/couchbase/couchbase-lite-core/blob/e25884358722da0939f325b8f0a31c53ccbafad2/Networking/Poller.cc#L241) , the socket read method returns 140 error code which is [ERROR_JOIN_TO_SUBST (The system tried to join a drive to a directory on a substituted drive)](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-).
The socker read is called [here](https://github.com/couchbase/couchbase-lite-core/blob/e25884358722da0939f325b8f0a31c53ccbafad2/Networking/WebSockets/BuiltInWebSocket.cc#L364).
Any idea on possible issues with the poll method?

**Comment by borrrden** [comment]
I like all solutions that attempt to normalize these conditions for logical checks like this!

**Comment by borrrden** [comment]
Closed via #1085
