### ISSUE TITLE
setSqliteTempDirectory function implementation not found

### ISSUE THREAD

**Issue by ionutcosminmihaipfa** [couchbase/couchbase-lite-core#1093]
Hi, when trying to compile the project (from couchbase-lite-C) the `setSqliteTempDirectory ` function is not implemented and it's used [here](https://github.com/couchbase/couchbase-lite-core/blob/1b40fc9714c4d568f7a29b0f4a6d81992e8d9d16/LiteCore/Storage/SQLiteDataFile.cc#L159). What is its purpose? Can we remove it? If yes, here is a [Pull Request](https://github.com/couchbase/couchbase-lite-core/pull/1094).

**Comment by borrrden** [comment]
Please refrain from using the issue tracker for questions.  We have a [forum](https://forums.couchbase.com/c/mobile/couchbase-lite/20) for that :)
