### ISSUE TITLE
continuous replication times out

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#113]
### Steps
1. Started a continuous replication between SG and LiteCoreServ with `{"source": "blip://<SG_IP>:4985/db", "continuous": true, "target": "ls_db"}`
```
POST http://<LiteCoreServ_IP>:52000/_replicate 200
{u'ok': True, u'session_id': 1}
```
2. Wait for replication to go idle for id = 1
3. Poll active_tasks constantly to check for idle status

### Actual
1. The test ultimately times out as active tasks always sends
```{u'status': u'Connecting', u'target': u'ls_db', u'continuous': True, u'pid': 1, u'session_id': 1, u'started_on': 1494437668, u'source': u'blip://<SG_IP>:4985/db', u'updated_on': 1494437668, u'type': u'replication'}```
-> The status never changes
2. After the test timeout, during teardown the DB can't be deleted, thats the issue #112 .
3. LiteCoreServ uses around 180% CPU with 19 threads as per activity monitor.
4. After a while, LiteCoreServ crashes in thread file at line 441`sleep_for(__ns);` with `SIGKILL`
`3 void std::__1::this_thread::sleep_for<long, std::__1::ratio<3600l, 1l> > const&)`

The `bt` at `(lldb)` prompt has not responded for a long time

Attaching the sample of LiteCoreServ LiteCoreServ_2017-05-10_113715_70LU.sample.txt

[LiteCoreServ_2017-05-10_113715_70LU.sample.txt](https://github.com/couchbase/couchbase-lite-core/files/990870/LiteCoreServ_2017-05-10_113715_70LU.sample.txt)

**Comment by snej** [comment]
I don't know what's going wrong, but it's creating threads at a very high rate — the sample shows 4000 GCD worker threads, most of which only appear in a single sample. Turning on more logging would provide a lot more info.

**Comment by raghusarangapani** [comment]
Console output:
https://gist.github.com/raghusarangapani/cc184c192cb958b6b5fd5b65d8ffceae

**Comment by snej** [comment]
The replicator was connecting to SG's admin port, which triggered a bug in the SG BLIP replicator causing it to panic and close the connection.

That triggered a bug in CBLWebSocket: the code reading the HTTP response from the socket didn't detect the error (because at the socket level it isn't an error, just an EOF) and kept repeating the read call, in a very fast infinite loop.
