### ISSUE TITLE
C4Error code 2

### ISSUE THREAD

**Issue by Brunz** [couchbase/couchbase-lite-core#1142]
Rarely, when running a query on both main and in the background, the app crashes.

What does c4error code 2 mean?
![Schermata 2021-03-23 alle 16 15 16](https://user-images.githubusercontent.com/2631738/112191156-049ca800-8c06-11eb-9fed-e1de87de60dc.png)
![Schermata 2021-03-23 alle 16 21 24](https://user-images.githubusercontent.com/2631738/112191186-0d8d7980-8c06-11eb-99e8-f287a8dfb610.png)
![Schermata 2021-03-23 alle 16 21 46](https://user-images.githubusercontent.com/2631738/112191217-15e5b480-8c06-11eb-982a-af89f171b8af.png)

**Comment by borrrden** [comment]
Please post questions on [the forums](https://forums.couchbase.com/c/mobile/14) and save the issue tracker for bug reports.

**Comment by Brunz** [comment]
ok, I will move the question to the forum but it would be a crash.

Crashed: com.apple.main-thread
0  CouchbaseLiteSwift             0x1059d7358 std::__1::__hash_iterator<std::__1::__hash_node<litecore::Query*, void*>*> std::__1::__hash_table<litecore::Query*, std::__1::hash<litecore::Query*>, std::__1::equal_to<litecore::Query*>, std::__1::allocator<litecore::Query*> >::find<litecore::Query*>(litecore::Query* const&) + 87 (__hash_table:87)
1  CouchbaseLiteSwift             0x1059d72c0 unsigned long std::__1::__hash_table<litecore::Query*, std::__1::hash<litecore::Query*>, std::__1::equal_to<litecore::Query*>, std::__1::allocator<litecore::Query*> >::__erase_unique<litecore::Query*>(litecore::Query* const&) + 2636 (__hash_table:2636)
2  CouchbaseLiteSwift             0x1059d6edc litecore::DataFile::unregisterQuery(litecore::Query*) + 122 (DataFile.hh:122)
3  CouchbaseLiteSwift             0x1059d6e80 litecore::Query::~Query() + 44 (Query.cc:44)
4  CouchbaseLiteSwift             0x105996728 litecore::SQLiteQuery::~SQLiteQuery() + 194 (SQLiteQuery.cc:194)
5  CouchbaseLiteSwift             0x105972b68 fleece::Retained<litecore::repl::IncomingBlob>::~Retained() + 96 (RefCounted.hh:96)
6  CouchbaseLiteSwift             0x1059867b8 c4Internal::C4QueryEnumeratorImpl::~C4QueryEnumeratorImpl() + 96 (RefCounted.hh:96)
7  CouchbaseLiteSwift             0x10598677c c4Internal::C4QueryEnumeratorImpl::~C4QueryEnumeratorImpl() + 23 (c4QueryEnumeratorImpl.hh:23)
8  CouchbaseLiteSwift             0x105ab66d0 cbl::QueryResultContext::~QueryResultContext() + 46 (CBLFleece.hh:46)
9  libobjc.A.dylib                0x19841cae0 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
10 libobjc.A.dylib                0x1984328a4 objc_destructInstance + 88
11 libobjc.A.dylib                0x1984396ec _objc_rootDealloc + 52
12 libobjc.A.dylib                0x19843c574 AutoreleasePoolPage::releaseUntil(objc_object**) + 200
13 libobjc.A.dylib                0x19843c450 objc_autoreleasePoolPop + 208
14 UIKitCore                      0x1869a7894 __processEventQueue + 6564
15 UIKitCore                      0x18699eafc __eventFetcherSourceCallback + 156
16 CoreFoundation                 0x184017bf0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
17 CoreFoundation                 0x184017af0 __CFRunLoopDoSource0 + 204
18 CoreFoundation                 0x184016e38 __CFRunLoopDoSources0 + 256
19 CoreFoundation                 0x1840113e0 __CFRunLoopRun + 776
20 CoreFoundation                 0x184010ba0 CFRunLoopRunSpecific + 572
21 GraphicsServices               0x19ad79598 GSEventRunModal + 160
22 UIKitCore                      0x1869022f4 -[UIApplication _run] + 1052
23 UIKitCore                      0x186907874 UIApplicationMain + 164
24 Eat                            0x1023b4920 main + 4334700832 (<compiler-generated>:4334700832)
25 libdyld.dylib                  0x183cef568 start + 4

Are you sure it's not a bug?

**Comment by borrrden** [comment]
It may be, but the end result of this report was a question.  No context was provided for this, so it seemed more appropriate for the forum.
