### ISSUE TITLE
Increase default revs_limit significantly

### ISSUE THREAD

**Issue by JFlath** [couchbase/couchbase-lite-core#116]
Currently the default revs limit is 20. This means that if an offline client makes >20 revisions before syncing, SG cannot match this to the existing tree and inserts it as a conflict. There's obviously a balance to be struck here, but I'm tempted to say aiming high and having the option "Hey, tune this down for better performance, with these caveats." is preferable to "Hey, tune this up to stop messing up your data."

**Comment by snej** [comment]
I'd rather avoid doing this; I prefer the approach of #117.

**Comment by JFlath** [comment]
I think we definitely need this too - the bandwidth and storage overhead of increasing it shouldn't be particularly major (33 bytes per rev with the old protocol IIRC). However if it's one too low and you end up with a false conflict, the cost of saving that 33 bytes is 2x doc size.

Unless we're doing away with a numerical limit entirely, I definitely think we need to revise the default. I suspect we will need some kind of catch-all approach even if we do #117, and that would be the revs_limit...

**Comment by djpongh** [comment]
With 2.0 there generally won't be conflicts so this shouldn't be needed.

**Comment by JFlath** [comment]
@djpongh Sorry, but that seems quite sweeping. Generally, there may or may not be, but that's orthogonal to the question of "if there are, what should the revs limit be?"
