### ISSUE TITLE
Consider being more dynamic about pruning

### ISSUE THREAD

**Issue by JFlath** [couchbase/couchbase-lite-core#117]
Currently, we prune to a specific revs_limit. The risk here is, as in #116, we prune away anything SG can recognise. Potentially we could be quite clever here (in certain scenarios) and somehow track revisions to avoid pruning the last seen rev by SG. There's a lot of caveats and what-ifs, but I wanted to raise the question.

**Comment by JFlath** [comment]
Perhaps a dirty bit on each document until replicated for the most lightweight option? And/Or a "lowest revision" to not prune past. 

Would also need to be disable-able for those not using replication who don't want unlimited metadata growth...

**Comment by snej** [comment]
This is a good idea that I've considered in the past.

Another possibility is to preserve the last revision we know the server knows about, as well as the most recent 20. But that means there could be a gap in the generation count in the history we send the server. So far we've treated that as an error, but if we allow it, it prevents false conflicts like this.

And then there's always the version-vector-based revisioning system that does away with all these problems; it's already implemented in CBL, but of course we can't switch to it until SG implements it too.

**Comment by djpongh** [comment]
With 2.0 not allowing conflicts, this isn't needed.

**Comment by JFlath** [comment]
@djpongh This seems contrary to your comments in https://github.com/couchbase/couchbase-lite-core/issues/116 : "generally won't be" != "not allowing"
