### ISSUE TITLE
Dart/FLutter support.

### ISSUE THREAD

**Issue by richard457** [couchbase/couchbase-lite-core#1177]
So far there is no official couchbase_lite for flutter we are working on https://github.com/Rudiksz/couchbase_lite_dart that use C API which I believe is the best way to, if you can take a look at it and maybe support/contribute on this will make couchbase_lite on flutter a reality. we need couchbase_lite for flutter really!.

**Comment by borrrden** [comment]
This is not a bug report, and as such not likely to gain attention on the GH issue tracker.  We don't have the bandwidth to contribute to outside projects, unfortunately, but certainly if there is a bug standing in the way of using CBL-C for this purpose then let us know on the C repo.
