### ISSUE TITLE
Read socket error

### ISSUE THREAD

**Issue by trufanov-w** [couchbase/couchbase-lite-core#1220]
In applications on IOS and android in debug versions, at a random moment an error occurs in the slice.hh on line 587

`   inline const uint8_t& pure_slice::operator[](size_t off) const noexcept  {
        assert_precondition(off < size);
        return ((const uint8_t*)buf)[off];
    }
`
size = 0 and off = 0

 In WebSocketProtocol.hh line 421 `payloadLength(frame)` return 0 and `isFin(frame)` return 0
 frame = 138

There is no such thing in the release versions of the application.
This is fine?

**Comment by borrrden** [comment]
It is not ok, but this has already been discovered (see [CBL-2169](https://issues.couchbase.com/browse/CBL-2169)) and PR #1217 is pending

**Comment by borrrden** [comment]
Issue was fixed via the above PR.
