### ISSUE TITLE
fts query doesn't run if index created twice

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-core#123]
The FTS index is created with the following

```swift
let hotelSearchIndex = try database.createIndex(["description"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
```

FTS query:

```swift
let hotelSearchQuery = Query
                        .select()
                        .from(DataSource.database(database))
                        .where(Expression.property("description").match("'seafront'"))
for row in try hotelSearchQuery.run() {
    if let ftsRow = row as? FullTextQueryRow {
        "hotelSearchQuery :: \(ftsRow.fullTextMatched!)"
    }
}
```

It works if the index doesn't already exists. As soon as the code is ran again (i.e the index already exists) the following can be observed:

1. The following message is logged

    ```bash
    2017-05-23 15:17:14.232 full-text search[47180:1847268] CouchbaseLite  WARNING: SQLite error (code 1): table "kv_default::.description" already exists
    ```

2. The FTS query doesn't run. I don't see any stack trace logged.

**Comment by snej** [comment]
When you say "the code is ran again", are you running the `createIndex` call again, or just the query code?

It sounds like `createIndex` may be failing with a Swift error. Did you check for that?

**Comment by snej** [comment]
The bugis that `SQLiteKeyStore::createIndex` throws a SQLite exception if the FTS virtual table already exists.
