### ISSUE TITLE
How to check the existence of a document

### ISSUE THREAD

**Issue by thanhldnv** [couchbase/couchbase-lite-core#1250]
This is not a bug, it's my question about the right way to check the existence of a document. I'm hesitating between
`c4doc_get` and `c4query_run`.  I see the difference is this `c4doc_get` method returns an error `kC4ErrorNotFound` if not found, and `c4query_run` returns non error.
So which is the right way to check the existence of a document ?

**Comment by borrrden** [comment]
Since this is not a bug please ask on the [forums](https://forums.couchbase.com/c/mobile/14) instead.  Thanks!
