### ISSUE TITLE
Error attempt to write a readonly database

### ISSUE THREAD

**Issue by nguoithichkhampha** [couchbase/couchbase-lite-core#1306]
this error happens on the pc of one of our customer
Platform: Windows 10 Version 2009

our program run with admin permission so, it should not has the limitation to write into database
the user case:

- program saved document to database successful a few times
- program is crashed
- it's started again
- it can not write to database anymore and print the error like "SQLite message: statement aborts at 202: [INSERT OR IGNORE INTO kv_default (version, body, flags, sequence, key) VALUES (?, ?, ?, ?, ?)] attempt to write a readonly database", "SQLite message: statement aborts at 23: [INSERT OR REPLACE INTO kv_info (version, body, flags, sequence, key) VALUES (?, ?, ?, ?, ?)] attempt to write a readonly database"

**Comment by borrrden** [comment]
You will need to provide some snippets on what you are doing here for this to be diagnosed.  Text descriptions of the steps is not enough.

**Comment by nguoithichkhampha** [comment]
[cortex (4).txt](https://github.com/couchbase/couchbase-lite-core/files/7606112/cortex.4.txt)
@borrrden , I attached log file from our program. Let me know if you need more info.

**Comment by borrrden** [comment]
It would be better to see a snippet of the section causing the failure.  This type of message means that the DB was opened in read only mode.  Are you using core directly or via CBL?

**Comment by nguoithichkhampha** [comment]
@borrrden , yes we are using CBL api . we call same function to open database in the case write successful and write failed. is there an internal handling inside CBL to open database as read only mode in the case something error with database ?

**Comment by borrrden** [comment]
> We are using CBL api

Which one?  .NET?  Java?  C?

**Comment by nguoithichkhampha** [comment]
we use C API.

**Comment by borrrden** [comment]
The only way it would open in read only mode, from my memory, is if it is specifically opened in read only mode.  This is not a filesystem error about not being able to write, it is a sqlite error meaning that the readonly flag was turned on.  There is no facility to do this in the C API so I would need to see a reproduction case.

**Comment by borrrden** [comment]
Without a reproduction case there is no way forward here.  Closing, but feel free to reopen if you can provide one.
