### ISSUE TITLE
Currently no way to set sqlite3_result as an array

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#132]
I think the resulting array must be encoded to text JSON and then set as sqlite3_result_text

**Comment by snej** [comment]
This is for the return values of the N1QL functions that make or modify arrays, right?

**Comment by borrrden** [comment]
Right sorry yes. Things like array_append and array_concat.

**Comment by snej** [comment]
This has been working for a while; since 2.0 at least I think.
