### ISSUE TITLE
'zlc/zlibcomplete.hpp' file not found

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#133]
Building the Xcode project as per instructions I get: 

`<path-to>/couchbase-lite-core/vendor/BLIP-Cpp/src/blip/MessageBuilder.cc:13:10: 'zlc/zlibcomplete.hpp' file not found`

It looks like BLIP-Cpp includes zlibcomplete but not sure why its not picking up the header?

**Comment by snej** [comment]
It's a submodule; is it checked out? (When doing the 'git checkout` or `git submodule init` of couchbase-lite-core, you have to use the `--recursive` flag.)

**Comment by adamski** [comment]
Yes I did `git submodule update --init --recursive`

The folder in `vendor` is there with all its files..

**Comment by adamski** [comment]
I did `git submodule update --init --recursive`

The folder in `vendor` is there with all its files: `vendor/BLIP-Cpp/vendor/zlibcomplete/lib/zlc/zlibcomplete.hpp`

**Comment by snej** [comment]
That's odd. Exactly what target are you trying to build?
And what are the git SHA IDs of each repo's head?

**Comment by adamski** [comment]
I'm building the "LiteCore dylib" target.

| submodule | SHA ID
|------------|----------
| BLIP-Cpp | b126e05
| SQLiteCpp | 2a688a9
|civetweb | be1146e
|fleece|7d1295f
|openssl | 3d789c7
|snappy | master
|sqlite3-unicodesn | a348530

**Comment by porchdog** [comment]
This is odd.  I cloned the repo using my laptop that is running 10.11.6 and Xcode 8.2.1.  I got the same error with zlibcomplete.hpp while building MessageBuilder.cc.

Then I cloned the repo on desktop running 10.12.4 and Xcode 8.3.2.  No error and everything builds correctly.

Not sure what might have changed in Xcode between the two versions that would cause this to happen.

**Comment by snej** [comment]
OK, that rings a bell — IIRC, the `SYSTEM_HEADER_SEARCH_PATHS` build setting was only added in Xcode 8.3. The BLIPCpp submodule's Xcode project uses it. I'll add a note to the README saying that Xcode 8.3 is required.
