### ISSUE TITLE
Does 2.0.0-DB007 version support replication from server ? 

### ISSUE THREAD

**Issue by zfort-vitalii** [couchbase/couchbase-lite-core#134]
For Swift on the release notes i se this example 
`let url = URL(string: "blip://localhost:4984/db")!
let replication = database.replication(with: url)
replication.start()`

but nothing for Java.
Also i tried to check android example, still nothing.

All i can found is C4Replicator. It looks like the thin i need, but it takes like parameter com.couchbase.litecore.Database which is private on com.couchbase.lite.Database.

Used version is : 2.0.0-DB007

Can any body help me with my problem ?

**Comment by snej** [comment]
You're asking about Couchbase Lite, which is the level above LiteCore. (This repo does have some Java in it, but it's the internal JNI bindings, not the public API.)

The CBL 2.0 Java work is happening in the [couchbase-lite-android](https://github.com/couchbase/couchbase-lite-android/tree/feature/2.0) repo.

**Comment by snej** [comment]
Oh, and to answer your question — I don't believe replication is implemented yet in CBL 2.0 for Java.
