### ISSUE TITLE
Race condition between constructors and delegation for replication

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#135]
So let's follow this path:

1. When creating a new c4Replicator, you may end up in [this constructor](https://github.com/couchbase/couchbase-lite-core/blob/5fec2095c9b510abd9a24f51f7c0a055b05e51e9/Replicator/Replicator.cc#L51-L55)

2. This constructor [delegates to another](https://github.com/couchbase/couchbase-lite-core/blob/5fec2095c9b510abd9a24f51f7c0a055b05e51e9/Replicator/Replicator.cc#L56-L57).  As one of the parameters, a new `Connection` object is created, passing `*this` as the `Replicator::Delegate` object.  However, at this point, the base constructor for that class has not yet been called, so the object is still invalid as a delegate.  

3. The connection object immediately [begins its operation](https://github.com/couchbaselabs/BLIP-Cpp/blob/b126e05a26c9a6d9a8d4736f39323b630ffe217d/src/blip/BLIPConnection.cc#L504) as part of its constructor.

4. Finally, the [delegated constructor](https://github.com/couchbase/couchbase-lite-core/blob/5fec2095c9b510abd9a24f51f7c0a055b05e51e9/Replicator/Replicator.cc#L29) for Replicator can be called and at this point the base constructors are called.  

There is a race, though.  If the web socket closes quickly enough then before step 4 completes, another thread could reach [this line](https://github.com/couchbaselabs/BLIP-Cpp/blob/b126e05a26c9a6d9a8d4736f39323b630ffe217d/src/blip/BLIPConnection.cc#L577) at which point everything goes down because the passed delegate object is still not valid and will be treated as if it were `null` (access violation).

If by chance it wins the race, the next race happens [here](https://github.com/couchbase/couchbase-lite-core/blob/5fec2095c9b510abd9a24f51f7c0a055b05e51e9/Replicator/Replicator.cc#L197).  The replicator has not had a chance to initialize `_checkpoint` yet and so an invalid mutex is used in `LOCK()` inside of `stopAutosave()`

**Comment by snej** [comment]
I think I should add an explicit `start` method to BLIPConnection, rather than starting as soon as the constructor is called.
