### ISSUE TITLE
c4dbobs_getChanges return external = true for local change

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#1413]
I saw the following behavior with current couchbase-lite-core master (c9c67c4dcf35f6dfcd8421544ca3e71f709ba3f2)
1. Client A edit document **X**
2. Client B received notification about change in document **X** via `c4dbobs_getChanges`
    with `outExternal` = true
3. Client B edit document **X**, and receive `outExternal` = true from `c4dbobs_getChanges`

where `outExternal` is paramter of `c4dbobs_getChanges`
```
    uint32_t c4dbobs_getChanges(C4CollectionObserver *observer,
                                C4CollectionChange outChanges[C4NONNULL],
                                uint32_t maxChanges,
                                bool *outExternal) C4API;
```

So if Client A not connected or not edit document, `external` flag setted correctly for local change on client B side,
but after the first external edit, `c4dbobs_getChanges` starts setted `outExternal` to `true` even for local changes.

I fixed it like this:
```
@@ -258,6 +258,8 @@ namespace litecore {
         if (!inTransaction()) {
             entry->committedSequence = sequence;
             entry->external = true; // it must have come from addExternalTransaction()
+        } else {
+            entry->external = false;
         }
 
         // Notify document notifiers:
```

though not sure is this right fix.

**Comment by snej** [comment]
Yes, I think that's the correct fix. The entry should be marked as non-external even if it's already in the change list due to an earlier external change that not all observers have picked up yet.
