### ISSUE TITLE
"Developer Mode" switch

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#143]
It could be useful for developers (and our support team!) if there were a global runtime "Developer Mode" flag in CBL. It defaults to true, but can be turned off with a function call in the public API. Then various stuff in LiteCore and CBL can test this flag, and if it's on, do something that might be more expensive but useful during development.

Developer Mode could do things like:

* Enable more verbose logging
* Log to the console
* Enable some more-expensive assertions

**Comment by djpongh** [comment]
Shouldn't the default be false?

**Comment by snej** [comment]
Well, like logging, we want it to be automatic, so we don't have to tell people (over and over) how to turn it on. Hopefully by the time they've learned enough about CBL to be ready to ship an app, they'll have learned about how to turn it o ff.

**Comment by borrrden** [comment]
Migration worthy?

**Comment by borrrden** [comment]
Migrated to [CBL-231](https://issues.couchbase.com/browse/CBL-231)
