### ISSUE TITLE
Reimplement/optimize doc expiration

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#146]
Expiration was implemented in the CBForest days using only key/value APIs, so it's inefficient. It uses a separate KeyStore with a record for every doc that has an expiration date, and scans through that.

What we can do now is add an `expiration` column to the SQLite table, and use SQL queries to find and purge expired docs. This will be much faster and use less code too.

**Comment by snej** [comment]
There is some talk about changing the semantics of expiration, across Sync Gateway as well as Couchbase Lite. If we're going to touch the implementation in 2.0, we should reimplement it as above. Otherwise this could wait.

**Comment by Fujio-Turner** [comment]
Some people have complained about the local TTL docs being replicated after the app comes back from the background and then push those docs, but TTL clean up hasn't happen on the CBL yet before the push.

**Comment by snej** [comment]
I don't think we need to keep the C4ExpiryEnumerator API -- I can't think of a reason that CBL needs to enumerate the docs to be expired. It's faster for it to just call `c4db_purgeExpiredDocs` and have LiteCore purge them all with one SQL `DELETE`.

**Comment by snej** [comment]
...OK, now merged to master, because I couldn't think of a reason not to. It's an API change, but no one is using the functions that changed.
