### ISSUE TITLE
REST: Query API

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#148]
We'll need to invent and implement a new REST API to expose queries and indexes, since we no longer use views.

I'm thinking:
* `POST /db/_query` — run a one-shot query
* `PUT /db/_query/xxx` — create/update a query named "xxx" (also `GET` to retrieve the query settings and `DELETE` to delete it)
* `POST /db/_query/xxx` — run a saved query (optionally passing parameter values like offset, limit and any named params defined in the query.)
* `GET /db/_query` — returns a list of all query names, i.e. all child resources
* `PUT /db/_index/yyy` — create an index. Exact specification in the JSON body. Also `GET`, `DELETE`.
* `GET /db/_index` — returns a list of all index names, i.e. all child resources

**Comment by snej** [comment]
This would be a big boon for functional testing, as well as for JavaScript developers.

**Comment by adamski** [comment]
Does this mean a departure from the CouchDB style design documents? I know there is already a departure from CouchDB in terms of `filterParams` being incompatible... just wondering if this a sign of further divergence.

**Comment by snej** [comment]
We don't have map/reduce views anymore, so yes. Instead, queries are based on N1QL semantics. (At the LiteCore level, a query is expressed as JSON that's basically like a parse tree of N1QL. There's a pretty detailed spec in the wiki.)

**Comment by snej** [comment]
Design docs made sense for a database server based on a REST API and intended to be used as a web server. For an embedded engine with a native API, they don't.

**Comment by rajagp** [comment]
Related to https://github.com/couchbase/couchbase-lite-ios/issues/1945

**Comment by borrrden** [comment]
Are we still considering this?

**Comment by borrrden** [comment]
Evidently not.
