### ISSUE TITLE
FullTextSearch:  Certain words return no results

### ISSUE THREAD

**Issue by rplankenhorn** [couchbase/couchbase-lite-core#1488]
I am trying to perform a full text search and I noticed that certain words don't seem to return any results even though I know they are indexed.  The words I have found (so far) are "the" and "with".  I'm starting to think that in order to keep indexing sizes low, certain types of words such as articles or prepositions are automatically not indexed.  Is this the case?  If so, are there a list of words that I can reference that Couchbase is using?

**Comment by bmeike** [comment]
Hey @rplankenhorn :  Let me see if I can find someone to answer this.  Let me suggest, also, that a better place to get an answer is here: https://forums.couchbase.com/tag/mobile

**Comment by snej** [comment]
Those are stop-words. See c4IndexTypes.h for how to configure them.
