### ISSUE TITLE
Replicator with unknown hostname (ex: "blip://foo.couchbase.com/db) fails with kC4NetErrDNSFailure, it should be kC4NetErrUnknownHost. 

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-core#149]
CBL Java uses CivetWeb for WebSocket implementation. In the case of running replicator with the unknown hostname (ex: "blip://foo.couchbase.com/db), the replicator fails with (Network, `kC4NetErrDNSFailure` (1)). I expected `kC4NetErrUnknownHost` (2) error. As `kC4NetErrDNSFailure` is a transient error, the replicator will retry. CBL iOS has `void convertError(NSError* error, C4Error *outError)` method to update error code. I guess CivetWeb also requires to implement convertError(...) method?

**Comment by snej** [comment]
The unit test "API DNS Lookup Failure" in ReplicatorAPITests.cc checks for this. The unit tests use CivetWebSocket, so it should be the same scenario you describe.

**Comment by djpongh** [comment]
@hideki is this OK to close?

**Comment by snej** [comment]
ping

**Comment by hideki** [comment]
CBL Android uses OkHttp instead of CivetWeb. I don't have this issue anymore.  I will close this ticket.
