### ISSUE TITLE
Proposal: allow alternativ indexDB storage 

### ISSUE THREAD

**Issue by frank-dspeed** [couchbase/couchbase-lite-core#1496]
Hello i am currently trying to implement Couchbase SDK as wasm because of some demos for the new browser direct socket api.

This Chromium api already allows us to directly connect to a couchbase cluster via the nativ c sdk as this project also uses it and uses the sync function 

i want to build also cblite for the demo with the fleece data structure but stored into indexDB as we got that already in the browser. 

It would be nice if you would enable me to more easy implement that. Via abstraction of the sqlite3 parts so that i can implement it with the indexDB Storage engine via wasm bindgens from the couchbase-lite-rust bindings. i also created a issue in the couchbase-lite-c api to track that effort but i guess 

this repo is the right starting point as the whole code is more or less hard coupled. because the usecase is relative new.

But it will enable to run cblite in browsers and webviews on all devices as also Sync with real couchbase clusters i guess this is a relativ motivating usecase.

**Comment by snej** [comment]
> Hello i am currently trying to implement Couchbase SDK

By this you mean the server SDKs, right? Not Couchbase Lite or LiteCore (which people sometimes call an SDK.)

>i want to build also cblite for the demo with the fleece data structure but stored into indexDB

Last I heard, WASM doesn't yet support threads; LiteCore needs threads to run. I've been looking at WASM every once in a while for years, and there's always something still missing that prevents it being useable for LiteCore.

> It would be nice if you would enable me to more easy implement that. Via abstraction of the sqlite3 parts so that i can implement it with the indexDB Storage engine

At a low level this is already abstracted; look at the abstract classes DataFile, KeyStore, Query, etc. But that abstraction doesn't go all the way up -- the higher levels directly use SQLiteDataFile, etc. Making the whole thing abstract would be way more than a "nice to have", it would be a huge refactoring.

Also, IndexDB is a really primitive database API. LiteCore really does require SQL. I've heard that someone got SQLite itself to run in WASM ... weirdly, it uses IndexDB as its virtual filesystem.

**Comment by frank-dspeed** [comment]
@snej it is not weirdly i am also looking into that and that is exactly the same thing that i want to do replace the filesystem with indexdb. I guess it is do able as you also saw it got done with sqlite3 already 

and the sdk will work without problems once "direct-sockets" is fully implemented there is ongoing effort to expose raw TCP/UDP 
Sockets.

The Filesystem Part in general can already get Solved by the rolled out NativeFilesystem API
