### ISSUE TITLE
Replicator: Puller messes up docs by encoding them without SharedKeys

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#156]
When the puller transcodes an incoming revision from JSON to Fleece, it doesn't use the database's SharedKeys map, so it writes all the keys as regular strings. If one of those keys is already in the SharedKeys, the database will expect it to be abbreviated as an integer, so looking up the key in the document will fail. 😱☠️💩

**Comment by snej** [comment]
The bug is in `IncomingRev::_handleRev`. Unfortunately the optimization of letting the individual IncomingRev objects encode the revs will have to be abandoned — you can only encode a rev using SharedKeys during a transaction, and the SharedKeys object isn't thread-safe. So the encoding has to be done by the DBWorker.

**Comment by pasin** [comment]
Here is the unit test that can reproduce the issue:

```
- (void) testPullDoc {
    NSError* error;
    CBLDocument* doc1 = [[CBLDocument alloc] initWithID:@"doc1"];
    [doc1 setObject: @"Tiger" forKey: @"name"];
    Assert([self.db saveDocument: doc1 error: &error]);
    AssertEqual(self.db.count, 1u);
    
    CBLDocument* doc2 = [[CBLDocument alloc] initWithID:@"doc2"];
    [doc2 setObject: @"Cat" forKey: @"name"];
    Assert([otherDB saveDocument: doc2 error: &error]);
    
    CBLReplicatorConfiguration* config = [self push: NO pull: YES];
    [self run: config errorCode: 0 errorDomain: nil];
    
    AssertEqual(self.db.count, 2u);
    doc2 = [self.db documentWithID:@"doc2"];
    AssertEqualObjects([doc2 stringForKey:@"name"], @"Cat");
}
```
