### ISSUE TITLE
Unexported functions in public headers

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#165]
Putting this here for evaluation.  The following functions are in public header files but not exported in the resulting shared library (warnings are generated during certain kinds of UWP builds):

FLKeyPath_Free
FLKeyPath_Eval
c4blob_computeKey
c4doc_detachRevisionBody
c4queryenum_fullTextMatched
c4socket_closeRequested
FLKeyPath_New
FLKeyPath_EvalOnce

**Comment by snej** [comment]
Ideally we should export these, but if they're not being used, exporting them would just increase the binary size for no practical reason.

**Comment by borrrden** [comment]
So the other choice is to remove them from the header files, because they won't work anyway without exporting them.  They aren't being used because otherwise an exception would be thrown.  Are they being used anywhere else that you know of?

**Comment by snej** [comment]
Keep in mind that the Obj-C version of Couchbase Lite links with the static library of LiteCore, so it doesn't require functions to be exported. They still _should_ be exported for consistency, but this means that lack of export doesn't mean a function is unused..

Also, those Fleece functions are used inside LiteCore, so they can't be removed from the Fleece headers.
