### ISSUE TITLE
Multiple MATCH expressions cause SQLite errors

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-core#166]
Originally filed: https://github.com/couchbase/couchbase-lite-ios/issues/1798

--------
* Version:   CBL 2.0

**The Request:**
Look for a string  in either "description" or "name" property.

**My two FTS indexes are:**

```
     try _db?.createIndex(["airportname"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
        
     try _db?.createIndex(["description"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
        
      try _db?.createIndex(["name"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
```

**Query Expression:**
```
descExp = Expression.property("description").match("'\(descriptionStr)'")
            .or(Expression.property("name").match("'\(descriptionStr)'" ))
```

**This Fails with following error in console**

`SELECT sequence, key, version, flags, offsets("kv_default::.description"), offsets("kv_default::.name") FROM kv_default, "kv_default::.description" AS FTS1, "kv_default::.name" AS FTS2 WHERE fl_value(body, 'type') = 'hotel' AND ((((fl_value(body, 'country') = 'London' OR fl_value(body, 'city') = 'London') OR fl_value(body, 'state') = 'London') OR fl_value(body, 'address') = 'London') AND ((FTS1.text MATCH '''Spa''' AND FTS1.rowid = kv_default.sequence) OR (FTS2.text MATCH '''Spa''' AND FTS2.rowid = kv_default.sequence))) LIMIT $limit OFFSET $offset`
```
0|0|1| SCAN TABLE kv_default::.description AS FTS1 VIRTUAL TABLE INDEX 0:
0|1|2| SCAN TABLE kv_default::.name AS FTS2 VIRTUAL TABLE INDEX 0:
0|2|0| SEARCH TABLE kv_default USING INDEX kv_default_seqs (sequence=?)
0|2|0| SEARCH TABLE kv_default USING INDEX kv_default_seqs (sequence=?)`
```

`2017-06-21 10:10:35.275 TravelSample[75237:35646168] CouchbaseLite  WARNING: SQLite error (code 1): statement aborts at 24: [SELECT sequence, key, version, flags, offsets("kv_default::.description"), offsets("kv_default::.name") FROM kv_default, "kv_default::.description" AS FTS1, "kv_default::.name" AS FTS2 WHERE fl_value(body, 'type') = 'hotel' AND ((((fl_value(body, 'country') = 'London' OR fl_value(body, 'city') = 'London') OR fl_value(body, 'state') = 'London') OR fl_value(body, 'address') = 'London') AND ((FTS1.text MATCH '''Spa''' AND FTS1.rowid = kv_default.sequence) OR (FTS2.text MATCH '''Spa''' AND FTS2.rowid = kv_default.sequence))) LIMIT $limit OFFSET $offset] unable to use function MATCH in the requested context`
```
2017-06-21 10:10:35.275 TravelSample[75237:35646168] CouchbaseLite Query ERROR: CBLQuery failed: 4/1
Error when fetching hotels Optional("unable to use function MATCH in the requested context")`
```

(**Note**: If I just did a match query on description, it works)

**Comment by snej** [comment]
From Richard Hipp on the SQLite mailing list:

>While the query planner is processing the WHERE clause, it passes
>various terms down to FTS4 and asks "can you deal with this?"
>Normally, FTS4 will answer "yes" to a MATCH operator and take full
>responsibility for it, so that the SQLite core does not do any more
>with it.  But in the specific query you have, FTS4 is unable to handle
>the MATCH function and so it answers "no".  Or, maybe due to the OR
>clause, the query planner is not able to factor out the MATCH function
>and so it never even asks.  I'm not sure which, but for whatever
>reason, FTS4 did not take responsibility for handling the MATCH
>operator.

Maybe it's the way that the `FTS2.rowid = kv_default.sequence` join is repeated in each clause? I could try factoring it out, doing it only once.

**Comment by snej** [comment]
More from Dr Hipp:

>Generally speaking, FTS4 (and FTS3 and FTS5) requires no more than one
>MATCH operator  in the WHERE clause for each FTS4 table in the FROM
>clause, and that one MATCH operator must be a conjunct.

By which I think he means that a query using FTS has to be of the form `... WHERE (...rest of predicate...) AND (ftsTable MATCH 'search key')`. This means we should change Couchbase Lite's query API to restrict how FTS matches are specified.
