### ISSUE TITLE
Geospatial support

### ISSUE THREAD

**Issue by raphaelauv** [couchbase/couchbase-lite-core#1723]
Is couchbase-lite supporting Geospatial index and query ?

if no , is there a plan for ? 

Thanks :+1:

**Comment by jianminzhao** [comment]
Hi @raphaelauv ,

Thanks for your query and sorry for the tardiness. It is currently not supported, nor is it planned, but it is in our backlog.

Cheers!

**Comment by raphaelauv** [comment]
@snej it's completed ?

**Comment by snej** [comment]
No, it's not in the current feature list. FYI we don't use Github issues anymore; Couchbase uses [Jira](https://issues.couchbase.com/projects/CBL/issues/CBL-5398?filter=allopenissues&orderby=created+DESC).
