### ISSUE TITLE
MATCH and JOIN in same statement

### ISSUE THREAD

**Issue by hendrik-haase** [couchbase/couchbase-lite-core#1764]
Hey, 
is there a way to have a MATCH and a JOIN in the same query?
I'm trying to do something like this:
`"SELECT foo.* FROM _ AS foo LEFT JOIN _ AS bar ON meta(bar).id = foo.fkbar WHERE foo.type = \"foo\" AND MATCH(ftsix_main, \"abc\")"`

This results in the following error message:
`property 'ftsix_main.' does not begin with a declared 'AS' alias`

How do I tell MATCH to search on foo?

Version: CBL 3.0
I tested it on the swift and c library with the same result.

**Comment by jianminzhao** [comment]
This problem has been fixed in the next 3.0.x release.
