### ISSUE TITLE
Use @type instead of _cbltype to define a custom data type such as blob

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#180]
From the discussion with @snej, LiteCore will provide a constant variable that other platforms can use.

**Comment by snej** [comment]
I just added the constant(s) in commit 7b1474aecc1fe0c135abd582b4cfdc063cd2ad01, but I'm still using the current value, `_cbltype`. Changing the value will break compatibility with existing 2.0 databases containing attachments, but this is probably OK. We should call this out in the DP13 release notes, though.

**Comment by snej** [comment]
We also need the C# and Java code to adopt the named constants before we change the value.

**Comment by borrrden** [comment]
What do you mean by "adopt" them?  If you just mean to use the same values then ok, but C# cannot bind to constant values in unmanaged code and so it cannot use them unless they are returned by a method.

**Comment by snej** [comment]
It's probably not worth your creating native methods just to return those strings, but at least make sure the C# (or Java) string literal only appears once, so it's easy to update. We obviously won't be changing this after 2.0 ships, but it's good for general reasons of DRY.

**Comment by snej** [comment]
This was implemented last week in 8b8635e74ffc5e343f2911df466411c9ed048403.
