### ISSUE TITLE
Support SELECT projection in Query

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#182]
Basically we would like to do the following:

* SELECT name, count(1)
* SELECT name as firstname, count(1) as count

NOTE:
* For function field without the alias name, we could do $1, $2, $3 or we could come up with the other name format.
* On the Query Result (Row), we would need to be able to get the data by key.

**Comment by snej** [comment]
Since you already know what the column names are, can't you just create a mapping from column name to column index, and use that?

In other words, I think this can be done without changes to LiteCore.

**Comment by pasin** [comment]
If SELECT (*) result is always grouped under a key (datasource name), we could do this in Lite.

**Comment by snej** [comment]
I think we can have LiteCore continue to return columns as an array, and do the keyed access in CBL, by having the CBL Query object create a name-to-index mapping based on the "AS" specifications given by the app as it creates the query.

**Comment by pasin** [comment]
If LiteCore continues to return columns as an array, how do you plan to return the following cases?
SELECT *
SELECT _id, *
SELECT *, count*

**Comment by snej** [comment]
1. Single column (value is dictionary containing doc properties)
2. Two columns: string, dictionary
3. Two columns: dictionary, number
4. Two columns: dictionary, dictionary
