### ISSUE TITLE
Support SELECT *

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#183]
From the discussion last week, we would like SELECT * to be able to return the content of the document. 

1. The content will be extracted to the root level for the following Query:
   - SELECT * FROM
   - SELECT * with other projections such as SELECT *, count(*) FROM
2. The content could be grouped to each data source alias name for JOINs query with multiple data sources.

**Comment by snej** [comment]
I don't really understand what you're saying in item 1. Can you explain?

I think it makes sense for "*" to map to a single column in the result. That's the way it's going to come back from the underlying query — as a blob containing a Fleece dictionary.

**Comment by snej** [comment]
Implemented by Jim and merged. The special property name `.*`, used in a `WHAT` column list, represents the entire document.
