### ISSUE TITLE
Improvement - P2P with Fleece

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/couchbase-lite-core#189]
In the new 2.0 couchbase lite core is it possible to replicate data from device to device sending data as fleece itself?
**SAVING**
A 30% saving in transfer can go a long way.
**USAGE**
Exposing fleece directly would encourage other to start natively using fleece

**Comment by snej** [comment]
Currently the replication protocol uses JSON. Mostly because if it used Fleece, I'd have to write a Go implementation of Fleece for the Sync Gateway side. I'd rather not have two different payload data formats; it seems like it'd add more complexity (and testing surface-area) than it's worth...

**Comment by snej** [comment]
Also, the revision bodies are gzip-compressed on the wire, and JSON compresses very well. (Better than Fleece does, actually; Fleece has less entropy to squeeze out.)
