### ISSUE TITLE
Need REST API Bindings.

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-core#19]

**Comment by snej** [comment]
We have a limited implementation of this already, mostly for QE purposes, but it's far from the complete REST API.

Since this issue was filed, we've been leaning more toward creating a direct JavaScript binding to CBL, as a preferred solution for PhoneGap / ReactNative / etc.

**Comment by borrrden** [comment]
Should I bother migrating this?  It seems less and less likely that this is going to happen.

**Comment by borrrden** [comment]
Closing because we won't be doing this.
