### ISSUE TITLE
N1QL 2-parameter trim() functions unimplemented

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#195]
Current status: only issue is that the 2-parameter forms of the trim/ltrim/rtrim functions — which take a string of characters to trim, instead of the default whitespace — aren't implemented.

<strike>The N1QL string functions in LiteCore don't work correctly with non-ASCII strings. They don't handle multi-byte UTF-8 sequences, and they use the plain C `toupper`/`tolower` functions that only transform ASCII letters.

We'll probably need to call into either ICU or CoreFoundation to handle these.</strike>

**Comment by borrrden** [comment]
Is there something more lightweight that we can use?  CoreFoundation is platform specific and ICU the last time I checked is gigantic.

**Comment by snej** [comment]
Didn't we do this before with the JSON collator in 1.x? Its string comparisons needed to be Unicode-aware too.

**Comment by borrrden** [comment]
not at the native level for .net but possibly for Java and android.

**Comment by borrrden** [comment]
@hideki any thoughts?

**Comment by snej** [comment]
The C++ library has functions to work with UTF-8 encoding, and to convert upper/lower case — it's part of the "locale" API.

**Comment by snej** [comment]
We can use the same libraries as in #196 — CFString, ICU, and whatever it is on Windows.

I'm pretty sure that we can't uppercase/lowercase strings simply by iterating over the characters; there's bound to be some language where that doesn't do the right thing (even with ASCII letters.)

**Comment by snej** [comment]
Leaving the issue open till these limitations are fixed:

- [ ] upper() and lower() are only Unicode-savvy on Apple platforms; see StringUtil_Apple.cc. On other platforms they will not transform non-ASCII letters.
- [ ] The two-parameter forms of the trim functions, which trim arbitrary characters, are not yet implemented and will fail with an error.

**Comment by borrrden** [comment]
Correction:  Not only apple but everything except android now :)

**Comment by snej** [comment]
What remains to be done here? I'll assign this to @hideki since it sounds Android-specific at this point.

**Comment by snej** [comment]
OK, this appears complete now except for the 2-parameter `trim` functions, so I'll change the title. We can probably defer this from 2.0.

**Comment by borrrden** [comment]
Migrated to [CBL-119](https://issues.couchbase.com/browse/CBL-119)
