### ISSUE TITLE
Query: String comparisons and ORDER BY are not Unicode-savvy

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#196]
SQLite's string collation doesn't support Unicode; see [the docs](https://sqlite.org/datatype3.html#collating_sequences). It only has binary or ASCII case-insensitive comparisons. The behavior is pretty bad for any non-English strings. 

We will need to register our own Unicode collation function, to do proper sorting. The collation function can then be used in a query expression or index via the `COLLATE` operator.

**Comment by pasin** [comment]
What are the collation names that we support?

**Comment by pasin** [comment]
@snej Can you review the supported [collations](https://github.com/couchbaselabs/couchbase-lite-apiv2/blob/1c50b1e22ab1c9064d61fca84ddd68d212ee446f/query/objc/CouchbaseLiteQuery/CBLQueryExpression.h#L13-L18)?

**Comment by snej** [comment]
This is how I've been envisioning it:

* ASCII (i.e. binary, i.e. SQLite's default)
    * _Maybe a case insensitive option? Not sure_
* Unicode
    * Case sensitive / insensitive
    * Ignore / consider diacritics/accents
    * Localized for language ________

This feels like a set of flags plus a language code. The flags would be like {Unicode, IgnoreCase, IgnoreDiacritics}, where IgnoreDiacritics implies Unicode. Also, specifying a non-null language would also imply Unicode.

The [Unicode Collation spec](http://www.unicode.org/reports/tr10/#Introduction) makes a pretty good case for why the localization option is important: users will be annoyed and may make mistakes if text isn't sorted or matched in the way that they expect:

>Languages vary regarding which types of comparisons to use (and in which order they are to be applied), and in what constitutes a fundamental element for sorting. For example, Swedish treats ä as an individual letter, sorting it after z in the alphabet; German, however, sorts it either like ae or like other accented forms of a, thus following a. In Slovak, the digraph ch sorts as if it were a separate letter after h. Examples from other languages and scripts abound. Languages whose writing systems use uppercase and lowercase typically ignore the differences in case, unless there are no other differences in the text.

>It is important to ensure that collation meets user expectations as fully as possible. For example, in the majority of Latin languages, ø sorts as an accented variant of o, meaning that most users would expect ø alongside o. However, a few languages, such as Norwegian and Danish, sort ø as a unique element after z. Sorting "Søren" after "Sylt" in a long list, as would be expected in Norwegian or Danish, will cause problems if the user expects ø as a variant of o. A user will look for "Søren" between "Sorem" and "Soret", not see it in the selection, and assume the string is missing, confused because it was sorted in a completely different location. In matching, the same can occur, which can cause significant problems for software customers; for example, in a database selection the user may not realize what records are missing.

**Comment by snej** [comment]
Re. the collations in your spec:
* I think we need a case-sensitive Unicode option. One example is for sorting identifiers in Swift or Go :)
* The rtrim option can be emulated by just calling the `rtrim` function on the string to be collated, i.e. `ORDER BY rtrim(name)`. So it doesn't feel necessary to me as a collation.

**Comment by pasin** [comment]
Do I understand correctly that an option can be mixed like, Unicode: Case Insensitive + Ignore Diacritics + "Spanish"?

Do we have a set of language codes that we support? Are we using [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for the language codes?

**Comment by snej** [comment]
Right, they can be combined. And yes, I think that's where the language codes are defined. (We already use those codes for the FTS tokenizer.)

I'm getting some of this from the parameters of `CFStringCompareWithOptionsAndLocale`.

**Comment by snej** [comment]
Current collation spec implemented by LiteCore queries is documented [here](https://github.com/couchbase/couchbase-lite-core/wiki/JSON-Query-Schema#collation). It's fully functional on Apple platforms; elsewhere, we don't have an implementation of Unicode collation yet, so the Unicode-aware options will fail.

I've investigated using C++'s `std::collate`, but it isn't supported on most platforms we've tried.

We may have to call ICU directly.

**Comment by snej** [comment]
@borrrden dug up info on an Android [ICU adapter](https://android-review.googlesource.com/c/121180/) that makes it possible to call into the built-in ICU library. So ICU looks like a good solution for Android as well as general Linux.

Meanwhile Jim is working on an implementation calling the Windows collation APIs.

**Comment by snej** [comment]
@borrrden has verified that the ICU based collator works on Linux, so I think we've got all the platforms covered. Closing now.
