### ISSUE TITLE
Need a way to distinguish boolean types

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#200]
SQLite does not have them but we need them to properly implement things like "isboolean" and proper bool querying (instead of comparing to the numeric value 1)

**Comment by snej** [comment]
I think we can use a value subtype (see the `sqlite3_result_subtype` function) to tag booleans returned from `fl_value` et al, and then detect this in functions like `isboolean`.

**Comment by borrrden** [comment]
Proper boolean querying is still weird...I don't know enough about SQLite to be able to force it to take subtypes into account when querying (or maybe it is impossible and if there is a chance that int and bools will overlap on the same property path in the DB then the user will have to use a combination of `ISBOOLEAN` and the comparison?).  I was able to implement `ISBOOLEAN()` though.

**Comment by snej** [comment]
SQLite value subtypes aren't visible to the result of the query, unfortunately (i.e. there is no sqlite3_column_subtype function), so SQLiteQuery.cc can't detect that a column value is a boolean not an integer. :frowning_face:

**Comment by borrrden** [comment]
FYI the above can be worked around if, for some reason, there end up being keys that are both int and bool depending on the document (although honestly this seems sloppy in the first place) by combining with the `ISBOOLEAN()` function.  What are the remaining items here?

**Comment by snej** [comment]
We can make booleans detectable in results by having the `fl_result` function detect the boolean subtype and wrap that value in Fleece as a boolean. (The same tactic used for returning blobs.)

However, that won't make booleans work completely, because the results of SQLite intrinsic operators like `>` and `LIKE`, are still 0 and 1.

**Comment by borrrden** [comment]
Migrated to [CBL-49](https://issues.couchbase.com/browse/CBL-49)
