### ISSUE TITLE
Possible unintended no-op

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#21]
Record.cc contains a couple calls to `_endian_encode` and `_endian_decode` but these are no-ops due to the lack of an `__ENDIAN_SAFE` define (forestdb defines it in option.h)

**Comment by snej** [comment]
Oh! Good catch! Funny that only those two macros are conditionalized.

I've added the `#define` to Endian.hh (in Fleece) and fixed all the source files that directly include forestdb_endian.h to include Endian.hh instead.
