### ISSUE TITLE
Named index support

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#211]
This is needed for a new API item (indices that support naming so that they can be overwritten and not leave old indices dangling around pulling down performance).  This would involve altering the signatures for two existing methods:

`c4db_createIndex(C4Database* database, C4Slice name, C4Slice propertyPath, C4IndexType indexType, const C4IndexOptions* indexOptions, C4Error* outError) noexcept`
(+ name parameter)

`c4db_deleteIndex(C4Database* database, C4Slice name, C4Error* outError)`
(- propertyPath parameter, - indexType parameter, + name parameter)

Behind the scenes this doesn't involve much for regular indices.  Basically, the name generated for the property path needs to be swapped for the index name and things will work as before.  The challenging part comes from FTS which doesn't use an index, but a virtual table.  That means that instead of automatically being used based on property index, as a normal index would, it needs to be explicitly joined during the query creation.  That means there is a need for some form of mapping between index name and FTS expression on the index.  The current top proposal is to write both the alias and the expression being mapped into the table name of the virtual table and query the sqlite metadata table to find the correct table name for joining (and also during the deletion).  It makes sense to use a simple encoding scheme such as:

`<expression>::<alias>`

Then at query time `LIKE <expression>::%` could be used, and at deletion time `LIKE %::<alias>` could be used.  The order here is important because if I recall correctly, `LIKE` lookups are faster when the wildcard is at the end vs the beginning and deletion will probably not happen as often as queries.  

At creation time, a check for an existing alias will need to be performed and the previous virtual table dropped.

**Comment by borrrden** [comment]
@snej How is the above proposal?

**Comment by snej** [comment]
Sounds good. the query to look up an FTS index by name would be like
```sql
SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '<tablename>::<indexname>::%'
```
where `<tablename>` is the name of the SQLite table for the KeyStore (always `kv_default` in our usage) and `<expression>` is the JSON expression, usually a property, being FTS-indexed.

We'll need to be careful with separators and quoting; for instance, with the above syntax we'd have to quote occurrences of `::` in the index name.

>if I recall correctly, LIKE lookups are faster when the wildcard is at the end vs the beginning and deletion will probably not happen as often as queries.

Performance shouldn't be a concern here, because creating queries doesn't happen that often.

**Comment by snej** [comment]
An easy option for quoting could be to JSON-encode the whole FTS table name, of the form `[<tablename>, <indexname>, <expression>]`, for example `["kv_default","articles",".article.text"]`. That makes it easy to encode and decode.

**Comment by borrrden** [comment]
> We'll need to be careful with separators and quoting; for instance, with the above syntax we'd have to quote occurrences of :: in the index name.

In light of that, and thinking of the KISS principle would it make more sense to store this information in a separate table (e.g. kv_fts_map)?

**Comment by snej** [comment]
Notes for documentation: 

* There are separate namespaces for value and FTS indexes. Or in other words, the (name, indexType) pair has to be unique. (That wasn't a design decision, it's just a result of how it's implemented.)
* It's illegal, as well as pointless, to create two FTS indexes on the same property, even with different names.
