### ISSUE TITLE
Blank-tombstone optimization for replication protocol

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#212]
Pasin and Adam noted today that, since the vast majority of tombstone revisions are empty (except for the implied `_deleted:true` metadata property), they don't need to be downloaded. Instead, the replicator can just include an "empty" flag in the [`changes`](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#changes) message for a revision that has no properties. Then the recipient can add the revision immediately.

**Comment by adamcfraser** [comment]
Can the same optimization be applied when users lose visibility to a non-deleted doc (`_removed:true`)?

**Comment by snej** [comment]
We could add a flag for that too...

Will implementing this require extra work for SG? I was thinking of how to add it to `blip_sync.go`, but realized I'd have to fetch every document that the changes feed says is deleted, to make sure it has no other properties. To do this cheaply, I think the "no other properties" flag would have to exist on the change items cached by the feed.

**Comment by borrrden** [comment]
Migrated to [CBL-120](https://issues.couchbase.com/browse/CBL-120)
