### ISSUE TITLE
Update SQLite to 3.21 when released

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#216]
We're using the copy of SQLite embedded in the SQLiteCpp submodule. Currently I think that's 3.18. The latest release (as of Aug 17 2017) is 3.20; we should update.

**Comment by borrrden** [comment]
Keep in mind that we will have to go through this same dance again when we switch to sqlcipher since sqlite source is also included there and will supercede the sqlite source from sqlitecpp.

**Comment by snej** [comment]
I think we can close this; we're now building from SQLCipher sources.

**Comment by snej** [comment]
Our SQLCipher source code incorporates SQLite 3.15.2, which is out of date. We should update it to 3.20. Reopening.

(Issue #249 seems to be directly caused by using this version; it goes away with 3.19.)

**Comment by snej** [comment]
SQLite 3.20 has a bug that causes crashes in ANY/EVERY operations in queries. The fix will be in 3.21. For now we're on 3.19 but we should upgrade to 3.21 when it's released.

**Comment by snej** [comment]
3.21 [was released](http://www.sqlite.org/releaselog/3_21_0.html) on Oct 24; somehow I missed the announcement. @borrrden says on HipChat that "3.21 based SQLCipher passes all native tests."

**Comment by borrrden** [comment]
Closed in commit 605ddd5ad256274b7347fdf479ee167f6f1341c5
