### ISSUE TITLE
unknown type name 'C4BlobKey'

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#228]
I'm getting a build error: `unknown type name 'C4BlobKey'`
After trying to use `c4db_encodeJSON` in order to get data ready for saving to a document. 

I've added 
```cpp
#include "c4Document+Fleece.h"
#include "c4BlobStore.h"
```
But I still get this error. I suspected a circular reference might be causing this. Any tips? 

I'm using the C API in a C++ project.

**Comment by snej** [comment]
What line does the build error occur at?

Try changing it to
```c
#include "c4.h"
#include "c4Document+Fleece.h"
```

**Comment by adamski** [comment]
Thanks, that sorted it.
