### ISSUE TITLE
Error writing document

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#229]
I'm getting an error from `c4doc_put ` with code: 25, domain: 1.

Not sure what might be going wrong. Is there a reference somewhere for the error codes? 

Relevant code below. I'm using the JUCE library and its String class appears here, as well as a method to convert it to a C4Slice (copying from `couchbase-lite-ios`). 

```cpp
    //...
    C4DocPutRequest put = {};
    put.docID = doc->docID;
    if (doc) {
        put.history = &doc->revID;
        put.historyCount = 1;
    }
    put.save = true;

    String bodyStr = "{ \"test\": \"" + String(rand() % 100 + 1) + "\" }";
    C4SliceResult body = c4db_encodeJSON(c4db, String2slice (bodyStr), &err); 

    put.body = {body.buf, body.size};

    C4Error outErr;

    // Save to database:
    C4Document* outDoc = c4doc_put(c4db, &put, nullptr, &outErr);
    c4slice_free(body);

    if (outDoc == nullptr)
    {
        printError(&outErr, "error writing document"); // prints out error code and domain alongside message
        return 1;
    }
```

I can see the SQLite db files are created, and `c4db_open` and `c4db_get` both return non-null values.

**Comment by borrrden** [comment]
Error codes are in c4Base.h.  Domain 1 (LiteCore) means C4ErrorCode is being used.  25 is `kC4ErrorNotInTransaction` so I think you can figure out what the problem is from that :).

**Comment by adamski** [comment]
Yep good clue. Problem sorted, at least that one anyway. I guess every put statement (or bunch of then) need to be wrapped in a begin/end transaction.

**Comment by snej** [comment]
There are also functions in c4Base.h to get an error message from a C4Error; these are good for logging errors in your code.
