### ISSUE TITLE
Empty result from c4db_encodeJSON

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#232]
Continuing my initial tests of LiteCore, I'm having trouble getting data encoded for writing to a document. 

I've simplified my code to
```c
C4SliceResult body = c4db_encodeJSON(c4db, c4str("{ test: 1 }"), &err);
```

However, debugging this it seems that body is `null`.
 
Screenshot attached (I'm using AppCode):
<img width="681" alt="screen shot 2017-08-24 at 00 39 37" src="https://user-images.githubusercontent.com/14980/29643147-1964a40c-8865-11e7-8148-57fe7efbe09a.png">

Am I using the function correctly?

**Comment by borrrden** [comment]
For one thing, that doesn't look like valid JSON (no quotes around the key).

**Comment by adamski** [comment]
Adding quotes around the key does not seem to make a difference:
```cpp
C4SliceResult body = c4db_encodeJSON(c4db, c4str("{ \"test\": 1 }"), &err);
```

I got something working finally using FLEncoder, copying some code from #230:
```cpp
    FLEncoder enc = FLEncoder_New();
    FLEncoder_BeginDict(enc, 1);
    FLEncoder_WriteKey(enc, FLSTR("number"));
    FLEncoder_WriteInt(enc, 123);
    FLEncoder_EndDict(enc);
    auto result = FLEncoder_Finish(enc, nullptr);
```

Then I can see the data has been saved 👍 

I'd still like to know why `c4db_encodeJSON` isn't working - I assume it just needs to be a valid JSON string?

**Comment by borrrden** [comment]
Well, what does `err` say?

**Comment by adamski** [comment]
Ah ok, should have checked that, "not in transaction" (again!) - so I realise I need to put begin transaction right after the first get.. I assumed a transaction only involved writing, not encoding JSON!

**Comment by borrrden** [comment]
It's not just encoding JSON, but encoding it in a way that is specific to the database that you passed.  That means that it could alter the state of the database potentially which is why it needs a transaction.  There are a number of functions in the lite-core API that require transactions, but I think you know how to figure out when you've run afoul of the rules now :).
