### ISSUE TITLE
ANY query with variable.key-path returns zero result

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#238]
Data (3 docs):
```
{"paths":[{"city":"San Francisco"},{"city":"Palo Alto"},{"city":"San Jose"}]}
{"paths":[{"city":"Mountain View"},{"city":"Palo Alto"},{"city":"Belmont"}]}
{"paths":[{"city":"San Francisco"},{"city":"Redwood City"},{"city":"San Mateo"}]}
```

JSON Query:
```
{"WHERE":["ANY","path",[".paths"],["=",["?path","city"],"San Jose"]],"WHAT":[["._id"]]}
```

Explain:
```
SELECT sequence, key, version, flags, key FROM kv_default WHERE EXISTS (SELECT 1 FROM fl_each(body, 'paths') AS _path WHERE fl_value(_path.pointer, 'city') = 'San Jose')
0|0|0| SCAN TABLE kv_default
0|0|0| EXECUTE CORRELATED SCALAR SUBQUERY 1
1|0|0| SCAN TABLE fl_each AS _path VIRTUAL TABLE INDEX 2:
```

Result: 0

**Comment by pasin** [comment]
If I switched the variable expression to `["?path.city"]` format as follows:

```
{"WHERE":["ANY","path",[".paths"],["=",["?path.city"],"San Jose"]],"WHAT":[["._id"]]}
```

Result: WARNING: Invalid LiteCore query: Invalid variable name 'path.city' as reported in (https://github.com/couchbase/couchbase-lite-ios/issues/1875).

**Comment by snej** [comment]
I added a LiteCore unit test equivalent to the first situation, and it returns the correct document. If I change the queried city to "Palo Alto", it returns two documents. The SQL looks the same as what you logged.

The second form, with `["?path.city"]`, isn't currently recognized by the parser. (Even though the docs say it is.) Do you need LiteCore to handle that? I can add it, but it'll increase the complexity of the parser.

**Comment by pasin** [comment]
> I added a LiteCore unit test equivalent to the first situation, and it returns the correct document. If I change the queried city to "Palo Alto", it returns two documents. The SQL looks the same as what you logged.

I will retest from CBL side.

> The second form, with ["?path.city"], isn't currently recognized by the parser. (Even though the docs say it is.) Do you need LiteCore to handle that? I can add it, but it'll increase the complexity of the parser.

CBL is currenty using this pattern, but we can change it to use the array pattern instead. So the answer is that CBL doesn't need it.

**Comment by snej** [comment]
From the original bug report, it looks like the path comes from the app, so it would be good for LiteCore to parse it. OK.

**Comment by pasin** [comment]
Confirmed the fix. 

> I will retest from CBL side.

I have a bug in my unit test which instead of creating 3 docs, it kept updating the same doc.
