### ISSUE TITLE
Adding COLLATE to FTS index expression doesn't work

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#239]
You should be able to specify the collation of an FTS index by wrapping the JSON COLLATE operator around the expression to be indexed. Unfortunately it doesn't work.

- [ ] The COLLATE operator appears in the FTS table name since it contains the JSON form of the expression.
- [ ] But the collation is ignored when generating the query SQL; it just uses a table name based on the uncollated expression.
- [ ] Also, I don't think the settings of the COLLATE operator are used when creating the FTS table.

This should be fixed as it will clean up both the C4 and the CBL APIs (i.e. we can get rid of C4IndexOptions.)

**Comment by borrrden** [comment]
Migrated to [CBL-50](https://issues.couchbase.com/browse/CBL-50)
