### ISSUE TITLE
Create partial indexes with NOT NULL to reduce index size

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#244]
Now that we're on the latest SQLite, we can use the Partial Indexes feature, i.e. a WHERE clause in a CREATE INDEX. This will be useful in the indexes we generate, to avoid having lots of `null` values in the index for docs that don't contain the property/expression.

**Comment by pasin** [comment]
Do we need the same for FTS index?

**Comment by snej** [comment]
I did some experimentation with eliminating nulls from indexes, and it seems to work fine -- the index gets used even when I don't explicitly test for null in the query, because the optimizer knows that '=' is never true if either side is null.
```
sqlite> .schema
CREATE TABLE docs (a int, b int);
CREATE INDEX ia_n on docs (abs(a)) where abs(a) not null;
sqlite> explain query plan select * from docs where abs(a)=2;
QUERY PLAN
`--SEARCH TABLE docs USING INDEX ia_n (<expr>=?)
sqlite> explain query plan select * from docs where abs(a) > 5;
QUERY PLAN
`--SEARCH TABLE docs USING INDEX ia_n (<expr>>?)
sqlite> explain query plan select * from docs where abs(a) is null;
QUERY PLAN
`--SCAN TABLE docs
```

**Comment by borrrden** [comment]
Migrated to [CBL-121](https://issues.couchbase.com/browse/CBL-121)
