### ISSUE TITLE
Remove default columns from query results (docID, body, sequence…)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#245]
For historical reasons, query results always include the docID, revID, sequence and doc body. This is a waste since the current CBL query API doesn't use those, just the custom columns defined by the query's WHAT clause.

- [x] Remove the default columns from SQLiteQuery.cc
- [x] Remove the accessors/fields from the c4Query API
- [x] Fix unit tests that use these
- [ ] Fix any CBL code that still relies on these (CBLPredicateQuery?)

**Comment by snej** [comment]
* Queries don't always return the docID, sequence, revision ID, flags; they return only the columns specified in the WHAT clause of the query.
* If there is no WHAT clause, docID and sequence are returned by default, as the first two indexed columns.
* Removed C4QueryEnumerator fields docID, docSequence, revID, docFlags.
* Added C4QueryEnumerator field fullTextID.
* Removed function c4queryenum_fullTextMatched().
* c4query_fullTextMatched() now takes a fullTextID value, not a docID and sequence.

Implemented and pushed to branch `feature/c4query_cols`. Not on `master` yet because the CBL implementations need to adapt to the [API changes](https://github.com/couchbase/couchbase-lite-core/commit/43a860827e105e879419d24acad68d1ee64cb934#diff-09da42994da1449985d0a9c4d80032a1).

**Comment by snej** [comment]
There's a CBL/iOS branch `feature/2.0-c4query_cols` that's compatible with this change (see commit linked above.)

**Comment by borrrden** [comment]
I've made the relevant changes in this repo, and so this branch will not be blocked by .NET.  Any further CBL changes on .NET can be done out of band because the submodule will stay back until it is ready.
