### ISSUE TITLE
Attachments in auto upgraded DB from 1.x is not accessible through getBlob()

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-core#248]
https://github.com/couchbase/couchbase-lite-android/issues/1286

Attachment data from 1.x does not contain "@type" with "blob". So getBlob() does not work.
```json
    {attach1={digest=sha1-P1i5kI/sosq745/9BDR7kEghKps=, length=7, stub=true, revpos=2, content_type=text/plain}}
```

from Jens:
> The new plan is that CBL will recognize an `_attachments` property and treat dictionaries inside it as blobs. For compatibility with pre-existing documents, and docs replicated (via SG) from 1.x or CouchDB/PouchDB.

**Comment by snej** [comment]
This is intentional. We can't insert the "@type" property because it would modify the revision -- but revisions are immutable.
You'll need to modify Couchbase Lite to recognize this as a blob even without that property.

**Comment by rashidmdk** [comment]
Would yo guys please suggest any solution of this issue currently. I am facing the same issue. I just upgraded couchbase lite from 1.0.4 to 1.4 and getting same issue. Following query is unable to load json of blob.

Line No. 219

Query: 

> SELECT sequence, revid, parent, current, deleted, json, no_attachments FROM revs WHERE doc_id=? ORDER BY sequence

Method: private Status importDoc(String docID, long docNumericID){...} 

Class Name: DatabaseUpgrade

Jar: couchbase-lite-java-core-1.4.0

**Comment by snej** [comment]
@rashidmdk Sorry, wrong repo — Couchbase Lite 1.4 doesn't use couchbase-lite-core; it's only in 2.0. Please file the issue in [couchbase-lite-java-core](https://github.com/couchbase/couchbase-lite-java-core/issues) instead.
