### ISSUE TITLE
pull replication _bulk_get settings

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/couchbase-lite-core#257]
have options for changing _bulk_get amount from a default to a user defined amount. This lets user define how many docs to pull down per _bulk_get call to optimize for docs sizes that are very small , but have a lot of them.

**Comment by snej** [comment]
`_bulk_get` is part of the v1 REST protocol. LiteCore uses the [v2 WebSocket/BLIP based protocol](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol). The issue you're talking about doesn't apply to the new protocol; every revision is sent as a separate request, but the overhead per request is a lot lower.
