### ISSUE TITLE
Resumable Upload/Download of Attachments	

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#272]
_From @ssmotra on October 6, 2017 4:14_

- Resume downloading of attachments from the point of failure/suspend rather than downloading from beginning.

- Resume uploading of attachment from point of failure/suspend rather than uploading from beginning.

_Copied from original issue: couchbase/couchbase-lite-ios#1922_

**Comment by snej** [comment]
This will require (minor) changes to the replication protocol to request and send a partial attachment.

It will also require changes in SG to handle the protocol changes and to store partially-uploaded attachments.

**Comment by borrrden** [comment]
Migrated to [CBL-122](https://issues.couchbase.com/browse/CBL-122)
