### ISSUE TITLE
2.0: Behavior of count() with an Integer 

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-core#273]
Platform : CBL 2.0, DB 16

The purpose of count() with an integer value is unclear as I am seeing the same result regardless of whether I pass in a zero or non zero value.

**Case 1:**
`
let searchQuery = Query
        .select(SelectResult.expression(**Function.count(1)**).as("NumHotels"))
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("hotel"))
        .limit(limit)
`
Returns 
[["NumHotels": Optional(917)]]

**Case 2:**
`
let searchQuery = Query
        .select(SelectResult.expression(**Function.count(0)**).as("NumHotels"))
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("hotel"))
        .limit(limit)
`
Returns (same as Case1) 
[["NumHotels": Optional(917)]]

(CC @hideki , @pasin , @borrrden )

**Comment by snej** [comment]
This is correct behavior. `count()` is defined in SQLite as:

>`count(X)`
>`count(*)`
>The `count(X)` function returns a count of the number of times that X is not NULL in a group. The `count(*)` function (with no arguments) returns the total number of rows in the group.
