### ISSUE TITLE
Remote cblite data file

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#274]
I'm thinking of trying to add support for an IPFS based data file, so that a simple data set could be persisted and queried via different LiteCore based clients. In terms of new transactions it would probably need two copies, original from IPFS and local with changes, using local to local replication. These feels a bit long winded but might just do what I'm after: serverless key-value data store accessible from cross-platform client applications.

Any glaring issues with this idea? What I'd really like is a p2p database similar to IPFS, where a given database or subset of data can be identified from its unique (and permanent) hash. Thats CouchDB compatible..!

**Comment by snej** [comment]
LiteCore can save past revisions of documents; there's a C4RevisionFlag that says "don't discard when updated".

This all sounds pretty doable; it might work similarly to the replicator. I know I've looked into IPFS in the past but I don't remember any details; how does it manage mutable data? Does it have a notion of a revision ID? Or I guess the hash of the data may form the revision ID, in which case there's a different identifier for the document itself?

**Comment by snej** [comment]
I'm going to close this, because we don't use Github issues for Q&A. But please feel free to talk about this on the Couchbase web forum or mobile mailing list.
