### ISSUE TITLE
Remove C4DocEnumerator; it’s unnecessary & unused

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#275]
The C4DocEnumerator API isn't necessary anymore, since queries can do the same thing more flexibly. Couchbase Lite 2 doesn't use it. So we could remove the API and implementation from LiteCore.

However, C4DocEnumerator is currently being used by the implementation of document expiration. So that makes #146 a prerequisite for removing it.

**Comment by snej** [comment]
I ripped unused functionality out of C4DocEnumerator as part of improving code coverage; see commits 295f8a775c506eb63ac067e1f5a0ca16da59d588 and 412df3d32c0354f6710cfe89cbd64e43fa0cd0c4.

But note that the replicator also uses C4DocEnumerator.

**Comment by snej** [comment]
Remaining users of C4DocEnumerator are:
- [ ] `DBWorker::_getChanges` (in the replicator)
- [ ] `RESTListener::handleGetAllDocs` (REST listener)
- [ ] `CBLiteTool::listDocs` (cblite tool)
- [ ] `DbEndpoint::exportTo` (cblite tool)

These can all be replaced by C4Query.

**Comment by borrrden** [comment]
Migrated to [CBL-51](https://issues.couchbase.com/browse/CBL-51)
