### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-core#28]

**Comment by borrrden** [comment]
**NATIVE BUILD**
- [X] Android arm64-v8a
- [X] Android armeabi-v7a
- [X] Android x86
- [X] CentOS
- [X] iOS
- [X] Mac OS
- [X] Ubuntu
- [X] Windows x86
- [X] Windows x64

**NATIVE TEST**
- [ ] Android arm64-v8a
- [ ] Android armeabi-v7a
- [ ] Android x86
- [X] CentOS
- [ ] iOS
- [X] Mac OS
- [X] Ubuntu
- [X] Windows x86
- [X] Windows x64

**.NET INTEROP BUILD**
- [X] .NET Standard 1.1

**.NET INTEROP TEST**
- [ ] Android
- [ ] iOS
- [X] Mac OS
- [X] Ubuntu
- [X] Windows

**JNI BUILD**
- [ ] Java v?

**JNI TEST**
- [ ] Android
- [ ] iOS
- [ ] Mac OS
- [ ] Ubuntu
- [ ] Windows

**Comment by hideki** [comment]
http://hub.internal.couchbase.com/confluence/display/cbeng/CBMLiteCoreTracking

**Comment by borrrden** [comment]
This is set up now. Android just needs to get migrated to a machine that is capable of supporting x86 emulators.
