### ISSUE TITLE
Add N1QL array_agg() function

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#280]
Add the N1QL `array_agg()` function, which is used in grouped query results to collect all the aggregated values as an array.

**Comment by borrrden** [comment]
Probably dependent on #132 (Currently no way to set sqlite3_result as an array)

**Comment by snej** [comment]
NOTE: The order of items in the array produced by `array_agg` is **undefined** and is not affected by `ORDER BY` clauses. This is because SQLite does not guarantee any ordering of the values passed to an aggregate function.
