### ISSUE TITLE
SIGSEGV on x86 Android

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#29]
For some reason the CppTests immediately segfault on Genymotion when compiled in release mode.

Details on a SO question I made:
https://stackoverflow.com/questions/40927350/why-does-declaring-this-variable-globally-cause-a-segfault

**Comment by snej** [comment]
I'm suspecting some x86 codegen bug since this only happens on Genymotion of all the platforms we've run Litecore on. Maybe adding an explicit copy constructor to `slice` would help; try adding these lines to slice.hh around line 58:
```c++
        constexpr slice(const slice &s)             :buf(s.buf), size(s.size) {}
        slice& operator= (const slice &s)           {buf = s.buf; size = s.size; return *this;}
```

**Comment by borrrden** [comment]
Adding those did not change the behavior, and I've confirmed this happens in the stock x86 Android emulator as well (but not, as expected, in the ARM emulator)

**Comment by borrrden** [comment]
[This line](https://github.com/couchbase/couchbase-lite-core/blob/5e0a599425fb719f3fa0c8055291c9c5ffba0037/LiteCore/VersionVectors/VersionVector.cc#L129) causes the problem, and changing it to `emplace_back` *does* work but only if that constructor is not private, or possibly friended somehow.

**Comment by snej** [comment]
Weird! Yes, I ran into that problem calling the constructor — it's a limitation of the way `emplace_back` is implemented, I guess. I found a clever workaround on SO, though...

**Comment by snej** [comment]
Actually it turned out I could just remove that private constructor and use the public one instead; the private functionality wasn't needed anymore.
