### ISSUE TITLE
c4queryenum_nameOfColumn has incorrect results

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#290]
"DB Query WHAT" test in c4QueryTest.cc:
```
> c4QueryTest.cc:287: FAILED:
  CHECK(c4query_nameOfColumn(query, 0) == C4STR("name.first"))
with expansion:
  slice["fl_value(body, 'name.first')"]
  ==
  slice["name.first"]
```

**Comment by snej** [comment]
But what should the name of a column be? For a simple property value like this one it's clearly just the property path, but in general it seems like it would have to be the N1QL syntax of the expression. That would imply adding a bunch of code to generate N1QL, maybe as a separate mode of QueryParser?

**Comment by borrrden** [comment]
We add the names in CBL, so perhaps they should be blank unless added?
