### ISSUE TITLE
ReplicatorAPITest prone to deadlocks with ThreadedMailbox

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#293]
It's hard to get this to happen but it happens on both Windows and Linux (the faster the machine and especially the disk, the more prone it is to happen).  Here is a sample of some of the output:

> 21:52:54 21:52:46.954952| -------- Creating 140 docs --------
21:52:54 21:52:46.959998| [Sync]: {179} Notified of 100 db changes #4831 ... #4930
21:52:54 21:52:46.960676| [Sync]: {179} Notified of 40 db changes #4931 ... #4970
21:52:54 21:52:46.960708| [Sync]: {183} Read 100 changes: Pusher sending 'changes' with sequences 4831 - 4930
21:52:54 21:52:46.961157| [Sync]: {183} Read 40 changes: Pusher sending 'changes' with sequences 4931 - 4970
21:52:54 21:52:47.011964| [BLIP] WARNING: {185} Bad incoming request number 3398
21:52:54 21:52:47.012003| [BLIP] WARNING: {185} Bad incoming request number 3399
21:52:54 21:52:47.060937| -------- Creating 142 docs --------
21:52:54 21:52:47.065753| [Sync]: {179} Notified of 100 db changes #4971 ... #5070
21:52:54 21:52:47.065790| -------- Done creating docs --------
21:52:54 21:52:47.065842| [DB]: Closing DataFile
21:52:54 21:52:47.066574| [Sync]: {179} Notified of 42 db changes #5071 ... #5112
21:52:54 21:52:47.066608| [Sync]: {183} Read 100 changes: Pusher sending 'changes' with sequences 4971 - 5070
21:52:54 21:52:47.067313| [Sync]: {183} Read 42 changes: Pusher sending 'changes' with sequences 5071 - 5112
21:52:54 21:52:47.117938| [BLIP] WARNING: {185} Bad incoming request number 3400
21:52:54 21:52:47.117970| [BLIP] WARNING: {185} Bad incoming request number 3401
21:52:54 21:52:47.156914| >> Replicator is busy, progress 51120/81792, 3195 docs
21:52:57 21:52:50.175916| [Sync]: {180} Saving remote checkpoint cp-SgpszJhV8EuUChbyFlWYu8P1tgA= with rev='1-cc' ...

The last Windows job has been stuck for hours after this and needs to be manually aborted

**Comment by snej** [comment]
Can you get an all-threads dump?

**Comment by borrrden** [comment]
I remember last time that actually nothing was happening in the threads (all were waiting for their next message).  I think this is not a hang in LiteCore but a hang in the tests, but brought on by some fishy mailbox behavior (i.e. the test is waiting for a condition that never comes but should).  If I am in a state where I can once again retrieve a thread dump then I will post it here.

**Comment by borrrden** [comment]
I just noticed that I had a hung test running on my machine since yesterday and I didn't notice.  The thread dump is less than interesting.  There are 6 threads:

The main thread is waiting for the test replication to finish
The next 4 are waiting for new mailbox messages
The final is in `Timer::Manager::run()`

Click on the below image for full size.

![replicatortesthang](https://user-images.githubusercontent.com/2470288/32578819-05a867f6-c522-11e7-97cf-c2b825c438b5.png)

**Comment by snej** [comment]
OK … maybe the full logs will be more interesting. Are they available somewhere?

**Comment by borrrden** [comment]
Hmmm luckily I left the test there hung, so the logs are all in the console window...I'll see if I can copy them here.

**Comment by snej** [comment]
The warnings like "{185} Bad incoming request number 3398" are worrisome, and could point to the root cause. They indicate a protocol error where the other side sent a message with an invalid message number, or else the local code misread the message number. The message is ignored; if it was something important like a response to a request, it could cause the replicator to wait forever.

(Which indicates, come to think of it, that I should create a timeout for responses in the BLIP implementation.)

**Comment by borrrden** [comment]
Could this happen from out of order scheduling?

**Comment by borrrden** [comment]
Here are the logs.  I cut out the portions that don't deal with the failing test

[HangLogs.txt](https://github.com/couchbase/couchbase-lite-core/files/1455727/HangLogs.txt)

**Comment by snej** [comment]
>Could this happen from out of order scheduling?

All of the message numbering and parsing happens in a single actor. If async calls to that actor ran in the wrong order, it could certainly cause problems like this (but I think it'd be causing worse problems elsewhere in the replicator.)

**Comment by borrrden** [comment]
New symptom:

> d:\development\couchbase-lite-net-2\vendor\couchbase-lite-core\replicator\tests\ReplicatorLoopbackTest.hh(103): FAILED:
  CHECK( _statusReceived.progress.unitsCompleted == _statusReceived.progress.unitsTotal )
with expansion:
  0 == 32

**Comment by borrrden** [comment]
Verbose logs for a hung run (last 100 lines):

[text_log_last_100.txt](https://github.com/couchbase/couchbase-lite-core/files/1456009/text_log_last_100.txt)

**Comment by borrrden** [comment]
Verbose logs for a hung run:

[text_log_take_2.txt](https://github.com/couchbase/couchbase-lite-core/files/1456033/text_log_take_2.txt)

**Comment by borrrden** [comment]
Verbose logs for hung run:

[text_log_last_100.txt](https://github.com/couchbase/couchbase-lite-core/files/1456036/text_log_last_100.txt)

**Comment by borrrden** [comment]
Upgraded logs:

I managed to get verbose (both BLIP, pusher / puller computeActivity) logs for all four cases (note these are full logs, ~20 MB each except for the third one since replication fails to start).  I also disabled throwing exceptions for the incorrect BLIP request number (instead log the error, as you will see), and added an arbitrary timeout to the replication so that the test would run to completion, thus flushing all the logs to disk.

- Successful run ([fast_push_success.txt](https://github.com/couchbase/couchbase-lite-core/files/1456316/fast_push_success.txt))
- BLIP Error with pendingRequest ([fast_push_blip_error.txt](https://github.com/couchbase/couchbase-lite-core/files/1456319/fast_push_blip_error.txt))
- Early failure with message as desribed above in "New Symptom" ([fast_push_early_fail.txt](https://github.com/couchbase/couchbase-lite-core/files/1456320/fast_push_early_fail.txt))
- Hang with no error messages, and incomplete total ([fast_push_late_hang.txt](https://github.com/couchbase/couchbase-lite-core/files/1456322/fast_push_late_hang.txt))

**Comment by borrrden** [comment]
I wrote a program to analyze these logs and here is what I found about the flow of BLIP messages.  The program will check to see if any messages got lost on their request -> received -> response -> received path.

- Successful run
    - 5208 messages total
    - Message 2 not responded to (kNoReply?)

- BLIP Error
    - 4652 messages total
    - Message 2 not responded to (kNoReply?)
    - Messages 4405 - 4652 not received

- Early Failure
    - 3 messages total
    - Message 2 not responded to (kNoReply?)
    - Response to message 3 not received

- No error hang
    - 5207 messages total
    - Message 2 not responded to (kNoReply?)
    - Response to message 1892 not received
