### ISSUE TITLE
FTS: Multiple ‘columns’ in one index

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#295]
Per Wayne, customers need to be able to query multiple doc properties in one FTS match query, using OR / AND. Since SQLite's support for multiple MATCH expressions in one SELECT is very limited, we'd need to do this by using a single FTS index with multiple 'columns' for the different properties. (I'm sure this also has better performance than multiple indexes.) Then the RHS of the MATCH expression can use a column name plus ':' to indicate a column. ([See SQLite docs](http://www.sqlite.org/fts3.html#full_text_index_queries).)

c4db_createIndex already supports multiple expressions (in a regular index they're used for primary/secondary/etc keys), so the API already exists. However, these don't have meaningful names to use in a query. We might need to make this a dictionary.

In the implementation, we'd create an FTS4 virtual table with a column for each expression, then add the necessary expressions to the INSERT statement that populates the table.

**Comment by snej** [comment]
There are some problems with this, since currently the MATCH operator takes a property name as its left-hand side:

* If you create an FTS index on multiple properties, how do you specify that you want to search the entire index, not just one of the properties?
* It'll be possible for a property to be included in multiple indexes, potentially with different index options. If you match this property, which index should be used?

**Comment by pasin** [comment]
Can we do something like this? Basically, users specify FTS index name to match.

```
Index ftsIndex = Index.ftsIndex(“title”, “description”);
db.createIndex(“titleAndDescription”, ftsIndex);

Query
	.select()
	.from(db)
	.where(Expression.property(“color”).equals(“red”)
		.and(Expression.fts(“titleAndDescription”).match(“Jeans”))
	.orderBy(Function.rank(“titleAndDescription”));
```

**Comment by snej** [comment]
That seems good. In the JSON query format, the first arg of a 'MATCH' node would be the name of the FTS index.

**Comment by snej** [comment]
Part 2 is 683b164, part 3 is c75a9a1. Release notes:

### API changes:
* Removed C4FullTextID.
* Renamed C4FullTextTerm --> C4FullTextMatch,
  Renamed its field 'termIndex' --> 'term',
  Prepended fields 'dataSource', 'property'.
* Renamed C4QueryEnumerator fields:
  'fullTextTermCount' --> 'fullTextMatchCount',
  'fullTextTerms' --> 'fullTextMatches'.
* c4query_fullTextMatched() now takes a C4FullTextMatch parameter
  instead of a C4FullTextID.

### Functional changes:
* An FTS index can now be created on multiple properties, i.e. the
  array in the `expressionsJSON` parameter of c4db_createIndex() may
  now contain more than one item.
* By default, search terms are matched in any of the indexed
  properties of a document. Prefixing a search term with the name of
  a property and a ":" (e.g. "address.street:Main") restricts it to
  being found in that property.

**Comment by pasin** [comment]
@snej does the CBL API need to be changed as my above comment?

**Comment by pasin** [comment]
Just looked into some unit tests and the answer is yes.
