### ISSUE TITLE
“LIKE”, "CONTAINS", "REGEX_LIKE" operators ignore collations

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#296]
The query `LIKE` operator just translates into a SQL `LIKE` operator, and SQLite's implementation of it ignores collations: it's always case-insensitive for ASCII but case-sensitive and diacritic-sensitive for non-ASCII (it just compares non-ASCII bytes bit-for-bit.)

We will need to implement our own function that's aware of the collation applied to the LHS.

**Comment by snej** [comment]
The `regex_like` function has the same issue. Possibly other string functions if they involve comparisons?

**Comment by snej** [comment]
Dr Hipp says "It is not currently possible for a [user-defined function] to find the collation associated with its arguments." So the query builder will need to pass the collation info as a parameter to the like/regex functions.

**Comment by snej** [comment]
LIKE is now case-insensitive for all characters (#325) so at least it's consistent.

**Comment by rajagp** [comment]
> LIKE is now case-insensitive for all characters (#325) so at least it's consistent.

@snej  : To confirm, u meant that LIKE is now _case-sensitive_ ... right ? 

So wondering how one would do case insensitive pattern matching...

**Comment by snej** [comment]
Sorry, yes, it is now case-**sensitive**. Currently FTS is the only case-insensitive pattern matching we have.

**Comment by rajagp** [comment]
Thanks! I look forward to the 2.1.0 enhancement on passing the collation info through Query builder (FTS may be an overkill for the simple cases ...indexes and such) ( CC @djpongh )

**Comment by snej** [comment]
If you think this is important for 2.0, ask for it to be prioritized. It does seem like something we're likely to get questions/complaints about.

**Comment by rajagp** [comment]
Yes, I would like to see this in 2.0 itself. Will ping @djpongh  about it

**Comment by waynecarter** [comment]
Will lower/upper case casting allow for case insensitive comparison for this case?

**Comment by rajagp** [comment]
AFAIK - The only way we specify lower/upper case is through collation ...something like this
```
Expression.property("name").collate(Collation.ascii().ignoreCase(true))
                .like(Expression.string("museum")))
```

Or did you mean something else ?

**Comment by snej** [comment]
I think Wayne means the `lower()` and `upper()` functions. These are Unicode-savvy. So yes, you can do case-insensitive LIKE as: `lower(str) LIKE '%pattern%'`.

**Comment by rajagp** [comment]
Ah OK...the functions...yeah that would work 
```
Function.lower(Expression.property("name")) .like(Expression.string("museum")))
```

**Comment by snej** [comment]
CONTAINS has the same limitation. This has now been reported in a CBSE.

**Comment by omegapatten** [comment]
FYI, the solution of using Function.lower() on the property expression is VERY SLOW. Has anyone had success getting LIKE case insensitive?

**Comment by borrrden** [comment]
Migrated to [CBL-52](https://issues.couchbase.com/browse/CBL-52)
