### ISSUE TITLE
Inter-document compression in replicator

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#297]
The BLIP-based replication protocol sends each revision in a separate message. The messages are gzip-compressed, but because the compressor starts over with each document, we don't get as optimal compression as we did in 1.x where `_bulk_docs` sent a whole series of documents in one gzipped HTTP message. (The benefits are greatest for small documents.)

Two options to remedy this:
* Implement inter-message compression in BLIP, where a single gzip codec is used across all messages.
* Or, pack a bunch of revisions into one BLIP message, as `_bulk_docs` did.

I prefer the first option as it doesn't require messing with the replication protocol; it will affect BLIP itself but the code changes will be limited to the BLIP source files. Bundling revisions would require some significant changes to the way the replicator works.

**Comment by snej** [comment]
FYI, I found a great blog post about [using a preset dictionary with deflate](https://blog.cloudflare.com/improving-compression-with-preset-deflate-dictionary/).

**Comment by snej** [comment]
Alternate, newer compression algorithms we should consider before finalizing:

* [Zstandard](https://facebook.github.io/zstd/): "providing high compression ratios … a very wide range of compression / speed trade-off, while being backed by a very fast decoder"
* [Brotli](https://github.com/google/brotli): "compression ratio comparable to the best currently available general-purpose compression methods … similar in speed with deflate but offers more dense compression"
* [lzfse](https://en.wikipedia.org/wiki/LZFSE): "compresses with a ratio comparable to that of zlib (DEFLATE) and decompresses 2–3x faster while using fewer resources"
* [Snappy](https://github.com/google/snappy): "aims for very high speeds and reasonable compression … an order of magnitude faster [than zlib] for most inputs, but the resulting compressed files are anywhere from 20% to 100% bigger"

**Comment by snej** [comment]
[SG pull request](https://github.com/couchbase/sync_gateway/pull/3138) is out for review.

**Comment by tleyden** [comment]
@snej do you want to try to coordinate this to get merged around the same time as https://github.com/couchbase/sync_gateway/pull/3138?  I put some minor feedback on the SG PR, so it should be close to being ready to merge.

**Comment by snej** [comment]
Yes, these need to be merged at around the same time.

**Comment by borrrden** [comment]
Please fix the broken BLIP submodule commit hash.  Was it squashed and merged inside BLIP and then the wrong commit hash committed to LiteCore I wonder?

**Comment by snej** [comment]
Fixed, sorry!
