### ISSUE TITLE
CBL cannot do the sync with sync gateway after sync gateway restart

### ISSUE THREAD

**Issue by zhouzx** [couchbase/couchbase-lite-core#303]
CBL cannot do the sync with sync gateway after sync gateway restart

**Comment by djpongh** [comment]
I think you filed this against the wrong repo. This should probably go to: https://github.com/couchbase/sync_gateway. IF you do refile there, please add more details so we can try and reproduce in house.

Thanks

**Comment by zhouzx** [comment]
I am using CBL 2.0 MB version,and I found a problem. Following is the steps to recreate the problem.
1. Start Sync gateway, and start replicate functions.
2. Stop Sync gateway, the CBL raises an exception.
3. Start Sync gateway.
4. Post a new data.
5. CBL cannot pull the new data.

I did the same for CBL 1.4, seems 1.4 doesn't have any problem.
