### ISSUE TITLE
Cloning issue on Windows

### ISSUE THREAD

**Issue by salmonz** [couchbase/couchbase-lite-core#304]
Receiving git error when trying to clone repo with recursive submodules.
git submodule update --init --recursive

error: unable to create file The-"cblite"-Tool.md: Invalid argument
Unable to checkout '437b678081a4565c969e31c39854175e41649a28' in submodule path 'wiki'

**Comment by borrrden** [comment]
Interesting.  That's an invalid character in the filename.  @snej Did you create this file through GitHub or on your machine?  This might be an issue for GitHub (but we should rename the file with single quotes anyway).

**Comment by borrrden** [comment]
That being said, just FYI, the wiki submodule is not needed for building.

**Comment by borrrden** [comment]
Ok this should be fixed now with a wiki update

**Comment by salmonz** [comment]
Thanks @borrrden. It's now working.
