### ISSUE TITLE
Latest QueryParser breaks GCC 4.x compatibility

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#31]
It has `std::stringstream` member variables, which are not move constructable until libstdc++5 and thus a QueryParser cannot be returned from a function (as in QueryParserTests::parserWith).  There are two choices here:

1. Require libstdc++5 or libc++
2. Remove those member variables

Considering Android, the second seems to be the only viable option...

**Comment by snej** [comment]
Or 3. Don't return QueryParser instances from functions. Let me take a look.
