### ISSUE TITLE
Building couchbase-lite-core in Windows 10 (VS 2017) fails due to initializing a Change in a non-MSVC blessed way

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-core#310]
Building in Windows 10 (Visual Studio 2017) fails with the following error:

```
C:\Users\mz2\Projects\couchbase-lite-node\vendor\couchbase-lite-core\LiteCore\Database\SequenceTracker.cc(220): error C2440: 'initializing': cannot convert from 'initializer list' to 'fleece::slice'
```

The function in question is this (I've inserted a comment on the offending line 220):

```
    size_t SequenceTracker::readChanges(const_iterator placeholder,
                                        Change changes[], size_t maxChanges,
                                        bool &external)
    {
        external = false;
        size_t n = 0;
        auto i = next(placeholder);
        while (i != _changes.end() && n < maxChanges) {
            if (!i->isPlaceholder()) {
                if (n == 0)
                    external = i->external;
                else if (i->external != external)
                    break;
                changes[n++] = {i->docID, i->revID, i->sequence, i->bodySize}; // <= MSVC does not appreciate this
            }
            ++i;
        }
        if (n > 0) {
            _changes.splice(i, _changes, placeholder);
            // (It would be nice to call removeObsoleteEntries now, but it could free the entries
            // that own the docID slices I'm about to return.)
        }
        return n;
   }
```

Maybe an issue brought on by using the 2017 rather than the 2015 compiler, but hopefully a useful issue to report still? If you want me to fix and have a preferred solution in mind, I'll be happy to help.

**Comment by borrrden** [comment]
Or better yet, as in the picture, I can see that the properties indicate the VS 2015 toolset:

![properties](https://user-images.githubusercontent.com/2470288/33304083-14db473e-d44a-11e7-964f-08079070098d.png)

**Comment by mz2** [comment]
Sorry, I was unclear. The compiler error happens indeed with the 2017 toolset (which you can set as a commandline flag). As it's the only compiler error with the 2017 toolset I figured you may want it resolved to allow building with this toolset version. Looks to be just a stricter compiler check that would require a constructor or setting the struct values one by one (if I interpret the compiler error correctly).

**Comment by borrrden** [comment]
I guess it wouldn't hurt.  What did you have in mind?  I need to test it out on Mac first because something clang has issues with the MSVC way too.  Yay for standards :D.

**Comment by borrrden** [comment]
@mz2 --^
