### ISSUE TITLE
Retry pushing doc that fails with a 403

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#313]
Manuel Hurtado:
>There are situations where catching this error is needed. This customer is facing an out-of-order processing of messages in a sequence like this:
>1.       Create ACL doc (which gives access to user to certain channel)
>2.       Write doc to that channel
>
>In this scenario, if 2 is processed by SG before 1, then a 403 error is thrown, because acl access rule has not yet been created.
For this situation, after catching the 403 error a retry can be done, which hopefully will succeed, since probably ACL would be processed.

**Comment by borrrden** [comment]
> There are situations where

This implies there are also situations where there are not.  Which one is more common?  Is the retry in this case going to be an option or is there some way to detect this situation?

**Comment by snej** [comment]
I think this is the same as #525?

**Comment by borrrden** [comment]
Kind of except it’s not clear what to do in this case. Normally a 403 is fatal and only sometimes is it retryable.

**Comment by borrrden** [comment]
Migrated to [CBL-123](https://issues.couchbase.com/browse/CBL-123)
