### ISSUE TITLE
Stopping continuous local to local replication outputs error message

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#318]
When trying to run continuous local-to-local replication on Windows, the following output is often observed when stopping the replication:

> ERROR) Sync {3}--> Repl<-file:/path/to/db
ERROR) Sync {3} Got LiteCore error: WebSocket connection closed by peer (7/1001)

**Comment by snej** [comment]
The passive side will get this status because the active side closes the connection. But I added code a while ago to ignore this status if the replicator is in passive mode. Weird.

**Comment by borrrden** [comment]
Was it more than a month ago?

**Comment by djpongh** [comment]
fixed
