### ISSUE TITLE
LIKE operator is case-insensitive, unlike in N1QL

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#325]
CBL Query
```
let searchQuery = Query
        .select(SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property("country")),
                SelectResult.expression(Expression.property("name")))
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("landmark")
            .and(Expression.property("name").like("Royal engineers museum")))
```
CBL response
```
[{'country': u'United Kingdom', 'id': u'landmark_10019', 'name': u'Royal Engineers Museum'}]
```
Equivalent n1ql query with name like "Royal engineers museum":
```
select meta().id, country, name from `travel-sample` t where t.type="landmark"  and t.name like "Royal engineers museum"
```
n1ql response:
```
[]
```
Modified n1ql query with name like "Royal Engineers Museum":
```
select meta().id, country, name from `travel-sample` t where t.type="landmark"  and t.name like "Royal Engineers Museum"
```
n1ql response:
```
[{u'country': u'United Kingdom', u'id': u'landmark_10019', u'name': u'Royal Engineers Museum'}]
```

**Comment by rajagp** [comment]
On related note : From [sqlite.org](https://sqlite.org/pragma.html#pragma_case_sensitive_like)

_The default behavior of the LIKE operator is to ignore case for ASCII characters. Hence, by default 'a' LIKE 'A' is true. The case_sensitive_like pragma installs a new application-defined LIKE function that is either case sensitive or insensitive depending on the value of the case_sensitive_like pragma. When case_sensitive_like is disabled, the default LIKE behavior is expressed. When case_sensitive_like is enabled, case becomes significant. So, for example, 'a' LIKE 'A' is false but 'a' LIKE 'a' is still true._

**Comment by snej** [comment]
So we may be able to fix this easily by using that pragma.
In the long run it would be best if the case sensitivity could be set by a COLLATE clause.

**Comment by borrrden** [comment]
So will this pragma be added?

**Comment by snej** [comment]
This is still a P1 for 2.0, so I assume so.
