### ISSUE TITLE
Specifying negative limit/offset values fetches the entire DB

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#329]
CBL Query:
```
    let searchQuery = Query
        .select(SelectResult.all())
        .from(DataSource.database(db))
        .limit(limit,offset: offset)
```
Run the above query with limit = -5 and offset = -5
The query returned 31591 results against the travel sample bucket.

Equivalent n1ql query:
```
select * from `travel-sample` where meta().id not like "_sync%" limit -5 offset -5
```
returned:
```
{
  "results": []
}
```

**Comment by snej** [comment]
This is SQLite behavior:

>If the LIMIT expression evaluates to a negative value, then there is no upper bound on the number of rows returned.
>...
>If the OFFSET clause evaluates to a negative value, the results are the same as if it had evaluated to zero.

To make this match N1QL I'll have to wrap the `max()` function around the limit expression to force negative values to zero.
