### ISSUE TITLE
substring pattern match does not match patterns

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#330]
CBL query:
```
let searchQuery = Query
    .select(SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property(select_property1)),
                SelectResult.expression(Function.upper(Expression.property(select_property2))))
     .from(DataSource.database(database))
     .where((Expression.meta().id).equalTo("hotel_16522"))
```
results in:
```
[{'$1': u'BELLE COUR HOTEL & SPA', 'email': u'bellecouruk@gmail.com', 'id': u'hotel_16522'}]
```
searchQuery.explain() 
```
SELECT key, fl_value(body, 'email'), N1QL_upper(fl_value(body, 'name')) FROM kv_default WHERE (key = 'hotel_16522') AND (flags & 1) = 0
0|0|0| SEARCH TABLE kv_default USING INDEX sqlite_autoindex_kv_default_1 (key=?)
```
The same CBL query with substring:
```
let searchQuery = Query
    .select(SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property(select_property1)),
                SelectResult.expression(Function.upper(Expression.property(select_property2))))
    .from(DataSource.database(database))
    .where((Expression.meta().id).equalTo("hotel_16522").and(
           Expression.property(select_property1).and(
           Function.contains(Expression.property(select_property1), substring: substring))))
```
results in:
```
[]
```
searchQuery.explain() 
``` 
SELECT key, fl_value(body, 'email'), N1QL_upper(fl_value(body, 'name')) FROM kv_default WHERE (key = 'hotel_16522' AND (fl_value(body, 'email') AND contains(fl_value(body, 'email'), 'gmail.com'))) AND (flags & 1) = 0
0|0|0| SEARCH TABLE kv_default USING INDEX sqlite_autoindex_kv_default_1 (key=?)
```

**Comment by borrrden** [comment]
`.and(Expression.property(select_property1).and` What is this part?  Why is it just there without checking for any condition?  Did you mean to say `Expression.property(select_proeprty1).notNullOrMissing()` ?

**Comment by raghusarangapani** [comment]
I was following the example from the query blog by @rajagp

**Comment by snej** [comment]
Why does it fail, though? `(fl_value(body, 'email')` will evaluate to a string, which is 'truthy'.

...oh, except it isn't. the SQLite docs say:
>To convert the results of an SQL expression to a boolean value, SQLite first casts the result to a NUMERIC value

A non-numeric string casts to zero, so it's considered false.

This is unintuitive (to me at least.) I wonder what N1QL's semantics are?

**Comment by raghusarangapani** [comment]
N1QL's substr function has a completely different meaning - it is used for string extraction - https://developer.couchbase.com/documentation/server/current/n1ql/n1ql-language-reference/stringfun.html

I use CONTAINS for comparison:

```select meta().id, select_property1, UPPER(select_property2) from `travel-sample` t where CONTAINS(t.select_property1, "gmail.com")```

**Comment by snej** [comment]
What does `substr` have to do with this? I don't see any reference to it above.

**Comment by snej** [comment]
As Jim pointed out, if you remove `Expression.property(select_property1).and(` from the query code, this should work correctly. That expression is evaluating to `false`. Please try that out.

There is a separate question of how a string value should be treated in a boolean context -- we inherit SQLite's behavior, which may be different from N1QL's and is IMHO confusing for people used to other languages. We may want to file a new issue on that.

**Comment by snej** [comment]
Hi @raghusarangapani, please update your test as described above (Jan 2nd). This doesn't seem to be a LiteCore bug.

**Comment by raghusarangapani** [comment]
Yes, I will and update my findings

**Comment by snej** [comment]
ping! Any update or shall we close this?

**Comment by snej** [comment]
(With Raghu out on leave, let's move this out of the 2.0 milestone.)

**Comment by rajagp** [comment]
Missed this ticket ...

> if you remove Expression.property(select_property1).and( from the query code, this should work correctly. That expression is evaluating to false. Please try that out.

Yes. That works as expected

> I was following the example from the query blog by @rajagp

There was this dangling property expression (copy and paste issue) but interestingly I was still getting a few results because of which I didn't notice the issue. I would have expected no results.

So for instance 
```
.where(Expression.property("email").and(Function.contains(Expression.property("email"), substring: Expression.string (".uk"))))
```
is still giving me these results. I expect no rows to be matched.
```
[["id": "landmark_16181", "name":"2 Willow Road", "email": "2willowroad@nationaltrust.org.uk", ["id":"landmark_16254", "name": "575 Wandsworth Road", "email": "575wandsworthroad@nationaltrust.org.uk"]]
```
Why is that the case ?

Removing the dangling property expression gives me the expected set ..
```
[["id": "hotel_10142", "name": "Glencoe Youth Hostel", "email": "glencoe@syha.org.uk"],[ "id": "hotel_10290", "name": "Hill House Holiday Cottage", "email": "owner@hillhousellanrhidian.co.uk"], ["id": "hotel_10291", "name": "Number 38 The Gower", "email": "julia@number38thegower.co.uk"], ["id": "hotel_11219", "name": "Sandy Patch", "email": "stay@holiday-harlech.co.uk"], ["id": "hotel_11315", "name": "The Granary at Roch Mill", "email": "granary@rochmill.co.uk"]])
```

**Comment by djpongh** [comment]
@rajagp , can you file a separate bug for the issue you describe above? I think that's another issue.

**Comment by rajagp** [comment]
@djpongh  Done . https://github.com/couchbase/couchbase-lite-core/issues/392

**Comment by snej** [comment]
With #392 split out, is there anything remaining here?

**Comment by suravarjjala** [comment]
@snej, @sridevi-15 is confirming whether there is a bug here or not with the what you have suggested "As Jim pointed out, if you remove Expression.property(select_property1).and( from the query code, this should work correctly. That expression is evaluating to false. Please try that out."

**Comment by sridevi-15** [comment]
made the change as mentioned in the comments and ran the test, it worked fine. Closing the ticket now.
