### ISSUE TITLE
Replication-Protocol mentions getchanges request, but no request of type getchanges listed

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-core#335]
In https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#changes:

> Notifies the recipient of a series of changes made to the sender's database. A passive replicator (like Sync Gateway) is triggered to send these by a prior getchanges request sent by the client.

However I'm not seeing a `getchanges` message type.  Is this statement still accurate?

**Comment by snej** [comment]
Oops, it's `subChanges`. I just fixed it.
