### ISSUE TITLE
Document when slices are expected to be long lived

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#338]
When making bindings from a managed language, the assumption is that for any passed in managed heap allocated values that the native library will only make use of them for the duration of the method.  If there are places that do not obey this rule then they need to be pointed out.  The most recent one I found is `c4db_initFLDictKey`.  The passed in slice is used as is in the FLDictKey and then returns to managed land (especially tricky since it does a placement new onto a struct that is full of private void pointers).  This causes some undefined behavior about the FLDictKey.  Either the garbage collector has since moved the underlying slice bytes, and the results FLDictKey contains garbage, or it hasn't and things work.  Perhaps the assumption is that only long lived slices would be passed into this method, but these assumptions need to be spelled out if there are anymore.  

~~Alternatively, FLDictKey could hold an alloc_slice instead of a slice so that it is guaranteed a copy of the bytes and this situation could be avoided in this case.~~ This probably won't work actually because the destructor might be invoked before the return of the method and deallocate the alloc_slice.

**Comment by snej** [comment]
In the API, `C4Slice` et al are considered ephemeral and won't be used by a called function after it returns. The situation with `c4db_initFLDictKey` seems like a bug. It stems from Fleece's `Dict::key` class, which stores the slice from the constructor as an member variable, assuming it'll stay valid.

`Dict::key` could easily be changed to use an alloc_slice as a member instead, but that means it'll have a destructor, which means FLDictKey will need a dispose function, which means we'll need a `c4db_freeFLDictKey`...
