### ISSUE TITLE
kData fleece type unable to be queried

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#341]
The first problem is fairly straightforward:

Given the following data

```c++
Transaction t(store->dataFile());
string docID = "rec-001";

fleece::Encoder enc;
enc.beginDictionary();
enc.writeKey("num");
enc.writeData("number one"_sl);
enc.endDictionary();
alloc_slice body = enc.extractOutput();

store->set(slice(docID), nullslice, body, DocumentFlags::kNone, t);

t.commit();
```

An attempt to extract this data in a query `"{'WHAT': ['.num']}"` will result in the following message

> ERROR: LiteCore throwing LiteCore error 23: file data is corrupted

because of the following snippet in SQLiteQuery.cc

https://github.com/couchbase/couchbase-lite-core/blob/d2dffd248809878d06dc82e0ed5322c505e14144/LiteCore/Query/SQLiteQuery.cc#L349-L352

This can be worked around, but even after working around this problem another one shows up with the query `"{'WHAT': [['type()', ['.num']]]}"`.  The `value_type` function first tries to create a fleece value and then check its type.  The flow of the function seems to assume that it is possible to create a "data" type value using the `fromData` or `fromTrustedData` function.  This suggests a more fundamental problem inside of `findRoot`.  Perhaps raw data has no root?  It returns `nullptr` because of the following snippet:

https://github.com/couchbaselabs/fleece/blob/260479eac5b274fae9642135978ab7b7d6edd3c5/Fleece/Value.cc#L249-L251
(Looks like embedded snippets are limited to the same repo)

```c++
// If the root is a direct value there better not be any data before it:
if (_usuallyFalse(s.size != kNarrow))
    return nullptr;
```

**Comment by snej** [comment]
The first problem is because the query object assumes that blob columns are encoded Fleece values, not raw data. So we need a way to distinguish between those, probably by wrapping raw data up in a Fleece container.

The second problem is because we don't have a value subtype that indicates that a blob is just raw data.

**Comment by borrrden** [comment]
Perhaps this could be fixed simply by changing the way that the encoder writes?  If it wraps the data into a fleece data type then it seems to me that both of these would be handled.

**Comment by snej** [comment]
This doesn't really have anything to do with the Fleece encoder. It has to do with the multiple interpretations of SQLite blob values in the query code -- they can be either a document body, a Fleece container, a wrapped pointer to a Value, or just a plain blob. I've been wanting to clean this up for a while, and this looks like a good reason to do so.
