### ISSUE TITLE
Too much logging and wrong log levels used in java code

### ISSUE THREAD

**Issue by kuscsik** [couchbase/couchbase-lite-core#343]
The library does to much logging and info log levels are set as error logs. There should be a mechanism to set the log levels, or the library should check if the builds is a release or debug build.

https://github.com/couchbase/couchbase-lite-core/blob/64111946701a2ce29707760976073950bb112452/Java/src/com/couchbase/litecore/C4Socket.java#L87

**Comment by snej** [comment]
Is your issue specific to the Java code?

**Comment by kuscsik** [comment]
Yes, this is specific to the java code.

**Comment by snej** [comment]
BTW, there is API to set log levels -- look at the logging API in c4Base.h.

**Comment by kuscsik** [comment]
Thanks @snej. As far as I can tell some of these java level logs are going trough the Android log system. I looked briefly into c4log_setLevel, but it seems to me that it has no effect/connection to Android log system.
   The logs I'm referring to are debug level logs, not errors. I'm testing a continuous replicator on Android and these logs are practically flooding the Android log buffers.

What I suggest, is to make these logging conditional to Build.DEBUG Android flag, alternatively use the java logging system that has more control over setting log levels during runtime than Android logs.

**Comment by snej** [comment]
All logging should go through the LiteCore logging APIs (Logging.hh), so that's something for @hideki to fix.

**Comment by kuscsik** [comment]
Only these two files are affected:

Java/src/com/couchbase/litecore/C4Socket.java
Java/src/com/couchbase/litecore/C4Replicator.java
