### ISSUE TITLE
Question on replication spec: passive replicator behavior w concurrent calls to subChanges

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-core#344]
How should a passive replicator behave if a client calls [subChanges](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#subchanges) multiple times on a single connection?

Should it ignore subsequent `subChanges` requests?  Throw an error?

I haven't tested this in the context of Sync Gateway, and so I don't even know the current behavior, but it came up in a discussion around testing and I figured I'd ask what the supposed behavior is.

**Comment by snej** [comment]
As speced, the active peer calls `subChanges` only once.
If there were to be multiple calls, I suppose the reasonable behavior would be for each call to override the behavior of the last, i.e. cancel the existing subscription before starting the new one.
