### ISSUE TITLE
MSVC linker error: unresolved external symbol __imp__SymCleanup@4

### ISSUE THREAD

**Issue by thamht4190** [couchbase/couchbase-lite-core#345]
I'm using LiteCoreStatic.lib file to include into my project. However, I get this error when building:

```
E:\Source\cortex\build\TestCouchbaseLite.vcxproj" (default target) (23) ->
(Link target) ->
  LiteCoreStatic.lib(Error_windows.obj) : error LNK2019: unresolved external symbol __imp__SymCleanup@4 referenced in function "public: static void __cdecl
litecore::error::logBacktrace(unsigned int)" (?logBacktrace@error@litecore@@SAXI@Z) [E:\Source\cortex\build\TestCouchbaseLite.vcxproj]
```

After digging into source code of LiteCore, I found out there is a little difference between declaration (which is static) and definition (which is non-static) of litecore::error::logBacktrace. I tried to change declaration into non-static, but compiling failed because this method was called in another static method :)

I think it is an issue. Please help me to figure it out. Thanks!

**Comment by thamht4190** [comment]
Additionally, after I commented to pass the above error, the build succeeded, however, I receive the log error as below:
```
15: 15:55:10.103328| [DB]: Opening DataFile .\mock.cblite2\db.sqlite3
15: 15:55:10.242674| WARNING: SQLite error (code 1): no such function: fts3_tokenizer
15: 15:55:10.242798| WARNING: Unable to register FTS tokenizer: SQLite err 1
```

This is the source code:
                ```
config = {
			kC4DB_Create | kC4DB_SharedKeys,
			kC4SQLiteStorageEngine,
			kC4RevisionTrees,
			C4EncryptionKey {kC4EncryptionNone}
		};
                C4Slice path = c4str(databasePath.c_str());
                C4Error err;
		C4Database* pDb = c4db_open(path, &config, &err);
```

Any help?

**Comment by snej** [comment]
>there is a little difference between declaration (which is static) and definition (which is non-static)

This is a C++ method. Static methods aren't the same as static functions (confusing, I know.) The `static` keyword goes in the declaration but not the definition, so this isn't a mistake.

**Comment by snej** [comment]
Anyway, the actual unresolved symbol in the linker error is `__imp__SymCleanup@4`, which must be some internal MSVC thing since it's definitely not in our code. Any idea, @borrrden ?

**Comment by borrrden** [comment]
@thamht4190 Have you linked with Dbghelp.lib as well?  That is where this function lives.

**Comment by thamht4190** [comment]
@borrrden Thanks a lot. It works perfectly.
