### ISSUE TITLE
Need LiteCore To Compile With SEE or SQLite

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-core#348]

**Comment by borrrden** [comment]
Initial work for this is on the `feature/sqlite_switch` branch.  CMake compiles with both SQLite and SQLCipher as controlled by the `BUILD_ENTERPRISE` CMake flag.  All tests pass in both versions.

**Comment by snej** [comment]
CMake can now build EE, but Xcode can't. I believe we need this for building couchbase-lite-ios. But I'm not sure how to make it possible to build with either of two SQLite source files depending on a configuration.

**Comment by borrrden** [comment]
Yes we do need this for iOS.  We could do some ifdef incantations if that would make things easier. Or switch to another way of doing things. It doesn’t have to be source switching.
