### ISSUE TITLE
User Agent for CBL

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-core#351]
Pattern
CouchbaseLite/2.0 (COUCHBASE_LITE_PLATFORM, DEVICE_PLATFORM; OS_NAME OS_VERSION; CPU_ARCHITECTURE)

Valid value for COUCHBASE_LITE_PLATFORM = Cocoa | Java | .NET 

Examples
CouchbaseLite/2.0 (Cocoa; iPhone; iOS 11.2.1; ARMv8)
CouchbaseLite/2.0 (Java; Linux; Android 4.4; x86)

**Comment by djpongh** [comment]
Should this be the same as 1.0?

**Comment by snej** [comment]
In 1.x it's of the form `CouchbaseLite/1.3 (iOS 1.4.1)` where `1.3` is the version of the replication protocol, `iOS` is the platform of course, and `1.4.1` is the library version number.

**Comment by snej** [comment]
The full User-Agent needs to be generated by the CBL implementations -- LiteCore isn't in charge of sending the HTTP requests, and it doesn't know the value of COUCHBASE_LITE_PLATFORM.

**Comment by borrrden** [comment]
FYI, This is the current version (that we all decided on before) in .NET:

CouchbaseLite/2.0 ( .NET; Windows 10.0.16299) Build/498 Commit/<hash>

**Comment by snej** [comment]
I added a LiteCore API function `c4_getVersion()` that returns a short version string: either the official version string defined during the build, or else the Git commit ID. This can be used in the CBL User-Agent header as a term starting with `LiteCore/...`. I've added that to CBL-iOS.
