### ISSUE TITLE
Add blip replication heartbeat mechanism

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-core#356]
From discussion in https://github.com/couchbase/go-blip/issues/12:

> we should have a period heartbeat that sends data over the socket periodically, as in the REST changes feed.

Without this, intermediate proxies and load balancers might close connections it determines to be idle, due to no replication activity.

This is a tracking ticket to implement that on the LiteCore side of that change.

**Comment by frozen-yogurt** [comment]
Hello @snej. Is that possible to modify kC4ReplicatorHeartbeatInterval from couchbase-lite-android? For example, when the user creates ReplicatorConfiguration, they could pass a parameter to set the heartbeat interval. Thank you very much.
