### ISSUE TITLE
Very poor performance on Android

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#36]
I know it should be slower than than desktop, but this seems a bit harsh

Tested on Nexus 5 with custom API 24 OS:

> \#\# c4AllDocsPerformanceTest.cc:
	>>> AllDocsPerformance
            SQLite, rev-trees
LiteCore-C info: Created 100000 docs
LiteCore-C info: Enumerating 100000 docs took 2768.801 ms (0.028 ms/doc)
LiteCore-C info: Created 100000 docs
LiteCore-C info: Enumerating 100000 docs took 3701.565 ms (0.037 ms/doc)
\#\# c4PerfTest.cc:
	>>> Import geoblocks
LiteCore-C info: Reading Couchbase/example-datasets-master/IPRanges/geoblocks.json ...  
LiteCore-C info: 100000  
LiteCore-C WARNING: Stopping JSON import after 15.032 sec  
LiteCore-C info: Committing...
Importing took 270512.413 ms for 191000 docs (1416.295 us/doc, or 706 docs/sec)
Reading random docs took 5798.508 ms for 100000 docs (57.985 us/doc, or 17246 docs/sec)
LiteCore-C info: Reading Couchbase/example-datasets-master/IPRanges/geoblocks.json ...  
LiteCore-C info: 100000  
LiteCore-C WARNING: Stopping JSON import after 15.112 sec  
LiteCore-C info: Committing...
Importing took 137176.062 ms for 134000 docs (1023.702 us/doc, or 977 docs/sec)
Reading random docs took 6344.108 ms for 100000 docs (63.441 us/doc, or 15763 docs/sec)

Notes:  Only one CPU core being utilized, and 18MB of RAM peak

**Comment by snej** [comment]
Are you sure this is an optimized build? What optimization level is the compiler using?

**Comment by borrrden** [comment]
As is starting to become par for the course here, this only happens when using libstdc++.  libc++ has acceptable performance, but crashes in the Import Names test...here is a sample of the poor performance compilation:

> /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/platforms/android-16/arch-arm  -DCMAKE -DFleece_EXPORTS -I/Users/borrrden/Development/couchbase-lite-core/vendor/fleece/Fleece -I/Users/borrrden/Development/couchbase-lite-core/vendor/fleece/vendor/libb64 -I/Users/borrrden/Development/couchbase-lite-core/vendor/fleece/vendor/jsonsl -isystem /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward  -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -fexceptions -frtti -O3 -DNDEBUG -Ofast -DNDEBUG -Ofast -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/Fleece.dir/Fleece/Writer.cc.o -c /Users/borrrden/Development/couchbase-lite-core/vendor/fleece/Fleece/Writer.cc

The many definitions at the end of `-Ofast` is weird, and likely coming from a messy CMakeList.

When using the GCC toolchain (bad performance again) it looks identical except for the compiler name and path

When using clang / libc++ (good performance)

> /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/platforms/android-16/arch-arm  -DCMAKE -DFleece_EXPORTS -I/Users/borrrden/Development/couchbase-lite-core/vendor/fleece/Fleece -I/Users/borrrden/Development/couchbase-lite-core/vendor/fleece/vendor/libb64 -I/Users/borrrden/Development/couchbase-lite-core/vendor/fleece/vendor/jsonsl -isystem /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/sources/cxx-stl/llvm-libc++/include -isystem /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/borrrden/Library/Developer/Xamarin/android-ndk/android-ndk-r13b/sources/android/support/include  -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -fexceptions -frtti -O3 -DNDEBUG -Ofast -DNDEBUG -Ofast -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/Fleece.dir/Fleece/Writer.cc.o -c /Users/borrrden/Development/couchbase-lite-core/vendor/fleece/Fleece/Writer.cc

**Comment by borrrden** [comment]
That's more in line with what I see with clang and libc++

**Comment by snej** [comment]
Also look into "link-time optimization" or "whole-module optimization" on those platforms — it makes a big difference with Apple's toolchain because it can intelligently decide what to inline. In particular it can inline functions and methods that aren't in header files.

**Comment by snej** [comment]
Is this resolved now by using libc++? Can we close it?

**Comment by borrrden** [comment]
Yes, libc++ resolves this issue.
