### ISSUE TITLE
null pointer deference during ReplicatorLoopbackTest

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#362]
Run using 85405bf07133065491fb5373541b74bfd556ab66 the following occurred, but it is intermittent (somewhat rare)

Error details:
![Error details and location](https://user-images.githubusercontent.com/2470288/35129292-4a43df8a-fcfe-11e7-8556-47c5eb575588.png)
Backtrace:
![Stack Trace](https://user-images.githubusercontent.com/2470288/35129319-71e6967c-fcfe-11e7-8893-af7fa3a21e14.png)

**Comment by snej** [comment]
Could you get a backtrace when there's a crash/exception?

This is at line 152; `_replClient._ref` is null.

**Comment by borrrden** [comment]
The backtrace is in the second image

**Comment by snej** [comment]
I don't see how `_replClient._ref` could be null ... it's initialized to a Replicator instance before the replication starts, and it's never set to anything else. The only possibility is that the test object itself has been destructed, but in that case it seems unlikely that the value in memory would be zero/null.

**Comment by snej** [comment]
Ah, `_replClient` is set to null in the test destructor. So this looks like a progress notification got posted while the test was partway through destruction. But the test doesn't finish until the replicators have both changed status to Stopped.

@borrrden, have you ever seen this crash again?

**Comment by borrrden** [comment]
No, but it's worth noting that I only saw it with this amount of detail because I happened to be debugging.  It seems like the majority of the replication based crashes come from notifications coming at a bad time, though.

It reminds me of an evolution of the old joke:

    There are only 2 hard problems in computer science:
    0. Cache invalidation
    1. Naming Things
    7. Asynchronous callbacks
    2. Off-by-one errors
    3. Buffer overrun

**Comment by borrrden** [comment]
Could this have to do with the misbehaving idle checkpoint message?

**Comment by djpongh** [comment]
haven't seen again
