### ISSUE TITLE
Language code '' not supported; ignoring it

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#365]
Discovered while writing .NET tests, but creating an index using the following:

`Index.FullTextIndex(FullTextIndexItem.Property("passage")).Locale("");`

results in the following LiteCore call:

`c4db_createIndex(c4db, name, json, concreteIndex.IndexType, &internalOpts, err);`

- json: [[".passage"]]
- concreteIndex.IndexType: C4IndexType.FullTextIndex
- internalOpts: 
    - disableStemming: false
    - ignoreDiacritics: false
    - language: ""
    - stopWords: null

This is the result of this block
```c++
 if (options->language) {
    if (unicodesn_isSupportedStemmer(options->language)) {
        sql << " \"stemmer=" << options->language << "\"";
        if (!options->stopWords)
            sql << " \"stopwords=" << options->language << "\"";
    } else {
        Warn("FTS does not support language code '%s'; ignoring it",
                         options->language);
    }
 }
```

However, in one of our Couchbase blogs, this is indicated as the way to disable stemming (setting the locale to empty string).  So the following questions need an answer:

1. By default, should stemming be active or inactive (in .NET, currently it seems to be inactive unless a locale is explicitly set)?
2. Should Couchbase Lite intercept a call to an empty or null locale and make use of the disableStemming flag?
3. Does the disableStemming flag actually do anything?  I can't see any reference to it in the codebase.

**Comment by snej** [comment]
The public API seems to agree with that blog post; at least, the Obj-C doc-comment for CBLFullTextIndexOptions (in CBLIndex.h) says

> Setting nil value to use current locale and setting "" to disable stemming.

(Although it should say "current _language_", not "locale".) So to answer your questions:

1. Stemming is based on language grammar, so it can't be performed unless the language is set.
2. Yes; the LiteCore and CBL APIs don't match here.
3. You're right, the `writeTokenizerOptions` function in SQLiteKeyStore+Indexes.cc should honor the `disableStemming` flag. I'll fix that.

**Comment by rajagp** [comment]
So looks like a ticket needs to be filed against couchbase-lite-ios then to disable stemming by default  because  I observed that stemming was always enabled even if I did not specify locale (because presumably it assumes a  "nil" locale as current locale and uses that for stemming) (I have not tested Android) (CC @pasin , @hideki )

**Comment by snej** [comment]
Yes, it interprets a `nil` locale as the current language, in CBLFullTextIndex.m:
```objc
    NSString* locale = _options.locale;
    if (!locale)
        locale = [[NSLocale currentLocale] objectForKey: NSLocaleLanguageCode];
```
Instead I think `_options.locale` should be initialized to this value (the current language), but the developer should be able to set it to nil to indicate no stemming or stop-words.

**Comment by snej** [comment]
Also, the property should be `language` not `locale` (https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/195)

**Comment by rajagp** [comment]
> Instead I think _options.locale should be initialized to this value (the current language), but the developer should be able to set it to nil to indicate no stemming or stop-words.

OK. Just to be clear then. 
- If no language is specified, the current language is assumed. So by default, even if no language is specified, stemming will be enabled using current language. (Which means the .Net default implementation would have to change...)
- To disable stemming, one would set the language to nil (and not an empty string as currently is the case)
- Setting to language to "" / empty string : Should that even be allowed by API ? If we support this,  it will have the same effect as setting language to nil.

**Comment by snej** [comment]
Those are questions about CBL, so @pasin is the authority. But my opinions are that

* FTS indexing should default to using the current locale's language.
* It's more consistent & intuitive to use `nil`/`null`, instead of an empty string, to disable language-related features.

**Comment by pasin** [comment]
I will look into this. The current API seems to be confusing.
