### ISSUE TITLE
Build on MacOS: SQLite error: No such function fts3_tokenizer

### ISSUE THREAD

**Issue by thamht4190** [couchbase/couchbase-lite-core#375]
I'm building my C++ project on Mac OS using static LiteCore. Building is ok, but running returns error log like this:
```
11:29:19.399286| [DB]: Opening DataFile ./demoIndex.cblite2/db.sqlite3
11:29:19.400009| WARNING: SQLite error (code 1): no such function: fts3_tokenizer
11:29:19.400030| WARNING: Unable to register FTS tokenizer: SQLite err 1
11:29:19.400790| [SQL]: DROP INDEX IF EXISTS "byApp"
11:29:19.400823| [SQL]: DROP TABLE IF EXISTS "kv_default::byApp"
11:29:19.400862| [SQL]: CREATE VIRTUAL TABLE "kv_default::byApp" USING fts4("appId", tokenize=unicodesn)
11:29:19.401101| WARNING: SQLite error (code 1): statement aborts at 28: [CREATE VIRTUAL TABLE "kv_default::byApp" USING fts4("appId", tokenize=unicodesn)] no such module: fts4
11:29:19.401246| [DB]: DataFile: Transaction exiting scope without explicit commit; aborting
11:29:19.401270| [DB]: DataFile: abort transaction
```
I have linked with these targets: 
`LiteCoreStatic FleeceStatic SQLite3_UnicodeSN BLIPStatic CivetWeb mbedcrypto sqlcipher`

Any libraries did I miss?

**Comment by snej** [comment]
The `fts3_tokenizer` SQL function is [part of the FTS3/4 extension](https://sqlite.org/fts3.html#f3tknzr), so that implies SQLite was built without FTS. Which is weird because we statically link it (as sqlcipher) and the build flags enable FTS4. Even if you were linking against the system sqlite3.dylib by mistake, that supports FTS4 too.

How did you build LiteCore, exactly? With Xcode or CMake? What Git revision are you building? Are your submodules all up to date?

**Comment by thamht4190** [comment]
> How did you build LiteCore, exactly? With Xcode or CMake? What Git revision are you building? Are your submodules all up to date

I built with CMake, LiteCore submodule is up to date with its master branch. This is a part of my CMakeLists.txt:
```
add_subdirectory(${THIRD_PARTY_DIR}/couchbase-lite-core)

set(LITECORE_LIBS LiteCoreStatic FleeceStatic SQLite3_UnicodeSN BLIPStatic CivetWeb mbedcrypto sqlcipher)
if (WIN64 OR WIN32) 
	set (LITECORE_LIBS ${LITECORE_LIBS} Dbghelp)
endif()
target_link_libraries(${MY_TARGET} ${OTHER_LIBS} ${LITECORE_LIBS})

target_include_directories(${MY_TARGET} PUBLIC
        ${OTHER_INCLUDE_DIR}
	${THIRD_PARTY_DIR}/couchbase-lite-core/C/include
	${THIRD_PARTY_DIR}/couchbase-lite-core/vendor/fleece/Fleece
)
```
I have run C4Tests executable file, it works perfectly. Then I think it must have something wrong with my CMakeLists.txt. Please help!

**Comment by snej** [comment]
@borrrden, any ideas?

**Comment by snej** [comment]
Does your `${OTHER_LIBS}` include SQLite, like the system sqlite3.dylib? If so, the app (including LiteCore) will probably end up linking with that instead of LiteCore's SQLite.

**Comment by borrrden** [comment]
That's what I was going to guess about SQLite.  You could try switching the order of `OTHER_LIBS` and `LITECORE_LIBS` and if possible show an example output from the compiler by running `make VERBOSE=1` (just for one file) and the output during the linking phase.  If you aren't sure then just make a gist of the whole thing.

**Comment by thamht4190** [comment]
@snej @borrrden You are absolutely right. There exists one of my libs which includes sqlite3.c. When I move ${LITECORE_LIBS} up to the top of the linked libraries list, it runs ok. Thanks a lot!
