### ISSUE TITLE
Throwing assertion failure error on CBL when updating doc in batch more than 30 times

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#376]
CBL Version : 2.0.0 - DB 22
platform : iOS -> 560 build

Steps to reproduce : 
1. Set up sync-gateway.
2. Create database and documents(around 10) in CBL.
3. update docs few times in CBL .
4. Start the replication with continuous 'true' and replication with 'PUSH_PULL'
5. update docs in CBL in batch with more than 30 times.

Result : 
1. When it saves document around 32nd time , it fails with error "assertion failure"

Expected : 
1. It should be able to update document .
Not sure if there is any max limit to update docs continuously . This following test passed when I update with 25 times at step 5. 

CBL logs : https://gist.github.com/sridevi-15/e51fbc2b09c62a17eb790d2d4563bbcc
Note : For convenience : I provided full log in gist and also at the end of the gist file, I extracted actual error and added at the end of gist file. 

Code for the test : https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L201

I pointed line number of test.

**Comment by snej** [comment]
```
 Assertion failed: i != revs.end() (..../RevTree.cc:152, in index)
  0  CouchbaseLiteSwift        litecore::RawRevision::encodeTree(....) + 507
  1  CouchbaseLiteSwift        litecore::RevTree::encode() + 42
  2  CouchbaseLiteSwift        litecore::VersionedDocument::save(litecore::Transaction&) + 89
  ....
```

**Comment by snej** [comment]
The LiteCore unit test "Document maxRevTreeDepth" does exactly this -- it saves a document 10,000 times in a transaction.

@sridevi-15, in step 5 do you mean updating the same document(s) 30 times in a row within the same batch/transaction?
Where in the test code is the loop that triggers the problem?

**Comment by sridevi-15** [comment]
yes, in step 5 updating same documents 30 times in a row within the same batch.

The code for the API written for updateDocuments in server
Pointing to the line : 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/DatabaseRequestHandler.swift#L156

This method : database_updateDocuments called 30 times  ( same set of docs 30 times)

**Comment by snej** [comment]
So each document is only updated once in any particular batch/transaction, then.

**Comment by sridevi-15** [comment]
yes

**Comment by snej** [comment]
Found & fixed it. The doc needs to have a revision that was added by the pull replicator; then after enough revisions are added that the remote revision gets pruned, the crash occurs.

I'm assuming we should get this fix into DB22 since the issue is a functional test failure.

**Comment by sridevi-15** [comment]
Great Thanks Jens.
