### ISSUE TITLE
Checkpoint isn’t saved immediately when continuous replicator goes idle

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#378]
Normally the replicator saves checkpoints every 5 seconds; but when it's finished its other work, it should save the checkpoint immediately. Otherwise it takes up to five extra seconds for its state to go to stopped/idle, which makes the replication take longer than it should.

(There is some code in Replicator.cc that attempts to do this, but it must not be working.)

**Comment by borrrden** [comment]
For what it's worth, I've always noticed this and can confirm that after getting up to speed it takes up to a few seconds to actually switch to idle.  Not sure about stopped, I think stopped actually switches immediately but not sure.

**Comment by snej** [comment]
It turns out the checkpoint _is_ saved immediately when a one-shot replication finishes; but it's not saved immediately when a continuous replication goes idle.

**Comment by djpongh** [comment]
fixed on dev branch
