### ISSUE TITLE
JOIN query with arrays resulting in crash 

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-core#379]
Original Issue was posted in the [Forums](https://forums.couchbase.com/t/what-is-the-correct-way-to-join-on-keys-in-couchbase-lite-v2-objective-c-api/15576)

Objective : JOIN documents if and only if LHS doc has a property value that is contained in array property of RHS document

Attempted to come up with a query to solve the problem
**Version**
Tested with latest feature/2.0 branch  of couchbase-lite-ios

**Test Data :** 
Create a file` forum.json` with this data in `couchbase-lite-ios`
https://gist.github.com/rajagp/485a6a61f51f7f27f2099df34613e8d7
 
**My sample JOIN Query** 
You can include this as a unit test to `couchbase-lite-ios`
 https://gist.github.com/rajagp/089a8d7cf233d1bcfdc6db8c1daac889

**Observed**
Crash in lite core: https://gist.github.com/rajagp/87f8aabc234bc6172d34b2dcb5018e8c

( CC @pasin )

**Comment by borrrden** [comment]
Running this in UWP gives the following analysis:

`rawRev->body()` is a call inside of `getCurrentRevBody(slice)` in RawRevTree.hh (37).  `rawRev` happens to be `null` here.

**Comment by borrrden** [comment]
Note: The crash log does not appear to line up exactly with the test source.  When I tried I got

> SELECT fl_result("itemDS".key), fl_result("categoryDS".key) FROM kv_default AS "categoryDS" JOIN kv_default AS "itemDS" ON (EXISTS (SELECT 1 FROM fl_each("categoryDS".body, 'items') AS _item WHERE _item.value = fl_value("itemDS".body, 'id'))) AND ("itemDS".flags & 1) = 0 WHERE ("categoryDS".flags & 1) = 0

but in the logs here are slightly different (indicating a possible comparison with ecc-102:
> SELECT fl_result("itemDS".key), fl_result("categoryDS".key) FROM kv_default AS "categoryDS" INNER JOIN kv_default AS "itemDS" ON (EXISTS (SELECT 1 FROM fl_each("categoryDS".body, 'items') AS _item WHERE _item.value = fl_value("itemDS".body, 'id'))) AND ("itemDS".flags & 1) = 0 WHERE (fl_value("itemDS".body, 'id') = 'ecc:102') AND ("categoryDS".flags & 1) = 0

In the end my query also suffered the same fate, though, so that doesn't appear to be related

**Comment by snej** [comment]
I've added a null check in `FleeceCursor::filter` so now it doesn't crash, but the query returns zero results, which is wrong. I don't understand why the filter function is getting called with a SQLite `null` instead of the expected document body, since the SQL parameter is `categoryDS.body`...

**Comment by snej** [comment]
I created an equivalent test using plain SQLite with the JSON extension, and it also returns zero rows:

```sql
CREATE TABLE docs (body string);
INSERT INTO docs VALUES('{"id":"ecc:102","type":"category","items":["eci:742","eci:743","eci:744"],"name":"Skills"}');
INSERT INTO docs VALUES('{"id":"eci:742","type":"item","chinese":"技术","english":"technique","pinyin":"jìshù"}');
INSERT INTO docs VALUES('{"id":"eci:743","type":"item","chinese":"技术","english":"skill","pinyin":"jìqiǎo"}');

SELECT "itemDS".rowid, "categoryDS".rowid 
FROM docs AS "categoryDS" 
INNER JOIN docs AS "itemDS" 
    ON (EXISTS (SELECT 1 FROM json_each("categoryDS".body, '$.items') AS _item 
                 WHERE _item.value = json_extract("itemDS".body, '$.id'))) 
WHERE 1;
```

**Comment by snej** [comment]
I've been trying different variations of this for an hour, and I think there's a bug in SQLite. Unless there are weird subtleties of SQL involved. Going to ask the mailing list.

**Comment by snej** [comment]
WTF:
```sql
CREATE TABLE docs (id text, body text);
INSERT INTO docs VALUES('ecc:102', '{"id":"ecc:102","type":"category","items":["eci:742","eci:743","eci:744"]}');
INSERT INTO docs VALUES('eci:742', '{"id":"eci:742","type":"item"}');
INSERT INTO docs VALUES('eci:743', '{"id":"eci:743","type":"item"}');

# No results:
SELECT itemDS.id, categoryDS.id
FROM docs AS "itemDS", docs AS "categoryDS" 
WHERE (EXISTS (SELECT 1 FROM json_each("categoryDS".body, '$.items') AS _item WHERE _item.value = 'eci:742'));

# 2 results:
SELECT categoryDS.id
FROM docs AS "categoryDS" 
WHERE (EXISTS (SELECT 1 FROM json_each("categoryDS".body, '$.items') AS _item WHERE _item.value = 'eci:742'));
```

**Comment by snej** [comment]
It is indeed a bug in SQLite: ["Incorrect result when join condition uses a table-valued function"](http://www.sqlite.org/src/info/80177f0c226ff54f6dd) (filed by DRH as a result of my mailing-list post.) A [fix was committed](http://www.sqlite.org/src/info/7daa687340e47597) yesterday (1/26) and will be in SQLite 1.23. Description:

>`SELECT * FROM t2 CROSS JOIN t1`
>` WHERE EXISTS(SELECT 1 FROM json_each(t1.json,'$.items') AS Z`
>`               WHERE Z.value==t2.id);`
>The problem is that the query planner fails to recognize that the EXISTS expression in the WHERE clause has a dependency on table t1, and so it generates code for the EXISTS expression after the outer loop over t2 and before the inner loop over t1 has been run. This means that the t1.json value for the EXISTS expression is incorrect, and an incorrect answer results.

>This problem appears to have been in the code ever since table-valued functions were introduced with version 3.9.0 (2015-10-14).

The workaround suggested yesterday by DRH is to swap the order of the join -- in the example, to use `t1 CROSS JOIN t2`. That's why a `CROSS JOIN` is used: it has the same effect as an `INNER JOIN` here, except that SQLite's optimizer won't reorder it.

My understanding now is that the condition that led to the initial crash -- `fleece_each`'s filter function being called with a null argument -- is indicative of the bug, and should never happen. In that case it would be good to change my first commit to return an error instead of OK, to force the query to fail, as well as returning an error message (or at least a Warn) indicating that reordering the join can help.

**Comment by rajagp** [comment]
> The workaround suggested yesterday by DRH is to swap the order of the join -- in the example, to use t1 CROSS JOIN t2. That's why a CROSS JOIN is used: it has the same effect as an INNER JOIN here, except that SQLite's optimizer won't reorder it.

@snej  @pasin  :  Is there a ticket to bring back the `on` clause in the cross join since this workaround relies on that? 
(Also, I had filed the ticket to remove the `on` clause from cross join because the results didn't produce the cartesian product - it was generating inner join results if I recall. Of course we have a unit test now to cover that)

(CC @borrrden , @hideki )

**Comment by pasin** [comment]
As it's correct to have ON on the cross-join, I will create an issue for that.

**Comment by pasin** [comment]
@rajagp I have chatted with @borrrden about the issue. It turns out we don't need to add ON back to Cross JOIN in 2.0. @snej fixed the issue in LC by using Cross Join internally. We will consider adding ON back to make Cross JOIN API inline with the spec in 2.x.

**Comment by rajagp** [comment]
Thanks @pasin . That indeed seems to be the case. I did a quick test of the query with CBL that has this fix and it seems to be working

**Comment by rajagp** [comment]
@snej : Looks like there may still be an issue here because I am not seeing the expected results with updated data set. 
**Tested With**:
 release/2.0-dev (iOS)

 **Test Data**  :
 https://gist.github.com/rajagp/018275d139c4236c50d271415899c379

 **Test Query **:
I would like to join all the "department" type and "location" type documents based on location code. So if a department is associated with multiple locations, I expect all the matching docs to be joined

https://gist.github.com/rajagp/a7a2accfa93e5092da9d2bba7ee25cf0

** Expected **:
```
["departmentName": "Engineering", "locationName": "HQ"]
["departmentName": "Engineering", "locationName": "Central HQ"]
["departmentName": "Product Management", "locationName": "HQ"]
["departmentName": "Product Management", "locationName": "Central HQ"]
["departmentName": "Marketing", "locationName": "HQ"]
["departmentName": "Marketing", "locationName": "Central HQ"]

["departmentName": "Sales", "locationName": "HQ"]
["departmentName":" HR", "locationName": "HQ"]
["departmentName": "Quality", "locationName": "HQ"]
```

 **Got** 
Note that department documents with multiple location matches are not displayed
```
["departmentName": "Sales", "locationName": "HQ"]
["departmentName":" HR", "locationName": "HQ"]
["departmentName": "Quality", "locationName": "HQ"]
```

Perhaps the query itself is missing something ....

**Comment by snej** [comment]
This is a different issue, since it's not a crash. Could you please file it as a new one? (Sorry to be a stickler about this, but what's happening now doesn't match the title of this issue, nor its severity or priority.)

**Comment by rajagp** [comment]
No worries - Here you go. https://github.com/couchbase/couchbase-lite-core/issues/393
