### ISSUE TITLE
409 conflict error on sync-gateway with concurrent updates on CBL and sync-gateway

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#380]
###CBL version 2.0 DB22
###platform : iOS . -> 560

###Steps to reproduce : 
1. Set up sync-gateway.
2. Create database and create documents in CBL.
3. update documents for couple of times in CBL.
4. Start replication with continuous True and with 'PUSH_PULL'
5. wait until replicator is idle.
6.update documents in sync-gateway in one thread and update document in CBL in another thread.
  Basically updating documents concurrently in sync-gateway and CBL.

###Result : 
1. At some point of time after couple of updates on sync-gateway and CBL, it throws 409 conflict error for one of the document in sync-gateway
We fail the test if any updating document throws 409 conflict error.

###Expected  : 
1. As no-conflicts is not enabled, it is expected not to throw conflict error in sync-gateway 

I filed it in CBL as in sync-gateway we have functional test which does concurrent updates on sync-gateway and through SDK and I do not see this issue on sync-gateway. Let me know if it is on sync-gateway, I can move it to syncgateway.

###CBL Logs  in Gist : https://gist.github.com/sridevi-15/019246aca65cdbdbbabb3ca1d0353187
sg logs in Gist : https://gist.github.com/sridevi-15/d1a3cd635490c33295ac10dbcf564716
Note :  Errors are neither in CBL logs nor in sync-gateway logs

As I do not see errors in either of logs, it looks like not a bug, but want to confirm if this is expected behavior. 

### Link for Test code : https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L558

Failing at line 624 while updating doc in sg in one thread

**Comment by snej** [comment]
> it throws 409 conflict error for one of the document in sync-gateway

This sounds like expected behavior. If you update a doc by doing a GET followed by a PUT, the PUT will return 409 if something else updated the doc in between. You need to check for this status and retry -- repeat the GET/modify/PUT again until it succeeds.

If that's not what's going on here, please give more detail about what happened.

**Comment by sridevi-15** [comment]
Yes Jens, it does update a doc by doing get followed by put and CBL also do update at same time.
I added retry method for docs which got conflict and was able to successfully update with retry. 

When I run same test with -no-conflicts mode, I get 403 with sync-gateway update(which is step6)  i.e while CBL is updating . I hope this is expected too. Isn't supposed to throw 409 with no-conflicts mode?

**Comment by snej** [comment]
Please file a new issue with all the needed details including logs.
Closing this one.
