### ISSUE TITLE
Deleting a database needs thread-safety, and should log

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#382]
Looking at `SQLiteDataFile::deleteDataFile()`, I noticed it's not fully thread-safe. The following could happen:

1. Thread 1 has a SQLiteDataFile on a specific file.
2. Thread 1 calls `deleteDataFile()`; the method checks that there's only one open instance on this file path and proceeds to call `close()`, but meanwhile...
3. Thread 2 opens a SQLiteDataFile on the same path.
4. Now thread 1 deletes the actual SQLite files.

This isn't far-fetched, since the `close()` method can take some time, as it sometimes does database optimization & vacuuming.

I also noted that nothing is logged when a SQLiteDataFile is deleted, which makes it hard to detect that a problem like the above is occurring (see #381).

**Comment by djpongh** [comment]
@hideki , could this be what you are seeing on Android?

**Comment by snej** [comment]
Deleting and simultaneously opening a database file is a bad idea anyway, regardless of this issue, because they're fundamentally conflicting operations. After this issue is fixed, the result will probably be that the call that happens second will fail.

**Comment by snej** [comment]
A similar race condition, though less likely, was possible with `c4db_deleteAtPath()`. Fixed that one too in a 2nd commit.
