### ISSUE TITLE
Revisions with more than 50 updates  are not stored 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#387]
### Steps to reproduce :
 1. Have sg config with no-conflicts enabled with  revs_limit = 50 
2. Create docs in CBL
3. Start a continuous Replicator with push_pull to have SG load all the docs. Verify if the no. of docs are same in both SG and CBL.
3. Create conflict in sync-gateway. 
4. Update docs in CBL and also update docs through SG with number of times more than revs_limit. check the docs after replication become idle
5. Verify the number of revisions stored in history is maintained whatever the revs_limit configured in sync-gateway

###Result : When I check revisions history in sync-gateway, I see less revisions 
if revs_limit in sync-gateway is 35, it shows 31 revisions in revision history of sync-gateway
if revs_limit in sync_gateway is 50 , it shows approximately 38
Errors in sync-gateway says docs got pruned

### CBL logs : 
Android logs : 
[less-revs-with50.txt](https://github.com/couchbase/couchbase-lite-core/files/1691353/less-revs-with50.txt)
ios logs : 
[less-revs-ios.zip](https://github.com/couchbase/couchbase-lite-core/files/1691358/less-revs-ios.zip)
sg logs : https://gist.github.com/sridevi-15/bbe8d005cb177e5cc8f197fa1d6519ea

### Testcode:
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L202
Test name : test_no_conflicts_update_with_revs_limit

**Comment by snej** [comment]
Is the current revision of each document the same in SG and CBL? If so, I don't think this is a bug. CBL isn't necessarily going to push every revision of the document to SG; it depends on whether the replicator can keep up.

**Comment by djpongh** [comment]
@sridevi-15 can you answer Jens' question? (Is the current revision of each document the same in SG and CBL?) 
Thanks!

**Comment by sridevi-15** [comment]
@snej , Is there any way to get current revision of document in CBL? I see that SG has current revision for one of the doc as 45-424e04b5ac190b6894abca4a50bb323b572a33e7' and in CBL logs , I see this message. CouchbaseLite Sync Verbose: {Push#69} Queueing rev 'no-conflicts_1' #45-424e04b5ac190b6894abca4a50bb323b572a33e7 (seq 4431).

**Comment by snej** [comment]
No; the API design decision was not to expose revision IDs.

**Comment by snej** [comment]
You can just compare the document bodies to see if they're equal. If you want to be completely sure, update your test to add a generation counter property that you increment every time you update the doc.

**Comment by sridevi-15** [comment]
I have generation counter.  Though I have generation counter, it is hard to predict what is the winning revision . Sometimes counter does not increment with cbl updates, but update with sync-gateway as winning revision could be sync-gateway.

**Comment by snej** [comment]
That is the expected behavior of the default conflict resolver: if both revisions are the same generation, it picks the winner in a deterministic but unpredictable way. (It's whichever has the greater revID according to strcmp.) You can avoid this by registering a custom conflict resolver.

**Comment by sridevi-15** [comment]
okay, will modify the test

**Comment by sridevi-15** [comment]
As this is expected, I will close this ticket
