### ISSUE TITLE
Error code for connection refused is different for iOS and Android

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#390]
### Environment:

CBL - 2.0- DB 22 -> ios build 576, Android 299
client -> ios, Android
sg -> 2.0.0- 773

### Steps to reproduce :
1. Create CBL db and create docs.
2. Do not start sync-gateway(make sure sync-gateway is stopped)
3. Configure replication and start sync-gateway

### Result : 
It throws an error with error code = -1004 on iOS with 'connection refused' message 
It throws an error with error code=111 on Android with 'connection refused' message 

### iOS logs:
2018-02-03 22:48:51.865463-0800 CBLTestServer-iOS[48251:4399852] CouchbaseLite DB Verbose: Pre-close housekeeping: 0 of 228 pages free (0%)
2018-02-03 22:48:51.920050-0800 CBLTestServer-iOS[48251:4129435] CouchbaseLite Sync Info: CBLReplicator[<* URL[ws://192.168.33.11:4984/sg_db1]]: Transient error (Connection refused); will retry in 8 sec...
2018-02-03 22:48:51.920375-0800 CBLTestServer-iOS[48251:4129435] CouchbaseLite Sync Info: CBLReplicator[<* URL[ws://192.168.33.11:4984/sg_db1]] is offline, progress 0/0, error: Error **Domain=NSURLErrorDomain Code=-1004 "Connection refused" UserInfo={NSLocalizedDescription=Connection refused}**

### Android logs:
02-03 06:11:03.662 8275-8306/com.example.hemant.coucbaselitesampleapp E/LiteCore [Sync]: {Repl#179} Got LiteCore error: Connection refused (2/111)
02-03 06:11:03.860 8275-8307/com.example.hemant.coucbaselitesampleapp E/C4Replicator: statusChangedCallback() handle -> 3509538944, status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=2, errorCode=111, errorInternalInfo=1014}
02-03 06:11:03.860 8275-9988/com.example.hemant.coucbaselitesampleapp E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=2, errorCode=111, errorInternalInfo=1014}
02-03 06:11:03.860 8275-9988/com.example.hemant.coucbaselitesampleapp E/Sync: **Replicator[<* URLEndpoint{url=ws://192.168.33.11:4984/sg_db1}] is offline, progress 0/0, error: CouchbaseLiteException{domain=2, code=111, msg=null}**
02-03 06:11:11.861 8275-9988/com.example.hemant.coucbaselitesampleapp E/Sync: Replicator[<* URLEndpoint{url=ws://192.168.33.11:4984/sg_db1}]: Retrying...

**Comment by sridevi-15** [comment]
For Android , it is not regression

**Comment by snej** [comment]
Networking error codes are not cross-platform. And our API does not define a standard set of exceptions or error codes.

* On iOS the error returned is one that would be expected when using a Cocoa API to access the network. -1004 is `NSURLErrorCannotConnectToHost`.
* On Android, CBL is returning an exception wrapping a domain of 2 (POSIX, according to LiteCore) and an errno value of 111. I don't know what the 111 means on Android; on MacOS errno.h only defines codes up to 106.

Also, in both of these cases the error is being generated by platform-specific WebSocket code in Couchbase Lite, so this isn't up to LiteCore at all.
