### ISSUE TITLE
2.0 : JOIN Query on array members not returning expected results

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-core#393]
**Tested With**:
 release/2.0-dev (iOS)

 **Test Data**  :
 https://gist.github.com/rajagp/018275d139c4236c50d271415899c379

 **Test Query **:
I would like to join all the "department" type and "location" type documents based on location code. So if a department is associated with multiple locations, I expect each department document to be matched up with eachh of the corresponding location documents.

https://gist.github.com/rajagp/a7a2accfa93e5092da9d2bba7ee25cf0

** Expected **:
```
["departmentName": "Engineering", "locationName": "HQ"]
["departmentName": "Engineering", "locationName": "Central HQ"]
["departmentName": "Product Management", "locationName": "HQ"]
["departmentName": "Product Management", "locationName": "Central HQ"]
["departmentName": "Marketing", "locationName": "HQ"]
["departmentName": "Marketing", "locationName": "Central HQ"]

["departmentName": "Sales", "locationName": "HQ"]
["departmentName":" HR", "locationName": "HQ"]
["departmentName": "Quality", "locationName": "HQ"]
```

 **Got** 
Note that department documents with multiple location matches are not displayed
```
["departmentName": "Sales", "locationName": "HQ"]
["departmentName":" HR", "locationName": "HQ"]
["departmentName": "Quality", "locationName": "HQ"]
```

Perhaps the query itself is missing something ....

**Comment by borrrden** [comment]
Your test data is invalid:

Several instances of this

> "location":["101,102"]}

instead of this

> "location":["101","102"]}

Using the correct data produces the correct result:

![image](https://user-images.githubusercontent.com/2470288/35949582-9a187b58-0cb5-11e8-8195-97e33a1131c0.png)

**Comment by rajagp** [comment]
Aaaah! Always helps to have second pair of eyes ! Glad it was as simple as this
