### ISSUE TITLE
Idea: Custom replicator using IPFS

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#403]
I'm interested in using IPFS as a data store for LiteCore. Reason: I don't want to have to manage a server instance for this app's data, and it's very light "public domain" type data, i.e. no sensitive info. 

So I'm thinking about a custom replicator that would talk to IPFS instead of Sync Gateway/CouchDB. 

What would be needed for this to be implemented? Ideally in a way that could be read in from a web app also. I've been following developments at [OrbitDB](https://github.com/orbitdb/orbit-db/issues/4) to get some ideas, most recently a plugin that replicates from OrbitDB (IPFS based DB) to PouchDB: https://github.com/garbados/pouchdb-orbit

My understanding of replication is its simply reading in and applying the changes feed and then, dealing with conflicts (the complicated part I guess).

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by adamski** [comment]
Sure, I wondered if I should have posted there first.. no problem.
