### ISSUE TITLE
Removing LiveQuery listener does not seem to stop the query 

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-core#407]
Originally from [forums](https://forums.couchbase.com/t/livequery-remains-alive/15786/8) . Reported on Android but appears to be a lite core issue.

**Issue** 
------
1. Create a live query. 
2. In query listener callback, remove the query listener to stop the query
3. Re-create the query object with new where criteria
4. Reattach the listener

**Expected**
-----------
- Only one query executed (per new where criteria)
- One callback

**Observed**
------------
- One callback (so listeners are managed properly)
- But it seems like old version of query is still executed
After 5 inserts (i.e call back run 5 times so 5 updated queries).  Observing the following messages. Expect to see a single message with 1 row (since only doc matches the updated query).
```
I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 2 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 3 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 4 rows (Y bytes) in Xms
```

**Alternative Solution**
-------------------
It was recommended that user parameterized queries (changed parameters to restart query) and that resolved .

**Comment by snej** [comment]
LiveQuery is implemented in CBL, not LiteCore -- all LiteCore provides is an API call to re-run a C4Query. So I think the investigation should start in CBL-Android.

**Comment by rajagp** [comment]
Unless this didn't make it into DB022,  equivalent implementation in both Android and iOS
Both call `stop()` to stop the query when listener is removed. Does something more have to be done ?

This is the implementation
```
void removeChangeListener(QueryChangeListenerToken token) {
        synchronized (lock) {
            queryChangeListenerTokens.remove(token);
            if (queryChangeListenerTokens.isEmpty())
                stop(true);
        }
    }
```
And the `stop()` makes a call to remove listener from database
```
   public void removeChangeListener(ListenerToken token) {
        if (token == null)
            throw new IllegalArgumentException("a token parameter is null");

        synchronized (lock) {
            if (token instanceof DocumentChangeListenerToken)
                removeDocumentChangeListener((DocumentChangeListenerToken) token);
            else
                removeDatabaseChangeListener((DatabaseChangeListenerToken) token);
        }
    }
```

(CC @hideki , @pasin )

**Comment by snej** [comment]
This issue was moved to couchbase/couchbase-lite-android#1606
