### ISSUE TITLE
Update WebSocket protocol to “BLIP_3"

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#411]
The `Sec-WebSocket-Protocol` value being sent in the WebSocket handshake is currently `BLIP_3a2`. For the release we should change it to `BLIP_3`, both because it's the final version 3 of BLIP, and to prevent anyone trying to use the GA release of CBL with a beta of SG or vice versa.

**Comment by snej** [comment]
I'm ready to merge the change (to "`BLIP_3+CBMobile_2`") as soon as SG is ready.

**Comment by adamcfraser** [comment]
SG change is ready (https://github.com/couchbase/go-blip/pull/26).
