### ISSUE TITLE
Intermittent failure of Continuous Fast Push test

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#416]
Observed on both Windows and Mac, and possibly others that I can't recall at the moment. 

[Gist of the logs](https://gist.github.com/borrrden/12829ebc6f45a7b2f22b288af8c2f95a).   The failure number is not variable (always 4970 == 5112).

**Comment by snej** [comment]
This may not be a P1 -- the only known effect is that the document count sent in the replication progress is too small, which is purely cosmetic.

What we don't know is whether this means not all the documents were replicated, which _would_ be a P1. Many of the tests compare the source and destination databases afterwards but this one doesn't. That would be the first thing to try.

**Comment by borrrden** [comment]
I updated the above gist with the log that showed both failures (separate file in the gist called failure_log2.txt)

**Comment by snej** [comment]
It's likely that the errors here were some of the ones that I've been fixing over the past few days while fixing #385, since I got them to appear by making a variant of "Continuous Fast Push" that pushes even faster (every 10ms).

Try reproducing this now that I've fixed (I hope) #385.

**Comment by borrrden** [comment]
Wouldn't you know...it just failed again 

http://mobile.jenkins.couchbase.com/view/Core_Based_Builds/job/couchbase-lite-core-linux/444/consoleFull

**Comment by borrrden** [comment]
And again on Windows

http://mobile.jenkins.couchbase.com/view/Core_Based_Builds/job/couchbase-lite-core-windows/398/consoleText

Note:  curl this URL since for some reason a piddling 5 MB log file is enough to choke Chrome AND Safari....

**Comment by snej** [comment]
Oops, I put the wrong issue number in that commit. It's not related to this one. Reopening.

**Comment by borrrden** [comment]
Update to this one anyway:  It happened again for both Linux and Windows as of bfded4e7bcbd2cdc1f881c93c97e3cd43f440c58

**Comment by borrrden** [comment]
I think I know what is happening here.  It doesn't seem like a library issue, but a test issue.  The replication is set up to stop a continuous replication once it goes idle.  In the failing case, the replicator happens to be going idle at 4970 docs, and so it is signaled to stop, but then it gets more docs and goes busy again.  However, since it is stopping those last docs never complete.  

I can see the DBWorker saying "hey, I actually got these....guys?" but it is ignored by the stopping replicator.

**Comment by borrrden** [comment]
My solution for this:  Instead of just checking for `_stopOnIdle` to stop the replication, check to see if either `_expectedDocumentCount` is <= 0 (the super fast sets it to -1 for some reason) , or matches the document count in progress.  This eliminates the race between `_stopOnIdle` and the DBWorker receiving write changes, while preserving the behavior of the existing tests.

**Comment by snej** [comment]
That makes sense ... in a continuous replication the pull side might still be idle an instant after the push side makes its last change.

> the super fast sets it to -1 for some reason

I added the feature that making `_expectedDocumentCount` less than zero disables the check. That's because the super-fast test goes so fast that the pull side misses many of the revisions the doc goes through, so the number of revisions that it actually  manages to pull is indeterminate.
