### ISSUE TITLE
Support multi process access same database

### ISSUE THREAD

**Issue by nguoithichkhampha** [couchbase/couchbase-lite-core#417]
Hi team,
I'm develop a system with many process read/write same database at the same time. Couch base can support this operation ?

**Comment by rajagp** [comment]
Multiple processes can share a CBL database as long they have relevant access to the shared location that hosts the database. However, CBL will not be able to automatically deliver change [database change](http://docs.couchbase.com/mobile/2.0/couchbase-lite-swift/db022/Typealiases.html#/s:18CouchbaseLiteSwift14DatabaseChangea)  notifications across processes - you will have to implement your own platform specific inter-process notification mechanism.  

Here is an [example](https://blog.couchbase.com/sharing-data-ios-app-extensions-sync-capability/)  of Couchbase Lite db shared between iOS App and corresponding App extensions 

(Also, in future , it would be preferable to raise such questions for clarifications in our [Dev Forums](forums.couchbase.com) .

**Comment by borrrden** [comment]
[Correct link for forums](https://forums.couchbase.com/c/mobile)

**Comment by nguoithichkhampha** [comment]
Thanks for quick reply. Did you have any benchmark result for read/write database on multi thread, multi process ?

**Comment by djpongh** [comment]
Please use GitHub for bugs only. Questions such as yours should be posted to our forums (link provided by @borrrden above).
