### ISSUE TITLE
Query by keys won't work in certain cases

### ISSUE THREAD

**Issue by mvysny** [couchbase/couchbase-lite-core#42]
When searching for documents indexed by a composite key (a list of strings), the view in some cases finds no documents. I am attaching a sample project to demonstrate the issue, just run it with ./gradlew - it will run the test and the test should fail (at least it fails for me, on Ubuntu 16.10 x86-64 java 8).

**Comment by mvysny** [comment]
[cblbug.zip](https://github.com/couchbase/couchbase-lite-core/files/668603/cblbug.zip)
I'm using CouchBase Lite 1.3.1 with ForestDB

**Comment by mvysny** [comment]
When I switch to SQLite the test case succeeds.

**Comment by borrrden** [comment]
This issue was moved to couchbase/couchbase-lite-java-core#1537
