### ISSUE TITLE
IncomingBlob quickly saturates file descriptor count

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#420]
One of the functional tests has a replication test that ends up with 2000 blobs.  The limit for number of open file descriptors for a process on Windows is 2048, and it seems that they all get used up during this process (Each DLL, etc, opened by the dotnet process itself also counts against this limit for .NET).  This causes mkTempFile to start returning invalid null handles and the result is that the handles cannot be closed later and the underlying numeric file descriptors are stuck open.  Specifically `fdopen` is setting `errno` to `EMFILE`.  It looks like these need to be throttled somehow.

**Comment by borrrden** [comment]
@snej I find it odd that the call to "open" succeeds inside of `mkstemp` to return a numeric fd, but then the subsequent call to `fdopen` to turn it into a `FILE *` fails.  Could we use all numeric file descriptors instead?

**Comment by snej** [comment]
Yikes! We shouldn't be opening that many file descriptors. IIRC, Mac and iOS default to a limit of 256 (3 of which are predefined.) Sounds like we need some throttling code to allow only a fixed number of IncomingBlobs to run at a time.

**Comment by borrrden** [comment]
I can take this on if you have an idea of the general location where this would be possible.  I get pretty lost when actors are involved.
