### ISSUE TITLE
Rename BLIP logging domain 

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-core#423]
We need to remove BLIP from the Couchbase Lite logs.

Possible choices -

BLIP  >> Replicator
BLIP >> Replicator Connection

**Comment by snej** [comment]
Why do we need to remove this from the logs? It's the name of the messaging protocol. This isn't part of marketing materials or anything.

**Comment by djpongh** [comment]
Agreed, closing. @ssmotra reopen if you disagree.
