### ISSUE TITLE
Null-pointer crash at Replicator::gotDocumentError

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#426]
### Builds
.net 2.0.0-b0571, SG 2.0.0-812, CBS 5.5.0-1924

### Test Ran
```
pytest -s --mode=di --server-version=5.5.0-1924 --sync-gateway-version=2.0.0-812 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py --liteserv-version=2.0.0-b0567 -k test_multiple_cbls_updates_concurrently_with_pull --skip-provisionin  --create-db-per-test test-db --no-conflicts
```
### Actual
Intermittently .net app crashes with the below error.
Crash in LiteCore.dll!litecore::repl::Replicator::gotDocumentError(fleece::slice docID, C4Error error, bool pushing, bool transient) Line 238

```
Unhandled exception at 0x00007FF9D31B070B (LiteCore.dll) in dotnet.exe.8528.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.
```
![screen shot 2018-02-26 at 3 30 27 pm](https://user-images.githubusercontent.com/24398601/36701950-0655bc92-1b0a-11e8-8ced-916c8348bb5a.png)

Backtrace:

![screen shot 2018-02-26 at 3 19 43 pm](https://user-images.githubusercontent.com/24398601/36701914-e8f0aa4a-1b09-11e8-88e1-d4a1367812f2.png)

Local Variables:

![screen shot 2018-02-26 at 3 56 09 pm](https://user-images.githubusercontent.com/24398601/36702837-9fe4a5aa-1b0d-11e8-97a1-0067ee43ce43.png)

**Comment by snej** [comment]
`_delegate` is null; need to test that before calling.
