### ISSUE TITLE
Null crash in SequenceTracker::mutex()

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#427]
### Builds
.net 2.0.0-b0571, SG 2.0.0-812, CBS 5.5.0-1924

### Test Ran
```
pytest --mode=di --server-version=5.5.0-1924 --sync-gateway-version=2.0.0-812 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py --liteserv-version=2.0.0-b0567 -k test_no_conflicts_update_with_revs_limit --skip-provisioning --no-conflicts --create-db-per-test test-db
```
### Actual
Intermittently .net app crashes with the below error.
Crash in LiteCore.dll!litecore::SequenceTracker::mutex() Line 48

```
Unhandled exception at 0x00007FF9D5F74C5D (LiteCore.dll) in dotnet.exe.8800.dmp: 0xC0000005: Access violation reading location 0x0000000000000020.
```
![screen shot 2018-02-26 at 3 38 12 pm](https://user-images.githubusercontent.com/24398601/36702242-1a8e0f6a-1b0b-11e8-9982-582923675b31.png)

Backtrace:

<img width="836" alt="screen shot 2018-02-26 at 12 02 54 pm" src="https://user-images.githubusercontent.com/24398601/36692515-1a7ddbf4-1aed-11e8-8122-3e1086acd060.png">

Local variables:

![screen shot 2018-02-26 at 3 51 11 pm](https://user-images.githubusercontent.com/24398601/36702671-eadebf10-1b0c-11e8-9eda-267702a2ef8b.png)

**Comment by snej** [comment]
Looks like `c4dbobs_getChanges` called on a NULL observer.
