### ISSUE TITLE
Possible unexpected merging when pulling an already-conflicted doc from server

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#431]
When a document with conflicts already exists on the server, and LiteCore pulls the document, it will receive all leaf revisions and add them one by one. When it receives the second leaf revision, that will create a conflict in the _local_ database. We haven't run a test, but we believe LiteCore will send a kC4ErrorConflict status for that document to CBL, which will trigger CBL to run its conflict resolver and create a merge revision.

On individual documents this might not be a bad thing, but en masse -- in a pre-existing server db that's accumulated a lot of conflicts made by 1.x clients that have never been manually resolved -- this would result in the 2.0 client doing a lot of work to create and push a lot of revisions. At least it would only happen to the _first_ 2.0 client, since afterwards the conflicts would all be merged and other clients wouldn't run into this.

We need to construct a functional test of this scenario to see what happens:

1. Create a SG database
2. Use the REST API or CBL 1.x to create documents that have active conflicts. Create various kinds, some where one branch is uniquely longest, some where there are two equally long branches, some with deleted branches.
3. Pull this db into a new CBL 2 db and observe what happens. Are new revisions created?
4. Push the CBL 2 db to SG and see whether revisions get pushed back.

We also need to look at the LC replicator code to see if there's a straightforward way to improve its behavior.

**Comment by tleyden** [comment]
I used SG REST API calls to generate the following conflicted docs in an SG instance .. more details to follow.

## Doc 088b928fc5847a947f06a65884af0205

```
digraph graphname{"2-fakerevhash_1b" -> "3-fakerevhash_1ba"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1b"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1a"; }
```

![screen shot 2018-02-27 at 12 53 47 pm](https://user-images.githubusercontent.com/296876/36754236-4bed9f8c-1bbd-11e8-8104-d20573f17c0d.png)


## Doc 38753358ef45a0e6c4fa63e1e4385a37

```
digraph graphname{"1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1a"; "2-fakerevhash_1b" [fontcolor=red];"1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1b" [label="Tombstone", fontcolor=red];}
```

![screen shot 2018-02-27 at 12 54 22 pm](https://user-images.githubusercontent.com/296876/36754272-603f7ba4-1bbd-11e8-9b7c-fcabf26cecc0.png)


## Doc aa9e3e60513bc5aa1c0a900de31b9179

```
digraph graphname{"1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-966a1fab90a810dc0a63565b70680e4e"; "2-866a1fab90a810dc0a63565b70680e4e" -> "3-766a1fab90a810dc0a63565b70680e4e"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-866a1fab90a810dc0a63565b70680e4e"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-aa9e3e60513bc5aa1c0a900de31b9179"; }
```

![screen shot 2018-02-27 at 12 55 00 pm](https://user-images.githubusercontent.com/296876/36754300-751e8178-1bbd-11e8-94d4-bdbd23a66409.png)


## Doc f42eb09046149ccfabf6a028a913271c

```
digraph graphname{"4-fakerevhash_1baa" [fontcolor=red];"3-fakerevhash_1ba" -> "4-fakerevhash_1baa" [label="Tombstone", fontcolor=red];"2-fakerevhash_1b" -> "3-fakerevhash_1ba"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1b"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash"; }
```

![screen shot 2018-02-27 at 12 55 29 pm](https://user-images.githubusercontent.com/296876/36754332-8524f52a-1bbd-11e8-9462-3fdccc12c986.png)


## Doc 2f3af5e9dd68c58dad874771a5a4e9bf

```
digraph graphname{"1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1a"; "1-fc2cf22c5e5007bd966869ebfe9e276a" -> "2-fakerevhash_1b"; }
```

![screen shot 2018-02-27 at 12 55 53 pm](https://user-images.githubusercontent.com/296876/36754359-95d394c6-1bbd-11e8-9699-7511791902b7.png)

**Comment by tleyden** [comment]
> Pull this db into a new CBL 2 db and observe what happens. Are new revisions created?

What's easiest way to introspect CBL 2 to find this info?  [cblite cat](https://github.com/couchbase/couchbase-lite-core/wiki/The-'cblite'-Tool)?

**Comment by snej** [comment]
'cblite revs' will show the rev tree.

**Comment by borrrden** [comment]
@tleyden Did you create a sync gateway with populated data for this?  If so where can I find it?

**Comment by tleyden** [comment]
I added a tried modifying mobile-training-todo to pull the database from sync gateway (after modifiying the [config](https://gist.github.com/tleyden/1c13a7516b8b137d5f911cd30c0648c7#file-sg_config-json) to add a few users with `admin_channels:["*"])

After pulling the DB I stopped the mobile-training-todo app, and found the database on the filesystem and used `cblite` to inspect it.

For some reason, `cblite` is only showing one doc:

```
$ cblite ls user1.cblite2/
aa9e3e60513bc5aa1c0a900de31b9179
```

I'm expecting it to show 5 docs rather than 1.

I'm still double-checking to make sure that this was a valid test.

**Logs**

- mobile-training-todo: https://gist.github.com/tleyden/1c13a7516b8b137d5f911cd30c0648c7#file-mobile_training_todo_logs-txt
- sync gateway: https://gist.github.com/tleyden/1c13a7516b8b137d5f911cd30c0648c7#file-sg_logs-txt

**Config**

- sync gateway: https://gist.github.com/tleyden/1c13a7516b8b137d5f911cd30c0648c7#file-sg_logs-txt

**Versions**

- couchbase-lite-core: 6bc10a3614b61ad63beb9c5909ff3c8c4ea1dd66 (feature/bump_blip_cpp_version branch.. this was an accident)
- couchbase-lite-ios: 44ca3f029d1b34e86a9b702963cd47fdd029b8ba  
- blip-cpp: a4f2ad8858ada06fd0d69410daee01c6d4f222da

**Comment by tleyden** [comment]
I think I see what happened:

```
2018-03-01 10:59:08.167362-0800 Todo[58588:2534009] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://34.237.242.100:4984/db]]: error pulling 'f42eb09046149ccfabf6a028a913271c': Error Domain=CouchbaseLite Code=6 "bad revision ID" UserInfo={NSLocalizedDescription=bad revision ID}
```

Cblite is rejecting the fake rev digests I added in the test data.  I'll regenerate the test data using real digests.

**Comment by tleyden** [comment]
# Results after pulling database from SG 

## Doc 9197e9e2e09c326d691de60c7021ec07

```
$ cblite revs user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
Document "9197e9e2e09c326d691de60c7021ec07", current revID 3-3b244220176442406c5ea22130e807becf8d76fe, sequence #10
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1), 16 bytes, KeepBody
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#10), Deleted, Leaf
  * 2-22c5e5007b (#2), 14 bytes
    * 3-3b244220176442406c5ea22130e807becf8d76fe (#10), 16 bytes, Leaf, KeepBody
```

## Doc 6688bc723084e87bd84cecef60c274a1

```
$ cblite revs user1.cblite2/ 6688bc723084e87bd84cecef60c274a1
Document "6688bc723084e87bd84cecef60c274a1", current revID 2-33e5e5007b, sequence #4
* 1-5ffe6ebf2a4bfc94eb8642bfa9dbbb7c (#3)
  * 2-44e5e5007b (#4), 22 bytes, Deleted, Leaf, KeepBody, Conflict
  * 2-33e5e5007b (#3), 14 bytes, Leaf, KeepBody
```

## Doc e8a6bd52edc0bde97c07880cc598ac5a

```
$ cblite revs user1.cblite2/ e8a6bd52edc0bde97c07880cc598ac5a
Document "e8a6bd52edc0bde97c07880cc598ac5a", current revID 3-fe3bcd1fd23857db2aac239e9d23d17187f3f452, sequence #12
* 1-5ffe6ebf2a4bfc94eb8642bfa9dbbb7c (#5)
  * 2-33e5e5007b (#5)
    * 3-44e5e5007b (#5), 16 bytes, KeepBody
      * 4-0670cab32a5c2ca03a950876e2be20bfbc0a4404 (#11), Deleted, Leaf
  * 2-22e5e5007b (#7), 14 bytes, KeepBody
    * 3-e0e28422b08c3772344efd1f61956bbae9a1c271 (#11)
      * 4-a62b0b205fee580d368fd92b1e68e73d34824047 (#12), Deleted, Leaf
  * 2-11e5e5007b (#6), 14 bytes
    * 3-fe3bcd1fd23857db2aac239e9d23d17187f3f452 (#12), 16 bytes, Leaf, KeepBody
```

## Doc 8c52a6d62ce3f7255268016515d32841

```
$ cblite revs user1.cblite2/ 8c52a6d62ce3f7255268016515d32841
Document "8c52a6d62ce3f7255268016515d32841", current revID 2-11b5e5007b, sequence #9
* 1-f4f4abf8d8358481992040b1b42629aa (#8)
  * 2-22b5e5007b (#9), Conflict
    * 3-33b5e5007b (#9), Conflict
      * 4-44b5e5007b (#9), Conflict
        * 5-55b5e5007b (#9), 26 bytes, Deleted, Leaf, KeepBody, Conflict
  * 2-11b5e5007b (#8), 14 bytes, Leaf, KeepBody
```


## Doc d7e2ebe80c1fd93811328a179f002cc8

```
$ cblite revs user1.cblite2/ d7e2ebe80c1fd93811328a179f002cc8
Document "d7e2ebe80c1fd93811328a179f002cc8", current revID 3-43ce8dbeeceb68fe4e892ec8cf0a2fb929911e23, sequence #15
* 1-327a5283f9ef0abdef309438fc898da0 (#13)
  * 2-33e5e5007b (#13), 14 bytes, KeepBody
    * 3-4ed62bad60c276fa8a3e257ecfc359c5c29e34bc (#15), Deleted, Leaf
  * 2-22e5e5007b (#14), 14 bytes
    * 3-43ce8dbeeceb68fe4e892ec8cf0a2fb929911e23 (#15), 14 bytes, Leaf, KeepBody
```

**Comment by snej** [comment]
SG now sends CBL only the current revision of a doc, not conflicting revisions, as a result of couchbase/sync_gateway#3349. That eliminates this issue.
