### ISSUE TITLE
Heap corruption in BLIPIO

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#432]
### Builds
.net 2.0.0-b0571, SG 2.0.0-812, CBS 5.5.0-1924

### Test Ran
```
pytest -s --mode=di --server-version=5.5.0-1924 --sync-gateway-version=2.0.0-812 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py --liteserv-version=2.0.0-b0567 -k test_migrate_conflicts_to_noConflicts_CBL  --create-db-per-test test-db
```
### Actual
Intermittently .net app crashes with the below error.
```
Unhandled Exception at 0x00007FF88F3E87BB (ntdll.dl) in dotnet.exe.6692.dmp: 0xC0000374: 
A heap has been corrupted (parameters: 0x00007FF88F44C6E0)
```
Stacktrace:
![screen shot 2018-02-27 at 11 46 12 am](https://user-images.githubusercontent.com/24398601/36752206-3441a668-1bb7-11e8-8b1a-b2d5eb0a35cf.png)

Source:

<img width="763" alt="screen shot 2018-02-27 at 11 59 55 am" src="https://user-images.githubusercontent.com/24398601/36752233-51844104-1bb7-11e8-8192-68076697b416.png">

Local variables for the last non Inline Frame:

![screen shot 2018-02-27 at 12 05 33 pm](https://user-images.githubusercontent.com/24398601/36752245-5f3701ec-1bb7-11e8-9ac3-0aea3e9444a5.png)

**Comment by raghusarangapani** [comment]
I ran the test against ios and did not see a Heap corruption issue. The test failed with a forbidden message tracked by #385 
```
HTTPError: 403 Client Error: Forbidden for url: http://192.168.33.22:4984/db/no-conflicts_0?conflicts=true&revs=true
```

Even with .net, the heap corruption is intermittent.

@borrrden might have better idea about the heap debugging modes in windows.

**Comment by borrrden** [comment]
@raghusarangapani How intermittent is this?

**Comment by raghusarangapani** [comment]
I've seen it only once so far.

**Comment by snej** [comment]
@djpongh Maybe consider downgrading from P1 since this seems pretty rare...

**Comment by borrrden** [comment]
I think I figured out why this happens by chance.  I saw the same exact heap corruption during investigation of a different issue which turned out to be .NET calling `c4socket_close` too many times when there was a transmission error condition.  My new theory is that it also caused this.

**Comment by borrrden** [comment]
I'm going to close this due to the above theory, but reopen it if it happens again.
