### ISSUE TITLE
Unable to push new revisions after pulling an already-conflicted doc from server

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-core#437]
I'm extracting this issue out of https://github.com/couchbase/couchbase-lite-core/issues/431 -- creating a separate issues since this is one particular case of https://github.com/couchbase/couchbase-lite-core/issues/431.

## Overview

After using cblite-ios to pull an already conflicted doc from sync gateway with rev tree:

<img width="419" alt="screen shot 2018-03-01 at 1 28 30 pm" src="https://user-images.githubusercontent.com/296876/36870598-8493d426-1d54-11e8-9da9-888484f17b1d.png">

it ends up w/ a revtree on the cblite side of:

```
$ cblite revs user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
Document "9197e9e2e09c326d691de60c7021ec07", current revID 3-3b244220176442406c5ea22130e807becf8d76fe, sequence #10
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1), 16 bytes, KeepBody
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#10), Deleted, Leaf
  * 2-22c5e5007b (#2), 14 bytes
    * 3-3b244220176442406c5ea22130e807becf8d76fe (#10), 16 bytes, Leaf, KeepBody
```

where it has chosen the *shorter* conflicting revision branch as the winner.

The reason it chooses the shorter conflicting revision branch is due to the order which it receives the revisions.  From the Sync Gateway logs:

```
2018-03-01T23:11:14.243Z Sync+: [5b6eb400] Sending rev "9197e9e2e09c326d691de60c7021ec07" 3-44c5e5007b based on 0 known.  User:GUEST
2018-03-01T23:11:14.243Z Sync+: [5b6eb400] Sending rev "9197e9e2e09c326d691de60c7021ec07" 2-22c5e5007b based on 2 known.  User:GUEST
```

1. When `3-44c5e5007b` is received, there are no local revs and so it is written as the local rev.  
1. When `2-22c5e5007b` is later received, it is treated as the remote rev and so the local rev (now `3-44c5e5007b`) is tombstoned.  

Cblite then attempts to push revision `3-3b244220176442406c5ea22130e807becf8d76fe` via the `proposeChanges` endpoint, which rejects it since it has a parent of `2-22c5e5007b`, which is a non-winning revision and would create a conflict.  Sync Gateway rejects this due to the fact that [proposeChanges](https://github.com/couchbase/couchbase-lite-core/blob/master/modules/docs/pages/replication-protocol.adoc#proposechanges) has the following behavior:

> If the document exists, but the given serverRevID is not known or not current, the proposed document SHOULD be rejected with a 409 status (see below.)

On couchbase lite, it shows the pushed revision being rejected with:

```
2018-03-01 15:11:14.452779-0800 Todo[75646:3001042] CouchbaseLite Sync ERROR: {Push#4} Proposed rev '9197e9e2e09c326d691de60c7021ec07' #3-3b244220176442406c5ea22130e807becf8d76fe rejected with status 409
```

Further updates to the document  are rejected for the same reason, with similar logs.

## Steps to repro

1. Run SG 2.0.0 build 815 with [this config](https://gist.github.com/tleyden/4d6f7a59b26c8a8b4cf7b466e0abca62)
1. Add the following revisions

Rev1

```
echo '{"value":"initial_rev_____"}' |  \
  http POST http://SG_URL:4985/db3/ \
  Accept:application/json \
  Cache-Control:no-cache \
  Content-Type:application/json 
```

Rev2a

```
echo '{
  "docs": [
  	{
         "_id":"a32719244b67ff5f9484d5f9641beab6",
         "_rev":"2-22e5e5007b",
         "_revisions":{
            "ids":[
               "22e5e5007b",
               "26dc9200767feefd2568e1a517c6be7e"
            ],
            "start":2
         },
         "description": "rev2a"
  	}
  ],
  "new_edits": false
}' |  \
  http POST http://SG_URL:4985/db3/_bulk_docs \
  Accept:application/json \
  Cache-Control:no-cache \
  Content-Type:application/json 
```

Rev2b

```
echo '{
  "docs": [
  	{
         "_id":"a32719244b67ff5f9484d5f9641beab6",
         "_rev":"2-22f4e5007b",
         "_revisions":{
            "ids":[
               "22f4e5007b",
               "26dc9200767feefd2568e1a517c6be7e"
            ],
            "start":2
         },
         "description": "rev2b"
  	}
  ],
  "new_edits": false
}' |  \
  http POST http://SG_URL:4985/db3/_bulk_docs \
  Accept:application/json \
  Cache-Control:no-cache \
  Content-Type:application/json 
```

Rev 2ba

```
echo '{
  "docs": [
  	{
         "_id":"a32719244b67ff5f9484d5f9641beab6",
         "_rev":"3-33f4e5007b",
         "_revisions":{
            "ids":[
            	"33f4e5007b",
               "22f4e5007b",
               "26dc9200767feefd2568e1a517c6be7e"
            ],
            "start":3
         },
         "description": "rev2ba"
  	}
  ],
  "new_edits": false
}' |  \
  http POST http://SG_URL:4985/db3/_bulk_docs \
  Accept:application/json \
  Cache-Control:no-cache \
  Content-Type:application/json 
```

1. Configure mobile-training-todo w/ these settings:

```
let kLoggingEnabled = true
let kLoginFlowEnabled = true
let kSyncEnabled = true
let kSyncEndpoint = "ws://SG_URL:4984/db3"
```

1. Launch mobile-training todo and login
1. For expected vs actual, see above
1. Bonus step: hack mobile-training-todo ListViewController.swift to add [this code](https://gist.github.com/tleyden/7db798086586033e421a8d191054cff8) to add a new revision, and note that it is not pushed to sync gateway for the reasons mentioned above.

**Comment by tleyden** [comment]
I caught up w/ @adamcfraser on this, and he mentioned that SG is sending the revision history and CBLite could use that to determine how to choose the winning revision.

For example, `3-44c5e5007b` is being sent with a rev history of:

`2-33c5e5007b,1-8a5979938263d941249bb42083feab0a` which is the **history** field of the blip request properties.

Likewise, `2-22c5e5007b` is being sent with a rev history of `1-8a5979938263d941249bb42083feab0a`

**Comment by snej** [comment]
Each revision is being sent as a separate BLIP message, and it's added to the local db when the message is received. This makes it awkward to compare two revisions of a document before inserting them.

**Comment by tleyden** [comment]
Digging into this more, it looks like the behavior is non-deterministic.   

In one test, it chose a different branch as the winning branch, and the revtree on the cblite side was as follows:

```
$ cblite revs user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
Document "9197e9e2e09c326d691de60c7021ec07", current revID 3-44c5e5007b, sequence #12
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#4)
    * 3-44c5e5007b (#4), 16 bytes, Leaf, KeepBody
  * 2-22c5e5007b (#1), 14 bytes, KeepBody
    * 3-02cb030dee9c8689e0b7de40f51ba2f1b56c4587 (#12), Deleted, Leaf
```

I think it might depend on the ordering in which the leaf revisions were received from Sync Gateway.  In this particular case,  `2-22c5e5007b` was received first, whereas in the previous case, `3-44c5e5007b`

**Comment by pasin** [comment]
With the current implementation of the conflict resolution in CBL, the revision that is saved first will be considered as `local revision`. The next revision that is saved will be considered as  `remote revision`. The local revision will be tombstoned after resolving the conflict.

**Comment by tleyden** [comment]
Meeting follow up w/ @snej @adamcfraser @pasin:

- Modify Sync Gateway `sendChanges()` and change `db.ChangesOptions{Conflicts:  true}` -> `db.ChangesOptions{Conflicts:  false}`.  This will cause Sync Gateway to only send the *winning* revision and history, which will sidestep the issue.

Further testing that should be done:

1. Repeat the steps in this ticket
1. Via the SG rest API, tombstone the winning revision and promote another branch (SG still has the full rev tree)
1. Verify that CBLite correctly pulls the new winning revision

**Comment by tleyden** [comment]
Looks like changing it to `db.ChangesOptions{Conflicts: false}` fixes this issue. 

After retesting w/ a Sync Gateway with that change, now the local cbite revtree is:

```
$ cblite revs user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
Document "9197e9e2e09c326d691de60c7021ec07", current revID 3-44c5e5007b, sequence #1
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1), 16 bytes, Leaf, KeepBody
``` 

In the SG logs, I can see it now only sends that single revision for that doc:

```
2018-03-02T20:05:19.776Z Sync+: [325032f3] Sending rev "9197e9e2e09c326d691de60c7021ec07" 3-44c5e5007b based on 0 known.  User:GUEST
```

**Comment by tleyden** [comment]
> Further testing that should be done:

If I delete the document on CBLite, it "bounces back" and shows a different revtree branch, which might feel like unexpected behavior to users.  This is without any SG REST api calls, just the local CBL delete and back and forth sync.

Also, it's worth calling out that the behavior is different depending on whether the device is connected (and syncing).  If the device is offline, the doc will appear as being deleted.  Once it comes back online however, the winning revision on the other revtree branch will be showing.

Steps to repro + details:

1. Pull docs from SG -> CBL  (actually it's a bidirectional continuous sync, but only the pull matters)
1. Shutdown sync gateway to temporarily disable sync, so that CBL can be observed before syncing happens
1. Delete doc on CBL side via `self.database.deleteDocument(self.database.document(withID: "9197e9e2e09c326d691de60c7021ec07")!.toMutable())`

At this point, cblite considers the doc as deleted:

```
$ cblite ls user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
(No documents with IDs matching "9197e9e2e09c326d691de60c7021ec07")

$ cblite revs user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
Document "9197e9e2e09c326d691de60c7021ec07", current revID 4-d0a944d3b4f02a4618088599618c0811c8bd163f, sequence #6, Deleted
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1), 16 bytes, KeepBody
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#6), Deleted, Leaf
```

1. Restart sync gateway to enable sync
1. Check the state of the cbl rev tree:

```
$ cblite ls user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
9197e9e2e09c326d691de60c7021ec07

$ cblite revs user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
Document "9197e9e2e09c326d691de60c7021ec07", current revID 2-22c5e5007b, sequence #7
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1)
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#6), Deleted, Leaf, KeepBody
  * 2-22c5e5007b (#7), 14 bytes, Leaf, KeepBody

$ cblite cat user1.cblite2/ 9197e9e2e09c326d691de60c7021ec07
{"description": "rev2a"}
```

The SG rev tree matches:

```
digraph graphname{"1-8a5979938263d941249bb42083feab0a" -> "2-22c5e5007b"; "4-d0a944d3b4f02a4618088599618c0811c8bd163f" [fontcolor=red];"3-44c5e5007b" -> "4-d0a944d3b4f02a4618088599618c0811c8bd163f" [label="Tombstone", fontcolor=red];"2-33c5e5007b" -> "3-44c5e5007b"; "1-8a5979938263d941249bb42083feab0a" -> "2-33c5e5007b"; }
```

<img width="623" alt="screen shot 2018-03-02 at 12 33 50 pm" src="https://user-images.githubusercontent.com/296876/36920595-febb53de-1e15-11e8-9935-ed2907cc7806.png">

**Comment by sridevi-15** [comment]
I tried this scenario : 
I created sync-gateway tree structure as mentioned by Traun in this ticket
1. Create docs in sg.
2. Create conflict 2a
3. Create another conflict 2b
4. update the docs -> this created child node to 2b which has some new update on doc.
5. push to CBL

According to cblite tool revs command, it has deleted the node which has created at step 4 and 2a is remained, but when I check the doc content, I can see the content updated at step 4 on cbl

**Comment by tleyden** [comment]
> If I delete the document on CBLite, it "bounces back" and shows a different revtree branch, which might feel like unexpected behavior to users.

After digging into this a bit more, this sounds like what is described here: https://github.com/couchbase/couchbase-lite-ios/issues/1788#issuecomment-359050200

and overall, it is following the expected behavior with respect to conflicts.   However, there are some notable differences in behavior between CBL2 and CBL1 in this scenario:

## CBL1.x gives the ability to tombstone all conflicting branches

In  CBL1 you can:

    - Detect the doc is in conflict
    - Tombstone *all* conflicting revisions, not just one of them.  This puts more power in the application developer to have it "really delete" when needed.  I don't see a way to do that in CBL2 in this scenario.  (@pasin / @snej if you know of a way, let me know)

## CBL1.x shows consistent behavior with SG even when offline 

CBL1 has a rev tree that is consistent with SG as soon as the revision is tombstoned, even if it's offline.

**CBL1 behavior**

After doc is deleted, regardless if online or offline, it immediately has this rev tree structure

```
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1)
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#6), Deleted, Leaf, KeepBody
  * 2-22c5e5007b (#7), 14 bytes, Leaf, KeepBody
```

and returns 2-22c5e5007b as the winning rev.

**CBL2 behavior**

*Time step 1:*

Even if the device is connected, there will be a small time period until it syncs up where the doc will be in this state:

```
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1), 16 bytes, KeepBody
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#6), Deleted, Leaf
```

Where the doc is deleted since the winning (and only branch) is tombstoned.

*Time step 2:*

After syncing, the doc will end up in this state, where `2-22c5e5007b` is now the winning revision

```
* 1-8a5979938263d941249bb42083feab0a (#1)
  * 2-33c5e5007b (#1)
    * 3-44c5e5007b (#1)
      * 4-d0a944d3b4f02a4618088599618c0811c8bd163f (#6), Deleted, Leaf, KeepBody
  * 2-22c5e5007b (#7), 14 bytes, Leaf, KeepBody
```

**Comment by snej** [comment]
SG now sends CBL only the current revision of a doc, not conflicting revisions, as a result of couchbase/sync_gateway#3349. That eliminates this issue.
