### ISSUE TITLE
Upgrade to 2.0 | Resolve existing conflicts 

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-core#438]
When a user upgrades their CBL database, any existing conflicts that existed in 1.x should be resolved.

The algorithm for resolving conflicts during the upgrade needs to be identical with the algorithm for picking the winning revision in 1.x.

**Comment by snej** [comment]
I couldn't remember whether the Upgrader class does this already. It should only copy the 1.x database's default revision (and ancestors), not conflicting branches.

**Comment by snej** [comment]
Fixed in ce4c4f59509ca2a8216d87b6e0770f2fdb076fc3
