### ISSUE TITLE
Port CBL unit tests into lite-core C4Test

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-core#44]
Task: Port unit test from Couchbase 1.x into C4Tests

##### Port from Couchbase Lite iOS:
- [ ] Database_Tests.m
- [ ] DatabaseInternal_Tests.m

##### Port from Couchbase Lite .NET:

**Comment by hideki** [comment]
#### Ported from DatabaseInternal_Tests.m
- [ ] test01_CRUD
- [ ] test02_EmptyDoc
- [ ] test02_ExpectedRevIDs
- [ ] test03_DeleteWithProperties
- [ ] test04_DeleteAndRecreate
- [ ] test05_Validation
- [ ] test06_RevTree
- [ ] test07_RevTreeConflict
- [ ] test08_DeterministicRevIDs
- [ ] test09_DuplicateRev
- [ ] test16_ReplicatorSequences
- [ ] test17_LocalDocs
- [ ] test18_FindMissingRevisions
- [ ] test19_Purge
- [ ] test20_PurgeRevs
- [ ] test21_DeleteDatabase
- [ ] test22_Manager_Close
- [ ] test23_MakeRevisionHistoryDict
- [ ] test24_UpgradeDB
- [ ] test25_FileProtection
- [ ] test26_ReAddAfterPurge
- [ ] test27_ChangesSinceSequence
- [ ] test28_enableAutoCompact
- [ ] test29_autoPruneOnPut
- [ ] test29_autoPruneOnForceInsert
- [ ] test30_conflictAfterPrune

#### Ported from Database_Tests.m
- [ ] test00_Manager
- [ ] test00_ValidDatabaseNames
- [ ] test01_ExcludedFromBackup
- [ ] test02_DeleteDatabase
- [ ] test03_CreateDocument
- [ ] test05_CreateRevisions
- [ ] test06_RevisionIdEquivalentRevisions
- [ ] test07_CreateNewRevisions
- [ ] test071_PutExistingRevision
- [ ] test072_PutExistingRevisionWithAttachment
- [ ] test075_UpdateDocInTransaction
- [ ] test08_SaveDocumentWithNaNProperty
- [ ] test09_DeleteDocument
- [ ] test10_PurgeDocument
- [ ] test11_Validation
- [ ] test12_AllDocuments
- [ ] test12_AllDocumentsPrefixMatchLevel
- [ ] test12_AllDocumentsBySequence
- [ ] test12_AllDocumentsBySequenceDescending
- [ ] test13_LocalDocs
- [ ] test14_Conflict
- [ ] test15_Resolve_Conflict
- [ ] test16_CreateIdenticalParentContentRevisions
- [ ] test17_History
- [ ] test18_Attachments
- [ ] test18a_EncryptedAttachments
- [ ] test18b_AttachmentMissingFile
- [ ] test19_ChangeTracking
- [ ] test20_ChangeUUID
- [ ] test21_ConcurrentWrites
- [ ] test22_CreateDocWithAttachmentInSingleRevision
- [ ] test23_ReplaceDatabaseSQLite
- [ ] test23b_ReplaceDatabaseForestDB
- [ ] test24_upgradeDatabase
- [ ] test25_CloseDatabase
- [ ] test26_DocumentExpiry
- [ ] test27_AbortedCommit
- [ ] test17_History
- [ ] test18_Attachments
- [ ] test18a_EncryptedAttachments
- [ ] test18b_AttachmentMissingFile
- [ ] test19_ChangeTracking
- [ ] test20_ChangeUUID
- [ ] test21_ConcurrentWrites
- [ ] test22_CreateDocWithAttachmentInSingleRevision

**Comment by borrrden** [comment]
@djpongh Not sure this is still worth doing.  I find that many of these tests already have the equivalent elsewhere, or the once exposed functionality is not easily accessible anymore.
