### ISSUE TITLE
parseClosePayload invalid logic

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#441]
Related to https://github.com/couchbase/couchbase-lite-net/issues/967 and https://github.com/couchbase/couchbase-lite-net/issues/977 

The function [parseClosePayload](https://github.com/couchbaselabs/BLIP-Cpp/blob/bb72dd8b966fe3423dc8077ac16625a75f604689/src/websocket/WebSocketProtocol.hh#L309) is responsible for ultimately setting the information that gets sent back to Couchbase Lite for analysis and reporting to the user if the close message is not blank, however it seems like any web socket code between 1004 and 1006 gets forced to 1005.

```c++
if (cf.code < 1000 || cf.code > 4999 || (cf.code > 1011 && cf.code < 4000) || 
(cf.code >= 1004 && cf.code <= 1006) || 
!isValidUtf8((unsigned char *) cf.message, cf.length)) {
    return {};
}
```

This will return a blank `CloseFrame` object back up to the caller, which will then switch the 0 status to 1005 and clear the message via

```c++
auto msg = ClientProtocol::parseClosePayload((char *)_closeMessage.buf, _closeMessage.size);
status.code = msg.code ? msg.code : kCodeStatusCodeExpected;
status.message = slice(msg.message, msg.length);
```

**Comment by snej** [comment]
I think this is correct, actually. According to the spec, 1004 is reserved/undefined, and 1005-1006 "MUST NOT be set as a status code in a Close control frame".
