### ISSUE TITLE
Intermittent BLIP invalid checksum causes replication failure

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#442]
Running functional tests on UWP (confirmed by me) or .NET Core Windows (confirmed by @raghusarangapani ) sometimes causes an exception to be thrown due to an invalid message checksum.  This will cause the replication to stop.  This needs to be root caused.  Is Sync Gateway getting it wrong or it Couchbase Lite?  

The first order of business is getting a debugging plan together to figure out the answer to this question.

**Comment by snej** [comment]
Interesting that this has only happened with CBL .NET ... maybe something's happening in the .NET WebSocket implementation that's modifying or re-ordering messages?

**Comment by borrrden** [comment]
I don't think it is possible for that to happen.  There is one method that reads data called `Receive()` and it does this:

1. Push the entire body of receive onto a serial queue
2. If already receiving, or closed, return
3. Set receiving = true
4. Wait for read access mutex
5. Setup a cancellation that will abort the read after the idle timeout
6. Start an async read on the network stream

That's the end of the serial queue block, and then there is the read callback

1. Set receiving = false
2. Check for error, if found then close the connection and release the read mutex
3. Add to receiving bytes pending list (marks bytes that are not yet processed by LiteCore)
4. Read the bytes from the stream (# indicated by return value of read)
5. Release the read mutex
6. Dispatch c4socket_received onto the C4Socket serial queue (separate from the above queue as in CBLWebSocket.mm).  It is guarded inside the block to make sure that the socket has not closed between now and then.
7. If we don't have too many pending bytes, call `Receive()` again (otherwise it will be called when appropriate from the `completedReceive` callback).

**Comment by borrrden** [comment]
Hmmm rubber duck debugging might be having an effect.  I guess it is possible for the read callbacks to race?

**Comment by borrrden** [comment]
I tweaked .NET to hold onto the read mutex until after `c4socket_received` and I can no longer reproduce the issue the way I used to, so I will close this
