### ISSUE TITLE
CBL gets rejected to push changes to sync-gateway which has two conflict with one tombstoned 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#448]
### Environment
sg version : 891
cbl ios version : 670
cbl Android version : 385

### Steps to reproduce : 
1. create docs in sg.
        2. Create two conflicts with 2-hex in sg.
        3. Tombstone the doc which has higher and active revision in sg.
        4. Start replication  with push_pull and continous. 
        5. Once replicator is idle, update doc in cbl.
        6. continue the replication and 
        7. Wait until replication is idle and stop the replicaitor
        8. Verify updates from cbl got replicated to sg. 

### Errors seen in cbl  :  2018-03-06 10:05:16.065429-0800 CBLTestServer-iOS[20058:795441] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://192.168.33.11:4984/db]]: error pushing 'sg_docs_0': Error Domain=CouchbaseLite Code=10409 "rejected by proposeChanges" UserInfo={NSLocalizedDescription=rejected by proposeChanges}
2018-03-06 10:05:16.065563-0800 CBLTestServer-iOS[20058:795522] CouchbaseLite Sync ERROR: {Push#4} Proposed rev 'sg_docs_8' 

Expected : Doc which got updated in cbl should get replicated to sg.

### cbl rev tree for one doc : 
admins-MacBook-Pro-175:Tools sridevi.saragadam$ ./cblite revs /Users/sridevi.saragadam/Library/Developer/CoreSimulator/Devices/9E83DB6D-391D-4CB3-972D-3FDA93279BB7/data/Containers/Data/Application/C2E0819B-E90E-4B38-BD9E-C25FA731E0CE/Library/Application\ Support/CouchbaseLite/cbl-test1520359488.39.cblite2 sg_docs_0
Document "sg_docs_0", current revID 3-94b1e97162fcaafe3700ff46de56185b4c5d09c4, sequence #19
* 1-a6014ad0cdb04db5f8b9fb881074bb74 (#1)
  * 2-41fa (#1), 34 bytes, KeepBody
    * 3-94b1e97162fcaafe3700ff46de56185b4c5d09c4 (#19), 38 bytes, Leaf

### sg tree for one doc 👍 
<img width="603" alt="screen shot 2018-03-06 at 10 18 34 am" src="https://user-images.githubusercontent.com/17035128/37050078-c28775b8-2127-11e8-9b4c-add612a625c0.png">

**Comment by snej** [comment]
Pushing that CBL doc to that SG doc should work, if the rev trees are as you showed. Is there something going wrong on the SG side?

**Comment by sridevi-15** [comment]
May be, but I do not see any errors or any traces related to this in sg logs.

**Comment by snej** [comment]
I just wrote a LiteCore unit test for this, and it passes. The only difference is that I use one-shot replications -- first I pull the doc from SG, then I update it in LiteCore, then I push to SG. But that shouldn't affect the way the revisions are handled.

**Comment by borrrden** [comment]
I pointed out that if you use upper case in this test it will fail. Lite core will force lower case and make a conflict. This seems to have been ignored when filing the ticket.

**Comment by snej** [comment]
OK, that's another side effect of LiteCore compressed revIDs -- it stores them as binary internally, then regenerates the hex. Of course that doesn't preserve case, but everything uses lowercase so it works. But yes, **if you manually create a revision ID with uppercase hex, things will break**.

@sridevi-15, if you change the uppercase hex to lowercase, does the test still fail?

**Comment by borrrden** [comment]
I commented this internally yesterday, but this change alone creates a similar race to #416 so the solution that passes every time for me is a combination of

1. Using lowercase
2. Waiting for idle multiple times until the success criteria is met

e.g.
```python
while True:
    replicator.wait_until_replicator_idle(repl)
    sg_docs = sg_client.get_all_docs(url=sg_url, db=sg_db, auth=session, include_docs=True)
    sg_docs = sg_docs["rows"]
    if sg_docs[0]["doc"]["updates-cbl"] == 1:
        break
```

**Comment by snej** [comment]
It's really a lot easier if you use one-shot replications for these kinds of tests, unless they require continuous replication to work.

**Comment by borrrden** [comment]
One-shot replication has the issue of not pushing the conflict resolutions it just made (as mentioned in point 2 of [this comment](https://github.com/couchbase/couchbase-lite-core/issues/433#issuecomment-370659705)

**Comment by borrrden** [comment]
The workaround being to run 2 one-shot replications one after another, I suppose.

**Comment by sridevi-15** [comment]
@borrrden having this logic 
"""
while True:
    replicator.wait_until_replicator_idle(repl)
    sg_docs = sg_client.get_all_docs(url=sg_url, db=sg_db, auth=session, include_docs=True)
    sg_docs = sg_docs["rows"]
    if sg_docs[0]["doc"]["updates-cbl"] == 1:
        break
"""
It might go into infinite loop if there a bug that sg_docs[0]["doc"]["updates-cbl"] never gets 1. I will change to one shot replication

**Comment by borrrden** [comment]
Yes, that was a simple sketch.  You could add a counter to only try a certain number of times or something.  Be careful with one shot replication if you need a resolved conflict on CBL to be replicated to SG though.

**Comment by sridevi-15** [comment]
Closing this ticket as with lower case  works. Jens adding check to reject upper case revision id and have error message in lite-core
