### ISSUE TITLE
Throwing bad revision id for the revision created by sync-gateway

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#452]
### Environment 
ios build : 678
Android build : 397

### steps to reproduce 👍 
1. create docs in sg.
2. Create two conflicts with 2-hex in sg.
3. update doc in sg to have new revision to one of the conflicted branch of sg, the counter for property updates increments to 1
4. Start replication with push pull and continous true
5. wait until replication is done.

### REsult : Cbl does not get any docs
Cbl errors : Throws bad revision id : 
_2018-03-06 22:51:38.489762-0800 CBLTestServer-iOS[43800:1672165] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://192.168.33.11:4984/db]]: error pulling 'sg_docs_0': Error Domain=CouchbaseLite Code=6 "bad revision ID" UserInfo={NSLocalizedDescription=bad revision ID}
2018-03-06 22:51:38.489962-0800 CBLTestServer-iOS[43800:1673543] CouchbaseLite Sync WARNING: {DBWorker#2} Failed to insert 'sg_docs_1' #3-ef3a984983cb4e47f6fdc1b7e8082e18 : error 1/6_

### Expected : cbl should have docs replicated from sg

cbl logs : https://gist.github.com/sridevi-15/b133bf59fcf34a2181474d89b4a5505f

Note : It worked fine on build ios 670, 647

**Comment by borrrden** [comment]
By any chance is this using upper case revision IDs again?  A commit today in LiteCore now rejects them.

**Comment by borrrden** [comment]
The latest commit in mobile-testkit uses upper case for this test.  Running it as is I notice this error.  Changing to lower case makes the test pass.
