### ISSUE TITLE
Replication with multiple buckets fails with sync gateway  accelerator 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#454]
### Steps to reproduce:  
        1. Create couple of buckets in CBS.
        2. Configure sync-gateway by mapping each sg db to each bucket in sync-gateway config and sg accel config 
        3. Start sync gateway and sg accel.
        4. Create docs in all 3 sg dbs.
        5. Start replication to cBL with multiple replicator instances
        6. Each replicator instance to each bucket DB
        7. Verify CBL got docs from all buckets to all CBL DBs.

### Result : 
CBL db 1, CBL db2 and CBL db3 did not get any docs replicated

### Expected : 
All 3 cbl dbs should get docs from all 3 sg dbs.

### logs: 
sg logs : https://gist.github.com/sridevi-15/bf4f82d988f361eecda48b8efc5fb83a
sg accel logs : https://gist.github.com/sridevi-15/c483fd7059f8111cbc566abcc17f6d6d
cbl logs : https://gist.github.com/sridevi-15/b258cf88e40bb0066325fb4d56041220

### sg config : 
"""
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket-1",
        "username":"data-bucket-1",
        "password": "password"
    },
    
    
    "databases":{
        "sg_db1":{
            "enable_shared_bucket_access": true,
            
            
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket-1",
            "username":"data-bucket-1",
            "password": "password",
            "channel_index":{
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket-1",
                "username":"index-bucket-1",
                "password": "password",
                "writer":false
            }
        },
        "sg_db2":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket-2",
            "username":"data-bucket-2",
            "password": "password",
            
            
            "channel_index":{
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket-2",
                "username":"index-bucket-2",
                "password": "password",
                "writer":false
            }
        },
        "sg_db3":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket-3",
            "username":"data-bucket-3",
            "password": "password",
            
            
            "channel_index":{
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket-3",
                "username":"index-bucket-3",
                "password": "password",
                "writer":false
            }
        }
    }
}

"""
### sg accel config : 
"""
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket-1",
        "username":"data-bucket-1",
        "password": "password"
    },
    
    
    "databases":{
        "sg_db1":{
            "enable_shared_bucket_access": true,
            
            
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket-1",
            "username":"data-bucket-1",
            "password": "password",
            "channel_index":{
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket-1",
                "username":"index-bucket-1",
                "password": "password",
                "writer":true
            }
        },
        "sg_db2":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket-2",
            "username":"data-bucket-2",
            "password": "password",
            
            
            "channel_index":{
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket-2",
                "username":"index-bucket-2",
                "password": "password",
                "writer":true
            }
        },
        "sg_db3":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket-3",
            "username":"data-bucket-3",
            "password": "password",
            
            
            "channel_index":{
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket-3",
                "username":"index-bucket-3",
                "password": "password",
                "writer":true
            }
        }
    }
}

"""

code :  https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L2399

command to run test : pytest -rsx -s -k test_replication_withMultipleBuckets --server-version=5.0.0 --sync-gateway-version=2.0.0-821 --mode=di --liteserv-host=localhost --liteserv-port=8080 --xattrs --liteserv-version=2.0.0-625 --liteserv-platform=ios --create-db-per-test=cbl-test --skip-provisioning testsuites/CBLTester/CBL_Functional_tests/

Note : This is happening only in DI mode, cc mode works fine

**Comment by snej** [comment]
If this only occurs with SG-Accel, it's likely to be an SG bug; have the SG team looked at it?

There are a bunch of warnings in the CBL log of the form `CouchbaseLite WS WARNING: {C4SocketImpl#5} Unexpected or unclean socket disconnect! (reason=errno, code=61)`, indicating that SG closed the socket unexpectedly ... that's often due to a panic in SG.

I don't see any panics in the SG log, but a bunch of `WARNING: Error initializing reader stable sequence:Unable to determine partition map for index - not found in index.`.

The SG log doesn't have any sync logging turned on, so all it shows is the initial HTTP request for `_blipsync`.

The times in the logs don't seem to match up. The CBL logs start at `2018-03-08 15:00:43.825603-0800`, which would be 3/8/18 23:00 GMT; but the SG logs start at `2018-03-07T11:44:40.965Z`, or 3/7/18 23:44 GMT ... a day earlier. Huh? Are these really matching logs, or does one of the machines have a misconfigured clock?

**Comment by snej** [comment]
FYI @adamcfraser @tleyden

**Comment by adamcfraser** [comment]
I agree - if it's accel-only it's much more likely to be an SG bug.  Will take a look later this evening.

**Comment by sridevi-15** [comment]
Yeah, I guessed it is sg related, but I did not see any errors from sg, so thought of filing as lite-core and then move to sg. Yes we do not have test on 1.x with multiple buckets.  @adamcfraser , if this is not supported, I can make this test to run only in cc mode. Let me know if I need to move this ticket to sg-accel issues.

**Comment by adamcfraser** [comment]
I don't actually see any problems in the accel or SG logs from the SG side.

In the SG logs, I can see that changes messages for all 10 docs are sent for sg2 and sg3, while sg1 only sends a few.  

In all cases, it looks like the websocket connection is terminated immediately after the changes are sent.  

@sridevi-15  Running SG with `*` logging might shed some light on whether any rev messages are being sent before the websocket connection is closed.

It might also help to get CBL logs that isolate a single test run - with the timestamp mismatch @snej mentioned, it's difficult to identify which test run corresponds to the SG logs.  It definitely looks like CBL thinks the replication completed, based on log entries matching the docid+sequences being sent by Sync Gateway, but I can't be sure those correspond to your latest test.
```
2018-03-08 16:45:50.675048-0800 CBLTestServer-iOS[99180:3693804] CouchbaseLite Sync Info: {Repl#334} Replication complete! Closing connection
```

**Comment by sridevi-15** [comment]
yeah, I cbl logs has previous test run logs too. I realized later that I did not clean up to put logs. I will run with * and put current test run cbl logs and add it here. sg logs and sg-accel should be current test

**Comment by sridevi-15** [comment]
sg-accel logs : https://gist.github.com/sridevi-15/10bc7dab2caefbf82c3eff4ab273c5e7
sg logs : https://gist.github.com/sridevi-15/c0b5b1fb7a8e11c053514df0353c02ba
cbl logs : https://gist.github.com/sridevi-15/0aca736a5198ff18ebdf3b73f5ea00ee

**Comment by snej** [comment]
>    4. Create docs in all 3 sg dbs.
>    5. Start replication to cBL with multiple replicator instances

From this it sounds like there is one CBL database that all the replications go to, but below it looks like there are multiple ones. Can you clarify?

From the logs I don't see any errors, or any messages about test assertion failures, so I have no idea what to investigate. What went wrong in the test? And what databases and documents are in error?

**Comment by borrrden** [comment]
This test passed once for .NET then failed after that several times.  My guess is that DI mode is delaying the time between SG write and available on SG changes feed enough that the replication finishes before SG is ready because it is still reporting "no changes".

Putting a 2 second delay (probably overkill) between the bulk docs write, and the replication start makes this test pass every time for me on .NET and iOS (I tried twice on each).

**Comment by adamcfraser** [comment]
Yes, there's the potential for additional latency vs. 'normal' SG when using DI, particularly in low volume tests like this.

Even in the Sync Gateway case, though, it sounds like the test code has a potential race.  There's never a guarantee that a one-shot replication issued after writes complete will return everything that's been written.  Any replication-based testing should account for this latency.  Our unit tests take a couple of different approaches - some use continuous replication and wait for n results, others perform multiple one-shot replications in a retry loop.  We've been trying to weed out tests that use a sleep - in most cases that leads to intermittent test failures when the tests are run on overloaded hardware, etc.

**Comment by borrrden** [comment]
Also the test could check all_docs in a loop until it finds the ones it wants and *then* start the replication being assured that all the writes have been recorded.

**Comment by adamcfraser** [comment]
@borrrden If you're talking about the SG _all_docs, it's not based on the same backing data as the _changes response, and doesn't guarantee that a one-shot replication will return the same results seen in _all_docs.  all_docs is generated by a view query, _changes is based on the server's mutation feed.

**Comment by sridevi-15** [comment]
Replacing one shot replication with continuous works . I did not add any delay to test and it works after running couple of times. Is one shot replication does not make sure that replication completed. In that case, I am forced to use continuous replication in all tests. If one shot is not reliable, is one shot replication feature required?

**Comment by borrrden** [comment]
One shot will make sure it "completes" but the definition of "completes" is the problem here.  It will stop once it finishes processing all the changes it received on the initial call to sync gateway.  If there are any more added after that (which probably happens here) then those will not be processed.

**Comment by sridevi-15** [comment]
Replication test written does not expect more updates, it expects whatever is updated before replication starts.

**Comment by sridevi-15** [comment]
Test is passing now with the change, I will close this ticket.

**Comment by borrrden** [comment]
What I meant was you are assuming that all the changes that are written are immediately available on the changes feed, which is not true.  I was assuming it too pretty much, but Adam pointed out otherwise.  Thus, even though you only write once, the replication starts so fast that at the time it starts there are only a few or no changes available so the replication quickly stops as "completed"

**Comment by sridevi-15** [comment]
got it @borrrden , in that case, I should add loop to verify expected docs got replicated. I added the loop along with continuous true
