### ISSUE TITLE
c4repl_parseURL, path component.

### ISSUE THREAD

**Issue by weis** [couchbase/couchbase-lite-core#465]
In couchbase-lite-core/Replicator/c4Replicator.cc,  c4repl_parseURL
line 95
When I change
`address->path = slice(pathStart, str.buf);` 
to
`address->path = slice(str.buf, str.size);` 
the path component seems correct.

**Comment by snej** [comment]
Hi, what's the problem you're reporting, i.e. what seems wrong with the path?

**Comment by weis** [comment]
Hi,
the code below results with path to "/", should this not  be "bern" ?
```
    C4String  remoteDbName = C4STR("bern");
    C4String  repUrl = C4STR("ws://192.168.1.30:9984/bern");
    C4Address request;

    if (!c4repl_parseURL(repUrl, &request, &remoteDbName))
    {
        return false;
    }
    std::string path((char*)request.path.buf, request.path.size); //  = "/"
```

**Comment by snej** [comment]
Oh, I see. The `path` field isn't very clearly named; it should be something like `pathPrefix`. It's the path components before the database name. Usually this is empty, but it's permissible for databases to be below the root level of a server's path namespace.
