### ISSUE TITLE
Change SQLite thread mode from “serialized” to “multi-thread"

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#469]
It turns out we don't currently configure SQLite's threading mode (`SQLITE_THREADSAFE`) so it's at the default value of "Serialized". In this mode a database connection can be used from multiple threads simultaneously, implying that there's a mutex wrapped around every API call. We don't need this because we already require that multiple threads don't access a database at once, so we can safely switch to "Multi-Thread" (`SQLITE_THREADSAFE=2`) and gain a slight amount of performance.

https://sqlite.org/threadsafe.html

**Comment by borrrden** [comment]
You say "require" but any mistake in that requirement means data corruption, as we painfully found out two summers ago...this change is scary for me.

**Comment by borrrden** [comment]
[CBL-124](https://issues.couchbase.com/browse/CBL-124)
