### ISSUE TITLE
iOS 9 crash in replicator: "Symbol not found: _deflatePending"

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#471]
In couchbase/couchbase-lite-ios#2097, @jayzhangs reports a crash on iOS 9 when the replicator starts:
```
dyld: lazy symbol binding failed: Symbol not found: _deflatePending
  Referenced from: /Users/jayzhang/Library/Developer/CoreSimulator/Devices/D3688125-182A-4CFB-A7CA-09F0C977CAB7/data/Containers/Bundle/Application/C7868412-87CF-418C-BB9C-D5B06452F4CE/companyNameHD.app/Frameworks/CouchbaseLiteSwift.framework/CouchbaseLiteSwift
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libz.1.dylib
```

**Comment by snej** [comment]
According to `<zlib.h>`, this symbol is available starting in iOS 8 and macOS 10, so it should be OK:
```c
ZEXTERN int ZEXPORT deflatePending OF((z_streamp strm,
                                       unsigned *pending,
                                       int *bits))
__OSX_AVAILABLE_STARTING(__MAC_10_10,__IPHONE_8_0);
```
However, I ran `nm` on the (simulator) libz.dylib, and that symbol doesn't show up, so apparently the header is wrong? :(

**Comment by snej** [comment]
@jayzhangs, have you tried this on an actual device with iOS 9, or just the simulator? This is an Apple bug and I'm filing a bug report, but it's possible that it's the simulator SDK that has the wrong version of zlib.

**Comment by snej** [comment]
Just confirmed the symbol _is_ in the iOS 10.3 simulator.

**Comment by jayzhanghs** [comment]
This cashes in iOS 9 device too, with a slight different trace:

https://gist.github.com/jayzhanghs/26c3f7a5bd5ef6413b68dae03e6f2615

By the way, did you test the fixes on device or simulator before merging?

**Comment by snej** [comment]
Embarrassingly, I'd forgotten until today that you can still download old iOS simulators :grimacing: The good news is that I have a workaround and I'm testing it now on iOS 9.3.

**Comment by snej** [comment]
No more crashes on iOS 9! The unit test suite has one failure, having to do with database copying, which I've filed as couchbase/couchbase-lite-ios#2105.

**Comment by jayzhanghs** [comment]
can't wait to test it out! but now pull submodule gives an error
```
git submodule update --init --recursive
error: Server does not allow request for unadvertised object e1fae5cc5ccb53f63cb1c5abcf75542cab80b82c
Fetched in submodule path 'vendor/couchbase-lite-core/vendor/BLIP-Cpp', but it did not contain e1fae5cc5ccb53f63cb1c5abcf75542cab80b82c. Direct fetching of that commit failed.
Failed to recurse into submodule path 'vendor/couchbase-lite-core'
```

**Comment by snej** [comment]
Sorry about that! I'm using a new Git client app and it doesn't automatically push submodules, so I forgot to do it manually.

Anyway, it turns out my fix didn't work -- the test for `&deflatePending == nullptr` is considered a no-op by the compiler because it "knows" the symbol exists, so it just treats the test as false.

I didn't detect this by running the Obj-C unit tests on iOS 9, because I hadn't configured the remote-host setting, and without that the test suite doesn't actually run any replications. 🤯 I'm going to replace that with an explicit OS version check.

**Comment by snej** [comment]
Oops, I put the wrong bug number in the commits so they didn't show up here. (Man, I am seriously spazzing today. Is this release cycle over yet??)

The actual fix is commit e1fae5cc5ccb53f63cb1c5abcf75542cab80b82c in BLIP-Cpp.
The CBL-iOS commit that brings in the fix is 80245a8921b295e148165b2b805cb4b8e3076eb8.

**Comment by jayzhanghs** [comment]
You nailed it! It no longer crashes on iOS 9!

**Comment by jayzhanghs** [comment]
When will the official DB023 release be out?

**Comment by djpongh** [comment]
It's in the "Pre-release" section on our downloads page.

**Comment by jayzhanghs** [comment]
@djpongh when was it built, before commit 80245a8921 or after?

**Comment by jayzhanghs** [comment]
nvm I found it out. It was before that commit.

**Comment by jayzhanghs** [comment]
Since this fix for iOS 9 crash came after DB23, will there be any DB24 release coming out pretty soon?

**Comment by snej** [comment]
The next release will be the final 2.0.

**Comment by jayzhanghs** [comment]
Any estimate of the release date?

**Comment by snej** [comment]
Just "ASAP".
