### ISSUE TITLE
Expose ability to control replicator compression level from CBLite

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-core#476]
It looks like there is no way to disable compression of BLIP/Websocket messages from CBLite -> Sync Gateway.

Currently it appears that disabling the `replicator_compression` setting on Sync Gateway only affects requests that *originate* from Sync Gateway -> CBLite, whereas requests that go the other direction and originate from CBLite -> Sync Gateway will use the CBLite replicator compression setting.

However, this setting can't be controlled via the API (eg, `ReplicatorConfig`), so it looks like there is no way to disable compression from CBLite -> Sync Gateway.

This would be useful to add for support / diagnosis reasons:

1. If a compression bug is suspected, being able to disable compression to isolate the bug would be very useful.  Given the higher-than-usual complexity of the compression approach, there is extra risk here.
1. The current version of the [blip wireshark dissector](https://github.com/couchbaselabs/blip-wireshark-dissector) cannot dissect compressed packets.

**Comment by tleyden** [comment]
This is controlled in `BLIPConnection.cc`, change: 

```
    static const auto kDefaultCompressionLevel = (Deflater::CompressionLevel)8; 

```

to

```
    static const auto kDefaultCompressionLevel = (Deflater::CompressionLevel)0; 

```

**Comment by borrrden** [comment]
Migrated to [CBL-125](https://issues.couchbase.com/browse/CBL-125)
