### ISSUE TITLE
Replicator stops while running with sg accel mode

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#481]
### Environment 
iOS : 738
Android : 450
sg : 823

### Steps to reproduce : 
1. Create docs in CBL.
2. Start replication with continuous true with push pull replication
3. Wait until replication is idle .
4. update docs in sync_gateway.
5. Wait until replication is idle.
6. Verify docs in cbl got replicated successfully with updates docs in sg

### Result :  I tried with 100 docs
92 docs replicated successfully and then replicator stopped.  I do not see any error on cbl logs

### Expected : All docs should replicated successfully.

Note : It worked fine with cc mode i.e just with sync-gateway
 As mentioned last time in one of the bugs which there is delay in replication with DI mode, I added logic to loop for sometime . have loop for 1 minute and still replication did not happened. I manually checked after 10 mins with cblite tool and did not replicated on cbl 

Verified that all docs updated successfull in sg, but only 92 docs got replicated from sg which has property 'updates=2" for the docs got replicated from sg and has property 'updates=0" for the docs which did not replicated from sg to cbl. 

### Test code : 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py#L52
test_replication_configuration_valid_values

Same test with continuous true passed with 10 docs and 1000 docs . Failure is not consistent

### command to run : 
pytest -rsx -s -k test_replication_configuration_valid_values[100-True] --xattrs --server-version=5.0.0 --sync-gateway-version=2.0.0-823 --mode=di --liteserv-port=8080 --liteserv-version=2.0.0-664 --create-db-per-test=cbl-test --liteserv-host=localhost --liteserv-platform=ios --skip-provisioning testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/

### Logs : 
cbl logs : https://gist.github.com/sridevi-15/7da1aba71d15130aa6e23f988b955275 
sg logs : https://gist.github.com/sridevi-15/564dafd4fbe6bbeccc9fca74a48b226d

**Comment by snej** [comment]
If this only happens with sg-accel, then it's more likely to be an SG bug.

**Comment by djpongh** [comment]
Filed as SGA issue 198
