### ISSUE TITLE
Filtered docs ids are not replicated to cbl from sg with sg-accel

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#484]
### Environment 
iOS : 738
Android : 450
sg : 823

### Steps to reproduce : 
1. Create docs in SG
        2. Create docs in CBL
        3. PushPull Replicate one shot from CBL -> with cbl doc ids as paramemter to replicate filtered doc ids
        4. Verify SG only has the doc ids set in the replication from CBL  -> This got replicated successfully 
        5. Add new docs to SG 
        6. PushPull Replicate one shot from SG -> with document ids to get filtered
        7. Verify docs got replicated in CBL with filter set of sg docs 
### Result :  
None of the sg docs got filtered into CBL As using with sg-accel has delay I added delay for sometime and it did not work. 

### Test code : 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py#L374
test_replication_configuration_with_filtered_doc_ids
### Note : 
It passed in CC mode.

### command to run : 
pytest -rsx -s -k test_replication_configuration_with_filtered_doc_ids --xattrs --server-version=5.0.0 --sync-gateway-version=2.0.0-823 --mode=di --liteserv-port=8080 --liteserv-version=2.0.0-664 --create-db-per-test=cbl-test --liteserv-host=localhost --liteserv-platform=ios --skip-provisioning testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/

### Logs : 
cbl logs : https://gist.github.com/sridevi-15/7e8e47ff411bbabaa46a3d3ea61c1dfe
sg logs : https://gist.github.com/sridevi-15/c26b25b7495d1c705609b16b2c3e0df4

**Comment by djpongh** [comment]
Moved to SGA #199
