### ISSUE TITLE
HTTP auth for P2P Listener

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#488]
P2P will need authentication, to ensure peers are trusted. We can do this with HTTP basic auth, since we should always be using SSL. Client certs would be a stretch goal.

**Comment by borrrden** [comment]
Unclear what the future of this is given the current state of P2P as "bring your own connection"

**Comment by borrrden** [comment]
With the advent of some new features, migrating this to [CBL-191](https://issues.couchbase.com/browse/CBL-191)
