### ISSUE TITLE
Replication progress complete and total could be out of sync

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#489]
I have seen this from testing with Todo.

```
2018-03-22 14:52:52.678100-0700 Todo[7959:2815036] [Todo] Replicator: Idle, 3956/6932
```

Client Log when issue happened: https://gist.github.com/pasin/82bbe51edc1f1f9b186f2bd521ec7708

It seems like it starts to happen when pull a blob.

CBL iOS : https://github.com/couchbase/couchbase-lite-ios/commit/4a4d82c5046dd7d1e73652093d13df29088860d0
Lite Core : CBL2.0.0-DB024

**Comment by snej** [comment]
There have been a number of fixes in this area since March ... does this still occur?

**Comment by borrrden** [comment]
I, for one, don't remember seeing it recently.

**Comment by borrrden** [comment]
Update:  Saw it twice today in test fest.

**Comment by snej** [comment]
What branch/rev was being tested?

**Comment by borrrden** [comment]
Migrated to [CBL-55](https://issues.couchbase.com/browse/CBL-55)
