### ISSUE TITLE
Consider including user in the checkpoint hash

### ISSUE THREAD

**Issue by JFlath** [couchbase/couchbase-lite-core#496]
This came up in discussion with @adamcfraser  and @bbrks the other week - raising this to keep track of the discussion.

Essentially, as we don't include the user in the checkpoint hash, it's possible for two users to reuse the same checkpoint. Couple of caveats:

* This supposes that two users are sharing the same local database. I know we've discussed this being not recommended in the past, but I don't believe this is unsupported (and I can potentially see use cases for it).
* This would only affect unfiltered replication - filters would alter the hash.

On the second point, the problem arises when the channels expand differently for the different users, e.g.:

* *U:James* has access to channel `foo` only. Replicates without a filter from `0` and pulls 1 document at `seq:1000`.
* *U:Jens* has access to channel `*`. Starts a replication and picks up `U:James`'s checkpoint at `seq:1000`. Misses out on up to 1000 revisions.

**Comment by snej** [comment]
By "user" you mean SG user account?

I think we've always said that you shouldn't pull into the same database with different accounts. It messes up permissions, like if user A has access to a specific doc but B doesn't -- as soon as A pulls, the doc will be visible in the database to use B as well. Worse, if a doc used to be visible to both but B's privileges were removed, then pulling as A will produce a different document body than pulling as B, since B will get a `"_removed":true` stub.

**Comment by JFlath** [comment]
> By "user" you mean SG user account?

>I think we've always said that you shouldn't pull into the same database with different accounts.

Yeah, I know it's been talked about, but I don't think we've ever made the hard recommendation, right? And we certainly don't enforce it. We've explicitly built a system where we can do this - otherwise it would have made sense to tie auth to the database level, not the replicator level?

**Comment by Fujio-Turner** [comment]
@JFlath ... Could having SG put in user and other info in xattr be a better method?

**Comment by JFlath** [comment]
@Fujio-Turner I think that's a solid idea, but orthogonal to this ticket. Having it human/N1QL readable would definitely be helpful in debugging, but here I'm concerned more with using it as part of the list of things we generate the hash with. Although it's not something we would generally expect to change for the same SRC->DST relationship, there's nothing to stop that happening. As "my" view of seq:1-1000 may be very different from "your" view of the same range, it's important not to share a checkpoint.

**Comment by borrrden** [comment]
Is there an action item here for us?

**Comment by borrrden** [comment]
Looks like the answer is no

**Comment by JFlath** [comment]
@borrrden sorry, seems to be a bit of miscommunication here - did we explicitly discount this as a feature/enhancement? Is there a conversation in another forum (e.g. JIRA)?

**Comment by borrrden** [comment]
Unclear what the actual thing proposed to do is and it seems that a lot of it is based on speculation around a behavior that we discourage and so given that and the fact that I commented a month ago with no response I was advised to close.

**Comment by JFlath** [comment]
Sorry, bit of confusion perhaps. From my perspective this still stands as a feature request - if you're unclear on the actions being asked for by the feature request, do let me know :)!

I raised above the point about this being a "discouraged behaviour" - I don't believe this has ever been the official advice...?

**Comment by borrrden** [comment]
Feature requests should go through PM and be on the CM project if I recall correctly. @djpongh thoughts?

**Comment by djpongh** [comment]
If you feel this should be added, please file a CM Jira ticket and assign to @rajagp

**Comment by JFlath** [comment]
Moved to [CM-228](https://issues.couchbase.com/browse/CM-228)
