### ISSUE TITLE
undefined reference to `ucol_strcollUTF8_55` when use LiteCore Static in Qt project on Linux

### ISSUE THREAD

**Issue by thamht4190** [couchbase/couchbase-lite-core#499]
Hi,
I'm using LiteCoreStatic library in my Qt project, `however,` there seems to be a link problem with icu. I have no problems if I don't use Qt.

Some of my system information:
Qt 5.10.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6)) on "xcb" 
OS: Ubuntu 16.04.4 LTS [linux version 4.13.0-37-generic]

Here the dump:
``
/usr/bin/g++-5 -Wl,-m,elf_x86_64,-rpath,/home/tham/Qt5.10.1/5.10.1/gcc_64/lib -L/home/tham/Qt5.10.1/5.10.1/gcc_64/lib -m64 -o /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/CouchBaseNativeSyncTest.e336d316/CouchBaseNativeSyncTest /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/CouchBaseNativeSyncTest.e336d316/3a52ce780950d4d9/CouchBaseNativeSyncTest.cpp.o /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/CouchBaseNativeSyncTest.e336d316/73489b871e127538/moc_CouchBaseNativeSyncTest.cpp.o /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/Emotiv.Common.CouchBaseNative.aa43059d/libEmotiv.Common.CouchBaseNative.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libLiteCoreStatic.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libsqlcipher.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libSQLite3_UnicodeSN.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libFleeceStatic.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libBLIPStatic.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libCivetWeb.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libSupport.a /home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libmbedcrypto.a /home/tham/Qt5.10.1/5.10.1/gcc_64/lib/libQt5Core.so.5.10.1 -lpthread -lz -lc++ -ldl -licuuc -licui18n -lz -lc++ -ldl -licuuc -licui18n /home/tham/Qt5.10.1/5.10.1/gcc_64/lib/libQt5Core.so.5.10.1 -lpthread /home/tham/Qt5.10.1/5.10.1/gcc_64/lib/libQt5Test.so.5.10.1 /home/tham/Qt5.10.1/5.10.1/gcc_64/lib/libQt5Core.so.5.10.1 -lpthread
/home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libLiteCoreStatic.a(UnicodeCollator_ICU.cc.o): In function `litecore::compareStringsUnicode(int, void const*, int, void const*, litecore::ICUCollationContext const&)':
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Storage/UnicodeCollator_ICU.cc:(.text+0x6ed): undefined reference to `ucol_strcollUTF8_55'
/home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libLiteCoreStatic.a(UnicodeCollator_ICU.cc.o): In function `litecore::ICUCollationContext::ICUCollationContext(litecore::Collation const&)':
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Storage/UnicodeCollator_ICU.cc:(.text._ZN8litecore19ICUCollationContextC2ERKNS_9CollationE[_ZN8litecore19ICUCollationContextC2ERKNS_9CollationE]+0x135): undefined reference to `ucol_open_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Storage/UnicodeCollator_ICU.cc:(.text._ZN8litecore19ICUCollationContextC2ERKNS_9CollationE[_ZN8litecore19ICUCollationContextC2ERKNS_9CollationE]+0x273): undefined reference to `ucol_setAttribute_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Storage/UnicodeCollator_ICU.cc:(.text._ZN8litecore19ICUCollationContextC2ERKNS_9CollationE[_ZN8litecore19ICUCollationContextC2ERKNS_9CollationE]+0x2a0): undefined reference to `ucol_setAttribute_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Storage/UnicodeCollator_ICU.cc:(.text._ZN8litecore19ICUCollationContextC2ERKNS_9CollationE[_ZN8litecore19ICUCollationContextC2ERKNS_9CollationE]+0x2d7): undefined reference to `ucol_setAttribute_55'
/home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libLiteCoreStatic.a(UnicodeCollator_ICU.cc.o): In function `litecore::ICUCollationContext::~ICUCollationContext()':
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Storage/UnicodeCollator_ICU.cc:(.text._ZN8litecore19ICUCollationContextD2Ev[_ZN8litecore19ICUCollationContextD2Ev]+0x36): undefined reference to `ucol_close_55'
/home/tham/workspace/sources/cortex-v2/build-cortex-ubuntu_16-Debug/qtc_ubuntu_16_Debug/ThirdParty.CouchbaseLiteCore.668d30ff/Libs/libLiteCoreStatic.a(StringUtil_icu.cc.o): In function `litecore::UTF8ChangeCase(fleece::slice, bool)':
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Support/StringUtil_icu.cc:(.text+0x3d): undefined reference to `ucasemap_open_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Support/StringUtil_icu.cc:(.text+0xb4): undefined reference to `ucasemap_utf8ToUpper_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Support/StringUtil_icu.cc:(.text+0xfa): undefined reference to `ucasemap_utf8ToLower_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Support/StringUtil_icu.cc:(.text+0x14e): undefined reference to `ucasemap_close_55'
/home/tham/workspace/sources/cortex-v2/src/ThirdParty/couchbase-lite-core/LiteCore/Support/StringUtil_icu.cc:(.text+0x1b5): undefined reference to `ucasemap_close_55'
``
Any help? Many thanks!

**Comment by borrrden** [comment]
Disclaimer:  This is not a supported configuration for LiteCore

That being said, it's likely that Qt is linking in its own version of ICU first that is different.  If the headers don't match the actual compiled library you will run into this issue.  Check the header search paths and library search paths and I bet you will find that Qt's version of ICU is interfering.

**Comment by thamht4190** [comment]
Thanks @borrrden.

**Comment by djpongh** [comment]
As @borrrden said, we don't support the use of LiteCore on its own.
