### ISSUE TITLE
Reimplement geo-queries

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#5]
Need to pull the SQLite-based implementation from CBL into LiteCore.

**Comment by Fujio-Turner** [comment]
@snej  .... will this be a R Tree implementation of sqlite: https://sqlite.org/rtree.html

**Comment by snej** [comment]
Yes.

**Comment by john-dalsgaard** [comment]
I would like to vote up this issue!!!

I had not even thought that a modern mobile database and SDK would _not_ support geo-spatial queries.... This is a showstopper for many apps - and I guess, even more future apps.....

**Comment by snej** [comment]
@john-dalsgaard We actually don't get many customer requests for geo-queries. (Which kind of surprises me, since it's obviously a useful feature for many types of mobile apps.)

And FWIW, the other major mobile dbs doesn't appear to support geospatial queries either. Realm has a still-open issue on Github for it, and Firebase appears not to have it directly, but there's an extension library called GeoFire that adds it, but the Github repo says "status: inactive" so I don't know if it's still supported...

**Comment by john-dalsgaard** [comment]
@snej Thanks for your comment.

I have been directed to try and use the "bounding box suggestion" by @rajagp - but I understand that solution correctly I find it difficult to solve these two queries:

1. Find all “locations” within x km from a specific point
2. Find the first x “locations” sorted in distance from a specific point

Any help is appreciated.

In the former framework for mobile dev. that I have worked with I used "SculeJS" as database on mobile - and it has geospatial searches to find e.g. the two different types of data that I need. The presence of geospatial searches in Couchbase was one of the first functionalities I checked - but alas I did not notice that it was only implemented server side :-(

/John

**Comment by snej** [comment]
(Hope you don't mind if I use SQL-ish syntax; it's the clearest way to write this stuff.)

The basic bounding-box test is `WHERE x BETWEEN $xmin AND $xmax AND y BETWEEN $ymin AND $ymax`. It works fine, the only problem is performance, because only one of those BETWEENs can be optimized with an index.

For distance from a point, you'd use `$pt_x - $radius` instead of `$xmin`, and equivalent for the other three parameters. That will limit you to the docs within a square around the point.

To get the distance you simply do `sqrt((x - $pt_x)*(x - $pt_x) + (y - $pt_y)*(y - $pt_y))`. You can add a test to check that it's `<= $r`, and then add a descending sort on it.

**Comment by borrrden** [comment]
Migrated to [CBL-113](https://issues.couchbase.com/browse/CBL-113)
