### ISSUE TITLE
Make BLIP Websocket FrameSize Configurable

### ISSUE THREAD

**Issue by mtrossbach** [couchbase/couchbase-lite-core#503]
Make the two parameters 

- **kDefaultFrameSize**
- **kBigFrameSize**

of the BLIP protocol configurable.

**Background:**
We have a deployment of Couchbase & Sync-Gateway on Microsoft Azure. As a gateway component (reverse proxy) we use the Azure Application Gateway. It seems that this gateway imposes a limit on the websocket frame sizes somewhere around 4096-8192 bytes. With the current configuration and a large websocket frame the gateway just stops forwarding this packet and also any subsequent packets. Then the connection times out.

After a long research I changed both constants in the BLIPConnection.cc to 4096 bytes and then replication is working fine.

The Azure Application Gateway has no configuration option to change this limit (in contrast to a real IIS installation). So it would be very nice if we could configure this parameters on the couchbase side. This would also apply for the Sync Gateway for the packets sent from there.

**Comment by snej** [comment]
That's strange. The WebSocket protocol doesn't impose any limits on message sizes, and it would seem pretty common to transmit messages larger than 4KB. Also, most gateways wouldn't be inspecting WebSocket message contents, they'd just route TCP traffic once they saw the HTTP upgrade to WebSocket protocol.

My suspicion is there's something else going wrong that's causing the problem. Do you have any more data on the problem, like WireShark traces or gateway error logs?

**Comment by tleyden** [comment]
@mtrossbach I think it might also be worthwhile to file a ticket with the Azure support folks and ask them if they have an undocumented limitation on the websocket frame size.

Also if you're willing to roll up your sleeves a little, we have a wireshark dissector for blip under development here: 

https://github.com/couchbaselabs/blip-wireshark-dissector

**Comment by mtrossbach** [comment]
I filed a ticket with the Azure support but I am still waiting for their response. I hope I have the time to try the wireshark dissector in the next days.

**Comment by djpongh** [comment]
@mtrossbach, did you get any more info on this?

**Comment by djpongh** [comment]
@mtrossbach , if you get any more info on this, feel free to re-open.
