### ISSUE TITLE
Update to C++17?

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#508]
Should we change the C++ language version from C++11 to C++17? It appears both [Clang 5](http://clang.llvm.org/cxx_status.html) and [MSVC 15.5](https://blogs.msdn.microsoft.com/vcblog/2017/12/19/c17-progress-in-vs-2017-15-5-and-15-6/) have good support for it. This would allow us to use a bunch of [new language and STL features](https://github.com/AnthonyCalandra/modern-cpp-features). Having [variable declarations inside an `if` or `switch` statement](https://github.com/AnthonyCalandra/modern-cpp-features#selection-statements-with-initializer), and [`std::variant` and `std::optional`](https://github.com/AnthonyCalandra/modern-cpp-features#stdvariant) would appease a lot of my Swift envy ;-)

(I originally wrote this about C++14, but after looking at the C++17 feature set and compiler support, I think we should go all the way.)

**Comment by borrrden** [comment]
We don't currently use MSVC 15, but MSVC 14.  I have been waiting for a chance to move to C++17 because of the filesystem namespace alone.  So much helper code would disappear.  

On the contrary, how would this affect people who want to deploy to embedded systems, etc?  Does LiteCore need to be able to be installed on those kinds of systems?

**Comment by gwaldvogel** [comment]
I feel like higher backwards compatibility (as long as it really does make sense) is better than losing some helper code.

Just to give you an example: Qt is still not compatible with the latest Android NDK/clang. This means if you want to use both Qt and LiteCore for your Android app you have to either make Qt compatible with clang or LiteCore compatible with GCC4.9 (which currently is just replacing some C++11 functionality that was still missing in the NDK GCC4.9). If you add the new functionality from C++17 on top of that this task would take way too much time and most likely force me to switch to a different embeddable database.

**Comment by snej** [comment]
@gwaldvogel -- that seems more a point about GCC support than about C++17. And in any case, you don't have to compile LiteCore and the rest of your app with the same compiler. LiteCore's API is C so it's ABI-compatible with other compilers.

**Comment by borrrden** [comment]
Migrated to [CBL-57](https://issues.couchbase.com/browse/CBL-57)
