### ISSUE TITLE
[Performance] Pull replication is slower in CBL 2.0

### ISSUE THREAD

**Issue by agyryk** [couchbase/couchbase-lite-core#509]
I have few basic tests comparing replication throughput of CBL 1.4 and CBL 2.0.
It was tested using single CBL instance (iPhone simulator) and 1 Sync Gateway node.
The test workflow is straightforward: start CBL, load docs, trigger replication, measure time it took to replicate all documents, calculate average docs/sec.

As expected, PUSH replication works better in CBL 2.0 especially when network latency is high. But PULL replication is slower.
Details:
[https://hub.internal.couchbase.com/confluence/display/~oleksandr.gyryk/CBL+Replication](https://hub.internal.couchbase.com/confluence/display/~oleksandr.gyryk/CBL+Replication)

I don't have any monitoring on CBL side yet so its hard to tell what is the root cause.
But I do have some Sync Gateway stats from that runs:
CBL 1.4, Pull, hi-lat network: [http://cbmonitor.sc.couchbase.com/reports/html/?snapshot=hebe_000-000_run_test_6f9a](http://cbmonitor.sc.couchbase.com/reports/html/?snapshot=hebe_000-000_run_test_6f9a)
CBL 2.0, Pull, hi-lat network:  [http://cbmonitor.sc.couchbase.com/reports/html/?snapshot=hebe_000-000_run_test_8ae2](http://cbmonitor.sc.couchbase.com/reports/html/?snapshot=hebe_000-000_run_test_8ae2)

**Comment by snej** [comment]
Could you re-run the tests with the current CBL 2.1 build? I added some significant optimizations to replication right after the 2.0 code freeze.
