### ISSUE TITLE
Query returns wrong results if docs are updated before it finishes

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#51]
If a client runs a query and updates documents during the query iteration, the query will start returning incorrect results. For example, consider a loop that runs an all-docs query and updates every document as it's returned by the query. The actual behavior is that the iterator keeps returning the first document over and over forever. :(

This is actually documented in ["Isolation In SQLite"](https://www.sqlite.org/isolation.html), in the section "No Isolation Between Operations On The Same Database Connection".

> What if a SELECT statement is started and the sqlite3_step() interface steps through roughly half of its output, then some UPDATE statements are run by the application that modify the table that the SELECT statement is reading, then more calls to sqlite3_step() are made to finish out the SELECT statement? Will the later steps of the SELECT statement see the changes made by the UPDATE or not? The answer is that this behavior is undefined.

also:

> …the application can UPDATE the current row or any prior row, though doing so might cause that row to reappear in a subsequent sqlite3_step().

This is a bummer. I need to rethink the way queries work. The two options seem to be

* Run the entire query when it starts and save all the results into memory, then have the query iterator just return the results out of the in-memory list. (Obviously has memory overhead and latency. This is actually how the SQLite storage in CBL 1.x worked, though.)
* Create another SQLite database connection for the query, so that it will be unaffected by changes being made in the transaction in the main connection. (The problem is I'm not sure if two connections will suffice, or if I might have to keep creating an indefinite number of connections if multiple queries are active at the same time.)

I've sent an email to the SQLite mailing list asking for advice.

**Comment by snej** [comment]
Here's the CBL 2 test code that exposed the bug:
```objc
    BOOL ok = [self.db inBatch: NULL do: ^BOOL {
        CBLQuery* allDocs = [self.db createQuery: nil error: NULL];
        for (CBLQueryRow* row in [allDocs run: NULL]) {
            CBLDocument* doc = row.document;
            NSInteger playCount = [doc integerForKey: @"playCount"];
            [doc setInteger: playCount + 1 forKey: @"playCount"];
            [doc save: NULL];
        }
        return YES;
    }];
```
The expected behavior is of course to increment the `playCount` property of every document.
The actual behavior is that the loop keeps updating the first document over and over forever.

**Comment by borrrden** [comment]
In Java and .NET currently the model is maintaining a pool of connections per database object.  One is dedicated to writing and the others (currently three for .NET and I think the same for Java) are readonly.  Whenever an operation happens the calling thread must secure one of the connections from the pool before it can continue, and it will have dedicated access to that connection until it relinquishes it.  

If we scale this back to be per thread then two connections should be enough for this (I don't think there will be any intra-thread contention for queries).  This was the previous behavior across all threads on .NET.

**Comment by snej** [comment]
I've thought about using an approach like that. It's more efficient than connection-per-thread if there are a lot of threads, especially if the read-only connections all use a shared cache.

What I'm unsure of in this case is how to do a query during a transaction if there have already been changes made:

1. Begin a transaction
2. Change some documents
3. Start a query

The query can't use any of the read-only connections because those don't see the uncommitted changes, so the results will be out of date. The only connection that can see the changes is the writer. But if the query runs on the writer connection, then we're in the exact situation described in this issue: any subsequent changes during iteration will screw up the SQLite iterator.

**Comment by borrrden** [comment]
The results will be out of date, but if those changes are not committed yet then is it a problem?  Those changes are either isolated or not isolated.  What if they were rolled back by aborting the transaction?  Then you would have had a query that had results that "never should have been there."  Since we don't expose any manual transaction API I don't expect any single transaction to be long lived anyway.  I really think the point of the batch operations is to do things as one unit, and not see any state in between so it would jump directly from result A to result B which has 10 changes (for example).

**Comment by snej** [comment]
A possible solution:

* Use a connection pool as described above
* If a query is run outside of a transaction, use one of the read-only connections, with the current mechanism where `c4queryenum_next` calls `sqlite3_step`.
* But if the query is run during a transaction, run it on the writer connection … but collect all the results in memory when the query starts, and have `c4queryenum_next` just pop them out of the result queue.

As a short-term fix for DP1, I can implement the second mode and always use it for all queries. Then later I can implement the connection pool.

**Comment by snej** [comment]
An optimization for the above would be to let query enumerators run in step-by-step mode, even during a transaction, but any time the database is about to be changed we first notify all the active enumerators on the connection, which will fast-forward and collect their remaining rows into memory (before the change is made.)

**Comment by snej** [comment]
I bet I can do the in-memory batching really easily using a Fleece encoder. Just begin an array, and then write every row as a nested array of the SQLite column values. Then at the end, close the outer array and the encoder. Then the enumerator can read the rows with an array iterator.

(I already have the columns-to-Fleece code in there as part of the 'projection' i.e. custom-columns API.)

**Comment by pasin** [comment]
FYI: The current Android SQLite connection pool is similar to the possible solution above.

**Comment by snej** [comment]
@pasin Yup, Jim and I are discussing it in HipChat right now :)
