### ISSUE TITLE
Cookie test failures on 32-bit Linux due to year 2038 bug

### ISSUE THREAD

**Issue by SJLC** [couchbase/couchbase-lite-core#510]
The cookie implementation uses mktime(), the 32-bit version of which can't cope with the far-future date of 2099 that the test code uses. This causes a few assertions to fail when running on 32-bit platforms, for instance

```
Cookie Parser
  Expires
-----------------------------------------------------------------------------------------------------------------------
/var/data/rlc/poky/build-nanoscope/tmp/work/cortexa9hf-neon-oe-linux-gnueabi/couchbase-lite-core/2.0-r0/git/Replicator/tests/CookieStoreTest.cc:21
.......................................................................................................................

/var/data/rlc/poky/build-nanoscope/tmp/work/cortexa9hf-neon-oe-linux-gnueabi/couchbase-lite-core/2.0-r0/git/Replicator/tests/CookieStoreTest.cc:90: FAILED:
  CHECK( c.expires == 4084683494 )
with expansion:
  -1 == 4084683494 (0xf37752e6)

```

**Comment by borrrden** [comment]
I'm inclined to just simply compile this out of 32-bit Linux.  There isn't a good way out of this without compiling lots more helper stuff and by 2038 I'm betting 32-bit is out of fashion anyway (or at least mktime64 will finally become widely available).  Here is the story with other platforms:

Windows - 32-bit uses 64-bit time_t
Mac - No more 32-bit systems being made
iOS - 32-bit support phasing out

**Comment by SJLC** [comment]
Alternatively it could just use 2037 as the future date, unless testing 64-bit dates is part of the point of the unit test goal... I did that locally to see that the cookies otherwise work fine on the arm32 target, could submit that as a patch if you are ok with it

**Comment by borrrden** [comment]
That sounds way simpler than what I thought to do, so I like it!  I'll run it by the person who wrote the test when he returns (he is out of the office for the next few weeks)

**Comment by SJLC** [comment]
ok, standing by

**Comment by borrrden** [comment]
@snej Is the above acceptable?

**Comment by snej** [comment]
>I'm betting 32-bit is out of fashion anyway

Not a good bet for embedded systems. Heck, 8-bit CPUs are still popular there today, including variants of the Zilog Z80 (which has been around for over 40 years! I used it in high school.)

**Comment by snej** [comment]
> it could just use 2037 as the future date

Sounds good to me. But it would be nice if our code handled overflows nicely, so that if we get a cookie with an expiration date of 2099 we pin that to the maximum representable date.

**Comment by borrrden** [comment]
That could work too.  There are two ways I can think of doing this.  

The simple way:
If we end up with -1 from `mktime`, then just use the hardcoded max value

The more complex way:
Check the size of time_t on Linux and if it is 32-bit and the tm struct has a higher value than can be handled, use the max value.
