### ISSUE TITLE
"unknown error domain" are reported by c4db_beginTransaction() and c4db_endTransaction()

### ISSUE THREAD

**Issue by thamht4190** [couchbase/couchbase-lite-core#511]
This is my code:
```
    C4Error err;
    c4db_beginTransaction(db, &err);
    if (err.code == 0) {
        std::cout << "c4db_beginTransaction: success";
    }
    else {
        C4StringResult msg = c4error_getMessage(err);
        std::cout << "c4db_beginTransaction: " << TO_STRING(msg);
        c4slice_free(msg);
    }
    if (c4db_isInTransaction(db)) {
        std::cout << "c4db_isInTransaction: true";
    }
    else {
        std::cout << "c4db_isInTransaction: false";
    }
```
Running it, I'll get the log:
```
c4db_beginTransaction:  "unknown error domain"
c4db_isInTransaction: true
```
I wonder why c4db_beginTransaction returns not 0 error code while the db is still in transaction. It happens the same with c4db_endTransaction: c4db_endTransaction return not 0 error code while db is not in transaction anymore. These things didn't always happen, so I think I must have done something wrong.

Any suggestions for me?

**Comment by borrrden** [comment]
The error code is not guaranteed to be zero on success. That is what the book return value is for. Be sure to check it.

**Comment by thamht4190** [comment]
Ok. Thanks @borrrden
