### ISSUE TITLE
no viable conversion from 'FLSlice' to 'C4Slice'

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#513]
I'm in the process of writing a C++ wrapper for LiteCore.

Rather than using another JSON implementation, I'm using a Fleece `Value` as a member of my Document class, with a `getValue` method to return it. 

I'm trying to get the C4Slice in order to pass it to `c4doc_update`/`c4doc_create`

```
#include "c4.h"
#include "c4Document+Fleece.h"

        //...

        C4Document* outDoc;
        auto* c4Doc = document.getC4Document();
        C4Slice dataSlice = document.getValue().asData();
        if (c4Doc) {
            outDoc = c4doc_update(c4Doc, dataSlice, revFlags, &err);
        } else {
            outDoc = c4doc_create(c4db, stdstringToSlice (document.id), dataSlice, revFlags, &err);
        }
```

However this results in an error: "no viable conversion from 'FLSlice' to 'C4Slice'". I'm including "c4Document+Fleece.h" which should typedef C4Slice to FLSlice. 
I'm wondering if there is a different order of includes that I should be using? 

Also, some feedback on whether I'm going about this in a good way would be useful too :)

**Comment by borrrden** [comment]
One thing to note...the C API is already a wrapper around C++ so you are effectively going C++ -> C -> C++ which could drive you crazy in the end.  Perhaps you could consider using the C++ classes directly (if you do that, you would be able to use the [fleece::slice](https://github.com/couchbaselabs/fleece/blob/master/Fleece/slice.hh) class directly)

**Comment by adamski** [comment]
Yes its already starting to drive me a bit crazy!! The reason I'm doing that is from a recommendation by @snej see https://github.com/couchbase/couchbase-lite-core/issues/80 

If its now advisable to use the C++ classes directly that would be preferable.

**Comment by borrrden** [comment]
I think it's more of a "buyer beware" kind of warning (we will change it without warning, etc).  We are less likely to change the C API (because it has broader implications to our other platforms) although it can still change without warning.  @snej Will be the authority here so you should listen to his advice over mine.  He will also know better than I do about order of includes, etc.

**Comment by thamht4190** [comment]
I've been writing C++ wrapper for LiteCore as well. Although I didn't use fleece as member of Document wrapper, I would like to update if there is a best practice for usage of LiteCore.

**Comment by adamski** [comment]
@thamht4190 do you have anything you're willing to share? Might be good to collaborate. You can find my email on my profile here.
