### ISSUE TITLE
Continuous push replication is not firing when adding a new document

### ISSUE THREAD

**Issue by stcleezy** [couchbase/couchbase-lite-core#515]
The replicator starts fine, and continuous pull replication occurs without issue:

```
15:45:51.656427| [DB]: Opening database /tmp/sandbox.cblite2/db.sqlite3
15:45:51.659759| [Actor]: Starting Scheduler<0x959f08> with 4 threads
15:45:51.661207| [Sync]: {Repl#1}==> litecore::repl::Replicator /tmp/sandbox.cblite2/ ->blip:10.101.43.88:4984/sandbox/_blipsync
15:45:51.661991| [Sync]: {Repl#1} Push=continuous, Pull=continuous, Options={"WS-Protocols":"BLIP_3+CBMobile_2"}
```

However, when I add a new local document via a posting to the REST server, nothing happens w/ replication. The document **is** created locally, it just doesn't push to the server.

If I restart the replicator, the change is detected and the document is pushed:
```
15:45:51.667902| [Sync]: {Repl#1} Local checkpoint 'cp-07v+pS0w820V2qUrKnfXE6ABGjg=' is [0, '30']; getting remote ...
15:45:51.719547| [Sync]: {Repl#1} Received remote checkpoint: [0, '30'] rev='0-3'
15:45:51.719743| [Sync]: {Push#2}==> litecore::repl::Pusher ->blip:10.101.43.88:4984/sandbox/_blipsync
15:45:51.719867| [Sync]: {Push#2} Starting continuous push from local seq #1
15:45:51.721784| [Sync]: {Push#2} Read 1 local changes up to #19: sending 'proposeChanges' with sequences #19 - #19
15:45:51.722010| [Sync]: {Push#2} Caught up, at lastSequence #19
```

Why isn't this happening continuously?

**Comment by snej** [comment]
Is the document added by the same process that's running the replicator?

**Comment by stcleezy** [comment]
No, as mentioned above this is added via the rest API, cblite serv running as a different process.

**Comment by snej** [comment]
That explains the behavior, then. Changes made by one process will not trigger any notifications in another process, so the replicator won't wake up and push the new docs.

We've talked about adding this functionality, but interprocess notifications are very platform-specific, and the alternative is polling the filesystem, which is wasteful.
