### ISSUE TITLE
Stable and supported C/C++ API

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#516]
From the current README:

> **The C API is considered unstable** and may change without notice, since it's considered an internal API of Couchbase Lite. In the future we want to provide a stable and supported C/C++ API, but not yet. 

Myself and others are working on C++ wrappers for LiteCore. Is there a timeline of when Couchbase might provide this, or is it still unknown?

**Comment by djpongh** [comment]
Please use GitHub for bugs. Questions such as this should be asked in our forums.

That being said, we currently have no plans for supporting a C/C++ API to LiteCore. But the more interest we receive, the more likely it will happen.
