### ISSUE TITLE
Issue with the kRevKeepBody flag

### ISSUE THREAD

**Issue by Oliver011986** [couchbase/couchbase-lite-core#519]
Hi, I have an issue with the kRevKeepBody flag. I am using the couchbase-lite-core library in version 2.0 with c++.
It seems that the kRevKeepBody flag isn’t set to the revision. My tests are equivalent to the test in https://github.com/couchbase/couchbase-lite-core/blob/master/C/tests/c4DocumentTest.cc#L188
My put requests are equivalent to the put requests used in the createRev function in https://github.com/couchbase/couchbase-lite-core/blob/master/C/tests/c4Test.cc#L335.
Every revision get the kRevKeepBody flag. At least I can find all the generated revisions in the document but only the actual one has a body. If I select an older revision (c4doc_selectRevision) or the parent revision of the actual (c4doc_selectParentRevision) the body is empty. Also selectedRev.flags is empty. Seems like the revision didn’t receive the flag.
Maybe I’m doing something wrong… I would be very grateful for any hints.

**Comment by borrrden** [comment]
I suppose there must be some small difference because the test checks that the flags *are* set.  It would be more helpful to share the code you are using (rather than saying "equivalent")

**Comment by Oliver011986** [comment]
Here are the code snippets I tested with.
The put request:
…
C4Error error;
c4db_beginTransaction(connInternal->database, &error);
C4SliceResult body = c4db_encodeJSON(connInternal->database, c4str(json), &error);
C4Document* curDoc = connInternal->GetDocument(document);
if (curDoc == nullptr)
{
curDoc = c4doc_create(connInternal->database, c4str(document), (C4Slice)body, kRevKeepBody, &error);
}
C4Slice history[2] = { c4str("2-c001d00d"), curDoc->revID};
C4DocPutRequest rq = {};
rq.existingRevision = true;
rq.allowConflict = true;
rq.docID = c4str(document);
rq.history = history;
rq.historyCount = 1 + (curDoc->revID.buf != nullptr);
rq.revFlags = kRevKeepBody;
rq.maxRevTreeDepth = 1000;
rq.body = (C4Slice)body;
rq.save = true;
C4Document* doc = c4doc_put(connInternal->database, &rq, nullptr, &error);
…
I have the first revision from the initial c4doc_create. Then I create a second one with revision-id 2-c001d00d and a third one with 3-c001d00d.
Then I try to get the body from the second revision.
The get request:
…
C4Error error;
c4db_beginTransaction(connInternal->database, &error);
C4Document* doc = connInternal->GetDocument(document);
if (doc != nullptr)
{
	c4doc_selectParentRevision(doc);
	bool test1 = c4doc_hasRevisionBody(doc);
	bool test2 = c4doc_loadRevisionBody(doc, &error);
	C4StringResult json = c4doc_bodyAsJSON(doc, false, &error);
	retJSON = std::string((char*)json.buf, json.size);
	retRevision = std::string((char*)doc->revID.buf, doc->revID.size);
selRevision = std::string((char*)doc->selectedRev.revID.buf, doc->selectedRev.revID.size);
	c4slice_free(json);
	c4doc_free(doc);
…
I select the actual revision (3-c001d00d) and with c4doc_selectParentRevision I get the 2-c001d00d revision. But c4doc_hasRevisionBody and c4doc_loadRevisionBody are booth false. The selectedRev is 2-c001d00d so at least the revision exists. Also selectedRev.flags is empty.

**Comment by borrrden** [comment]
Hmmm well it's been a while since I worked with that API.  It was phased out for use with Couchbase Lite and ironically now only exists in tests.  Instead, Couchbase Lite uses the `c4doc_update` method if a document already exists to update it.  As a bonus, it is much simpler to use than the one you are trying to use.  I would suggest trying that.

**Comment by Oliver011986** [comment]
Yes I know the c4doc_update function and I used it before without success. I have tested again with the following code:
C4Error error;
c4db_beginTransaction(connInternal->database, &error);
C4SliceResult body = c4db_encodeJSON(connInternal->database, c4str(json), &error);
C4Document* curDoc = connInternal->GetDocument(document);
if (curDoc == nullptr)
{
curDoc = c4doc_create(connInternal->database, c4str(document), (C4Slice)body, kRevKeepBody, &error);
}
else
{
	C4Document* docNew = c4doc_update(curDoc, (C4Slice)body, kRevKeepBody, &error);
	c4doc_free(docNew);
}
c4doc_free(curDoc);
c4slice_free(body);
c4db_endTransaction(connInternal->database, true, &error);
In the test code I just use the c4doc_create function when the document don’t exist and the the c4doc_update function if the document exist. I use the test code from my last post for getting the body from an older revision. The result is the same. I find the old revisions with no body and no flag set. Only the latest revision has it’s body.

**Comment by borrrden** [comment]
For sanity sake, the tests you mimic all pass on your setup right?

**Comment by Oliver011986** [comment]
Yes they all pass right.

**Comment by borrrden** [comment]
No errors are getting reported either?  I'm running out of ideas since the tests are fine but this is not.

**Comment by snej** [comment]
`kRevKeepBody` might not work anymore — there were some major changes to revision management (for conflict handling) late in the 2.0 release cycle, so I might have added code in the `RevTree` or `TreeDocument` classes that forces different behavior. Not the cleanest thing to do, but that's what can happen in the rush to finish a release. It's been several months now so I don't recall the details.

**Comment by djpongh** [comment]
Keeping  open to remind us to REMOVE this code.

**Comment by borrrden** [comment]
What code is supposed to be removed here?  I don't think we can just remove this flag (at the very least it needs to be refactored since it is still being used by the inserter)

**Comment by borrrden** [comment]
Migrated to [CBL-58](https://issues.couchbase.com/browse/CBL-58)
