### ISSUE TITLE
Litecore does not retry subChanges request that fails with temporary 503 error

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-core#525]
As part of https://github.com/couchbase/sync_gateway/issues/3595, I'm trying to run the Litecore replication tests against Sync Gateway that's configured to return 503 errors on every nth request.  

To give a broader picture, the motivation behind https://github.com/couchbase/sync_gateway/issues/3595 is to enable changes such as https://github.com/couchbase/sync_gateway/issues/3509, which will propagate more temporary errors from Couchbase Server back to CBLite, rather than retrying them internally in Sync Gateway.  

This change would put more of the onus for retrying onto Couchbase Lite.  Before making this the default behavior in Sync Gateway, I wanted to verify the CBLite retry behavior.

## Actual behavior

In an initial test, I'm seeing a case where CBLite sends a `subChanges` request to SG in frame 193:

```
BLIP Couchbase Mobile
    BLIP Message Number: 2
    BLIP Frame Flags: 0
    BLIP Properties Length: 45
    BLIP Properties: Profile:subChanges:batch:500:activeOnly:true
    BLIP Message Body: 
``` 

and SG responds in frame 197 with:

```
BLIP Couchbase Mobile
    BLIP Message Number: 2
    BLIP Frame Flags: 2
    BLIP Properties Length: 33
    BLIP Properties: Error-Domain:HTTP:Error-Code:503
    BLIP Message Body: Database server is over capacity (gocb.ErrTmpFail)
```

which causes CBLite to close the connection in frame 201:

```
WebSocket
    1... .... = Fin: True
    ...
```

## Expected behavior

When encountering 503 errors, CBLite would do a backoff / retry of the `subChanges` request until it succeeded or failed with a non-temporary error.  

Does this expectation match up w/ the [replication spec](https://github.com/couchbase/couchbase-lite-core/blob/master/modules/docs/pages/replication-protocol.adoc#subchanges)?  I'm not seeing temp errors addressed here, so maybe the first step should be to nail down exactly what the expected behavior is.

## Steps to repro

- Litecore commit 3657e009a12c1dbfad5f9571b7042df175c3fe56 (WARNING: old version, from March 21, 2018)
- Build Sync Gateway from source on the `feature/issue_3595_random_temp_blip_errors` SG branch
- Start SG with [this SG config](https://gist.github.com/0ef8eb9d4c3db5170e54d500ebe9536e)
- Run `./vendor/couchbase-lite-core/build_cmake/macos/C/tests/C4Tests -r list '[.SyncServer]'` 

## Pcap file 

[pcap.pcap.zip](https://github.com/couchbase/couchbase-lite-core/files/2055665/pcap.pcap.zip)

## Logs

- C4tests: https://gist.github.com/tleyden/0c47ab6830bc86f61ab6f1e447b2f55d#file-c4tests_logs-txt
- SG: https://gist.github.com/tleyden/0c47ab6830bc86f61ab6f1e447b2f55d#file-sg_logs-txt

**Comment by tleyden** [comment]
I tried to upgrade from litecore https://github.com/couchbase/couchbase-lite-core/commit/3657e009a12c1dbfad5f9571b7042df175c3fe56 -> a2319234a9aeab9d7ca3d71db7d54732a8685273 (May 18, 2018 at 8:03:25 PM PDT), to reproduce with a more recent version of CBLite / Litecore.  

However, now it's failing with different errors, and it doesn't even manage to do the BLIP websocket upgrade.  (even when disabling the temporary 503 artificially injected errors)

- Pcap: 
[issue_525_no_503.pcap.zip](https://github.com/couchbase/couchbase-lite-core/files/2055768/issue_525_no_503.pcap.zip)
- SG logs: https://gist.github.com/tleyden/7b071c44abcdf02d4e8e50609771a3cf#file-sg_logs-txt
- C4tests logs: https://gist.github.com/tleyden/7b071c44abcdf02d4e8e50609771a3cf#file-c4tests_logs-txt

**Comment by tleyden** [comment]
> it doesn't even manage to do the BLIP websocket upgrade.

I think this is happening because the tests aren't adding `_blipsync` to the DB URL, due to this check:

https://github.com/couchbase/couchbase-lite-core/blob/058d1218aaa52c9f2ab438c986d468d8b8da4f2e/Replicator/c4Replicator.hh#L78-L80

```
        if (slice(address.scheme) == "ws"_sl || slice(address.scheme) == "wss"_sl) {
            newPath += "/_blipsync";
        }
```

not triggering due to:

https://github.com/couchbase/couchbase-lite-core/blob/058d1218aaa52c9f2ab438c986d468d8b8da4f2e/C/include/c4Replicator.h#L31-L32

```
#define kC4Replicator2Scheme    C4STR("blip")
#define kC4Replicator2TLSScheme C4STR("blips")
```

Looks like the check for `ws` / `wss` was introduced in https://github.com/couchbase/couchbase-lite-core/commit/5ec8cd8a66caf9c48d0650d72085787ed250e46c

For the purposes of this testing, I'll switch over from `master` to `release/2.0.x `, since it looks like it doesn't have that commit.

**Comment by tleyden** [comment]
After applying the patch from PR https://github.com/couchbase/couchbase-lite-core/pull/526 to https://github.com/couchbase/couchbase-lite-core/commit/a2319234a9aeab9d7ca3d71db7d54732a8685273 (master), I'm seeing the same issue originally reported on this issue where CBLite closes the connection after getting a 503 in response to the `subChanges` request.

So it goes back to the question -- should CBLite be retrying when receiving a 503 error to a `subChanges` request?

**Comment by borrrden** [comment]
I'm getting confused because you are referring to "CBLite" but running "C4Tests".  Couchbase Lite should be retrying, but that is because retry logic is implemented in Couchbase Lite, not LiteCore.

**Comment by borrrden** [comment]
I know of some for .NET, but I am not sure they will be useful for you.  They are for the P2P functionality and use a mock connection that can simulate errors.

**Comment by tleyden** [comment]
I'll close this for now and re-open a new ticket if I see any issues with the CBLite retry logic.

**Comment by pasin** [comment]
The behavior that I have seen when investigating https://github.com/couchbase/couchbase-lite-ios/issues/2160 is that the LC replicator doesn't stopped and notify the error back to CBL so the retry logic doesn't get triggered. Basically LC replicator should stop and return the error when getting at least 503 error.

**Comment by pasin** [comment]
Note: To reproduce the issue the [SG config](https://gist.github.com/0ef8eb9d4c3db5170e54d500ebe9536e) that @tleyden posted needs changes as follows:

```
inject_nth_bucket_op_artificial_errors  to bucket_503_injected_error_frequency
```

**Comment by borrrden** [comment]
The puller class seems to already be attempting to do this [here](https://github.com/couchbase/couchbase-lite-core/blob/a71229a247c5598b184c97054a277580905792c1/Replicator/Puller.cc#L100-L103) so this is the place to put a breakpoint to see what is happening if it is still `subChanges` and not `getCheckpoint` in which case the error handling is [here](https://github.com/couchbase/couchbase-lite-core/blob/a71229a247c5598b184c97054a277580905792c1/Replicator/Replicator.cc#L385-L386)

**Comment by pasin** [comment]
I should have mentioned that I tested the push replicator (which is not exactly the case originally created in this ticket). I will try to identify the operations that causes the issue and retest with pull tomorrow.

**Comment by snej** [comment]
@borrrden and I talked about this on HipChat; I feel that the replicator should treat a 503 from a BLIP reply as fatal (maybe any 5xx) and stop the replicator. That will allow the platform bindings (CBL) to retry later.

**Comment by snej** [comment]
@tleyden: Can this be closed? As I said above (on 7/20), the existing reconnect/retry logic is part of Couchbase Lite. It can easily handle a 503 error the same way.

**Comment by tleyden** [comment]
@snej if the retry handling is being pushed out to the platform specific code, then it sounds like this ticket should be closed and new tickets should be opened on platform repos.

No work has been done on https://github.com/couchbase/sync_gateway/issues/3509 yet, so I think it would be fair to consider these issues on hold until that SG ticket makes it into a release plan.  I can also just make a note on that issue to open CBLite platform tickets once the SG development is planned.

**Comment by snej** [comment]
@borrrden I think there is, since `c4error_mayBeTransient` returns true for a 503 status. The Obj-C replicator code, in `-[CBLReplicator handleError:]`, calls that function and schedules a retry if it's true. I assume the Java and C# code does the same?

**Comment by borrrden** [comment]
The 503 error is considered transient but the issue was that the error is not getting handled from *inside* the BLIP message.  Only if the connection is closed with HTTP 503 will this cause a retry.  The conclusion that we came to was that the replicator should stop in the presence of such a message and pass the 503 to the platform so that it can use its retry logic.  Has that been implemented?

**Comment by snej** [comment]
Oh, sorry! So to paraphrase, the issue here is that LiteCore should handle a 503 error _in a BLIP response_ as fatal and stop the replicator, passing the 503 along as the replicator error. That makes total sense.

**Comment by borrrden** [comment]
Migrated to [CBL-126](https://issues.couchbase.com/browse/CBL-126)
