### ISSUE TITLE
cblite using forestdb rather than sqlite3?

### ISSUE THREAD

**Issue by kefir-** [couchbase/couchbase-lite-core#527]
README.md says that the storage engine for cblite is pluggable so that sqlite3 can be replaced. I have a database that I've pulled off a device I own, and it uses forestdb rather than sqlite3. Is there an easy way to coax cblite to use this format, or do I have to implement the DataFile, KeyStore and Query interfaces myself using forestdb? Currently, the cblite tool simply bails out with the error:

    Error: Couldn't open database dbname.cblite2: file/data is not in the requested format (1/21)

and using strace I can see that it tries to open dbname.cblite2/db.sqlite3, but this doesn't exist so cblite gives up and returns the error.

**Comment by borrrden** [comment]
Please use the forums for questions, and use issues for reporting bugs.  The storage engine *is* pluggable but it requires a nontrivial amount of effort as you've found out (implementing all the interfaces that are currently using sqlite).  Furthermore, the internals have changed so the best thing to do would be to use CBL v1.x to convert your db to sqlite first.

**Comment by kefir-** [comment]
Thanks. Where can I find CBL v1.x?

I had asked on the forum as well (right after I asked here, as soon as I found it), but I haven't had any response there yet.

**Comment by borrrden** [comment]
I don't see the forum post you made.  Did you make it in https://forums.couchbase.com/c/mobile ?

**Comment by kefir-** [comment]
https://forums.couchbase.com/t/export-or-query-data-from-cblite2-database/17066

It's not on /mobile, but I'm not on mobile either. I'm trying to get this working on Ubuntu Linux.
