### ISSUE TITLE
Upgrading CBL 1.x database fails if any strings contain codepoint 0 (\u0000)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#528]
Upgrading a Couchbase Lite 1.x database fails if any document in the database contains a string (key or value) that contains Unicode codepoint 0 (i.e. the escape sequence `\u0000`.) The call to `c4db_open` will fail and return an error. This makes it impossible to open such a database in CBL 2.

**Comment by snej** [comment]
The source of this is the jsonsl library, which Fleece uses to parse JSON. Its function `jsonsl_util_unescape_ex()` returns an INVALID_CODEPOINT error if it decodes a Unicode escape with a zero codepoint.

I checked the [latest version of jsonsl](https://github.com/mnunberg/jsonsl/blob/master/jsonsl.c), and the incorrect code that returns this error no longer exists, so it seems like a bug that was fixed. We should either update to this version, or just remove the problematic two lines of code.

**Comment by borrrden** [comment]
I can confirm that the latest version of jsonsl does not have the issue, but I also had trouble figuring out release strategies, etc, so I filed [this issue](https://github.com/mnunberg/jsonsl/issues/40) to ask the question.  The answer is "it should be fine to take the latest master, just make sure to check performance etc".  

Original issue directly related to this FYI -> https://github.com/mnunberg/jsonsl/issues/21

**Comment by snej** [comment]
Ah, this was [explicitly filed as an issue against jsonsl](https://github.com/mnunberg/jsonsl/issues/21) and fixed last year.
