### ISSUE TITLE
Checkpoint.cc:115 compilation error on raspbian

### ISSUE THREAD

**Issue by brunohpg** [couchbase/couchbase-lite-core#529]
When the source code is compiled in raspbian (debian modified version for Raspberry Pi) an error is generated:

[...]/couchbase-lite-android/libs/couchbase-lite-core/Replicator/Checkpoint.cc:115:27: error: no matching constructor for initialization of 'actor::Timer'
        _timer.reset( new actor::Timer( bind(&Checkpoint::save, this) ) );

This happens because Checkpoint::save() will return bool. So bind(&Checkpoint::save, this) returns some object that can be cast to function<bool()>, but not to function<void()>.

An easy and ugly fix is to create another function "void Checkpoint::savev () {save ();}" and bind to it (bind(&Checkpoint::savev, this)). But, certainly, there is another better way.

Some system details:
clang version 3.8.1-24+rpi1 (tags/RELEASE_381/final)
Target: armv6--linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin

Linux 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

**Comment by snej** [comment]
Weird, why would this fail on Raspbian and no other OS?

>bind(&Checkpoint::save, this) returns some object that can be cast to function<bool()>, but not to function<void()>.

It's always OK to ignore a return value in C/C++ AFAIK. Or does Raspbian have an unusual ABI that doesn't allow this?

**Comment by snej** [comment]
(Also, we've built LiteCore on Raspbian before without errors. It's been a year or so, but this particular code hasn't changed in longer than that.) Any ideas, @borrrden ?

**Comment by borrrden** [comment]
IIRC, this was an issue with the 3.8.x and below versions of libc++.  3.9.1 or higher is required.
