### ISSUE TITLE
Crash in WebSocketProtocol::consume

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#531]
We have two reports of the following crash in CBL-iOS 2.0.x:
```
0  _platform_memmove + 324
1  uWS::WebSocketProtocol<false>::consume(char*, unsigned int, void*) + 80
2  uWS::WebSocketProtocol<false>::consume(char*, unsigned int, void*) + 80
3  litecore::websocket::WebSocketImpl::onReceive(fleece::slice) + 84
4  c4socket_received + 16
...
```
Looking at WebSocketProtocol::consume, it's doing some scary stuff right at the start:
```c++
    void consume(char *src, unsigned int length, void *user) {
        if (spillLength) {
            src -= spillLength;
            length += spillLength;
            memcpy(src, spill, spillLength);
        }
```
It _writes to memory before the start of the buffer passed in_, which is bad news — this crash must have occurred because the buffer was at the start of a VM page with no mapped memory before it. But it could equally well overwrite malloc metadata and corrupt the heap.

It appears `spillLength` only gets set if the previous buffer ended with an incomplete WebSocket header; that partial header gets saved and then prepended to the input data. A WebSocket header being split between two reads is probably pretty rare, which is why we haven't seen this crash ourselves. (Also, it only happens when using a real TCP stream, not the LoopbackProvider.)

**Comment by snej** [comment]
Note: Fixed on the `release/2.0.x` branch; needs to be merged into `master` (along with other stuff on that branch.)

**Comment by borrrden** [comment]
Sorry I was trying to merge couchbase-lite-ios, not lite-core.  There is another issue though.  It seems that 1006 was arbitrarily added to the list of transient errors in 20f9d45920e7c646e0d3e0a433183ce500a81329 .  Since I map all errors that cannot otherwise be translated into a meaningful close error to 1006 something needs to be done or all of these "unknown" errors will become transient.

**Comment by snej** [comment]
I think it'd be best to map the unknown errors to something else, preferably in the Network or POSIX domain. 1006 means the socket was disconnected without a clean closing handshake, which is something we should treat as a transient error.

**Comment by borrrden** [comment]
Would LiteCore / Unexpected error be an acceptable default mapping?

**Comment by snej** [comment]
That sounds reasonable.
