### ISSUE TITLE
CppTests Undefined behavior sanitizer errors

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#533]
The following errors were reported during CppTests:

- /litecore/couchbase-lite-core/LiteCore/RevTrees/RawRevTree.cc:125:25: runtime error: null pointer passed as argument 2, which is declared to never be null [Upgrade from Android 1.2]
- /litecore/couchbase-lite-core/LiteCore/Support/Error.cc:147:13: runtime error: load of value 1000, which is not a valid value for type 'error::LiteCoreError' [C4Error messages] <-- Intended I think?
- /litecore/couchbase-lite-core/vendor/fleece/Fleece/slice.hh:89:73: runtime error: null pointer passed as argument 1, which is declared to never be null [SharedKeysTest decode]
- /litecore/couchbase-lite-core/vendor/fleece/Fleece/slice.hh:89:78: runtime error: null pointer passed as argument 2, which is declared to never be null [same as above]
- /litecore/couchbase-lite-core/vendor/BLIP-Cpp/src/blip/MessageOut.cc:211:28: runtime error: null pointer passed as argument 1, which is declared to never be null [Push Empty DB]
- /litecore/couchbase-lite-core/vendor/BLIP-Cpp/src/blip/MessageOut.cc:211:44: runtime error: null pointer passed as argument 2, which is declared to never be null [Same as above]
- /litecore/couchbase-lite-core/vendor/fleece/Fleece/JSONEncoder.cc:59:21: runtime error: null pointer passed as argument 1, which is declared to never be null [Push Small Non-Empty DB]
- /litecore/couchbase-lite-core/vendor/fleece/Fleece/JSONEncoder.cc:59:28: runtime error: null pointer passed as argument 2, which is declared to never be null [Same as above]
- /litecore/couchbase-lite-core/vendor/fleece/Fleece/slice.hh:77:61: runtime error: addition of unsigned offset to 0x629000041dcc overflowed to 0x629000041dc8 [Same as above]
- /litecore/build_debug/tlm/deps/libcxx.exploded/include/c++/v1/string.h:95:83: runtime error: null pointer passed as argument 1, which is declared to never be null [Same as above]

**Comment by snej** [comment]
Thanks for recording these. I'd tried the UBS a few months ago but decided against making changes when we were so close to shipping. It would be good to do so now; I use the UBS with Fleece and it finds some good bugs.
