### ISSUE TITLE
Symbols cause crash in Select statement

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-core#545]
Originally: https://github.com/couchbase/couchbase-lite-android/issues/1744

I am using CBL 2.0. My objects have a key "$writable". When trying to query these objects and return (amongst other values) the "$writable" value, a CouchBaseLiteException is thrown. Are symbols like $ meant to be supported? For now, I am simply removing the symbol before storing it in CBL, which avoids this issue.

**Comment by djpongh** [comment]
@percula, Pretty much anything is allowed in a key except for leading underscores (and empty strings.) So this is unexpected. We'd like to see the source code that creates the query, as well as the exception.

**Comment by snej** [comment]
@borrrden pointed out that this is likely from an ambiguity in the JSON-encoded query — the leading $ being interpreted as an ANY/EVERY variable reference.

**Comment by snej** [comment]
It's actually different — the property path gets compiled into a path string (kind of like JSONPath) by QueryParser, which is evaluated by Fleece's Path class. In those strings a leading `$` is special, so it was being misinterpreted.

I've added code to the Path class to support `\`-escapes, and to QueryParser to insert `\`s before special characters.

**Comment by snej** [comment]
(This is fixed on the feature/array-indexing branch; not merged to master yet.)

**Comment by borrrden** [comment]
There is no harm in merging it now, it will go into the iridium build.  2.1 will not be affected.

**Comment by percula** [comment]
Thank you very much for fixing this!!!
