### ISSUE TITLE
c4doc_update not validating that body is Fleece

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#554]
I'm hitting an assertion when calling `c4doc_bodyAsJSON` after `c4doc_update` in a C++ class. 

<img width="726" alt="screen shot 2018-08-15 at 21 37 39" src="https://user-images.githubusercontent.com/14980/44172084-060fa680-a0d4-11e8-9fa1-fd4ee6ed8736.png">

I had a previously successful test using `c4doc_put` and passing in a manually constructed Fleece dictionary. Debugging it looks like the `selectedRev.body` that is passed into the offended method is not null.

Any ideas to fix/debug this, or is this a potential bug? 

The wrapped update method:
```cpp
using namespace std;
//...

        C4Error outErr;

        c4::Transaction transaction (c4db);
        if (!transaction.begin (&outErr))
        {
            printError(outErr, "error beginning transaction");
            return string();
        }

       ////// RELEVANT CODE ////
        
        C4Document* outDoc = c4doc_update (c4doc, c4str ("{\"foo\":\"bar\"}"), 0, &outErr);

        cout << "revID after: " << sliceToStdstring (c4doc->revID) << endl;
        cout << "revID outDoc: " << sliceToStdstring (outDoc->revID) << endl;

        bool test1 = c4doc_hasRevisionBody(outDoc);   //  == true
        bool test2 = c4doc_loadRevisionBody(outDoc, &outErr);  // == true
        C4StringResult json = c4doc_bodyAsJSON(outDoc, false, &outErr);  // <-- hits assertion here
        cout << std::string((char*)json.buf, json.size);
        c4slice_free(json);

        /////////////////////////////////

        bool success = transaction.commit (&outErr);

        if (! success)
        {
            printError (outErr, "error committing document");
            return string();
        }

        c4doc_free (c4doc);
        c4doc = outDoc;

//...

```

**Comment by adamski** [comment]
I can't help but think this is a bug. If `c4doc_update` does not report an error, and the transaction commits, I don't see why I should get this assertion.

**Comment by snej** [comment]
That assertion means that the data is not valid Fleece. From your code, it looks like the problem is that you're passing JSON, not Fleece, to `c4doc_update`.

**Comment by snej** [comment]
`c4doc_update` should be validating that the body parameter is valid ... I'm surprised it's not.

**Comment by snej** [comment]
Well, here's why there was no error from passing JSON to c4doc_update:
```c++
    void Database::validateRevisionBody(slice body) {
        if (body.size > 0 && body[0] != '{') {        // There are a few unit tests that store JSON
```
That was dumb/lazy, and my fault. Better to fix the unit tests, or add a debugging global `gAllowJSONBodies`...
