### ISSUE TITLE
Don't send deltas:true in every proposeChanges message

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#558]
@bbrks noted,
>I noticed the changes/proposeChanges messages specifies “deltas”: true property to determine if deltas may be generated for the coming rev messages.
>This feels like it would be better to be negotiated once in the replication handshake when the connection opens the blip context.

**Comment by snej** [comment]
On the other hand, it's only ~12 bytes of overhead on the wire for every 200 docs; that's not much.

**Comment by bbrks** [comment]
It helps simplify the protocol a bit, and makes it cleaner to separate the delta/non-delta logic in SG if we know an entire BLIP connection context has deltas enabled or not.

When we come to using BLIP replication in sg-replicate, we wouldn't necessarily expect to see batches of 200 docs. The batch size could be much lower in that case, and the ~12 byte overhead is now amplified to once every few docs instead.

**Comment by snej** [comment]
How about sending the property only in the first `proposechanges` response, and having it persist for the rest of the connection?

That way we don't have to add another message to the protocol.

**Comment by snej** [comment]
@bbrks what do you think of what I proposed above (on Oct 4)?

**Comment by snej** [comment]
OK, I will simply update LiteCore to do the same, i.e. only pay attention to the first `useDeltas:true` flag.
