### ISSUE TITLE
conflict resolver does not update doc with high revision generation 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#560]
### Environment
lite core : 2.1.0
ios - 263
.Net - 232
DI mode only i.e with sg-accel

### Steps to reproduce : 
1. Create docs in CBL.
        2. Replicate docs to SG with push_pull and continous false
        3. Wait unitl replication done and stop replication.
        4. update doc 1 time in Sg with key 'updates' and update doc 2 times in CBL by incrementing key 'updates-cbl' 
        5. Start replication with push pull and continous False.
        6. Wait until replication done
        7. Verfiy doc with higher rev id is updated in CBL.
        8. Now update docs in sync gateway 3 times by incrementing counter for key 'updates' 
        9. Start replication with push pull and continous False.
        10. Wait until replication is done
        11. As sync-gateway revision id is higher, docs from sync-gateway should get updated on both.

### Result : 
1. Docs with high rev generation is not updated.
2. The counter for 'updates' is 3

### Expected : 
1. The counter for updates should be 4 which incremented at step 4 and step 8 and high revgeneration 

Note : It passed in previous RC and also it is successful in CC mode i.e sync-gateway without acceleration. It fails when it runs with sg-accel
It can be related to sync-gateway, but wanted to confirm it is not related to CBL and then I can move to sg.

**Comment by snej** [comment]
If it happens only with sg_accel, then it's probably an SG issue.

**Comment by djpongh** [comment]
Moved to SG Accel repo: https://github.com/couchbaselabs/sync-gateway-accel/issues/226
