### ISSUE TITLE
Queries does not work with float values

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#564]
### Environment
Android -> 2.1.0-176
.Net  -> 2.1.0-232

### Steps to reproduce : 
1. Create docs and make sure you float values : 
Sample docs : {'doc_with_double_1_1': {'item': 1L, 'item_price': 1.754}, 'doc_with_double_1_0': {'item': 0L, 'item_price': 0.754}, 'doc_with_double_1_3': {'item': 3L, 'item_price': 3.754}, 'doc_with_double_1_2': {'item': 2L, 'item_price': 2.754}, 'doc_with_double_1_4': {'item': 4L, 'item_price': 4.754}}

2. Query the data with float value  : 
Float key_val = 2.574
Expression exp_val = Expression.floatValue(key_val);
Query search_query = QueryBuilder
            .select(SelectResult.expression(Meta.id),
                SelectResult.expression(Expression.property("item")),
                SelectResult.expression(Expression.property("item_price"))
            .from(DataSource.database(database))
            .where(Expression.property(item_price).equalTo(exp_val));

### Expected results : 
It should return 1 row.

### Result : 
3. Returns 0 results

Note : When I change above code Expression.floatValue to Expression.doubleValue, it works fine.
Expression exp_val = Expression.doubleValue(key_val);

Looks like it works for double , but not for float

It works fine on iOS, It issue only on .Net and Android

### json query and compiled query
Compiling JSON query: {"WHAT":[["._id"],[".item"],[".item_price"]],"WHERE":["=",[".item_price"],2.754]}

Compiled as SELECT fl_result(key), fl_result(fl_value(body, 'item')), fl_result(fl_value(body, 'item_price')) FROM kv_default WHERE (fl_value(body, 'item_price') = 2.754) AND (flags & 1) = 0

**Comment by snej** [comment]
Floating point math is approximate, especially for 32-bit floats, and comparing floating point results for equality is always dangerous. This is true of any database.

The problem with this test is that `float(2.754)` is not equal to `double(2.754)`. So actually LiteCore is behaving correctly.
