### ISSUE TITLE
Failed RevTree Test: Delete the current winning rev, leaving the other one

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-core#57]
[TEST] c4DatabaseInternal.cc `N_WAY_TEST_CASE_METHOD(C4DatabaseInternalTest, "RevTree", "[Database][C]")`
https://github.com/couchbase/couchbase-lite-core/blob/59eb5e64bc8f0c3b5e53e9cdb2873c167033945c/C/tests/c4DatabaseInternal.cc#L704-L711

Before Delete current winning rev
```
1-1111
2-2222     
3-3333    3-3030
4-4444    4-4545
-         5-5555
```

After deleted
```
1-1111
2-2222     
3-3333    3-3030
4-4444    4-4545
-         5-5555
-         6-922c42851427bb9fdd17e7850f6f62460664b68a (DELETED)
```

Revision `4-4444` should be current revision, but DELETED revision `6-922c42851427bb9fdd17e7850f6f62460664b68a` becomes current revision.

**Comment by snej** [comment]
@hideki, can we close this or is it still an issue on Android?
