### ISSUE TITLE
Floating point numbers truncated during replication

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#583]
As an example of this consider the following code for saving a document:

```objc
CBLMutableDocument* doc = [CBLMutableDocument documentWithID:@"test"];
[doc setFloat:1.0f / 3 forKey:@"number"];
[db saveDocument:doc error:nil];
```

Now the result of getting the float from the document is `0.333333343`.  However after replication, this becomes 0.333333 in Sync Gateway.  On .NET it is actually 0.3333333 (7 places) vs 0.333333 (6 places) but the issue is the same.

As a sanity test, a direct PUT with 7 decimal places stores correctly in Sync Gateway so there is some place in LiteCore that is causing this it seems.

**Comment by snej** [comment]
The test code uses a 32-bit `float`, which is only good to about six significant figures. The various results you got were all equivalent at that level of precision, so if you converted them back to a `float` you'd get an identical value. I'd say this is behaving correctly.

(Of course, if you needed more precision, you'd use `setDouble:forKey:` instead.)

**Comment by borrrden** [comment]
I believe that the result of even the conversion back to float is differing, but I will double check.  For example, if you saved, pushed, deleted, and then re-pulled you would get a different value.  That was the original issue that was reported.

**Comment by borrrden** [comment]
Ok so the value before replication is `0.333333343` and the value after replication is `0.333332986` which (rounded) is the same to 6 decimal places.  So the stance is that this is expected?  Shouldn't the raw bytes be the same and result in the exact same number on Couchbase Lite (even if it is different elsewhere?).

**Comment by snej** [comment]
Remember, it went through several conversions: to JSON in the replicator, then parsed and (probably) rewritten as JSON in SG, then parsed back to Fleece by the replicator in the other CBL instance.

**Comment by borrrden** [comment]
I think one of the goals in post 5.0 Couchbase Server is to avoid the JSON conversion and just write the raw bytes that it receives, but perhaps it's not fully done.  I think that might help here as well.  @adamcfraser Could elaborate more on that I think.

**Comment by snej** [comment]
Couchbase Server doesn't do any rewriting (to my knowledge) since it doesn't care whether the doc is even JSON or not.
I believe SG rewrites JSON when it processes an incoming revision, in order to strip `_id` and `_rev` properties out of it, convert attachments to stubs, etc. None of that is necessary for revs coming from the BLIP replicator, but IIRC the replicator code still has to send the JSON into the pipeline that does all that work.

**Comment by borrrden** [comment]
Erm I was referring to Sync Gateway with Couchbase Server 5.0+ since they are able to use XATTRS now.

**Comment by adamcfraser** [comment]
As Jens mentioned, SG is still remarshalling documents before writing, both to strip out _id/_rev and to write _sync.  The goal is to preserve raw bytes for BLIP-replicated documents when using xattrs to store _sync.  I'd like to get that in Iridium.  Filed https://github.com/couchbase/sync_gateway/issues/3797 to track.

**Comment by djpongh** [comment]
This is a Sync Gateway issue - will fix in Iridium
