### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by KraemerDEM** [couchbase/couchbase-lite-core#585]
I have an app that crashes only in the release version on Android (debug version works fine) .
I've found that for some reason in some queries sqlite calls fl_value with an empty body as argument 0, so that setResultFromValue crashes. 
As a workaround i patched  LiteCore/Query/SQLiteFleeceFunctions.cc:
```
@@ -56,6 +56,8 @@ namespace litecore {
 
     // fl_value(body, propertyPath) -> propertyValue
     static void fl_value(sqlite3_context* ctx, int argc, sqlite3_value **argv) noexcept {
+        if (valueAsSlice(argv[0]).size == 0)
+            return;
         try {
             QueryFleeceScope scope(ctx, argv);
             setResultFromValue(ctx, scope.root);
```
With this patch everything works.
The crash only seems to happen on Android, the same app on iOS doesn't have this problem.
Unfortunately I cannot provide a database that reproduces the crash.
I don't know if sqlite guarantees that the values passed to a self defined function are always valid database values, so maybe that's normal behaviour of sqlite and couchbaselite has to check for valid data anyway.
I'm using couchbaselite from commit https://github.com/couchbase/couchbase-lite-core/commit/b49a9ac4354bde663e0b92a4739ed405093edc89 and sqlite version 3.25.2
This behaviour happens on both compilers (gcc and llvm)

**Comment by snej** [comment]
Is your crashing app built with that recent commit (b49a9ac), or from a released version of Couchbase Lite? The latest commits in LiteCore are definitely not stable at this point.

**Comment by djpongh** [comment]
@KraemerDEM, any update on this?

**Comment by djpongh** [comment]
If you get any more info, feel free to reopen
