### ISSUE TITLE
Use a stronger digest algorithm for attachment storage

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#59]
We've always used SHA-1 digests as identifiers for attachments: as the `digest` metadata property, and as the key for storing the attachment files. Like many other systems, we treated the digests as unique for all practical purposes. That's not viable anymore; the SHA-1 algorithm has been broken such that it's now possible to create multiple files with the same digest (and there are such files in the wild.)

We need to upgrade to a stronger algorithm, likely SHA-256 or SHA-3. The downside is that the digests are twice as large, and take longer to compute.

Backward compatibility will take some thought. Attachment stores can be upgraded by re-digesting and renaming all the files, but what do we do about the existing revisions containing `"digest":"sha1-…"` properties? It seems like we'll need to support both digests for a while — the attachment store may need to have both types of keys in use.

**Comment by snej** [comment]
* [The article describing the new attack on SHA-1](https://shattered.io/static/shattered.pdf)
* [A good Ars Technica article covering it](https://arstechnica.com/security/2017/02/at-deaths-door-for-years-widely-used-sha1-function-is-now-dead/)
* [SHA-1 collisions are breaking SVN repositories due to deduplication failures](https://arstechnica.com/security/2017/02/watershed-sha1-collision-just-broke-the-webkit-repository-others-may-follow/)

**Comment by snej** [comment]
A shorter-term workaround is to use the [SHA1-Collision-Detection library](https://github.com/cr-marcstevens/sha1collisiondetection), an augmented SHA-1 implementation that detects and rejects data that shows the signs of being crafted to create a collision.

**Comment by borrrden** [comment]
Migrated to [CBL-114](https://issues.couchbase.com/browse/CBL-114)
