### ISSUE TITLE
Add date collation?

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#590]
It just occurred to me that date-comparison issues could be resolved cleanly by adding a new “date” collation to queries, which would parse the strings as dates and compare those. It fits in perfectly with our existing collation support and makes it possible to specify a date comparison on any relational expression without having to alter the query syntax.

**Comment by borrrden** [comment]
Migrated to [CBL-129](https://issues.couchbase.com/browse/CBL-129)
