### ISSUE TITLE
Full-Text Search prefix queries are not working properly in some cases

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#593]
_From @stas9019 on October 16, 2018 16:54_

For query "'\*alterna\*'" FTS search finding the only word "alterna-porn", however, it should also match  "alternate", "alternative", "alternating" etc. I have no matches for "'*alternat*'" as well.

However, for query "'\*altern\*'" I see expected results, including "alternate", "alternative", "alternating".  Also, for  "'\*alternate\*'" I see exprected "alternate", "alternately".

I am creating the index in the following way. Probably it caused by English language stemmer.

```
let headwordFTSIndex = IndexBuilder
                .fullTextIndex(items:
                    FullTextIndexItem.property(Headword.Keys.headword.stringValue),
                    FullTextIndexItem.property(Headword.Keys.associated.stringValue)
                )
                .language("en")
                .ignoreAccents(true)
 try database.createIndex(headwordFTSIndex, withName: Index.FTS.Headword)
```

--------
* Version:   2.1.1 Community Edition
* Client OS: iOS 11/12

_Copied from original issue: couchbase/couchbase-lite-ios#2217_

**Comment by snej** [comment]
We use the Snowball stemmer, as packaged in the [sqlite3-unicodesn](https://github.com/illarionov/sqlite3-unicodesn) library. We've made a few changes to tokenization but no changes to the stemmer.

The stemmer doesn't have a perfect grasp of English grammar so it may produce the wrong stems for some words ... I'm not familiar with how it works internally, to be honest (apparently there's a Snowball DSL that takes the grammar info and emits a bunch of tables, and all we have in our code is the tables.)

**Comment by snej** [comment]
If LiteCore had a pluggable tokenizing/stemming API (#147) then CBL-iOS could use NSLinguisticTagger for this, which has better stemmers and broader language support.

**Comment by borrrden** [comment]
Migration candidate?

**Comment by borrrden** [comment]
Migrated to [CBL-232](https://issues.couchbase.com/browse/CBL-232)
