### ISSUE TITLE
Support N1QL `DISTINCT` modifier on aggregation functions

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#598]
Pasin points out that N1QL supports `DISTINCT` as an option on [aggregation functions](https://docs.couchbase.com/server/6.0/n1ql/n1ql-language-reference/aggregatefun.html), e.g. `SUM(DISTINCT exp)`, `COUNT(DISTINCT exp)`, `AVG(DISTINCT exp)`,  `ARRAY_AGG(DISTINCT exp)`. This seems to be different than the `DISTINCT` modifier applied to `SELECT`.

The `DISTINCT` modifier on a function means that only unique values should be considered, implying that the implementation will need to keep some kind of set of already-seen values so it can ignore duplicates.

**Comment by borrrden** [comment]
Migrated to [CBL-192](https://issues.couchbase.com/browse/CBL-192)
