### ISSUE TITLE
Adding Expiration Date to C4Document & enabling query for expiration date in docs 

### ISSUE THREAD

**Issue by Sandychuang8** [couchbase/couchbase-lite-core#600]
Please add Expiration Date to C4Document and enable query for expiration date in docs base on the API design: https://github.com/couchbaselabs/couchbase-lite-apiv2/pull/218/commits/71c603f3c6b79c01624283a534d830cb6f317b6d

**Comment by snej** [comment]
There are already functions `c4doc_getExpiration()`, etc. in c4Document.h.

Query capability was just requested as #599.
