### ISSUE TITLE
Add the ability to get a removed notification to replication eventing

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#607]
Currently there is no way to tell if a document has been removed from a channel (other than possibly reading some private properties from it).

**Comment by snej** [comment]
From Jim's Document Removal spec:
>The proposal is to eliminate the “_removed” revision insofar as an actual revision that gets saved and replace it with a purge.  Since users can no longer access revision history, and the document body is removed along with the channel removal, purge and removed effectively become the same thing.
