### ISSUE TITLE
Jenkins EE builds don't identify their Git commit correctly

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#613]
In EE builds from Jenkins, the Git commit ID in the output of `c4log_getBuildInfo()` is not meaningful. It's not an actual commit ID, rather [IIRC] a digest generated from the commit IDs of both the couchbase-lite-core and couchbase-lite-core-ee repos.

This means that one can't look at unit test logs and identify what source code they came from. For example, in [this failed build's logs](http://mobile.jenkins.couchbase.com/view/Core_Based_Builds/job/couchbase-lite-core-linux/880/consoleText):
```
19:55:01.969347| This is LiteCore EE build number 1545 from commit 00337b2c ... short version  (1545)
```
There is no commit `00337b2c` anywhere.

I know the computed digest is needed to work around some issue with how we trigger Jenkins builds, but IMO it shouldn't be returned from `c4log_getBuildInfo`. Or if it is, the actual Git commit ID(s) should be returned too.

**Comment by snej** [comment]
`c4log_getBuildInfo()` gets this from the constant `GitCommit`, which is generated by `get_repo_version.sh` at build time. In an official build, this script sets it equal to `$VERSION` instead of the Git commit ID.

If we need to be able to get this version info from a build, we could have the function return it as well as the real commit ID.

**Comment by borrrden** [comment]
To clarify, in order to correctly identify an EE build, we need two SHAs.  One for the commit that was used from the EE repo and one that was used from the CE repo.  The combination of the two produces a given build.
