### ISSUE TITLE
Stop-words with "*" in Match expression cause error

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#626]
From the [forum](https://forums.couchbase.com/t/fts-query-logical-and-wildcards-and-stop-words-causes-malformed-search-string-exception/19397):

> When I FTS search with a string like so: "anything* AND stopword*", the query execution fails with a SQLite error saying the query was given a "malformed search string".
> 
> Some examples:
> "usfs* AND he*"
> "banana* AND she*"
> "orange* AND i*"
> 
> I'm guessing this is caused by stop words (common English words) being extracted from the search string *before* taking logical operands and wildcards into account, resulting in:
> "usfs* AND *"
> "banana\* AND \*"
> "orange\* AND \*"
> 
> All of which are indeed "malformed search strings". Because I don't need any stemming or NLP features, I just set the index language to null, and the issue went away, so my problem is solved, but I figured I'd make a post as this is some very odd behavior!

**Comment by azane** [comment]
Yay! Thanks for the re-post. I'll post bugs here in the future. : )

**Comment by snej** [comment]
SQLite calls our tokenizer to break the search string into words. Unfortunately I can't find any way for the tokenizer to tell when it's being invoked for this purpose, as opposed to tokenizing text in the database. So the tokenizer can't tell whether it's supposed to preserve stop-words or not.

The best workaround I can think of is to make the tokenizer preserve a stop-word when it’s followed by a “*” … but there are contexts where this can happen in regular text being indexed, when the “*” is a footnote marker or the end of a Markdown emphasis sequence.

I've sent a question to the SQLite-users mailing list.

**Comment by snej** [comment]
I found a way to do this without having to upgrade to FTS5, although it's a bit of a hack. I added a per-thread flag that tells the tokenizer that a query is running; when that flag is set, it doesn't remove a stop-word when it's immediately followed by a "*". LiteCore sets that flag when running the SQLite query and clears it afterwards.
