### ISSUE TITLE
Store smaller blobs in the SQLite database

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#627]
It's more efficient to store smaller blobs in the SQLite db, rather than as external files. There's [a document on the SQLite website](https://sqlite.org/fasterthanfs.html) that quantifies this:

>SQLite reads and writes small blobs (for example, thumbnail images) 35% faster¹ than the same blobs can be read from or written to individual files on disk using fread() or fwrite().
>
>Furthermore, a single SQLite database holding 10-kilobyte blobs uses about 20% less disk space than storing the blobs in individual files.
>
>The performance difference arises (we believe) because when working from an SQLite database, the open() and close() system calls are invoked only once, whereas open() and close() are invoked once for each blob when using blobs stored in individual files. It appears that the overhead of calling open() and close() is greater than the overhead of using the database. The size reduction arises from the fact that individual files are padded out to the next multiple of the filesystem block size, whereas the blobs are packed more tightly into an SQLite database.

Their test only examined blobs in the range of 8-12kb, though. So there's a question of what the cutoff size should be, since storing 20MB blobs in SQLite is probably going to make compaction expensive.

**Comment by borrrden** [comment]
Migrated to [CBL-193](https://issues.couchbase.com/browse/CBL-193)
