### ISSUE TITLE
`_deleted` metaproperty is not or-able

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#638]
Given the following query:

```
{"WHERE":["OR",["=",["._deleted"],false],["=",["._deleted"],true]],"WHAT":[["._id"],["._deleted"]]}
```

All documents, deleted or otherwise, should be included.  However, only non-deleted docs are included.

**Comment by snej** [comment]
Sounds like the implicit `AND !_deleted` test isn't being suppressed, even though there are explicit references to `_deleted`. Either that, or the value of `_deleted` is neither true nor false...

**Comment by snej** [comment]
...or this may be an operator precedence problem in the generated SQL, i.e. missing parentheses. Let me write a test. (FYI, in issues involving queries it'd be great to include the generated SQL.)
