### ISSUE TITLE
Missing enqueueAfter function for ThreadedMailbox

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#64]
> /home/jenkins/workspace/litecore-linux/label/s61112cnt72 (litecore)/vendor/BLIP-Cpp/src/util/Actor.hh:207:22: error: 
      no member named 'enqueueAfter' in 'litecore::ThreadedMailbox'
            _mailbox.enqueueAfter(delay, std::bind(fn, (Rcvr*)this, args...));
            ~~~~~~~~ ^

**Comment by snej** [comment]
Fixed in BLIP_Cpp commit 57189b0.
