### ISSUE TITLE
STR_TO_MILLIS not returning null for invalid date(Feb 30th)

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#641]
N1QL: 
```
SELECT STR_TO_MILLIS("2020-02-30T01:01:01Z") as Milliseconds;

{
  "results": [
    {
      "Milliseconds": null
    }
  ]
}

```

LiteCore: 
```
results: {
    "STR_TO_MILLIS()" = 1583024461000; // Sunday, March 1, 2020 1:01:01 AM
}
```

Tested with 2018-12-32, and it is returning null. But this case is failing.

It's a leap year, hence Feb-30th.

**Comment by snej** [comment]
Feb 30 is invalid whether or not it's a leap year. Does N1QL check for leap years too — i.e. does it know that 2/29/18 is invalid but 2/29/20 is valid?

(I'm sort of afraid of this being a slippery slope. Calendars get very complicated, especially when you support past dates, i.e. before the adoption of the Gregorian calendar.)

**Comment by snej** [comment]
The fix is leap-year-aware :-p

**Comment by jayahariv** [comment]
Yes, N1QL knows whether its a leap year or not. It returns 2/29/20 as valid  and 2/29/18 as invalid.
