### ISSUE TITLE
LiteCore crashes when passing blob properties to query without blob operator

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#649]
Consider the following document:
```json
{
    "text": "<blob>"
}
```

JSON query:
```json
{"WHERE":[">",["PREDICTION()","TextModel",{"text":[".text"]},"wc"],15],"WHAT":[[".text"],["PREDICTION()","TextModel",{"text":[".text"]},"wc"]]}
```

and resulting SQLite query:
```sql
SELECT fl_result(fl_value(_doc.body, 'text')), fl_result(prediction('TextModel', dict_of('text', fl_value(_doc.body, 'text')), 'wc')) 
FROM kv_default AS _doc 
WHERE (prediction('TextModel', dict_of('text', fl_value(_doc.body, 'text')), 'wc') > 15) AND (_doc.flags & 1 = 0)
```

When this query is executed, the following Fleece exception is thrown:

```
encoder error: Numeric key given without SharedKeys
```

At the following location:
```
fleece::FleeceException::_throw(fleece::ErrorCode code, const char * what, ...) Line 61
fleece::impl::Encoder::writeKey(const fleece::impl::Value * key, const fleece::impl::SharedKeys * sk) Line 613
fleece::impl::Encoder::writeValue(const fleece::impl::Value * value, const fleece::impl::SharedKeys * & sk, const fleece::function_ref<bool __cdecl(fleece::impl::Value const *,fleece::impl::Value const *)> * writeNestedValue) Line 483
fleece::impl::Encoder::writeValue(const fleece::impl::Value * value, const fleece::function_ref<bool __cdecl(fleece::impl::Value const *,fleece::impl::Value const *)> * fn) Line 500
litecore::writeSQLiteValue(sqlite3_context * ctx, sqlite3_value * arg, fleece::slice key, fleece::impl::Encoder & enc) Line 351
litecore::dict_of(sqlite3_context * ctx, int argc, sqlite3_value * * argv) Line 392
sqlite3VdbeExec(Vdbe * p) Line 89964
sqlite3Step(Vdbe * p) Line 81041
sqlite3_step(sqlite3_stmt * pStmt) Line 81104
SQLite::Statement::executeStep() Line 259
litecore::SQLiteQueryRunner::fastForward() Line 430
litecore::SQLiteQuery::createEnumerator(const litecore::Query::Options * options, unsigned __int64 lastSeq) Line 475
c4query_run::__l2::<lambda>() Line 173
c4Internal::tryCatch<C4QueryEnumerator * __ptr64>(C4Error * outError, fleece::function_ref<C4QueryEnumerator * __cdecl(void)> fn) Line 60
c4query_run(c4Query * query, const C4QueryOptions * c4options, FLSlice encodedParameters, C4Error * outError) Line 175
```

**Comment by snej** [comment]
I think the blob property isn't being tagged with the value subtype that indicates it's a raw blob (not Fleece data.)

**Comment by snej** [comment]
I made a unit test similar to this but it's passing ... the bug might depend on exactly what "`<blob>`" is. Do you know the exact bytes that were in it?

**Comment by borrrden** [comment]
There aren't any actual bytes in it.  It's the metadata dictionary that gets saved from CBL.

**Comment by snej** [comment]
Ah, "`<blob>`" must actually be a CBL blob value, i.e. a dictionary. This bug actually reproduces if the `text` property is any dictionary.

**Comment by pasin** [comment]
The crash issue has been fixed but I have a problem getting the blob content from the `FLDict` of the PredictiveModel callback. Currently CBLPredictiveModel objects are registered globally (independent of database objects). When getting the blob dictionary in FLDict, there is no database reference to get the blob store. 

Can the FLDict include the blob content instead of the blob meta data the same way as using BLOB operator like `@{ @"text": @[@"BLOB", @".text"]}`?

**Comment by snej** [comment]
That's what the `BLOB` operator is for -- your query should use it to get the blob data to pass to the prediction function.

**Comment by pasin** [comment]
For the API point of view, it's not very obvious that the blob operation is needed. For example, when using SELECT statement, there is no need to use blob operation. It took a good chunk of time to know that I need to use blob operation and I could expect the same for the users.

If we cannot automatically extract the blob data into the FLDict, can we provide the c4db as another parameter in the predictive model callback?

**Comment by snej** [comment]
This has diverged from the original bug report ... could you file a new issue please?
