### ISSUE TITLE
"mutex lock failed" error while replicating document with multiple updates

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#652]
_[Originally [filed in the cblite tool repo](https://github.com/couchbaselabs/cblite/issues/6) by @sharujayaram]_

**Steps to reproduce**

```
1. Setup CB cluster & Configure SG
2. Create a document using POST API via SG
3. Create a cblite db on local server using cblite serve
     ./cblite/build/cblite serve  --create db.cblite2
4. Replicate between SG -> db.cblite2
     ./cblite/build/cblite push  ws://172.23.100.204:4985/db db.cblite2
5. Validate number of records on db.cblite2 ->Should be  equal to number of documents created in Step2
6. Update existing document using update API via SG (more than twice)
     PUT sghost:4985/bd/doc_id?=rev_id
7. run replication between SG -> db.cblite2 again
```
On step7 below error message is thrown . This issue happens only when a document is updated more than once . Ideally irrespective of number of updates on a single doc replication should still get the latest revision .

**ErrorMessage**
```
mv-mbp-sharathsulochana:~ sharathsulochana$ ./cblite/build/cblite push  ws://sghost/db db.cblite2
...
11:23:25.156137| [Sync] ERROR: {IncomingRev#1}==> litecore::repl::IncomingRev ->ws://sghost:4985/db/_blipsync @0x7ff132f0f670
11:23:25.156641| [Sync] ERROR: {IncomingRev#1} Threw C++ exception: mutex lock failed: Invalid argument
```

**Comment by snej** [comment]
Apparently "`mutex lock failed: Invalid argument`" means that the mutex object is in an invalid state, probably because it's gone out of scope (i.e. parent object destructed) and contains garbage. So running with the Address Sanitizer would also be helpful.

**Comment by snej** [comment]
Another report: https://issues.couchbase.com/browse/CBSE-6260

**Comment by snej** [comment]
I wrote a LiteCore unit test for this but can't reproduce it. @sharujayaram, I'm confused about your steps to reproduce. You say to **push** from LiteCore to SG, but that doesn't make sense to me because you never create any docs in LiteCore, only in SG, so there's nothing to push! I assumed this was a typo for "pull", so I wrote my unit test pulling from SG, and it passes.

**Comment by sharujayaram** [comment]
@snej 
Yeah its other way around . It should have been "push"

**Comment by sharujayaram** [comment]
Interestingly , this is not happening consistently . I  will try it again and see if this still reproducible with older version of SG .

**Comment by snej** [comment]
Don't you mean "it should have been _pull_"? 🤯

**Comment by sharujayaram** [comment]
Yes you are right  . I had Source & Destination reversed .  Apparently it still works with it .

**Comment by snej** [comment]
I don't know how I can diagnose what's going wrong without a backtrace of the exception ... so I will need a way to reproduce this in Xcode.

**Comment by djpongh** [comment]
Unfortunately, we haven't found a way to reproduce. Feel free to reopen if you can reliably reproduce this.
