### ISSUE TITLE
Incorrect progress after doc rejected by validation function

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#667]
Continuous Pull replication with deleted doc is returning "WebSocket 403 'rejected by validation function'". 

Found below issue, 
1. The progress status is not correct.

[Unit test which is failing](https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/Tests/ReplicatorTest.m#L2008)
[Console Log](https://gist.github.com/jayahariv/c277ab3ffd2be6061faefabd2689814e)

**Comment by borrrden** [comment]
Does the test fail, because the behavior you mentioned is correct.  You are rejecting one of the deletions, and so it will show up to the other side as a 403.  This error will be received by the "other side's passive pusher" so the "push rev" is also correct.  The way that replication works is that "pull" is just a "request for push from the other side" basically so there will always be both push and pull involved in any replication.  Progress status weirdness is something I also noticed, though.

**Comment by jayahariv** [comment]
yes test fails, due to the progress status. It will wait for the replicator to change the status to idle and then status.progress.completed == status.progress.total. But unfortunately, the completed is less than the total, so the test is timing out.

**Comment by snej** [comment]
(FWIW, that test for `status.progress.completed == status.progress.total` probably shouldn't be there. The code is detecting whether a continuous replicator has caught up; it can do that by checking whether the status is Idle, as it already does. It's not necessary to look at completed or total. It's fine if the test asserts that completed == total, after the replicator goes idle. That assertion would fail here, of course. This makes the failure easier to understand.)

**Comment by snej** [comment]
If the replicator couldn't get all the documents, then it's correct for completed to be less than total. It couldn't complete the total number of documents it needed to pull. This doesn't sound like a bug.

**Comment by jayahariv** [comment]
So if the DB1 is having an extra documents which is not pulled to DB2(due to filter), then the `progreess.completed` should be less than the `progress.total`. But why push is showing those values equal. 

Also if so, is there a way we can validate whether the docs finished replicated or not in continuous replication.

**Comment by pasin** [comment]
> That assertion would fail here, of course. This makes the failure easier to understand.

We can change the test code to not waiting and use assertion to check the completed and total.

> If the replicator couldn't get all the documents, then it's correct for completed to be less than total. It couldn't complete the total number of documents it needed to pull. This doesn't sound like a bug.

When the document gets rejected, can we mark them as completed so the total and completed could be in sync? Otherwise, if using filter to reject documents, the completed and total will never be synced.
