### ISSUE TITLE
Use SQLITE_TEMP_STORE=0 for both CE and EE

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#674]
From https://github.com/couchbase/couchbase-lite-android/issues/1818, the SQLite query aborted with error code `6410` which is `SQLITE_IOERR_GETTEMPPATH`. The `SQLITE_IOERR_GETTEMPPATH` error code is an extended error code for `SQLITE_IOERR` indicating that the VFS is unable to determine a suitable directory in which to place temporary files. Note that the user also confirms that the issue didn't appear when using CBL Android EE.

Currently LiteCore EE version builds the SQLite with `SQLITE_TEMP_STORE=2` while the CE version uses the default value which is `SQLITE_TEMP_STORE=1` meaning that the temp files will be stored on disk. At least on Android, we should always set the `SQLITE_TEMP_STORE=2` as the temp directory on android cannot be determined consistently.

After discussing with @snej today, we should set `SQLITE_TEMP_STORE=2` for both CE and EE to get consistency behavior even though using `SQLITE_TEMP_STORE=2` could use more memory.

**Comment by pasin** [comment]
Wait, the recent comment from @snej :

```
Why don't we add a LiteCore function, like c4_useTempDir, that the app can use to tell LiteCore where the writeable temp directory is?

(I'm a bit squeamish about using SQLITE_TEMP_STORE=2 because it will increase RAM usage during queries. I don't know about Android, but on iOS this can lead to the app being killed for hogging RAM.)
```

**Comment by pasin** [comment]
From what I see [here](https://android.googlesource.com/platform/external/sqlite/+/android-cts-8.0_r16/dist/Android.mk), Android set the SQLITE_TEMP_STORE=3 which is always using memory.

**Comment by borrrden** [comment]
The result of the discussion today is as follows:

Modify Xcode project to have SQLITE_TEMP_STORE=2 next to SQLITE_HAS_CODEC in the xcode configs, and modify the CMake project to set SQLITE_TEMP_STORE=2 for CE on desktop platforms.

Note: The advice received was from SQLCipher and I find no information that the same recommendation comes from the SQLite team regarding SEE.

**Comment by pasin** [comment]
@borrrden are we still setting SQLITE_TEMP_STORE=2 as your comment above?

**Comment by borrrden** [comment]
Not sure anymore.  We should discuss again given the input from the SQLite mailing list.

**Comment by borrrden** [comment]
Changing the recommendation to SQLITE_TEMP_STORE=0 everywhere.  However this opens up a weird situation.  Since we linked sqlite3_temp_directory with LiteCore's temp directory, the sqlite temp directory will be moving often.  This is because LiteCore's temp directory *has* to be on the same partition as its database, but the sqlite one does not.  @snej Should we decouple these two?

**Comment by pasin** [comment]
For more information about what @borrrden is explaining, currently the temp directory for CBL Android will depend the database directory set to DatabaseConfiguration to avoid the partition issue.

Note: if the directory is not set, a default temp directory which is an APP_CACHE directory will be used.
