### ISSUE TITLE
Stopped status not reported for active side of replication

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#677]
Test case is consistently failing in Jenkins.

**Comment by borrrden** [comment]
I'm having a hard time finding out exactly what is causing this ( @snej ? ).  However, putting a breakpoint in `reportStatus()` of Replicator.cc shows a stopped status coming through for the passive replication side of a P2P replication but not the active one.

**Comment by borrrden** [comment]
The DBWorker is never notified of the pushing doc being aborted due to the response from `proposeChanges` never being handled (state is never `complete`, first `awaitingReply` and then `disconnected`)

**Comment by borrrden** [comment]
https://github.com/couchbase/couchbase-lite-core/blob/857e8d5838a4e6715fd4d3961b38ea18bd0b7011/Replicator/DBWorker.cc#L1187-L1190

In the above snippet, the `DBWorker` returns that it is busy if it has items to process but this doesn't seem to take into account the connection status.  If there is no connection left then no messages can be sent to ever fulfill this criteria.  I have verified that replacing `if(!_pushingDocs.empty())` with `if (connection() && !_pushingDocs.empty())` will fix the test, but is that an acceptable thing to do?

**Comment by snej** [comment]
The Pusher is responsible for tracking the status of docs being sent via BLIP, so it's the one that gets notified if the connection is closed. Sounds like it's failing to notify the DBWorker that the document is no longer being pushed. I'll go check.

**Comment by borrrden** [comment]
In that case I think where the propose changes request gets sent the disconnect gets ignored. The callback from send request simply returns if the status of the message is not “sent”. It ignores “disconnected”

**Comment by snej** [comment]
Turns out the DBWorker already gets notified that the connection has closed. I just added a line there to clear out `_pushingDocs`.
