### ISSUE TITLE
Send deltas for revs with blobs

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#679]
The replicator currently will not send a delta when the revision has blobs. This affects performance, as the entire revision body always gets sent. (This has nothing to do with sending the blobs themselves; those are out of line, sent in separate BLIP messages and only if they've changed.)

**Comment by snej** [comment]
See also #678 — should fix that as part of implementing this.

**Comment by bbrks** [comment]
@snej How are final deltas going to look between 2 revs with changed blobs? I want to do the same on the SG side for pull replication if at all possible, to keep the replication symmetric.

**Comment by snej** [comment]
The deltas would look like what you'd expect, to reflect the changes in the `_attachments` dict.

The problem with implementing this is that LiteCore's pusher transforms the real document body, with `"@type":"blob"` dicts anywhere, into the "legacy" form SG can handle with an `_attachments` dict. And the puller applies a reverse transformation. So the base revision it uses for deltas will have to be the legacy form.

The implementation headache is that LiteCore doesn't keep the legacy form persistently, so when re-creating it I'll have to make sure that it consistently gets created the same way as the original, even if the original came from SG. (I.e. the transformation needs round-trip fidelity.)

**Comment by snej** [comment]
From my perspective this would be a lot easier if SG adopted the "blobs anywhere" format of CBL 2, so this transformation wouldn't have to happen. But I understand that's a nontrivial task.
