### ISSUE TITLE
Crash passing non-string to `regex` query functions

### ISSUE THREAD

**Issue by adityasonel** [couchbase/couchbase-lite-core#682]
I am using couchbase lite version `android-ee:2.1.2`. I stored some data in local couchbase lite database. Now, I am trying to query data from local couchbase lite database with the help of regex query like,
```
Query query = QueryBuilder
                .select(SelectResult.property("info"))
                .from(DataSource.database(localDatabase))
                .where(Expression.property("info").regex(Expression.string("^v" + "_" + "(4.6.2|1.7.7)" + "_" + "[123]" + "_" + "[12345678]")));
```
And my database looks like,
```
v_1.7.7_1_3
v_1.7.5_1_3
v_4.7.1_2_8
v_4.7.1_1_8
v_4.7.2_2_8
v_4.7.2_2_8
v_4.7.1_1_8
v_4.7.1_2_8
v_4.7.5_1_8
v_4.9.3_1_1
...
...
...
and so on many entries
```
To understand database structure let's take an example of v_1.7.7_1_3 here v can be defined as a just value, 1.7.7 is tag then 1 is parent class(this can be of type 1,2 and 3) and then 3 is child class(this can be of type 1,2,3,4,5,6,7 and 8).

Now user can select multiple tags, parent classes, and child classes as a choice. Then I have to query data from local couchbase lite according to parameters selected respectively. Currently, as I stated above I am trying to query data with the help of regex as like,

For example, let a user selected tag 4.6.2 and 1.7.7, then the parent classes are 1,2 and 3 and then child classes 1-8. So my query will be like,

`"^v" + "_" + "(4.6.2|1.7.7)" + "_" + "[123]" + "_" + "[12345678]"`

I already tried this query on https://regex101.com where it is working perfectly, but not with couchbase lite. Although the application is just crashing with a fatal error,

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 25543 (.mains.activity)`

Here some logs,

```
V/Query: Query encoded as {"WHAT":[[".info"]],"WHERE":["regexp_like()",[".info"],"^v_(4.6.2|1.7.7)_[123]_[12345678]"]}
I/LiteCore [Query]: {Query#3}==> N8litecore11SQLiteQueryE 0x7f5a2d9098
I/LiteCore [Query]: {Query#3} Compiling JSON query: {"WHAT":[[".info"]],"WHERE":["regexp_like()",[".info"],"^v_(4.6.2|1.7.7)_[123]_[12345678]"]}
I/LiteCore [Query]: {Query#3} Compiled as SELECT fl_result(fl_value(body, 'info')) FROM kv_default WHERE (regexp_like(fl_value(body, 'info'), '^v_(4.6.2|1.7.7)_[123]_[12345678]')) AND (flags & 1) = 0
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 28308 (.mains.activity)
```

**Comment by jayahariv** [comment]
validated the issue with the test case below, seems like `std::regex_search`([reference](https://github.com/couchbase/couchbase-lite-core/blob/650c27df206fcc62167a5e0a6a8769da4d700bdd/LiteCore/Query/SQLiteN1QLFunctions.cc#L651)) is looking for a string length, which is NULL in this case.

[backtrace.txt](https://github.com/couchbase/couchbase-lite-core/files/2818237/log.txt)


```
func testRegexCrash() throws {
        let doc11 = MutableDocument()
        doc11.setValue("name", forKey: "v_1.7.5_1_3")
        try saveDocument(doc11)

        let select = [SelectResult.expression(Expression.property("version"))]
        let searchQuery =
            QueryBuilder.select(select)
                .from(DataSource.database(db))
                .where(Expression.property("version").regex(Expression.string("^v" + "_" + "(4.6.2|1.7.7)" + "_" + "[123]" + "_" + "[12345678]")))
        
        
        for result in try searchQuery.execute() {
            print(result.toDictionary())
        }
    }
```

**Comment by snej** [comment]
Ugh, there are other problems too with `regex_like` and the nearby regex functions — they're assuming the data in the slice is followed by a null byte, which I think happens to be true in this case but it's dangerous to depend on. I'll fix them up.

**Comment by snej** [comment]
Note: There are no unit tests of any of the regex functions, in LiteCore nor in CBL-iOS. Also, the only function exposed in the public API (on iOS at least) is `regexp_like` -- not `regexp_position` or `regexp_replace`.
