### ISSUE TITLE
Passive push/pull sometimes getting stuck in busy

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#684]
This is hard to trigger but happens pretty regularly on Jenkins windows slave.  The passive replicator gets stuck in busy with a queued message.  Here is a gist with a good and bad run logs scoped to the same replicator object:

https://gist.github.com/borrrden/9e3e42380d78cb5cc4cc737c1a31505d

**Comment by snej** [comment]
In the bad log, the Replicator object's delayed-event count never goes back to 0. The only delayed event that class uses is for reporting status to the delegate, line 216:
```c++
enqueueAfter(actor::delay_t(waitFor), &Replicator::reportStatus);
```
That delay should always be 0.2 sec or less. I wonder if something's wrong with the Timer class and the timer set by ThreadedMailbox isn't firing?

**Comment by borrrden** [comment]
Darn I thought I was careful about the wording.  This needs to be closed with a submodule update.  Reopening!
