### ISSUE TITLE
Explicit partial indexes

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#685]
Feature request: The ability to create a partial index, i.e. restrict the index to documents matching some criterion (often based on the `type` property.)

This will reduce the size of indexes, the overhead of indexing, and likely improve query performance.

(Implementation of this is straightforward, just adding a `WHERE` clause to the `CREATE INDEX` statement, plus plumbing to pass this through the API.)

**Comment by borrrden** [comment]
Migrated to [CBL-215](https://issues.couchbase.com/browse/CBL-215)
