### ISSUE TITLE
Default conflict resolver fails for high revision generation of resolving conflict

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#690]
### CBL version : 2.5.0

iOS : 2.5.0-175
.net : 2.5.0-144
Android: 2.5.0-147

### Steps to reproduce :

       1. Create docs in CBL.
        2. Replicate docs to SG with push_pull and continous false
        3. Wait unitl replication done and stop replication.
        4. update doc 1 times in Sg and update doc 2 times in CBL and vice versa in 2nd scenario
        5. Start replication with push pull and continous False.
        6. Wait until replication done
        7. Verfiy doc with higher rev id is updated in CBL.
        8. Now update docs in sync gateway 3 times.
        9. Start replication with push pull and continous False.
        10. Wait until replication is done
        11. As sync-gateway revision id is higher, updates from sync-gateway wins

### Actual :

All the docs appear back to CBL after replication and Docs still exist on both SGW and CBL
Expected:

Docs deleted at step #4 on CBL , it should get deleted on both CBL and SGW as delete has to win with default conflict resolver

### Regression test :

https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py#L1417

### Tests that are failing:

test_default_conflict_scenario_highRevGeneration_wins[cbl-True]
test_default_conflict_scenario_highRevGeneration_wins[cbl-False]

Command to run test :

pytest -s -rsx -k test_default_conflict_scenario_highRevGeneration_wins[cbl-True]--timeout 1800 --liteserv-version=2.5.0-147 --liteserv-host=localhost --liteserv-port=8080 --sync-gateway-version=2.5.0-204 --mode=cc --server-version=6.0.1-2037 --liteserv-platform=ios --create-db-per-test=cbl-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests

cbl logs :

https://gist.github.com/sridevi-15/d0fed1fd02655233d5f666f439f33ab2

SGW logs :

https://gist.github.com/sridevi-15/e84ad9c53b5ba492d7d1a7c4986e650f

**Comment by sridevi-15** [comment]
Note : default conflict resolver works for high rev id though

**Comment by borrrden** [comment]
There is no "expected" and "actual" looks to be copied and pasted from a previous ticket...

**Comment by pasin** [comment]
I have updated iOS and Android to pickup the fix. Added verify tag.

**Comment by snej** [comment]
The fixes in #697 should help with this too.

**Comment by sridevi-15** [comment]
passed in latest build
