### ISSUE TITLE
c4doc_bodyAsJSON crashes on fleece::impl::Value::tag()

### ISSUE THREAD

**Issue by sinosoidal** [couchbase/couchbase-lite-core#692]
I'm trying to get the body as json using the function c4doc_bodyAsJSON but it is crashing at fleece::impl::Value::tag(). 

Is there any obvious reason for this to be happening? I'm using the master branch and all its dependencies.

**Comment by borrrden** [comment]
Saying "it is crashing" is not a very useful piece of information for diagnosing something.  What is the stack trace and how are you calling this method?

**Comment by sinosoidal** [comment]
@borrrden I think the problem is that the database was somehow corrupted from my tests. I have deleted it and from that point onwards, it is working. Sorry for wasting your time! I ended up making rubber ducking with you! 😄
