### ISSUE TITLE
Update to SQLite 3.27.1, to fix #632

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#695]
SQLite 3.27.1 is out — it fixes the `OR` query bug (#632) we found a few months ago.

**Comment by borrrden** [comment]
Branches ready [here](https://github.com/couchbasedeps/SQLiteCpp/tree/feature/sqlite_3_27_1) and [here](https://github.com/couchbase/couchbase-lite-core-EE/tree/feature/sqlite_3_27_1)

**Comment by snej** [comment]
Have you run our unit tests with these branches? If they pass, go ahead and merge into LiteCore.

**Comment by borrrden** [comment]
I will do all of that after the closed DB.

**Comment by borrrden** [comment]
Closed with a143657b9f73f691c0142c19aed3cdc16c44c790
