### ISSUE TITLE
Object destructed with invalid ref count

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#696]
Related to #652 probably, but seen on UWP.  

The ref count was 1, meaning that somewhere there is a race between a retain somewhere (already gone by the time of the crash) and the DataFile destructor (triggered via DBWorker -> Database -> DataFile).  The crash dump is available on one of the Jenkins machines and I can set it aside if it might be useful.

**Comment by djpongh** [comment]
@borrrden, have you seen this again?

**Comment by borrrden** [comment]
I have not seen this since.  It's a rare event to begin with.

**Comment by djpongh** [comment]
Darn, we'll close and hope you never hit it again...
