### ISSUE TITLE
SQLiteDataFile::Factory doesn't delete -shm or -wal files

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#7]
For example, shm and wal files for SQLite or .0 / .meta files for forestDB.  I see that it attempts to do so by doing `path.withExtension` but in the case of shm / wal they are not extensions but more like "extras" tagged onto the end of the filename (db.extension-shm).

**Comment by borrrden** [comment]
Correction: Only shm and wal are affected, not ForestDB.

**Comment by snej** [comment]
Oops, yeah:
```c++
    bool SQLiteDataFile::Factory::deleteFile(const FilePath &path, const Options*) {
        return path.del() | path.withExtension("shm").del() | path.withExtension("wal").del();
        // Note the non-short-circuiting 'or'!
    }
```
