### ISSUE TITLE
Change optimization to size, not speed

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#701]
The current Clang optimization flags for release builds are `-Ofast` (Xcode) and `-O2` (CMake).

I've experimented with changing to `-Os` (optimize for size) or `-Oz` (even further size optimizations). The size improvements are dramatic — the macOS `libLiteCore.dylib` goes from 2.6MB to 1.7MB, a third smaller! (With -Os it's 1.8MB.)

I've used the iOS project's TuneMark test to compare performance on my iMac. The numbers change by around 5%, mostly down but some up. These numbers are pretty fuzzy anyway, and even re-running the same binary they'll bounce around by a few percent from run to run, so I think the performance impact is pretty negligible.

**Comment by snej** [comment]
With CMake we can optimize for size on the command line by running `cmake -DCMAKE_BUILD_TYPE=MinSizeRel`. This uses `-Os`; to get `-Oz` we'd have to explicitly add that flag to `CMAKE_CXX_FLAGS_MINSIZEREL` and `CMAKE_C_FLAGS_MINSIZEREL`.

**Comment by borrrden** [comment]
I was just going to say the same thing about `CMAKE_BUILD_TYPE` but with `MinSizeRel` we lose debug information so I'd like to add `-g` back in in that case (or whatever is used to govern that)

**Comment by snej** [comment]
Changed in Xcode builds via 2b2bbfeea1cc40af75ed1cb34c924779ad65a69d.
