### ISSUE TITLE
Issues with new isQueryRunning() for iOS simulator

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#708]
I see a few problems with the recent commit to sqlite3-unicodesn that adds a thread-local flag for the iOS simulator —

1. If `setQueryRunning` is called before `isQueryRunning`, the pthread key will be used before it's created.
2. The key is created every time `isQueryRunning` is called. I don't know whether this is safe or not; the macOS man page for `pthread_key_create` doesn't say what happens if it's called twice with the same key. It might create a new empty key every time.

Also, I think it'd be good to move this is/setQueryRunning code to a header file since it's grown a bit.

**Comment by borrrden** [comment]
I keep forgetting to put in keywords.  Closed via 4e1a2cebbcd28645893f4376fb4454e662eab01f
