### ISSUE TITLE
Select dictionary literal with large integer values returning wrong results

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#709]
Originally reported in https://github.com/couchbase/couchbase-lite-ios/issues/2367 that querying predictive function that returns results with large integer numbers returned wrong results. 

For example, the following JSON query returns the value as `{int_min: 0, int_max: -1}` when a document has the content as `{int_min: INT64_MIN, int_max: INT64_MAX}`.

```
{"WHAT":[{"int_min":[".int_min"],"int_max":[".int_max"]}]} 
```

**Comment by borrrden** [comment]
This is fixed now right?
