### ISSUE TITLE
One-off failure in "Continuous Push From Both Sides" unit test

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#711]
The "Continuous Push From Both Sides" test failed for me once this morning; wasn't able to reproduce in ~10 further attempts. Log is attached: [FAILED Continuous Push From Both Sides.txt](https://github.com/couchbase/couchbase-lite-core/files/2916419/FAILED.Continuous.Push.From.Both.Sides.txt)

The failure is that the doc isn't updated to the latest revision on the client side; it's a few revs behind.

In the log, the problem starts when client rev 39 is pushed to the server with an obsolete parent revision 37, when it should be 38:

`18:21:17.696111| [Sync]: {dbworker#1237} Rejecting proposed change 'doc' #39-8521eca06be62cefb744f608d21a891c8bb02c6c with parent 37-c2ce77a525eb7486e1131b07150734b4e1cd5e5b (status 409; current rev is 38-9ca082d7b1432532f2abf4e9cd09bf8cbad9d2ff)`

Rev 39 was just created by the bg task, but by that time rev 38 had already been successfully pushed and the remote-ancestor was already updated to 38, so I don't know why it was sent with 37 as the ancestor...

**Comment by snej** [comment]
FYI, current LiteCore rev is 21eda300 "Fleece optimizations, and improved delta-sync test", which hasn't been pushed yet.

**Comment by djpongh** [comment]
haven't been able to repro
