### ISSUE TITLE
Floats seem to be truncated when sent which occasionally causes precision loss

### ISSUE THREAD

**Issue by JRascagneres** [couchbase/couchbase-lite-core#718]
When creating a document with a float and sending it over BLIP the value appears to be truncated to 6 significant figures. This can cause loss of precision. This has been reproduced in Android by following the below steps:

- Create a document with a float field with the value '27874302100000.0F'
- Setup push replication to SG

This value appears as `2.78743e+13` over BLIP. Resulting in a loss of `2100000`. This then obviously means that this truncated value is the one received by Sync Gateway and therefore Couchbase Server.

The value does appear correctly if you just get the document directly from the local Couchbase Lite database so I believe the issue is somewhere in how the data is prepared for sending.

This has also been reproduced on iOS.

**Comment by bbrks** [comment]
Just for completeness, here's what gets sent to SG in a rev message:

![Screenshot 2019-03-13 at 15 15 00](https://user-images.githubusercontent.com/1525809/54290527-08bb7700-45a3-11e9-9c56-3b898f737311.png)

**Comment by snej** [comment]
How exactly was this value added to the document, i.e. which CBL API call?

If you mean `float` literally, then your value as stored in the database only has about seven significant figures in decimal (23 bits), so Couchbase Mobile is behaving correctly. Store the value as a `double` instead.

(I think it's likely that this is the case, since otherwise CBL would have used more precision in the JSON encoding it sent SG. Unless there's something wrong with CBL's JSON encoder.)

**Comment by JRascagneres** [comment]
This is the method I was doing in CBLite:

`MutableDocument mutableDoc = new MutableDocument("testdoc")
                    .setFloat("version", 27874302100000.0F);`

Then obviously saved and had the replication running.

**Comment by snej** [comment]
Yeah, change that to `setDouble` and it should resolve the problem.

**Comment by bbrks** [comment]
> How exactly was this value added to the document, i.e. which CBL API call?

That clarifies a little on this side. Thanks. I think we may need to bounce back to QE to make sure their tests are using doubles in that case.

Thanks!

**Comment by JRascagneres** [comment]
Yeah, thanks! This did solve the issue. As Ben mentioned we'll _double_ check this with QE. Pun intended.
