### ISSUE TITLE
BLIP errors on macOS

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#720]
This is consistently happening on Jenkins now.  The Pull (and Push) large database no-conflicts tests is failing after encountering various BLIP errors such as:

LiteCore error 15: BLIP message invalid checksum [ref](http://mobile.jenkins.couchbase.com/view/Couchbase_Lite_Core/job/couchbase-lite-core-macosx/1181/consoleFull#-18803601568a3f092e-ca05-45f9-b44d-e3eaa99bc999) (note:  Scroll up to before the actual failure)<br />
Caught exception handling incoming BLIP message: BLIP protocol error: Bad incoming REQ #10576 (too high) [ref](http://mobile.jenkins.couchbase.com/view/Couchbase_Lite_Core/job/couchbase-lite-core-macosx/1180/consoleFull#-14398836018a3f092e-ca05-45f9-b44d-e3eaa99bc999)

**Comment by borrrden** [comment]
Not reproducible on my local mac machine...

**Comment by snej** [comment]
I've been trying to repro it here on my iMac, unsuccessfully.

By weird coincidence, a forum user just reported a similar invalid-checksum error: https://forums.couchbase.com/t/attachment-replication/20580

**Comment by snej** [comment]
I've now run that test and all the C++ tests repeatedly, in Debug and Release mode, with and without sanitizers and MallocScribble. Can't reproduce.

**Comment by borrrden** [comment]
Whatever it was it seems to be gone now...
