### ISSUE TITLE
remove_diacritics always enabled in FTS indexes

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#723]
According to the [SQLite FTS docs](https://www.sqlite.org/fts5.html) the default value for 'remove_diacritics' is "1", but our code assumes it is "0" as in the following

https://github.com/couchbase/couchbase-lite-core/blob/ef0b278297a9f42c0ca78e5129c156c167cb1ea8/LiteCore/Query/SQLiteKeyStore%2BFTSIndexes.cc#L132-L134

This means that remove_diacritics will always be "1" and give incorrect results by default.

**Comment by snej** [comment]
That documentation refers to the Unicode61 tokenizer in FTS5. We are using a custom tokenizer with FTS4. But it happens that the tokenizer we use has the same default value (see fts3_unicodesn.c:322), so your fix works.
