### ISSUE TITLE
query performance is slow down when database has big documents

### ISSUE THREAD

**Issue by thamht4190** [couchbase/couchbase-lite-core#725]
I have some document types called Record, Attributes. Record is small (~1Kb) and Attributes is large (~0-20Mb). I also have "doc_type" field in json to mark type of document, this field is indexed by value.
When I query on Record (using ["=",[".doc_type"],"rec"] condition in "WHERE"), I see that the query performance is affected a lot by size of Attributes document:
Attributes: number of document: 2 size: 15Mb --> time to query Record: 1.2s
Attributes: number of document: 4 size: 15Mb --> time to query Record: 2.2s
Attributes: number of document: 8 size: 15Mb --> time to query Record: 4.2s
while:
Attributes: number of document: 8 size: 10Kb --> time to query Record: 130ms

Is that expected? I thought that indexing on "doc_type" field would help, but it seems not. Can you help me point out the problem then I can accelerate query performance?

Updated: I also have a document type Session. I tried to queried on Session (using ["=",[".doc_type"],"ses"] condition in "WHERE"), although "att" documents still has large size and amount, time to query is about 100~200ms. I check that the difference between number of Session and number of Record is not the problem (I have about 1000 documents of each).

I tried to delete indexing on "doc_type" field. The time to query Record is quite the same, the time to query Session is much slower (closer as time to query Record). It seems that "doc_type" indexing doesn't work on Record???

Updated 2: I tried to delete indexing on "doc_type" then create that index again. database updates index successfully. The first query on Record is only 100ms, but only that time, after that, the time to query is always 4s. I don't understand somehow the first query make a change on a database?

**Comment by snej** [comment]
Can you describe the platform this is running on, to put those times in perspective?

Huge documents are generally not a good idea for performance. Any operation on a document requires reading it into RAM, including any time a query examines it. So your test for the tiny `doc_type` string results in 15MB of excess I/O.

I don't know what kind of data is making the docs that big, but consider putting it in blobs. (Even if it's structured data, you can store JSON or Fleece in a blob and access it pretty easily.)

Use the `c4query_explain` function to see SQLite's overview of how it runs the query. Watch out for the word "scan" — that means a linear scan of a table. "Search" is a fast O(log n) b-tree search.

**Comment by thamht4190** [comment]
Thanks @snej. I added `c4query_explain`.
Now I created a fresh new database, copied all the huge Atrributes first, then I had a loop in which:
* I copied a Record into new database
* I queried all Record document
At a step, the "SEARCH" keywork didn't appear anymore, but "SCAN" as you can see below:
```
[CBL] "{DB#3446}==> class litecore::SQLiteDataFile C:/Users/Tham/Desktop/thanh_db/10/couchDb.cblite2\\db.sqlite3 @00000284D34E1210"
[CBL] "{DB#3446} Opening database"
Query string:  "[\"SELECT\",{\"WHAT\":[[\".\",\"doc_type\"]],\"WHERE\":[\"=\",[\".\",\"doc_type\"],\"rec\"]}]"
[CBL] "{Query#3447}==> class litecore::SQLiteQuery 00000284D0A51848 @00000284D0A51848"
[CBL] "{Query#3447} Compiling JSON query: [\"SELECT\",{\"WHAT\":[[\".\",\"doc_type\"]],\"WHERE\":[\"=\",[\".\",\"doc_type\"],\"rec\"]}]"
[CBL] "{Query#3447} Compiled as SELECT fl_result(fl_value(_doc.body, 'doc_type')) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'doc_type') = 'rec') AND (_doc.flags & 1 = 0)"
[CBL] "{QueryEnum#3448}==> class litecore::SQLiteQueryEnumerator 00000284D09E9428 @00000284D09E9428"
[CBL] "{QueryEnum#3448} Created on {Query#3447} with 1148 rows (9194 bytes) in 47.704ms"
"SELECT fl_result(fl_value(_doc.body, 'doc_type')) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'doc_type') = 'rec') AND (_doc.flags & 1 = 0)\n\n0|0|0| SEARCH TABLE kv_default AS _doc USING INDEX doc_type_index (<expr>=?)\n\n[\"SELECT\",{\"WHAT\":[[\".\",\"doc_type\"]],\"WHERE\":[\"=\",[\".\",\"doc_type\"],\"rec\"]}]\n"
[CBL] "{QueryEnum#3448} Deleted"
[CBL] "{DB#3446} Closing database"
[CBL] QThread(0x284cecc3160) save document id = "rec:38d570bf-08f3-48b6-a232-b57eaed2c95f" successfully
[CBL] "{DB#3449}==> class litecore::SQLiteDataFile C:/Users/Tham/Desktop/thanh_db/10/couchDb.cblite2\\db.sqlite3 @00000284D34E1810"
[CBL] "{DB#3449} Opening database"
Query string:  "[\"SELECT\",{\"WHAT\":[[\".\",\"doc_type\"]],\"WHERE\":[\"=\",[\".\",\"doc_type\"],\"rec\"]}]"
[CBL] "{Query#3450}==> class litecore::SQLiteQuery 00000284D0A52548 @00000284D0A52548"
[CBL] "{Query#3450} Compiling JSON query: [\"SELECT\",{\"WHAT\":[[\".\",\"doc_type\"]],\"WHERE\":[\"=\",[\".\",\"doc_type\"],\"rec\"]}]"
[CBL] "{Query#3450} Compiled as SELECT fl_result(fl_value(_doc.body, 'doc_type')) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'doc_type') = 'rec') AND (_doc.flags & 1 = 0)"
[CBL] "{QueryEnum#3451}==> class litecore::SQLiteQueryEnumerator 00000284D09EA128 @00000284D09EA128"
[CBL] "{QueryEnum#3451} Created on {Query#3450} with 1149 rows (9202 bytes) in 5622.715ms"
"SELECT fl_result(fl_value(_doc.body, 'doc_type')) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'doc_type') = 'rec') AND (_doc.flags & 1 = 0)\n\n0|0|0| SCAN TABLE kv_default AS _doc\n\n[\"SELECT\",{\"WHAT\":[[\".\",\"doc_type\"]],\"WHERE\":[\"=\",[\".\",\"doc_type\"],\"rec\"]}]\n"
[CBL] "{QueryEnum#3451} Deleted"
```
Can you help me have a look at the database in the link: https://drive.google.com/file/d/1wrqivmrREJuWE2H987jkDKsHLpkW4ik8/view?usp=sharing

I also understand your recommendation with storing huge Attributes as a blob. I'll try it.

**Comment by snej** [comment]
That's weird; it looks like the SQLite query planner stops using the `doc_type_index` index on the second iteration shown. Can you describe _exactly_ what you're doing in the loop? For example, you're closing and re-opening the database each time, according to the logs.

**Comment by snej** [comment]
Your query string seems wrong: `["SELECT",{"WHAT":[[".","doc_type"]],"WHERE":["=",[".","doc_type"],"rec"]}]` is a _nested_ SELECT expression, not a full query. The query string you want is just the portion in the braces, i.e. `{"WHAT":[[".","doc_type"]],"WHERE":["=",[".","doc_type"],"rec"]}`. The query parser will accept an expression in brackets (`[]`) but wraps it in a generic `{WHERE: [...]}` query. This changes the meaning of your query a lot.

The weird thing is that your logs show LiteCore parsing the query as though it were just the part in the braces. That's not what happens when I run that query. What commit of LiteCore are you using?

**Comment by snej** [comment]
When I open your database and run the query, it runs very quickly and the "explain" output shows SEARCH not SCAN. Can you show me the code you're using in your test?

**Comment by thamht4190** [comment]
I've tested on both Windows and MacOS and I see that I dont have this problem on MacOS, only on Windows. I don't have problem with another database, only with the database I sent you.
I'll send you the code when I come back to my office on Monday.

**Comment by thamht4190** [comment]
Sorry for replying late. I'm trying to create a project which is similar with the test on my project (because I cannot send all the source code to you), but it seems that no slow query at all. I'm checking on it and will tell you if I found something. Thanks!

**Comment by djpongh** [comment]
@thamht4190, any update?

**Comment by thamht4190** [comment]
Well. I have realized that the problem happened when I encrypted that database. In the project I intend to send to you, database is unencrypted. However, we still use sqlcipher to encrypt db, so I'm not sure I can get support from you. I'm asking for SEE license from the company 😂

**Comment by borrrden** [comment]
You mean adding your own encryption on top of Couchbase lite?

**Comment by thamht4190** [comment]
Yes. I still keep sqlcipher thirdparty from the previous version of couchbase lite. I think after applying SEE, I will tell if the problem remains. Is that ok?

**Comment by borrrden** [comment]
Well it's certainly OK to tell us but I don't think there is anything we can do about it.  I don't see any way to accomplish what you are doing without altering the library and making your own derivative version (which is not something we can support even via paid support).

**Comment by thamht4190** [comment]
Thanks for your support. Then I think I will close this ticket.
