### ISSUE TITLE
fix build with gcc

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#734]
There are few missed include in BLIP-Cpp, see couchbaselabs/BLIP-Cpp#16 ,
that cause build failure of couchbase-lite-core .

I create this issue, because of after resolving these issues, submodule should be updated in couchbase-lite-core .

**Comment by borrrden** [comment]
The downstream has been merged, but unfortunately this has to wait until either the nodbworker branch gets merged into BLIP or LiteCore gets changed to accomodate the "revert make batcher more generic" commit.
