### ISSUE TITLE
release a version support Swift 5.0

### ISSUE THREAD

**Issue by lacklock** [couchbase/couchbase-lite-core#737]
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Users/Code/Pods/CouchbaseLite-Swift/iOS/CouchbaseLiteSwift.framework/Modules/CouchbaseLiteSwift.swiftmodule/x86_64.swiftmodule

**Comment by borrrden** [comment]
This is not the repo for Couchbase Lite iOS.  See https://github.com/couchbase/couchbase-lite-ios
