### ISSUE TITLE
SQLite Disk Error I/O upgrading Database

### ISSUE THREAD

**Issue by K-Leon** [couchbase/couchbase-lite-core#740]
I've seen this bug while doing Upgrades of large Databases. After maybe 500-1000 Docs i get this error:

04-01 21:22:04.340 I/LiteCore(10703):         ...rev 114-e66def601dbdc9c87949d8ae112c539b
04-01 21:22:04.438 W/LiteCore(10703): SQLite error (code 6410): statement aborts at 18: [SELECT sequence, revid, parent, deleted, json, no_attachments FROM revs WHERE doc_id=? and current=0 ORDER BY sequence DESC] disk I/O error

Devices with smaller Databases are upgrading like they should and seem to work okay.

I happens on most of the devices we upgrade. (Android 5.1) Current release/CBL2.1.x branch CE self built ( i did this because had to workaround the upgrade error with design documents).

**Comment by borrrden** [comment]
This is the now infamous 6410 error that we've been fighting against.  @pasin Is there a way to mitigate this in the 2.1.x branch?

**Comment by pasin** [comment]
@K-Leon there is a fix in the release/iridium` branch but iridium is not officially released but close. 

Another option would be changing the build [configuration](https://github.com/couchbase/couchbase-lite-core/blob/release/CBL2.1.x/CMakeLists.txt#L47) in Lite-Core CMake to use `-DSQLITE_TEMP_STORE=2` for non enterprise build as well.

**Comment by K-Leon** [comment]
i tried Irididium yesterday as well, but it crashed for me on android - i will try it again tonight

**Comment by pasin** [comment]
For the crash, Can you create a new issue and provide the crash detail?

**Comment by pasin** [comment]
As the issue has been fixed in iridium, I'm closing the ticket.
