### ISSUE TITLE
Database Change fired before Docs can be fetched with database.document

### ISSUE THREAD

**Issue by K-Leon** [couchbase/couchbase-lite-core#741]
I just stumbled about some kind of race condition. 

It looks like the databaseChange Handler fires before the actual document is saved. I noticed it when i replicated a batch of documents ( 100 or so )  and tried to access the docs after databaseChange fired with the id list. 
The first 30-40 Docs couldn't be fetched - looks like they aren't created yet. 

--------
* Version:   Release 2.1 built from branch
* Client OS: IOS 11

**Comment by snej** [comment]
Hm. The notification isn’t sent till after the commit of the transaction that writes the docs, so they should be available by then.

Could you reproduce this and set a breakpoint when the doc fails to load? Then get a dump of all threads’ stacks and post it. That will show if the re-locator is still in its transaction.

**Comment by K-Leon** [comment]
I just made a thread dump of every remotely interesting thread - i hope it helps.  i'm also open for experiments - i can reproduce it consistent. 

https://gist.github.com/K-Leon/69af7fd4b100ae6d9a8c0920d068bb8c

**Comment by snej** [comment]
In your gist, none of the threads are still in a transaction.

I just noticed that you're using the databaseChange listener — sorry, I thought you were talking about replicator notifications. That should also be called after the transaction completes. I can double-check.

**Comment by K-Leon** [comment]
So - i got to the bottom of this. First of sorry for the hazzle! 

I got a really crowded channel - hundrets of deletions etc. Now while doing the initial sync i get database notifications for all tombstones which made my code throwing up. (100 Percent on me this one)

One Thing i would propose for the documentation is mentioning the tombstone issue.
 
Or even better: surpressing database notification for tombestones relating to docs that never arrived on the device. It makes reacting on new documents in combination with an initial sync really hard.

**Comment by snej** [comment]
Oh! That explains it. Yeah, the same thing will happen if you delete a document locally. You'll get a change notification, but you can't get the document.

In 2.5 we're adding a `flags` parameter to the `DocumentReplication` class (the parameter to the replicator document change listener) so you can tell whether the document is deleted.
