### ISSUE TITLE
Add vcpkg support

### ISSUE THREAD

**Issue by sinosoidal** [couchbase/couchbase-lite-core#752]
It would be great if couchbase-lite-core was available on vcpkg. I have just tried to buid it using the cmake scripts and it failed. 

The reason of the failure was because I had cmake x86 installed instead of cmake x64. It seems to be building now, but having this as a vcpkg would be great anyway!

https://github.com/Microsoft/vcpkg

**Comment by borrrden** [comment]
This is not a product that we distribute and I feel like having a vcpkg would suggest that it is and so I'm hesitant to provide it in any sort of packaged standalone form.  Although I'll keep vcpkg in mind if and when that changes (this is the first time I've heard of it).

**Comment by sinosoidal** [comment]
@borrrden I totally understand that. I have only get to know vcpkg in the last 6 months. It is the first there is a decent open source package manager for windows, where a lot of opensource libs are available and built properly and installed in a well defined location. Lovely... for Windows! :)
