### ISSUE TITLE
Remind Couchbase Lite of still-conflicted docs when DB opens

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#758]
LiteCore notifies Couchbase Lite of a replication conflict by setting the kConflicted flag in the replicator notification it posts. In response CBL is supposed to resolve the conflict and update the document.

However, it's possible for the app to crash before the conflict is resolved. In that case, currently the conflict will never get resolved, not unless a later remote update is pulled which will trigger the notification again.

To mitigate this, there should be a query when the database opens(?) to find all conflicted documents, and then resolve them. This can be done using a `C4DocumentEnumerator`, setting the `kC4IncludeNonConflicted` flag to `false`.

**Comment by snej** [comment]
It may be simpler for Couchbase Lite to run this enumerator itself. If LiteCore does it, we need to define a new callback or API for notifying CBL, since a replicator notification isn't appropriate.

**Comment by pasin** [comment]
Currently CBL API has the conflict resolver as a property of ReplicatorConfiguration so the process to resolve the pending conflicts needs to be done when start the replicator.

**Comment by borrrden** [comment]
Is this still open?  The PR should have been worded to auto close this.

**Comment by jayahariv** [comment]
closing as #779 is merged.
