### ISSUE TITLE
LEFT JOIN broken

### ISSUE THREAD

**Issue by bmeike** [couchbase/couchbase-lite-core#760]
One of the android unit tests has started to fail, as of commit: 49781055a36137baaea42

This query:
```
Joins[json={FROM=[{AS=main}, {AS=secondary, JOIN=LEFT OUTER, ON=[=, [.main.number1], [.secondary.theone]]}], WHAT=[[.main.number2], [.secondary.theone]]}]
```
... should return 101 rows but now returns only one.

**Comment by borrrden** [comment]
Looks like "removing the workaround" possibly removed too much.  Instead of removing the whole line perhaps this is needed:

`_sql << " " << kJoinTypeNames[ joinType ];`

If you are in a position to do so could you add and try that @bmeike ?

**Comment by bmeike** [comment]
I confirm that code reading:
```
                        _sql << " " << kJoinTypeNames[ joinType ];
                        _sql << " JOIN " << _tableName << " AS \"" << alias << "\"";
```
works fine.
