### ISSUE TITLE
AS in WHAT clause doesn't define an alias for properties

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#761]
If a JSON query uses an AS operator in the WHAT clause, to name a result column, this doesn't define that name as an alias for use in property lookup.

For example, if the query returns `foo.bar.baz` and names it AS `baz`, and then in the WHERE clause the property `baz` is used, that `baz` will refer to a document property named `baz`, though it really should be `foo.bar.baz`.

This isn't just to make the query shorter — it has an effect on performance. SQLite's optimizer doesn't have common-subexpression elimination, so if you can't use the result alias you have to repeat the result expression again in the WHERE clause, which means it gets evaluated twice.

**Comment by borrrden** [comment]
Also to make things more complicated, this case needs to be handled:

`SELECT orderlines[0].productId AS productId, orderlines[0] AS totords FROM orders WHERE test_id="select_func" ORDER BY productId, totords.qty`

Where one of the `ORDER BY` clauses accesses a property on an alias (`totords.qty`)
