### ISSUE TITLE
Ordering null values inconsistent with N1QL expectations

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#762]
Given the following query:

```
SELECT fl_result(fl_value(_doc.body, 'shipped-on')) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'test_id') = 'select_func') AND (_doc.flags & 1 = 0) ORDER BY fl_value(_doc.body, 'shipped-on')

{"ORDER_BY":[[".shipped-on"]],"WHAT":[[".shipped-on"]],"WHERE":["=",[".test_id"],"select_func"]}
```

The results should be entries with missing shipped-on, null shipped-on, and then values, but the actual result is missing shipped-on, values, null shipped-on.

**Comment by snej** [comment]
Same issue as #765 ... we need a custom collation to sort different data types the way N1QL does.

**Comment by borrrden** [comment]
Custom collation is not possible in this case, which seems to be a significant blow.  SQLite does not apply collation to entities that it does not consider to be textual:

From [Section 7.2](https://www.sqlite.org/datatype3.html)

> Note that a text comparison may not be required, and no collating sequence used, in the case of numeric, blob or NULL values.

**Comment by snej** [comment]
I've sent a question about this to the SQLite mailing list.

Saving Fleece results as strings would make it impossible to distinguish them from actual strings, unless we also encoded strings. (I'm also leery of feeding SQLite fake strings that contain nul bytes and aren't even valid UTF-8.)

**Comment by borrrden** [comment]
Migrated to [CBL-216](https://issues.couchbase.com/browse/CBL-216)
