### ISSUE TITLE
FTS indexing an array-valued property is unreliable

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#772]
From [this forum thread](https://forums.couchbase.com/t/weird-behaivor-from-cb-lite-full-text-search-on-string-lists/21276), it appears an FTS index on an array-of-strings property sort of works but not reliably. The post implies that this works correctly on Server.

My hunch is that the FTS indexer is being given the raw Fleece form of the property. The strings are in there, but surrounded by binary stuff, so at a minimum the first and last word of every string probably won't be indexed...

**Comment by borrrden** [comment]
Migrated to [CBL-218](https://issues.couchbase.com/browse/CBL-218)
