### ISSUE TITLE
Move deleted docs to a different SQLite table

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#774]
Currently, deleting a doc just sets the `kC4DocDeleted` flag on its row in the `kv_default` table. This means that queries need to explicitly filter out deleted docs. This adds overhead to every query. It also means that the `kv_default` table can get larger and larger as docs keep getting created and deleted with different IDs.

We can fix this by having a separate `kv_deleted` table just for deleted docs. When a doc is deleted, its row is removed from `kv_default` and added to `kv_deleted`. Bingo, problem solved.

Except...
* When a document is created we'd need to remove the corresponding row from `kv_deleted`.
* The deleted docs still need to be given sequence numbers so the replicator can find them. So the replicator needs to query both tables and merge the sequence numbers. Sounds like a custom SQLite query.
* I suspect there are other complications I haven't noticed yet.

**Comment by snej** [comment]
This is mostly implemented. The work is on the branch `feature/deleted-keystore`.

**Comment by borrrden** [comment]
Migrated to [CBL-219](https://issues.couchbase.com/browse/CBL-219)
