### ISSUE TITLE
Replicator: Authentication

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-core#78]
For OpenID Connect, etc.

**Comment by snej** [comment]
I wrote down [some notes/thoughts](https://github.com/couchbase/couchbase-lite-core/wiki/Authentication) in the wiki last week.

The replicator now supports sending custom HTTP headers (#121) and returns HTTP response headers to the caller (#120), which will allow CBL to do auth at its level ... except for TLS, which probably requires its own issue(s).

**Comment by tleyden** [comment]
Will `setCookieNamed` still be supported?  I was speaking to a developer recently who wants to move to Couch base Lite 2.0, and is using this method.

**Comment by snej** [comment]
LiteCore will send whatever headers CBL tells it to. Cookie handling will need to be done by CBL.

**Comment by snej** [comment]
Going to close this — we have more specific issues like #140 for cert pinning and #145 for client certs.

**Comment by tleyden** [comment]
@snej:

> Cookie handling will need to be done by CBL.

Should I file an issue in https://github.com/couchbase/couchbase-lite-ios/issues for this?

**Comment by snej** [comment]
I don't know if we're filing issues on every existing CBL feature that needs to be reimplemented in 2.0; check with @pasin.

**Comment by tleyden** [comment]
@pasin @djpongh any thoughts on this?

**Comment by pasin** [comment]
I have the list on my note but I just created the issue to track this at the API Level.

https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/105
