### ISSUE TITLE
Windows cannot handle dates before 1970 with C API

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#782]
As noted in [the docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s?view=vs-2015) `gmtime_s` (the Windows equivalent of `gmtime_r` and `gmtime` (as well as local time equivalents) will return `nullptr` when called on a date that is before the Unix epoch.

**Comment by borrrden** [comment]
My recommendation is to adopt the awesome [date.h](https://github.com/HowardHinnant/date/blob/master/include/date/date.h) header throughout the code base.

**Comment by snej** [comment]
I take it this is regarding the N1QL date/time functions?

**Comment by borrrden** [comment]
It's much more likely to occur during that (specifically date math functions that add onto a certain date or subtract from it), yes, but it affects the codebase currently for any dates that happen to be before that time (i.e. stored in docs, etc).

**Comment by snej** [comment]
My only worry about `date.h` would be how much it affects the code size. (I'm probably worrying too much, but you never know with big C++ headers...)

**Comment by borrrden** [comment]
Well perhaps I can ease your mind a bit on that one.  I built LiteCore on the base of master before the date time function branch and its total size was 3279488 bytes.  Checking out the date_part_functions branch increases the size to 3296592 bytes (difference of 17104 bytes).  That includes four new implemented functions as well.  The branch with a number (7 - 10 or so) of P2 functions implemented (and another header `iso_week.h` included) increases the size to 3299080 bytes (difference of 19592 bytes from the original).

My assumption was that "if using date.h is ok, then other parts of the library should be refactored to use that instead of the homegrown stuff that we have"

**Comment by snej** [comment]
Thanks for checking! Sounds good. It seems weird to put all this date/time stuff in Fleece, but if not there then we'd have to add a lower-level support library, which I know would make your head explode (and mine too probably.)

**Comment by borrrden** [comment]
Migrated to [CBL-220](https://issues.couchbase.com/browse/CBL-220)
