### ISSUE TITLE
Delta sync regression

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#784]
Starting at or around commit 14bca86de2a95a1911e76c63fa7bb8c7f7f8776d 

Delta Attachments Push+Pull is failing with the following error message:

> 08:20:58   CHECK( _statusReceived.progress.documentCount == uint64_t(_expectedDocumentCount) )
08:20:58 with expansion:
08:20:58   0 == 1
08:20:58 
08:20:58 /Users/jenkins/workspace/couchbase-lite-core-macosx/couchbase-lite-core/Replicator/tests/ReplicatorLoopbackTest.hh:116: FAILED:
08:20:58   CHECK( asVector(_docPullErrors) == asVector(_expectedDocPullErrors) )
08:20:58 with expansion:
08:20:58   { "att1" } == {  }
08:20:58 
08:20:58 /Users/jenkins/workspace/couchbase-lite-core-macosx/couchbase-lite-core/Replicator/tests/ReplicatorLoopbackTest.cc:1548: FAILED:
08:20:58   CHECK( string(json) == "{\"attached\":[{\"@type\":\"blob\",\"content_type\":\"image/jpeg\",\"digest\":\"sha1-rATs731fnP+PJv2Pm/WXWZsCw48=\",\"length\":27}," "{\"@type\":\"blob\",\"content_type\":\"text/plain\",\"digest\":\"sha1-rATs731fnP+PJv2Pm/WXWZsCw48=\",\"length\":10}," "{\"@type\":\"blob\",\"content_type\":\"text/plain\",\"digest\":\"sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=\",\"length\":0}]}" )
08:20:58 with expansion:
08:20:58   "{"attached":[{"@type":"blob","content_type":"text/plain","digest":"sha1-ERWD9RaGBqLSWOQ+96TZ6Kisjck=","length":27},
08:20:58   {"@type":"blob","content_type":"text/plain","digest":"sha1-rATs731fnP+PJv2Pm/WXWZsCw48=","length":10},{"@type":"blob"
08:20:58   ,"content_type":"text/plain","digest":"sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=","length":0}]}"
08:20:58   ==
08:20:58   "{"attached":[{"@type":"blob","content_type":"image/jpeg","digest":"sha1-rATs731fnP+PJv2Pm/WXWZsCw48=","length":27},
08:20:58   {"@type":"blob","content_type":"text/plain","digest":"sha1-rATs731fnP+PJv2Pm/WXWZsCw48=","length":10},{"@type":"blob"
08:20:58   ,"content_type":"text/plain","digest":"sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=","length":0}]}"

Also of note:

> 08:20:58 16:22:10.380008| [Sync] WARNING: {IncomingRev#1839} Failed to strip legacy attachments: error 4/4
08:20:58 16:22:10.441021| [Sync] ERROR: {pusher#1836} Got error response to rev 'att1' #2-6f9ae492ab2940191b3ba3407c8c8ad6da52df31 (seq #2): HTTP 500 'invalid legacy attachments'

**Comment by borrrden** [comment]
This is due to a change in behavior in Fleece.  The slice `contains` method was renamed to `containsAddress` and `containsAddressRange` and `containsBytes` was added with a new behavior (which also happens to be correct).  Now that LiteCore is using the correct method it's failing to encode the old attachment properties because `nullptr` is being passed for shared keys due to the following:

https://github.com/couchbase/couchbase-lite-core/blob/14bca86de2a95a1911e76c63fa7bb8c7f7f8776d/Replicator/IncomingRev.cc#L103

now evaluates to `true` and so the `processBody` method is entered which calls

https://github.com/couchbase/couchbase-lite-core/blob/14bca86de2a95a1911e76c63fa7bb8c7f7f8776d/Replicator/IncomingRev.cc#L152

**Comment by snej** [comment]
I ran into this today and filed it as #791, forgetting you'd already filed it. It's fixed now.
