### ISSUE TITLE
Unable to correctly upload blob to server

### ISSUE THREAD

**Issue by sinosoidal** [couchbase/couchbase-lite-core#786]
I'm trying to upload blobs to couchbase-server using couchbase-lite-core. 

Every-time I add a document with an attachment, the sync-gateway is disconnected by peer. The error message is:

**Error decompressing frame RPY#2~: unexpected EOF.**
--- RAW FRAME CONTENTS DUMP ---
**Error: parseLoop closing socket due to error: unexpected EOF**

At this point, in the client side the replicator is disconnected:

**ERROR: {Repl#5} Got LiteCore error: WebSocket error 1001 "WebSocket connection closed by peer"**

While the document is created on the database, the translated attachment is always 0 length. Even if I add two different documents with two different attachment, only one binary can be found on the database side and the digest is the same for both documents. Please look below:

```
{
  "_attachments": {
    "blob_/attached/0": {
      "content_type": "text/plain",
      "digest": "sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=",
      "length": 0,
      "revpos": 1,
      "stub": true
    }
  },
  "attached": [
    {
      "@type": "blob",
      "content_type": "text/plain",
      "digest": "sha1-Vso8xrLnRCZL8FgJeetZ/4yHGS4=",
      "length": 25332
    }
  ]
}
```

```
{
  "_attachments": {
    "blob_/attached/0": {
      "content_type": "text/plain",
      "digest": "sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=",
      "length": 0,
      "revpos": 1,
      "stub": true
    }
  },
  "attached": [
    {
      "@type": "blob",
      "content_type": "text/plain",
      "digest": "sha1-5nuo+M3sDPTz+jso3ZwQzaiHaIk=",
      "length": 23030
    }
  ]
}
```

I've made a simple program to replicate this issue.

You can check it out here -> https://github.com/imaginando/cb_test

And there are build and usage instructions here -> https://github.com/imaginando/cb_test/blob/master/README.md

I really want to use couchbase but this problem is preventing me from moving forward as my application relies on attachments.

**Comment by sinosoidal** [comment]
I have found that this problem is happening because of Traefik.

**Comment by ekjuanrejon** [comment]
@sinosoidal how did you fix the problem with Traefik. am having the same problem

**Comment by sinosoidal** [comment]
@ekjuanrejon I didn't. I'm contacting the server directly. Still looking forward for a solution for this.
