### ISSUE TITLE
save method is not failing when same doc is updated 

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#788]
1. conflicted doc A 
2. while resolving conflict, save a new revision. I have updated the same document inside conflict resolver method. 
3. when calling the `void resolveConflict(C4String winningRevID, C4String losingRevID,
                             C4Slice mergedBody, C4RevisionFlags mergedFlags)`, this is returning success. 

expecting the `if (!winningRev->isLeaf() || !losingRev->isLeaf())` condition gets called and return failure with CBLConflict error.

adding the below unit test in Swift will show the error, 
```
- (void) testConflictResolverCalledTwice {
    NSString* docId = @"doc";
    NSDictionary* localData = @{@"key1": @"value1"};
    NSDictionary* remoteData = @{@"key2": @"value2"};
    [self makeConflictFor: docId withLocal: localData withRemote: remoteData];
    
    TestConflictResolver* resolver;
    CBLReplicatorConfiguration* pullConfig = [self pullConfig];
    
    resolver = [[TestConflictResolver alloc] initWithResolver: ^CBLDocument* (CBLConflict* con) {
        
        // update the doc will cause a second conflict
        CBLMutableDocument* savedDoc = [[self.db documentWithID: docId] toMutable];
        if (![savedDoc booleanForKey: @"secondUpdate"]) {
            NSError* error;
            [savedDoc setBoolean: YES forKey: @"secondUpdate"];
            [self.db saveDocument: savedDoc error: &error];
            AssertNil(error);
        }
        
        CBLMutableDocument* mDoc = con.localDocument.toMutable;
        [mDoc setString: @"local" forKey: @"edit"];
        return mDoc;
    }];
    pullConfig.conflictResolver = resolver;
    
    [self run: pullConfig errorCode: 0 errorDomain: nil];
    
    AssertEqual(self.db.count, 1u);
    NSMutableDictionary* exp = [NSMutableDictionary dictionaryWithDictionary: localData];
    [exp setValue: @"local" forKey: @"edit"];
    [exp setValue: @YES forKey: @"secondUpdate"];
    AssertEqualObjects([self.db documentWithID: docId].toDictionary, exp);
}
```

**Comment by jayahariv** [comment]
savedDoc revID(3-3b580c270ad4412a50fc38bcdafdf2b1475f1270) and sequence(4)
localDocument revID(2-4d55da5a6671a685a75717f7307503ba87cfb87c) and sequence(2) 
remoteDocument revID(2-f4f98fb3159f12e000071914ee6dbe8bb4cc074d) and sequence(3)

**Comment by snej** [comment]
`c4doc_resolveConflict` operates in memory only; it doesn't access the database. So when you call it, it has no idea that the document in the DB has been modified. The conflict error will occur when you call `c4doc_save` afterwards -- the parent revision you pass in (the original revID of the document) will not match the revID in the database (the new one from that saveDocument call during conflict resolution).

**Comment by jayahariv** [comment]
I can see [treeDocument-save](https://github.com/couchbase/couchbase-lite-core/blob/ecf16ecb29ac139e7af8e7d411ac8631344cdd91/LiteCore/Database/TreeDocument.cc#L549) is returning false due to `litecore::VersionedDocument::kConflict:`. 

But it is not validated in the save.

**Comment by jayahariv** [comment]
This will make it work!

<img width="722" alt="Screen Shot 2019-05-22 at 11 55 09 AM" src="https://user-images.githubusercontent.com/10448770/58200781-7ad9c780-7c88-11e9-88f9-f2fc9c74c4da.png">

**Comment by snej** [comment]
Yes, you're right! This is a longstanding bug I introduced two years ago(!) in commit 4c4b933 when I made `TreeDocument::save` return bool so it could indicate a conflict without throwing an exception. I forgot to update this call site. The bug just never turned up till now because `c4doc_save` wasn't used in a context where there could be a conflict.
