### ISSUE TITLE
Query: Cross-database joins

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#79]
Extend the join functionality to support querying between docs in different databases.

In terms of the JSON query language, this means implementing the `db:` key of the items in the `FROM:` clause.

**Comment by snej** [comment]
This has been deferred out of 2.0. High priority for 2.1.

**Comment by borrrden** [comment]
Migrated to [CBL-115](https://issues.couchbase.com/browse/CBL-115)
