### ISSUE TITLE
Truncated blob saved on peer if replicator stopped in mid-upload

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#790]
[Reported on the forum](https://forums.couchbase.com/t/corrupted-blob-data-after-sudden-replication-disconnect/21563):

>I created 10 Documents with 3 photos each taken with the mobile camera. I started a one-time replication to push these blobs to the server – we do not currently use continuous replication. During the replication I went into the app switcher and swiped to close the mobile app. One of the photos on the server ended up corrupted, just like our users reported.

I think what happens is that the replicator is told to stop while it’s halfway through sending a blob, and when it closes the connection it looks like the blob is finished, so SG just saves what it received so far. Instead it needs to indicate that the upload failed, so SG will throw away the received data.

The problem is that the BLIP protocol doesn't have a way to respond with an error after it starts sending a response, or to cancel the response. I could add this to BLIP but I'd rather not open the hood on the protocol spec just to fix this...

- [ ] The recipient [SG in this case] should be checking whether the length and SHA-1 digest of the response match the `length` and `digest` properties in the document. LiteCore already does this; sounds like SG doesn't? If so, this can be fixed on the SG side. And checking the digest is a good idea anyway.

There are also some things to check in the replicator / BLIP implementation in both LiteCore and SG:
- [ ] When the replicator stops, it shouldn't be finalizing a blob response. That is, when a blob uploader is told to stop, it should not send a final frame with `moreComing`=false. That way, the recipient will know that the response wasn't fully received.
- [ ] Likewise, when a BLIP connection closes, any incoming message that hasn't received its final frame should be dropped and ignored, not treated as complete.

**Comment by snej** [comment]
CC @bbrks

**Comment by snej** [comment]
From my reply on the forum:

>For a workaround, on the server side you should check whether a blob’s length property in the document matches the actual length of the blob in bytes. I’m pretty sure that the corruption here is from truncation of the data, so the length will end up less than expected. (To make double sure you can compare the digest property against a SHA-1 digest of the blob, but I don’t think that’s necessary here.)

>I’m pretty sure the truncated blobs won’t spread from the server to any other clients, because the CBL replicator does verify the SHA-1 digest before saving. I believe the replicator will just throw away the incoming document if a blob is invalid, so the other clients just won’t see that revision at all.

**Comment by snej** [comment]
Note to self: It _would_ be good, for other reasons, to allow a BLIP message to be canceled in mid-stream. For instance, if the peer sending the blob gets a file (or Couchbase Server) error reading the data, there's currently nothing it can do. It would be better if it could cancel the BLIP message. This would just require a new frame flag.

**Comment by bdgza** [comment]
From my reply on forum:
> The corrupted blob does spread to other clients. And if the Document is updated elsewhere it will sync back to the originating client as well and overwrite the original undamaged blob with the corrupted version.

**Comment by bbrks** [comment]
Raised [**CBG-378** - Verify attachment length and digest when downloading attachment](https://issues.couchbase.com/browse/CBG-378) to address the first point in the issue.

**Comment by snej** [comment]
The corrupted blobs should be simply truncated from the originals, with no bytes changed. Could you please confirm that?

I’m really surprised that the bad blobs would spread to other clients! I know for certain that Couchbase Lite verifies the SHA-1 digest of a blob before storing it, so if the blob received from the server doesn’t match the digest in the document, it will be rejected. Let me go double-check that.

**Comment by snej** [comment]
If the corrupt blob spreads back to the originating client, then it _must_ have a different digest (in the doc body), otherwise the client wouldn't download it. That is, if the originator receives the updated document, and if the blob dictionary in the doc body still had a `digest` property with the original digest, the replicator would see it already had that blob (since it created it!) and wouldn't download anything.

That implies that something is changing the `digest` property in the document, from the correct blob's to the corrupted blob's.

**Comment by bbrks** [comment]
> That implies that something is changing the `digest` property in the document, from the correct blob's to the corrupted blob's.

@snej Sync Gateway will re-generate the digest based on what bytes it received when it stores the blob for both the binary document in the bucket, but also the actual documents `_sync`/`xattr` metadata.

If I comment out the fix to block mismatched digests in https://github.com/couchbase/sync_gateway/pull/4129 and run the included test against Couchbase Server, this is what ends up in the bucket, given 3 blobs (correct, truncated, and corrupt (two swapped bits)):

![Screenshot 2019-05-29 at 11 47 04](https://user-images.githubusercontent.com/1525809/58551714-9dc82680-8208-11e9-8df1-221373370a5f.png)

And a snippet of `_sync` data showing the truncated digest, even though the original digest sent with this blob was the correct one.

![Screenshot 2019-05-29 at 11 49 38](https://user-images.githubusercontent.com/1525809/58551719-9f91ea00-8208-11e9-8ea8-7bd14d65e9e1.png)

Clients who already have the original blob will get an incorrect proof in proveAttachment. I'm not sure what CBL decides to do in that case.

**Comment by snej** [comment]
Thanks, Ben. That would explain what's happening — the revision body gets altered to refer to the truncated blob, so other clients pulling the revision don't see any digest mismatch and accept it.

**Comment by snej** [comment]
When CBL stops the replicator, LiteCore handles it by immediately closing the WebSocket and throwing away the queues of unsent and in-progress messages. It will _not_ send a final frame for a blob being uploaded.

So I think that it’s SG’s BLIP implementation (or replicator code) that finalizes the incoming blob and inserts it when the connection closes. That would be good to fix -- a BLIP message/reply that's left unfinished when the connection closes should be ignored.

**Comment by bdgza** [comment]
Any progress on when this might be fixed? My users are still experiencing corrupted blobs.

**Comment by snej** [comment]
We should have closed this issue, as the problem turned out to be in Sync Gateway. The [SG issue](https://issues.couchbase.com/browse/CBG-378) was [fixed a month ago](https://github.com/couchbase/sync_gateway/pull/4129), and is scheduled for release in "Cobalt", which is 2.7. We're finishing up development of that release; probably a month or so till release, but that's just my guess.
