### ISSUE TITLE
run ./build_unix.sh fail with error 

### ISSUE THREAD

**Issue by JiajieHuang** [couchbase/couchbase-lite-core#794]
I try to build on my ubuntu machine but fail with error below"
../../libLiteCoreStatic.a: error adding symbols: File format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)

LiteCore/tests/CMakeFiles/CppTests.dir/build.make:859: recipe for target 'LiteCore/tests/CppTests' failed
make[2]: *** [LiteCore/tests/CppTests] Error 1
CMakeFiles/Makefile2:5014: recipe for target 'LiteCore/tests/CMakeFiles/CppTests.dir/all' failed
make[1]: *** [LiteCore/tests/CMakeFiles/CppTests.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

how could I solve this?

**Comment by borrrden** [comment]
GitHub is for bug reports, not questions.  Please ask questions on https://forums.couchbase.com/c/mobile
