### ISSUE TITLE
Inconsistent behavior regarding the 'bundled' flag between create and delete

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#8]
This has spawned from the c4ThreadingTest port that I am doing but I noticed something that was causing test failure:

When creating a view by specifying a path to the view file, the bundled flag will be ignored and the file will be created as expected.

```
c4view_open(onDB, c4str(kViewIndexPath),
                                   c4str("myview"), c4str("1"),
                                   c4db_getConfig(db), NULL);
```

However, when deleting with the bundled flag, the delete operation silently fails leaving the previous file intact:

```
c4db_deleteAtPath(c4str(kViewIndexPath), c4db_getConfig(db), NULL);
```

The problem here is that if ForestDB is then used, it will attempt to read the SQLite file and barf (since a file with no additional extensions or end modifiers is a valid file for both engines).

**Comment by snej** [comment]
This is one of those "Doctor, it hurts when I do this" / "Well, then don't do that" situations —
* If the database is bundled, you shouldn't give a path to `c4view_open`, just the name of the view.
* Views should be deleted with `c4view_delete`, not `c4db_deleteAtPath`.
* If you give the Bundled flag to `c4db_deleteAtPath`, that tells it that the path is a directory; if it isn't, it'll give up.

**Comment by snej** [comment]
I've added some checks to prevent the 1st and 3rd of those things; they'll now return an InvalidParameter error.

**Comment by borrrden** [comment]
Interesting, I'm going by what is [in the C tests](https://github.com/couchbase/couchbase-lite-core/blob/master/C/tests/c4ThreadingTest.cc#L34) so I wanted to confirm this.  Thanks for the additional checks.

**Comment by snej** [comment]
Oh, interesting — looks like I missed some stuff when I converted the C tests to use bundled databases [blush]. I'll fix that.

**Comment by borrrden** [comment]
In that case, allow me to point out that c4GeoTest also does this.

**Comment by snej** [comment]
Fixed that one too. I'll push the commit after I get a chance to rebase onto your commits...
