### ISSUE TITLE
DISTINCT doesn't work correctly due to implicit result columns

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#81]
_From @pasin on March 16, 2017 0:29_

Test with NSPredicate Query:

```
- (void) test_SelectDistinct {
    for (int i = 0; i < 10; i++) {
        NSError* error;
        CBLDocument* doc = [self.db document];
        doc[@"number"] = @(1);
        Assert([doc save: &error], @"Error when creating a document: %@", error);
    }
    
    CBLQuery *q = [self.db createQueryWhere: nil];
    q.returning = @[@"number"];
    q.distinct = YES;
    Assert(q);
    NSLog(@"%@", [q explain: nil]);
    uint64_t numRows = [self verifyQuery: q test: ^(uint64_t n, CBLQueryRow *row) { }];
    AssertEqual(numRows, 1u);
}
```

Results: All 10 docs are returned.

Explain Plan:

```
2017-03-15 17:27:14.039 xctest[12618:34769790] SELECT DISTINCT sequence, key, meta, fl_value(body, 'number') FROM kv_default ORDER BY key LIMIT $limit OFFSET $offset
0|0|0| SCAN TABLE kv_default USING INDEX sqlite_autoindex_kv_default_1
0|0|0| USE TEMP B-TREE FOR DISTINCT
```
--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

_Copied from original issue: couchbase/couchbase-lite-ios#1669_

**Comment by snej** [comment]
_From @pasin on March 23, 2017 15:5_

@borrrden do you get this test pass? What am I missing?

**Comment by snej** [comment]
_From @borrrden on March 23, 2017 21:11_

I didn't get this test working.  I don't think the correct results are being returned from LiteCore.

**Comment by snej** [comment]
_From @borrrden on March 24, 2017 4:7_

An analysis of this is that the underlying SQLite query is incorrect.  In this case it is getting translated to:

> SELECT DISTINCT sequence, key, meta FROM kv_default LIMIT $limit OFFSET $offset

That means that unless all three columns are unique (which is impossible since duplicate keys / sequences are not allowed) it won't be considered unique.

**Comment by snej** [comment]
_From @borrrden on March 27, 2017 21:33_

I guess the bigger question here is "does SELECT DISTINCT make sense in our current model?"  It would only make sense if we are only optionally returning the document that the properties came from and have the result set also have key accessors since SELECT DISTINCT, by definition, needs to only select bits that are exactly the same as the others.  At that point there is no way to tell which document the properties came from.

**Comment by snej** [comment]
So because the query translator implicitly adds `sequence, key, meta` to the returned columns, that breaks `DISTINCT`? I guess that makes sense. I thought it would be a good idea to always return these so the query row object can point to the document, but I'll have to rethink that.

**Comment by borrrden** [comment]
Yes, that is the issue.  DISTINCT is an all or nothing option (either every column has to be unique, or none of them can be) so adding in an ID that is guaranteed to be unique means that you will never have any distinct elements if you include it.  On the other hand, removing it means you lose track of which document the properties are from.  Actually they may be "from" two or more documents if distinct does its job properly.  This has the side effect of meaning that distinct *needs* to have at least one property to select.  A blank "SELECT DISTINCT" is meaningless since the majority of non-user properties are unique (revision ID might be the only one that is not?)

**Comment by snej** [comment]
It seems that, at least with DISTINCT, the query shouldn't include those implicit columns. (They don't make sense when any aggregate functions are used, either.)

**Comment by borrrden** [comment]
This is going to require some C struct enhancements too, I believe, to make these columns available without the docID, etc.
