### ISSUE TITLE
count() query is slow

### ISSUE THREAD

**Issue by thanhldnv** [couchbase/couchbase-lite-core#822]
Hi Team,
I have a problem relate to  performance when using count(), there are my query.
["SELECT",{"FROM":[{"as":"rec"}],"LIMIT":["$limit"],"OFFSET":["$offset"],"WHAT":[["count()",[".","rec","uuid"]]],"WHERE":["LIKE",[".","rec","_id"],"rec:%"]}]
Explain: 
"SELECT fl_result(count(fl_value(\"rec\".body, 'uuid'))) FROM kv_default AS \"rec\" WHERE (\"rec\".key LIKE 'rec:%') AND (\"rec\".flags & 1 = 0)\n\n4|0|0| SEARCH TABLE kv_default AS rec USING INDEX sqlite_autoindex_kv_default_1 (key>? AND key<?)\n\n[\"SELECT\",{\"FROM\":[{\"as\":\"rec\"}],\"WHAT\":[[\"count()\",[\".\",\"rec\",\"uuid\"]]],\"WHERE\":[\"LIKE\",[\".\",\"rec\",\"_id\"],\"rec:%\"]}]\n"

and the database(bellow link) contains about 2000 records, and some records has large size.

This take time 1395.760 ms on my machine(Windows 10, RAM: 8 GB, CPU:  3.00 GHz) 

[couchDb.cblite2.zip](https://github.com/couchbase/couchbase-lite-core/files/3504220/couchDb.cblite2.zip)

Anyone can give me an advice to improve?

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
