### ISSUE TITLE
Query result set is preloaded into memory

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#83]
The current query implementation reads all rows of the result into memory at once when the query is run. The enumerator then just unpacks and returns individual rows. This can result in memory pressure when running a very large query. (The workaround for that is to use pagination, or to request less data per row.)

This is done as a workaround for a SQLite limitation: If a query cursor (`sqlite3_stmt`) is still in the middle of the result set when a database mutation occurs on the same connection, the cursor gets messed up — it can skip rows or return to a previous row. (This is the typical CS problem of mutating a collection while iterating it.)

To go back to streaming the results from the database, we'd have to open a read transaction on that connection first, not make any writes during the iteration, and then end the transaction. That way the connection retains a snapshot of when the transaction was opened. The drawback is that this connection can then only be used by that one query until its iterator completes — it can't even be used for other reads because it'll get out of step with changes made after the query started. This has the potential of creating lots of open SQLite handles, each with their own block cache.

This design seems to fit the connection-pool approach that Jim's used on .NET, where one connection is reserved for writes, and a pool of others for reads. A query would 'check out' a read connection from the pool, and then not return it until the iterator ends.

**Comment by snej** [comment]
I've done some work on this in branch `feature/one-shot-query`. It adds a new query option `oneShot`. If this isn't set, queries behave exactly like today. We need the current behavior for live queries and for when the client needs random-access to the rows.

In one-shot mode the query enumerator only keeps a small number of rows at a time, and keeps the SQLite statement open until it reaches the end. It avoids the problem with database mutations by listening for transactions: when the db connection starts a transaction, the enumerator immediately fast-forwards, reading all the rest of the rows into memory.

Still to be done: support for opening multiple enumerators on a query at the same time. Currently they all share the SQLite statement, so Bad Stuff would happen.

**Comment by borrrden** [comment]
Migrated to [CBL-117](https://issues.couchbase.com/browse/CBL-117)
