### ISSUE TITLE
hiding sqlite3* on Linux

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#845]
I use sqlite in my project and libLiteCore.so, 
it would be nice if libLiteCore doesn't export sqlite symbols, that prevents mixing symbols with system sqlite3 shared library :

```
$ nm -D libLiteCore.so | grep sqlite3_open
000000000016ddb0 T sqlite3_open
000000000016dca0 T sqlite3_open16
000000000016dda0 T sqlite3_open_v2
```

Ideally if libLiteCore.so hide all symbols except exported via C/include,
but hiding sqlite3_* functions will be nice.

Also this is theoretically make LTO more effective, see https://clang.llvm.org/docs/LTOVisibility.html if you hide sqlite3_ with `-fvisibility=hidden`

**Comment by borrrden** [comment]
Seems like the downstream is busy and hasn't considered the other suggestion on the PR (which is fine), so I filed [CBL-430](https://issues.couchbase.com/browse/CBL-430) to get this into a sprint in the near future.

**Comment by borrrden** [comment]
This enhancement is in 2.7.0. Will close if I don't hear back in 7 days.
