### ISSUE TITLE
the right way to use default conflict resolution in replicator?

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#850]
I pass such options to `c4repl_new`
```
C4ReplicatorParameters {
            push: kC4Continuous,
            pull: kC4Continuous,
            optionsDictFleece: EmptyFLSlice,
            pushFilter: nullptr,
            validationFunc: nullptr,
            onStatusChanged: call_on_status_changed,
            onDocumentsEnded: nullptr,
            onBlobProgress: nulptr,
            callbackContext: my_context,
            socketFactory: ptr::null_mut(),
            dontStart: false,
        }
```

It works fine, if two users of replicator is online.
But then I cut the connection between client A and client B to sync-gateway.
And modify the same document on A and B.

```
 $ ./cblite ls -l  /tmp/test.cblite2
Document ID             Rev ID     Flags   Seq     Size
8610598f-d848-490d-9963-c104cc3f3ba8 5-576d9dce ---       5     0.2K
$ ./cblite ls -l  /tmp/another_test.cblite2
Document ID             Rev ID     Flags   Seq     Size
8610598f-d848-490d-9963-c104cc3f3ba8 5-5d1283ba -c-       5     0.3K
```

Then I restore the connection for A and B to sync-gateway, but 
as result I got the A's variant of document on server and in A's local database.
And B's variant in B's local database.

So for some reason conflict resolution doesn't happens.

Then I add `kC4ReplicatorOptionOutgoingConflicts` to `true` and it seems work somehow.
After offline editing I got the same version of document on all three: A, B and server.

But I little confused here, I use couchbase-lite-java as reference.
And it looks like `C4Socket.REPLICATOR_OPTION_OUTGOING_CONFLICTS` is not used anywhere,
while documentation claims that it has default conflict resolving strategy: https://docs.couchbase.com/couchbase-lite/2.6/java.html#handling-conflicts

So I should use some other way to get working default conflict resolution, some other option ?

**Comment by borrrden** [comment]
Please put questions into the [forums](https://forums.couchbase.com/c/mobile)
