### ISSUE TITLE
MSVC warning C4068: unknown pragma mark

### ISSUE THREAD

**Issue by WimLeflere** [couchbase/couchbase-lite-core#862]
When compiling with MSVC I get the following warning `C4068: unknown pragma` for `#pragma mark - COOKIES` in `c4Replicator.h`.
https://github.com/couchbase/couchbase-lite-core/blob/master/C/include/c4Replicator.h#L232

It seems to be an Xcode specific pragma.
Can I remove it (in a PR) or should I wrap it with an `ifdef`?

**Comment by borrrden** [comment]
What I usually just do is disable the warning for unknown pragma.  But to answer your question, you surely cannot remove it.  It seems easier to disable the warning since an unknown pragma is harmless.

**Comment by WimLeflere** [comment]
Removing the pragma would make the code more portable.
But I can disable the warning if removing the pragma is not preferred.

**Comment by borrrden** [comment]
Is there a platform where this causes an actual problem aside from an annoying compiler warning?  If not then keeping it in makes the Apple developers happy because it lays things out in a nice way for Xcode.

**Comment by WimLeflere** [comment]
Your call, making Windows devs happy vs making Apple devs happy.
