### ISSUE TITLE
user_version 302 on empty sqlite database not handled correctly

### ISSUE THREAD

**Issue by weis** [couchbase/couchbase-lite-core#883]
When starting with an empty sqlite database, the user_version pragma is 0.
So in SQLiteDataFile::reopen() it is set to 302.
But after that SQLiteDataFile::ensureIndexTableExists() is called which sets user_version to 301.
This leads to an sqlite error the next time SQLiteDataFile::reopen() is called:
As the user_version is 301 the method wants to adds the purgeCnt column to kv_meta again, which fails, because the column already exists.
I think the user_version should only be set to 301 in SQLiteDataFile::ensureIndexTableExists() if the current user_version is < 301

**Comment by borrrden** [comment]
Exactly right, very good catch!

**Comment by borrrden** [comment]
Opened [CBL-550](https://issues.couchbase.com/browse/CBL-550)

**Comment by borrrden** [comment]
This fix is in 2.7.0. Will close if I don't hear back in 7 days.
