### ISSUE TITLE
Networking/TCPSocket.cpp (Windows section) does not compile 

### ISSUE THREAD

**Issue by victorbergeronsemi** [couchbase/couchbase-lite-core#890]
Hello, 

On the LiteCore version currently tagged in Couchbase-Lite-C, the file TCPSocket.cc presents the following code (lines 591, 592):

        if (!checkSocket(acc))
            return false;

which does not properly compile on Windows, with the following error message:

C:\Users\beave\Desktop\couchbase-lite-C\vendor\couchbase-lite-core\Networking\TCPSocket.cc(591): error C2664: 'bool litecore::net::TCPSocket::checkSocket(const sockpp::stream_socket &)': cannot convert argument 1 from 'sockpp::tcp_acceptor' to 'const sockpp::stream_socket &'
C:\Users\beave\Desktop\couchbase-lite-C\vendor\couchbase-lite-core\Networking\TCPSocket.cc(591): note: Reason: cannot convert from 'sockpp::tcp_acceptor' to 'const sockpp::stream_socket'
C:\Users\beave\Desktop\couchbase-lite-C\vendor\couchbase-lite-core\Networking\TCPSocket.cc(591): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

**Comment by borrrden** [comment]
I am aware of this problem, and have solved it by simply removing those two lines (Not sure how they are supposed to function) @snej Maybe you can shed some light here.

**Comment by snej** [comment]
Sorry, that code had succumbed to bit-rot since I last enabled it (I don't have access to Windows.) I've fixed it now.
