### ISSUE TITLE
Replication Completed ---> Should this be Stopped Not Busy?

### ISSUE THREAD

**Issue by wilsondy** [couchbase/couchbase-lite-core#892]
https://github.com/couchbase/couchbase-lite-core/blob/51d14d0933353546af96fa7e1244cc9d3078c908/Replicator/Replicator.cc#L250

The support side will hate me for doing this... but just in case this is my problem.

**Comment by borrrden** [comment]
No, because the protocol is not finished yet (it still needs to write the checkpoint)
