### ISSUE TITLE
[Error] XMLHttpRequest cannot load http://lite.couchbase./justbe due to access control checks.

### ISSUE THREAD

**Issue by qdcxj1993** [couchbase/couchbase-lite-core#895]
import { CouchbaseLite } from '@ionic-native/couchbase-lite/ngx';
import { Http } from '@angular/http';
import { Observable } from 'rxjs'
constructor(private couchbase: CouchbaseLite, private platform:Platform,private _http:Http) {
   this.initMethod();
}
url:string;
initMethod() {
   this.couchbase.getURL().then((url)=> {
       this.url = url;
   })
}
getUrl() {
     return this.url;
}
// DATABASES //
createDatabase(database_name:string) {
     let url = this.getUrl();
     url = url+database_name;
     return this._http
       .put(url)
       .map(data => { this.results = data['results'] })
       .catch((error:any) => {
          return Observable.throw(error.json() || 'Couchbase Lite error');
        })
 }
createdata(){
    this.createDatabase("justbe")
  }

**Comment by borrrden** [comment]
What does this have to do with LiteCore?

**Comment by snej** [comment]
We do not support Ionic. If there's an Ionic binding to Couchbase Lite, you should file the bug report against that.
