### ISSUE TITLE
ForestDB c4db_deleteAtPath should delete more files

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#9]
`c4db_deleteAtPath` fails to delete the path passed as the filename when used with the ForestDB storage engine because it seems to only look for .0 (.1, etc) and .meta files.  This has the side effect that if an old SQLite file with the same path (normal operation in some cases of the SQLite engine) is lying around ForestDB will attempt to read it and barf if a db or view is opened using that path.

**Comment by snej** [comment]
I'm letting `fdb_destroy()` delete the files. I think because the config settings say to use auto-compact, it only deletes paths that would be generated in auto-compact mode (with .0, .1, etc.)
I'll add another line to explicitly delete the base path.
