### ISSUE TITLE
branch without c++17?

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#901]
On my old linux there is even C++14 compatible compiler, but looks like master require C++17,
will be some kind of branch for c++11, or there is no way except fork?

**Comment by borrrden** [comment]
Our new requirements going forward are going to be clang 5 or higher or g++ 7 or higher.  This is something we are able to make happen for CentOS 7 which is very old, and we don't have the bandwidth to maintain a c++11 only branch (especially when we can finally use the C++ filesystem API which will replace hundreds of lines of our ifdef code).  Some advice for making a fork would be that a lot of the C++17 stuff is either directly inspired by (i.e. almost identical API) or an alternative exists using boost.

**Comment by Dushistov** [comment]
This is sad.

**Comment by snej** [comment]
What's the reason for not being able to upgrade the OS or the compiler?
Could you build on a newer OS and copy the binary to the old one?

**Comment by Dushistov** [comment]
@snej 

> What's the reason for not being able to upgrade the OS or the compiler?
> Could you build on a newer OS and copy the binary to the old one?

OS version is fixed in document and this old linux distribution will be used
at least several more months. My application is depend on C++ libraries from OS,
like Qt. So if I want use more modern C++ compiler with more modern C++ runtime,
I need rebuild Qt also. So at the end of the day I will be responsible for support of C++ compiler, C++ standard library, Qt and also my application. It is huge task for our small team.

And funny thing that after several months support of that old linux distro is the end,
and the shiny new version of OS is coming - with gcc 6.3.0. So and new OS has no c++17 support.

As result, I suppose I create and support fork for some time, and after that I need find something other solution instead of couchbase.
