### ISSUE TITLE
Replication Lifecycle Spec

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-core#94]
In order to plan test scenarios, need a document from dev detailing the following:
- Diagram of the possible replication states for the 2.0 replicator (I.e. Active, Idle …)
- All of the platform notifications that initiate a state change (I.e Endpoint now longer reachable, wifi disabled on device, etc.)

**Comment by snej** [comment]
Created a placeholder [wiki page](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Lifecycle).

**Comment by snej** [comment]
I've written a description of the states in the form of a flowchart. I may add more to it later, but I think what's there is enough to answer the questions.
