### ISSUE TITLE
Replicator: Specifying a set of docIDs

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#95]
The client API should be able to specify a set of document IDs to push or pull.

(Needed for feature parity with 1.x.)

**Comment by Fujio-Turner** [comment]
I do know that there are people right now that are using this feature for use case like below.

<img width="546" alt="screen shot 2017-04-18 at 8 39 25 am" src="https://cloud.githubusercontent.com/assets/16341130/25139611/a26c7d68-2412-11e7-8197-92da1ac642c3.png">
