### ISSUE TITLE
Getting error WebSocket error 1001 "WebSocket connection closed by peer

### ISSUE THREAD

**Issue by Malcom100** [couchbase/couchbase-lite-core#957]
I am beginner, I started to use the library two days ago. I use Couchbase lite 2.7 for Android and when I implement the replicator to sync with gateway I got the error: WebSocket error 1001 "WebSocket connection closed by peer"

This is my code maybe will help you to understand
1.Creating Replicator
    private fun instantiateReplicatorPush() {
        var uri:URI ? = null
        try {
            uri = URI("ws://10.0.0.2:4984/db")
        }catch (c: CouchbaseLiteException) {
            c.printStackTrace()
        }
        uri?.let {
            val endpoint = URLEndpoint(it)
            val config = ReplicatorConfiguration(mDatabase,endpoint)
            config.replicatorType = CustomReplicatorType.getPushAndPull()
            config.isContinuous = true
            config.authenticator = BasicAuthenticator(user,password)
            config.pushFilter = ReplicationFilter { document, flags -> true }
            config.setPullFilter { document, flags -> true }
            mReplicatorPush = Replicator(config)
        }
    }

**Comment by borrrden** [comment]
I don't see anything wrong with that code, nor anything to suggest that it is a core bug.  If you want to talk about an issue you are having please use the [forums](https://forums.couchbase.com/c/mobile) and then you can open an issue here if you think you have found a defect in the product.
