### ISSUE TITLE
[Replication] Return client based error for custom validator rejection

### ISSUE THREAD

**Issue by iwasrobbed-ks** [couchbase/couchbase-lite-core#960]
## Expected Behavior

Within the context of a pull filter during replication, Couchbase should return a client-based error code (e.g. `CBLErrorRejectedByClientValidation`)  when the client chooses to reject pulling a document. 

## Actual Behavior

Couchbase returns a `CBLErrorHTTPForbidden` error which doesn't make sense for this scenario (the docs state `// User doesn't have permission to access resource` but that's not true)

The error shows `rejected by validation function` but doesn't specify if that's at the sync gateway or client.

Mixing error codes like this makes us think it's an issue at the sync gateway level rather than something the client has control over.

## Code

See https://github.com/couchbase/couchbase-lite-core/blob/master/Replicator/IncomingRev.cc#L194

**Comment by borrrden** [comment]
Assigning to @snej since this is a behavioral thing

**Comment by borrrden** [comment]
Created [CBL-1285](https://issues.couchbase.com/browse/CBL-1285) to track this

**Comment by snej** [comment]
Issue is open but tracked in Jira.
