### ISSUE TITLE
[Threading] c4dbobs_getChanges crash from thread safety issue

### ISSUE THREAD

**Issue by rob-keepsafe** [couchbase/couchbase-lite-core#973]
We've only seen this crash rarely, but figured it's worth filing as a threading issue.

The context for when this happens is we are importing a lot of files and mutating the backing documents for the file metadata.

#### Version

[CouchbaseLiteSwift v2.7.0](https://github.com/couchbase/couchbase-lite-ios/releases/tag/2.7.0) built as a framework

#### Crash:

EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x22203630303131d5.

```
mach
{
  "code": 808530389,
  "exception_name": "EXC_BAD_ACCESS",
  "subcode": 8,
  "exception": 1
}
```

#### Relevant stack trace:

```
Thread 22 crashed
0  libsystem_pthread.dylib _pthread_mutex_lock
1  libc++.1.dylib          std::__1::mutex::lock()
2  CouchbaseLiteSwift      _hidden#5573_
3  CouchbaseLiteSwift      unsigned int c4Internal::tryCatch<unsigned int>(C4Error*, fleece::function_ref<unsigned int ()>)
4  CouchbaseLiteSwift      c4dbobs_getChanges
5  CouchbaseLiteSwift      litecore::repl::Pusher::dbChanged()
6  CouchbaseLiteSwift      litecore::actor::GCDMailbox::safelyCall(void ( block_pointer)()) const
7  CouchbaseLiteSwift      _hidden#7933_
8  libdispatch.dylib       __dispatch_call_block_and_release
9  libdispatch.dylib       __dispatch_client_callout
10 libdispatch.dylib       __dispatch_lane_serial_drain
11 libdispatch.dylib       __dispatch_lane_invoke
12 libdispatch.dylib       __dispatch_workloop_worker_thread
13 libsystem_pthread.dylib __pthread_wqthread

Thread 24
0  libunwind.dylib         libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::setInfoBasedOnIPRegister(bool)
1  libunwind.dylib         libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step()
2  libunwind.dylib         __Unwind_RaiseException
3  libc++abi.dylib         ___cxa_throw
4  CouchbaseLiteSwift      fleece::RefCounted::~RefCounted()
5  CouchbaseLiteSwift      litecore::repl::Pusher::~Pusher()
6  CouchbaseLiteSwift      fleece::Retained<litecore::repl::RevToSend>::operator=(litecore::repl::RevToSend*)
7  CouchbaseLiteSwift      litecore::repl::Replicator::changedStatus()
8  CouchbaseLiteSwift      litecore::repl::Worker::afterEvent()
9  CouchbaseLiteSwift      litecore::actor::GCDMailbox::afterEvent()
10 libdispatch.dylib       __dispatch_call_block_and_release
11 libdispatch.dylib       __dispatch_client_callout
12 libdispatch.dylib       __dispatch_lane_serial_drain
13 libdispatch.dylib       __dispatch_lane_invoke
14 libdispatch.dylib       __dispatch_workloop_worker_thread
15 libsystem_pthread.dylib __pthread_wqthread
```

#### Code
https://github.com/couchbase/couchbase-lite-core/blob/master/C/c4Observer.cc#L71

**Comment by borrrden** [comment]
This is surely a threading issue but it will be tough to track down (especially without some code for context).  I'll keep it in mind though.  What's happening is that the actor's ref count has been decremented for the last time and the destructor is running while at the same time a message is getting processed on another thread.  It should be impossible for this to happen because every time something is added to the queue the actor is retained to save it from being destructed.

**Comment by snej** [comment]
Do you have access to the logs? Thread 24 must have logged a fatal error message right before that happened.

Also, which of those threads crashed? Usually the crash log says `crashed` after the thread number/name.

**Comment by rob-keepsafe** [comment]
Going to close this out as it's not reproing in our latest release. I'll reopen if it resurfaces
