### ISSUE TITLE
There are no SQLiteCpp (15f5b3275e875fed9a4fcc2a8cf7de9352cbf44d) 

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#986]
@borrrden

commit 53e5407dbcf0aa8691f55011866df86564a149c6 updates reference to SQLiteCpp,
but 15f5b3275e875fed9a4fcc2a8cf7de9352cbf44d doesn't exists in the public repository,
for example

https://github.com/couchbasedeps/SQLiteCpp/tree/15f5b3275e875fed9a4fcc2a8cf7de9352cbf44d

gives 404

**Comment by borrrden** [comment]
Sorry about that, I'm usually good at making sure that doesn't happen with my commits!

**Comment by borrrden** [comment]
It's there now.
