### ISSUE TITLE
proper usage of PUBLIC in target_include_directories ?

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#987]
For some unknown reason PUBLIC not used properly in target_include_directories inside cmake files.
Include directories marked as public can be used automatically by cmake.

For example:

vendor/fleece/CMakeLists.txt
```cmake
 target_include_directories(
        ${platform} PRIVATE
        API
       Fleece/Support
```
and every library/executable  that depend on fleece you have to
write:
```cmake
target_include_directories(
    Support PRIVATE
    vendor/fleece/API
    vendor/fleece/Fleece/Support
```

but in cmake 3.x you can mark that some include directories is **PUBLIC**,
and then any library that depend on fleece can just write:
```
target_link_libraries(Support PRIVATE FleeceBase)
```
and that's all, it will get automatically all **PUBLIC** include paths,
and don't have to repeat again and again 

```cmake
target_include_directories(
    Support PRIVATE
    vendor/fleece/API
    vendor/fleece/Fleece/Support
```

**Comment by borrrden** [comment]
I found out about this way later than I should have (this is actually the first project I've ever used CMake on, and when I wrote that particular stuff I had no idea what public and private meant).  Going forward I want to take this approach for both include directories and linked library exports / dependencies!

**Comment by borrrden** [comment]
If there are any more places you'd like to specifically point out then please do so, otherwise I don't think this ticket will serve a purpose to remain open.  Going forward the public include directories and stuff will be considered first, and only made private in the face of issues.
