### ISSUE TITLE
SQLiteCpp: sqlite3.c build error with gcc 10.1.0

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#989]
With recent update SQLiteCpp update (https://github.com/couchbasedeps/SQLiteCpp/tree/15f5b3275e875fed9a4fcc2a8cf7de9352cbf44d) I can not build couchbase-lite-core master:

couchbase-lite-core uses -Werror=uninitialized and that's why:

```
In file included from /LiteCore/Storage/SQLiteChooser.c:38:
/LiteCore/Storage/../../vendor/SQLiteCpp/sqlite3/sqlite3.c: In function 'analyzeOneTable':
/LiteCore/Storage/../../vendor/SQLiteCpp/sqlite3/sqlite3.c:15649:26: error: 'i' may be used uninitialized in this function [-Werror=maybe-uninitialized]
15649 | # define VdbeComment(X)  sqlite3VdbeComment X
      |                          ^~~~~~~~~~~~~~~~~~
In file included from /LiteCore/Storage/SQLiteChooser.c:38:
/LiteCore/Storage/../../vendor/SQLiteCpp/sqlite3/sqlite3.c:108199:7: note: 'i' was declared here
108199 |   int i;                       /* Loop counter */
       |       ^
```

gcc message is pretty cryptic, but looks like it points into:

```
        for(j=0; j<pPk->nKeyCol; j++){
          k = sqlite3TableColumnToIndex(pIdx, pPk->aiColumn[j]);
          assert( k>=0 && k<pIdx->nColumn );
          sqlite3VdbeAddOp3(v, OP_Column, iIdxCur, k, regKey+j);
          VdbeComment((v, "%s.column(%d)", pIdx->zName, i));
        }
```
may be in `VdbeComment` should be `j` instead of `i`.
Looks like worth to fix, even if gcc not officially supported.

cc @borrrden

**Comment by Dushistov** [comment]
Looks like gcc-7.x also enough, travis failed with the same error in my PR #988

**Comment by borrrden** [comment]
> even if gcc not officially supported.

I got fed up with clang on Linux and at the advice of our build team all master builds have been using GCC 7 for the past month or two.  PR validation as well.

**Comment by borrrden** [comment]
However, we use the source of sqlite directly from the SQLite developers so if this is an issue it should probably also be reported to them.

**Comment by borrrden** [comment]
So why does it build with GCC 7 on our servers (even if the test fails), but fail to build on Travis....that's the part that bugs me.

**Comment by borrrden** [comment]
I filed a bug report for this (and I think you did too, as I see an anonymous poster posted the same issue about an hour ago but it hasn't been approved yet) and hopefully they will say "use j" and I will just modify that part of it.

**Comment by Dushistov** [comment]
@borrrden 

Now as fix merged into sqlite's trunk (https://www.sqlite.org/src/info/1cb248a3fc4c35c5), would you backport it into https://github.com/couchbasedeps/SQLiteCpp to make master great again?

**Comment by borrrden** [comment]
I already did -> https://github.com/couchbasedeps/SQLiteCpp/commit/7b250854fffbdc13e2d040a7e96be8e561e51d08

**Comment by Dushistov** [comment]
Thanks
