### ISSUE TITLE
Improvement - Timestamp in Checkpoint

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/couchbase-lite-core#99]
It be great to have a data time stamp in a check point from CBL in SG/CB. So on the CB server I could do a N1QL query to get all the checkpoints that are 2-3 years old and delete them. People upgrade their phones every year or two years so need to clean them up.

**Comment by snej** [comment]
SG could do this by simply setting an expiration time on docs written to `_local`. That would get around the problem of having to trust a client-side clock. (I know of situations where people deliberately set the date back a year on their computer or phone to get around things like expiring beta versions or games, or expired dev certificates.)

**Comment by Fujio-Turner** [comment]
@snej , I suggest that to @adamcfraser 
https://github.com/couchbase/sync_gateway/issues/1860
and maybe leverage the getAndTouch() and move the TTL forward every time you read it and have it a setting in SG config file, but your right timestamp cant be trusted from CBL.
