### ISSUE TITLE
sporadic ReplicatorLoopbackTest.hh:117: FAILED

### ISSUE THREAD

**Issue by Dushistov** [couchbase/couchbase-lite-core#992]
Time to time I see such failure in github actions CI/linux:
```
couchbase-lite-core/Replicator/tests/ReplicatorLoopbackTest.cc:635
.......................................................................................................................

couchbase-lite-core/Replicator/tests/ReplicatorLoopbackTest.hh:117: FAILED:
  CHECK( asVector(_docPullErrors) == asVector(_expectedDocPullErrors) )
with expansion:
  { "doc" } == {  }
```

I was able to reproduce it locally vai sequentially running `./CppTests -r list`.
I tested current master (775893eddbfaff3569f1d351e12d1b27eb19fd40).
I ran `./CppTests -r list` 8 times, I got failure during 0, 4, 8 run.
I attach run 0 - bad, and  next one 1 - good.
[logs.zip](https://github.com/couchbase/couchbase-lite-core/files/4707911/logs.zip)

The similar problem was triggered in #988 in jenkins/linux,
but I run my test against vanilla master without my changes.

**Comment by borrrden** [comment]
We are aware of this issue and currently working on it, there is a PR being worked on at the moment to address it ( #982 )

**Comment by borrrden** [comment]
This should be fixed at this point.  I saw once that a failure that looks very similar happened (push error vs pull error) but not the pull error again.  Let us know if you see it again.
